### ISSUE TITLE
Setup Portus with environment variables

### ISSUE THREAD

**Issue by zot24** [SUSE/Portus#1000]
I just figure out that you can add the following environment variables and a `registry` will added automatically when creating `portus`

```
REGISTRY_SSL_ENABLED=true
REGISTRY_HOSTNAME=registry.my.domain
REGISTRY_PORT=5000
REGISTRY_NAME=Registry
```

I was just wondering if it is possible to create a `team` and a `namespace` as well as using environment variables I couldn't found any documentation about it neither about the previous environment variables.

**Comment by mssola** [comment]
How exactly are you doing that :sweat_smile: ? I just checked both or Docker image and our config files, and if I'm not mistaken this is not possible.

**Comment by zot24** [comment]
jeje 😅 my bad! the magic seems to be happening in here -> https://github.com/sshipway/Portus/blob/master/startup.sh 

Because I'm using this image https://hub.docker.com/r/sshipway/portus/

Thanks @mssola 

btw amazing how fast you give feedback 👍
