### ISSUE TITLE
Request : Add a parameter for catalog page size

### ISSUE THREAD

**Issue by Seb-Solon** [SUSE/Portus#1001]
Hi!

Due to docker/distribution#1854 I had to manually edit the request page size here : https://github.com/SUSE/Portus/blob/master/lib/portus/registry_client.rb#L97
Do you think it is a good to make it configurable for the user? In my case it would be a better workaround for my issue. I am afraid that you may have some issue created in this repo regarding missing repositories/image in the web interface due to this registry bug. This could be a workaround while the registry is fixed.

Regards,

**Comment by mssola** [comment]
Sounds good to me :+1:. We are already providing a configurable value like `jwt_expiration_time` which is pretty "internal" anyways.

**Comment by mssola** [comment]
That being said, development for this will start once the bug is confirmed in distribution :wink:

**Comment by mssola** [comment]
@Seb-Solon done! I'm adding the `registry.catalog_page` configurable value for this.

**Comment by Seb-Solon** [comment]
Thanks!
