### ISSUE TITLE
SSL Error when sync the registry with portus

### ISSUE THREAD

**Issue by sinc59** [SUSE/Portus#1005]
Hello, 
When i push an images to the registry, i can view it in portus.
With the registry output, i gview this error message :

```
registry_1 | time="2016-07-22T08:34:27.025926519Z" level=error msg="retryingsink: error writing events: httpSink{https://docker-registry.my-company.lan/v2/webhooks/events}: error posting: Post https://docker-registry.my-company.lan/v2/webhooks/events: x509: certificate signed by unknown authority, retrying" 
registry_1 | time="2016-07-22T08:34:27.027221918Z" level=warning msg="httpSink{https://docker-registry.my-company.lan/v2/webhooks/events} encountered too many errors, backing off" 
```

My registry container environment contains this:
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/docker-registry-all.crt
    - SSL_TRUST=docker-registry.my-company.lan:443,192.168.18.243:443
    - ENDPOINT_NAME=docker-registry.my-company.lan
    - ENDPOINT_URL=https://docker-registry.my-company.lan/v2/webhooks/events

The docker-registry-all.crt certificate contain:
Root_Certificate
Intermediate_Certificate
Server_Certificate

Do you know what is wrong ?

Thanks for all,
Regards

**Comment by It4lik** [comment]
Hi sinc59, 

Are you using the official registry image ? "SSL_TRUST" isn't a used variable by the official image but by this one : https://github.com/h0tbird/docker-registry.

You need to your cacerts to your containers trusted ca store : 
- docker pull official registry image
- docker run with all my config (config.yml, cert & key, etc.)
- docker cp the cacerts you need somewhere in the container
- docker exec -it bash $your_container
- cp /path/to/cacert /usr/local/share/ca-certificates/ (your cacerts actually NEEDS the .crt extension, not pem or something else)
- update-ca-certificates
- exit
- docker commit this container
- docker run your_container (with all common options you were using with the official image)

**Comment by qiukunlong** [comment]
Hi @sinc59 , I met the same problem. Did you solve this problem and how?

**Comment by sinc59** [comment]
Yes, i cloned the official repository and build the container with my certificate trusted (like the It4lik answer).

**Comment by e311043** [comment]
Hi all

I have the same problem on centos 7.
Push step OK
but I can not see my images in Portus

log registry

2017-10-13T09:37:33.981195000Z time="2017-10-13T09:37:33Z" level=warning msg="httpSink{https://registry.infa.fr/v2/webhooks/events} encountered too many errors, backing off"
2017-10-13T09:37:34.989905000Z time="2017-10-13T09:37:34Z" level=error msg="retryingsink: error writing events: httpSink{https://registry.infa.fr/v2/webhooks/events}: error posting: Post https://registry.infra.fr/v2/webhooks/events: x509: certificate signed by unknown authority, retrying"

This is my docker-compose.yml

version: "2"

services:

  portus:

    image: opensuse/portus:head

    environment:

      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are

      # probably better off with Docker Swarm secrets.

      PORTUS_PRODUCTION_HOST: db

      PORTUS_PRODUCTION_DATABASE: portus_production

      PORTUS_PRODUCTION_PASSWORD: ${DATABASE_PASSWORD}

      # Secrets. It can possibly be handled better with Swarm's secrets.

      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}

      PORTUS_KEY_PATH: /certificates/portus.key

      PORTUS_PASSWORD: ${PORTUS_PASSWORD}

      # SSL

      PORTUS_PUMA_TLS_KEY: /certificates/portus.key

      PORTUS_PUMA_TLS_CERT: /certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,

      # uncomment this line.

      #RAILS_SERVE_STATIC_FILES: 'true'

    ports:

      - 3000:3000

    links:

      - db

    volumes:

      - ./secrets:/certificates:ro

      - static:/srv/Portus/public

  crono:

    image: opensuse/portus:head

    environment:

      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are

      # probably better off with Docker Swarm secrets.

      PORTUS_PRODUCTION_HOST: db

      PORTUS_PRODUCTION_DATABASE: portus_production

      PORTUS_PRODUCTION_PASSWORD: ${DATABASE_PASSWORD}

      # Secrets. It can possibly be handled better with Swarm's secrets.

      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}

      PORTUS_KEY_PATH: /certificates/portus.key

      PORTUS_PASSWORD: ${PORTUS_PASSWORD}

      # We want to execute crono, not portus

      PORTUS_INIT_COMMAND: bin/crono

    links:

      - db

    volumes:

      - ./secrets:/certificates:ro

  db:

    image: library/mariadb:10.0.23

    environment:

      MYSQL_DATABASE: portus_production

      # Again, the password shouldn't be handled like this.

      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}

    volumes:

      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:

    image: library/registry:2.6

    command: ["/bin/sh", "/etc/docker/registry/init"]

    environment:

      # Authentication

      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token

      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}

      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}

      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL

      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt

      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint

      REGISTRY_NOTIFICATIONS_ENDPOINTS: >

        - name: portus

          url: https://${MACHINE_FQDN}/v2/webhooks/events

          timeout: 2000ms

          threshold: 5

          backoff: 1s

    volumes:

      - /var/lib/portus/registry:/var/lib/registry

      - ./secrets:/secrets:ro

      - ./registry/config.yml:/etc/docker/registry/config.yml:ro

      - ./registry/init:/etc/docker/registry/init:ro

    ports:

      - 5000:5000

      - 5001:5001 # required to access debug service

    links:

      - portus:portus

  nginx:

    image: library/nginx:alpine

    volumes:

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

      - ./secrets:/secrets:ro

      - static:/srv/Portus/public:ro

    ports:

      - 80:80

      - 443:443

    links:

      - registry:registry

      - portus:portus

volumes:

  static:

    driver: local

Can you help US.

Regards

[docker-compose.yml.txt](https://github.com/SUSE/Portus/files/1382112/docker-compose.yml.txt)

**Comment by mssola** [comment]
A lot has happened meanwhile, and we are now providing tons of examples, and we have also documented how to properly [deploy portus](http://port.us.org/docs/deploy.html) on production.
