### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1010]
There are a couple of tests that are flaky (aka they fail unreliably every now and then). We should fix those.

**Comment by monstermunchkin** [comment]
I second that. One of them is `RepositoriesHelper#render_push_activity creates the proper HTML for each kind of activity`. I don't think I've come across any others so far.

**Comment by mssola** [comment]
There's another in the `spec/features` directory, but I don't remember which one.

**Comment by monstermunchkin** [comment]
PR #1011 doesn't seem to fix the failing build. See https://travis-ci.org/SUSE/Portus/jobs/147950881
