### ISSUE TITLE
Logged-in user can pull from namespace, but not see the namespace in the web interface

### ISSUE THREAD

**Issue by PadaKwaak** [SUSE/Portus#1013]
Hi,

We have the situation where :
- a (team) namespace's visibility is set to "Logged-in users can pull images from this namespace"
- the logged-in user isn't a member of the team owning that namespace

Now that user can pull images from the namespace, which is what we want, HOWEVER, that user cannot see the namespace in the Portus web interface.

I'm not sure whether its intentional or a bug.

Our setup is configured using docker-compose and the web interface reports the version as 2.1.0-dev 

Thank you in advance!

**Comment by PadaKwaak** [comment]
I just have to add that the logged-in user can actually browse that namespace, but to do that the user would have to acquire the URL to that namespace. eg. https://portus.example.com/namespaces/15

**Comment by monstermunchkin** [comment]
Thanks for reporting, this seems to be a bug. Users should be able to see all namespaces they have access to.
