### ISSUE TITLE
Force that there always has to be an admin user

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#102]
Imagine the following situation:

1. There are no users in our system, and we create a new admin.
2. Go to the admin page and click the "Users" container.
3. Update the current admin user to not be an admin user.
4. Now there are no admin users.

Even though this might be proper behavior, it's unexpected. I propose two solutions:

1. Don't allow to remove admin rights to the last admin.
2. Cleaner solution imho: don't allow a user to "un-admin" itself. This would protect the user from making any mistakes. Therefore, it should be another admin user the one to "un-admin" this user. This way, we make sure that there's always an admin in the system, and that stupid mistakes cannot happen.

**Comment by flavio** [comment]
I have slight preference for the 2nd one.
