### ISSUE TITLE
require pull image have to login

### ISSUE THREAD

**Issue by lamhaison** [SUSE/Portus#1020]
I build system using portus + registry to manage private docker hub
- registry: 2.3.1
- portus: build from source, I have cloned image since 5 days ago

But I face a issue that: I have to login to push image to hub repository, but when I pull image, i do not have to login. But I want to user have to login to pull image from my own private repository.
How to configure to portus require login to pull image?
Thanks

**Comment by holgerreif** [comment]
Have a look at the [namespace documentation](http://port.us.org/features/3_teams_namespaces_and_users.html#kinds-of-namespaces) and [this screenshot](http://port.us.org/build/images/docs/create-namespace2.png). I guess you have set the namespace public.
