### ISSUE TITLE
RFE Download really all activities

### ISSUE THREAD

**Issue by holgerreif** [SUSE/Portus#1022]
With #994 resolved I found out, that there is no possibility to download **all** activities at once. Only the first 25 activities (which would be displayed on first webpage) get into the csv file. This is independent from which page you request the download. 

Manually requesting somthing like `.../admin/activities.csv?page=3` gives the entries from the 3rd page (entries \#51 to \#76).

I guess this is because of the same implementation for html and csv output in `/app/controllers/admin/activities_controller.rb`. The test in `/spec/controllers/admin/activities_controller_spec.rb` doesn't catch this case because there are just 10 entries.

**Proposal**: implement something like `.../admin/activities{.csv}?page=all` and treat this _all_ page special.

**Comment by mssola** [comment]
sigh... You are right :sweat:
