### ISSUE TITLE
Push fails, then succeeds

### ISSUE THREAD

**Issue by SUSEsean** [SUSE/Portus#1032]
sleuser@portus-prod:~> docker push portus-prod.cloud.geeko.land:5000/srickerd/busybox:latest
The push refers to a repository [portus-prod.cloud.geeko.land:5000/srickerd/busybox]
9a39129ae0ac: Preparing 
98305c1a8f5e: Preparing 
0185b3091e8e: Preparing 
ea9f151abb7e: Preparing 
Get http://portus-prod.cloud.geeko.land:5000/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
sleuser@portus-prod:~> docker push portus-prod.cloud.geeko.land:5000/srickerd/busybox:latest
The push refers to a repository [portus-prod.cloud.geeko.land:5000/srickerd/busybox]
9a39129ae0ac: Pushed 
98305c1a8f5e: Pushed 
0185b3091e8e: Pushed 
ea9f151abb7e: Pushed 
latest: digest: sha256:c6674c44c6439673bf56536c1a15916639c47ea04c3d6296c5df938add67b54b size: 1128
## [production.txt](https://github.com/SUSE/Portus/files/413410/production.txt)

production.log attached.

**Comment by monstermunchkin** [comment]
Which version of Portus are you running? Does this happen every time you try and push something?

**Comment by SUSEsean** [comment]
@monstermunchkin

Portus-20151120162040-2.2.x86_64

This is the currently supported version in SLES 12 SP1

**Comment by mssola** [comment]
@SUSEsean are you sure about that ? IIRC the currently supported version is 2.0.5. Am I wrong @jordimassaguerpla ?
