### ISSUE TITLE
lib/tasks/portus.rake#L50 uninialized namespace

### ISSUE THREAD

**Issue by EugenMayer** [SUSE/Portus#1036]
looks like either namespace is not initialized yet or probably in some cases

```
portus      | rake aborted!
portus      | NoMethodError: undefined method `name' for nil:NilClass
portus      | /portus/lib/tasks/portus.rake:50:in `block (2 levels) in <top (required)>'
```

https://github.com/SUSE/Portus/blob/master/lib/tasks/portus.rake#L50
u.namespace.name

**Comment by monstermunchkin** [comment]
This would be the expected behavior if there was no registry configured. Are you sure your registry is configured properly?

**Comment by mssola** [comment]
Another possibility is that the user to be created was supposed to have a private namespace that clashed with an existing one. @EugenMayer maybe this is your case ? If so, we could extend that rake task to be more informative about this case.

**Comment by EugenMayer** [comment]
@mssola it happens during initial bootstrap of a fresh portus using my test-repo https://github.com/EugenMayer/docker-image-portus/tree/master/test - if there is a namespace conflict, i am not sure "how" - its probably related to the entrypoint script https://github.com/EugenMayer/docker-image-portus/blob/master/build/startup.sh#L43

**Comment by mssola** [comment]
Then it's exactly what @monstermunchkin said, you have to create the registry in the DB before creating users. From your `startup.sh` I see that you are creating the admin user right before creating the registry, you should do this the other way around :wink:

From our side, maybe we can improve this by adding a check for the existence of a registry before doing anything at all. And it would also be nice from our side to provide a rake task for creating a new registry (I see that you have one of your own right ?)
