### ISSUE TITLE
Vagrant image broken

### ISSUE THREAD

**Issue by hotpxl** [SUSE/Portus#1037]
I was trying to `vagrant up` on my Arch Linux box.

It gave me this error:
```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:

set -e
mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the command was:

No such file or directory
```

**Comment by tboerger** [comment]
There is also a vagrant plugin available that automatically installs the virtualbox guest additions

**Comment by mssola** [comment]
We are using Virtualbox in our vagrant setup. So, first of all make sure that your virtualbox installation is fine.

**Comment by hotpxl** [comment]
Yes. Virtualbox backend works with other vagrant images (like debian and such)

**Comment by mssola** [comment]
I tried the vagrant setup again, and everything works fine on my machine. Make sure that guest additions really work on your system (e.g. you have the proper packages installed, proper permissions, etc).

**Comment by hotpxl** [comment]
OK. I'll try later and reopen if problem still persists.
