### ISSUE TITLE
Make password length configurable

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1040]
I'm not entirely sure about this, but it was brought up in the mailing list (see [discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/portus-dev/5jKp70sGqHE/vq05vWxOAAAJ)).

The gist of it is: in LDAP environments, passwords might not match the minimum length required by Portus (and Portus administrators might not be in charge of the LDAP server), so trying to login with Portus with valid LDAP credentials is simply not possible. Moreover, in this specific case, the Portus instance is run internally, so security concerns shouldn't be that important.

Of course, this would be really discouraged but it would solve this scenario. I'm not entirely sure about adding this, and that's why I'm adding the `discussing` label.

**Comment by maksonlee** [comment]
Security is important, but if we decide to authenticate to ldap, maybe we should let ldap to check the password policy, portus should do the check only when using built-in authentication.

**Comment by Mika56** [comment]
:+1: I'm currently having issues with this :)
I think that while Portus is right to enforce a password policy (that should be configurable) for internal users, I can't enforce one for external users, the LDAP directory should

**Comment by BBBernsteyn** [comment]
When delegating authentication to LDAP it really stops being Portus' responsibility to enforce password policies. I dug around in `devise` and found the responsible validation in the `validatable` module [here](https://github.com/plataformatec/devise/blob/69bee06ceee6280b54304928bb6e55c5064abad8/lib/devise/models/validatable.rb#L35).

What do you think about disabling the `validatable` module in the user model (see gist [here](https://gist.github.com/BBBernsteyn/11b2e507da343ec0f191ab84f3f5698a)) in LDAP setups?

**Comment by holgerreif** [comment]
I am wondering why password policy is enforced at logon time. Usually a policy is enforced at password generation/change time, eventually accompanied by the possibility for an admin user to override this policy.

**Comment by BBBernsteyn** [comment]
I skimmed the documentation but to no avail. What if we asked the generous folks to give us devise to explain their rationale?

**Comment by mssola** [comment]
Fixed with #1064
