### ISSUE TITLE
Unable to delete created namespaces

### ISSUE THREAD

**Issue by bbraunstein** [SUSE/Portus#1045]
I have Portus fully configured and running for production deployment, but the only outstanding issue I see I that I cannot delete created namespaces. I created a team and then a namespace underneath that team. 

I want to remove the namespace now, but I do not see any option to delete it. I have `delete enabled true` in my config.yml and I am able to delete and manage images/tags. The only blocking point for me at the moment is namespace deletion.

**Comment by holgerreif** [comment]
This is not implemented yet and tracked in #767

**Comment by mssola** [comment]
Closing in favor of #767. We expect to implement this in the following days :wink:
