### ISSUE TITLE
Why normal user can delete other's image ?

### ISSUE THREAD

**Issue by AEGQ** [SUSE/Portus#1057]
I  want to delete two images at a time , while images are  from two different portus. (same DB  and using rsync to sync images )

 Unable to do that from web page ,so I made a simple [tool](https://github.com/AEGQ/Registry-Sync/blob/master/test/rmi.go) .

what i did :

#### 2、Use that token to delete other people's image . it works . why?

I think may be it's a safety problem , so create this issue here . 

(Sorry for my poor english ,hope you can understand what i said . If it is not a problem for you ,Just close this issue , it's ok )

### log:

```
[13] 10.43.175.162 - - [05/Sep/2016:09:05:14 +0000] "GET /v2/token?account=10039212&service=hub.com:5000&scope=repository:10036782/rcp-ft-centos:* HTTP/1.1" 200 - 0.3031
Started POST "/v2/webhooks/events" for 10.43.175.162 at 2016-09-05 09:05:14 +0000
Processing by Api::V2::EventsController#create as JSON
Handling 'delete' event:
{
  "id": "0f9f403b-3d7b-4bc1-979e-ff7dabe811fd",
  "timestamp": "2016-09-05T09:05:14.800004271Z",
  "action": "delete",
  "target": {
    "digest": "sha256:0a30385dd641c0c9ca66a0b43b2fa9e93a6cd109c009721fc9a5a192162d4e95",
    "repository": "10036782/rcp-ft-centos"
  },
  "request": {
    "id": "11bd2a11-1f32-4fbd-8795-6905b9ae3388",
    "addr": "10.43.175.162:37594",
    "host": "hub.com:5000",
    "method": "DELETE",
    "useragent": "Go-http-client/1.1"
  },
  "actor": {
    "name": "10039212"
  },
  "source": {
    "addr": "bbd2966b8087:5000",
    "instanceID": "b53c68cb-226a-4e7f-a8b1-f1e3506c042f"
  }
}
Completed 202 Accepted in 16ms (ActiveRecord: 1.7ms)

```

### Version:

$ docker -v

Docker version 1.9.1, build a34a1d5

$ docker exec -it portus_registry_1 registry -v

registry github.com/docker/distribution v2.4.1

portus: 

Version: master@3499bae (2016-8-10)

**Comment by holgerreif** [comment]
> Unable to do that from web page ,so I made a simple tool .

Do you mean, you were unable to manually delete a tag from UI at all or do you mean you were unable to do this using just one web UI?

**Comment by AEGQ** [comment]
Thanks @holgerreif !  I mean I‘m unable to do this using just one web UI , but it is not what I am concerning about , the safety problem is . 

#### eg: 

User 10039212 delete image "cent_cn_svn_git_erl18"  which is belongs to user 10165290.

#### Get Token:

```
http://10.43.175.41:80/v2/token?account=10039212&service=hub.com:5000&scope=repository:10165290/cent_cn_svn_git_erl18:*
```

#### Delete Image:
![image](https://cloud.githubusercontent.com/assets/16302289/18259773/5a9884b2-741a-11e6-9049-3360b737bd02.png)
#### Not admin:
![image](https://cloud.githubusercontent.com/assets/16302289/18259793/90d41366-741a-11e6-81e0-d0a4e7f1b94c.png)
![image](https://cloud.githubusercontent.com/assets/16302289/18259848/1507fa76-741b-11e6-9913-7cac6a57f8b9.png)

**Comment by lonewulf** [comment]
Your screenshot shows that the 10039212 user is a Portus admin, and AFAIK, an admin can push/pull/delete in any repository.

**Comment by lonewulf** [comment]
Nevermind, it is the opposite, can you access the user repository with the namespaces/{id} URL ?

**Comment by mssola** [comment]
With your script I haven't been able to reproduce your issue (note that you are using the same username + password combo for both "users").

**Comment by AEGQ** [comment]
Thanks @mssola  :)
I try it again , and it only can be reproduced  while the Visibility of namespace is  **_not_** private .

**Comment by AEGQ** [comment]
Finally, I got  [this](https://github.com/SUSE/Portus/blob/master/app/controllers/api/v2/tokens_controller.rb#L66). 

It won't  be equal  in this case:

auth_scope.actions = ["*"] 
action = "all"  

 Hope that helps :)

**Comment by mssola** [comment]
Could you walk me through your script and how you reproduce this issue ? I can see that now in your script you are only using one user, so you are no longer reproducing this exact issue no ? Could you paste the logged messages ? (and it would be awesome if you could run Portus in debug mode (see [this link on how to do it](https://github.com/SUSE/Portus/blob/master/CONTRIBUTING.md#reporting-issues) when doing that :wink:))

**Comment by AEGQ** [comment]
If you want to reproduce it : 

Get [rmi.go](https://github.com/AEGQ/Registry-Sync/blob/master/test/rmi.go) and change  **"Webserver","Regserver","Hostname"**

```
	p_162 := Portus{Webserver: "your_portus_server:80",
		Regserver: "your_registry_server:5000",
		Username:  username,
		Password:  password,
		Hostname:  "same_as_your_configuration_in_admin_registries_page:5000"}
```

**Follow the steps to reproduce :**

1、Namespace is not private:
![image](https://cloud.githubusercontent.com/assets/16302289/19259940/6ca361e0-8fb8-11e6-9bc3-1fdc5b9dbc66.png)

2、Delete image:

```
[root@hub test]# go run rmi.go
USERNAME(工号): 10039212
PASSWORD(密码): 123456
IMAGE(namespace/image:tag): 6092002155/centos:7.2.1511
202 Accepted
Delete image from 162 success!
```
3、Log messages in debug mode
```
action all not handled/authorized, removing from actions
[jwt_token] [claim] {:iss=>"hub.com", :sub=>"10039212", :aud=>"hub.com:5000", :iat=>1476169908, :nbf=>1476169903, :exp=>1476170208, :jti=>"LjpQjd6yMS29NFdzcCNbMXm3XmDkkrE5WrxJnP8Tpw", :access=>[{:type=>"repository", :name=>"6092002155/centos", :actions=>["*"]}]}
Completed 200 OK in 215ms (Views: 0.4ms | ActiveRecord: 34.8ms)
[15] 10.43.175.162 - - [11/Oct/2016:15:11:48 +0800] "GET /v2/token?account=10039212&service=hub.com:5000&scope=repository:6092002155/centos:* HTTP/1.1" 200 - 0.3699
Started POST "/v2/webhooks/events" for 10.43.175.162 at 2016-10-11 15:11:48 +0800
Processing by Api::V2::EventsController#create as JSON
Incoming event:
{
  "id": "505fa7fc-7653-46f0-ab2e-b783c19b10e6",
  "timestamp": "2016-10-11T15:11:48.559477505+08:00",
  "action": "delete",
  "target": {
    "digest": "sha256:c98a0289eeba9fc68b714b39820a8c4cfeff09df9a051e69ac1bd80afd2b97e9",
    "repository": "6092002155/centos"
  },
  "request": {
    "id": "8323bf09-0fa7-471c-8f9d-d9061948f6b9",
    "addr": "10.43.175.162:51798",
    "host": "hub.com:5000",
    "method": "DELETE",
    "useragent": "Go-http-client/1.1"
  },
  "actor": {
    "name": "10039212"
  },
  "source": {
    "addr": "a0d814c63b6b:5000",
    "instanceID": "68e6ca10-ce62-4094-8f85-63530c10cf76"
  }
}
```

**As you can see action all is not removed successfully :)**

**Comment by mssola** [comment]
@AEGQ thanks a lot! With that I could reproduce it and finally got to the problem. The PR #1084 fixes this :+1:

**Comment by AEGQ** [comment]
Thats good, thanks for your job, and I will close this issue now.  谢谢 :)
