### ISSUE TITLE
remove images and GC

### ISSUE THREAD

**Issue by fahimeh2010** [SUSE/Portus#1059]
Hello all

I just installed the newest protus on github ( https://github.com/SUSE/Portus).
there is "Delete image" link located on the top right corner of the page, and I can delete images. but when I want garbage-collect on registry container using:
bin/registry garbage-collect [--dry-run] /etc/docker/registry/config.yml
it returns:

configuration error: open garbage-collect: no such file or directory

Usage:
  registry <config> [flags]
Flags:
  -h, --help=false: help for registry
  -v, --version=false: show the version and exit

actually the version of docker registry used in the latest released Portus is 2.3.1 and sounds like garbage-collect is avalible on registry 2.4. is that correct?

Based of this link (http://port.us.org/features/removing_images.html) the version of 2.1 is avalible where can I download it?

Thanks a lot

**Comment by holgerreif** [comment]
Just in case you havn't found out yourself already:

> actually the version of docker registry used in the latest released Portus is 2.3.1 and sounds like garbage-collect is avalible on registry 2.4. is that correct?

Yes, you have to use registry 2.4 or newer. registry 2.3.1 does not contain a garbage collector.

> Based of this link (http://port.us.org/features/removing_images.html) the version of 2.1 is avalible where can I download it? 

Version 2.1 was released on september 30th, the current version is [2.1.1](https://github.com/SUSE/Portus/releases/tag/2.1.1). However, if you were able to delete images from the web ui you probably used a current git version so just changing the registry version for a quick test should be sufficient.
