### ISSUE TITLE
Portus 2.0.5 installation with local registry

### ISSUE THREAD

**Issue by adidragomir** [SUSE/Portus#1061]
Hi,
I was trying to install Portus version 2.0.5 on OpenSuse Leap 42.1 64bit. When I run portusctl setup --local-registry I've got the following messages:

"ssl" already present
missing file /etc/apache2/ssl.key/mycomputer.domain.com-ca.key

Installing Portus version 2.0.3 is working.

Thank you for your help.

**Comment by mssola** [comment]
Closing since more versions have been released since then. If this is still relevant, please feel free to re-open it.
