### ISSUE TITLE
Some users can not be found and some are repeated  in "/admin/users" page!

### ISSUE THREAD

**Issue by AEGQ** [SUSE/Portus#1080]
I want make a user to be admin today, but **can not found** him in the admin page. 
and more weird thing is that some users appear again in the last page.

### repeated :
**page 1:**
![image](https://cloud.githubusercontent.com/assets/16302289/19230067/d2706388-8f04-11e6-950b-98bb71697623.png)
**page 5:**
![image](https://cloud.githubusercontent.com/assets/16302289/19230029/82589b40-8f04-11e6-8f0e-0168be87f8ad.png)

When i change this [line](https://github.com/SUSE/Portus/blob/master/app/controllers/admin/users_controller.rb#L6):

![image](https://cloud.githubusercontent.com/assets/16302289/19230124/4ad6641c-8f05-11e6-9302-8c44215f8806.png)

To this :

```
  def index
    @users = User.not_portus.order(:created_at).page(params[:page])
    @admin_count = User.admins.count
  end 
```

**It works !**  No more repeated users and lost users are back to the page. but I don't known why , may be there is a bug or some thing. hope that helps :)

**Comment by mssola** [comment]
That's really weird :confused: Could you provide a set of users in which you can reproduce this ? (I cannot reproduce this). Moreover, instead of ordering by `created_at` I'd say that it would make more sense to order by `username`.

**Comment by tboerger** [comment]
I would recommend to add the ordering anyway because otherwise the ordering is not guaranteed

**Comment by AEGQ** [comment]
If you want to reproduce it ,try this:
 
**Backup your database and use this one:**

docker exec portus_db_1 mysql -uroot -pportus -e "drop database portus_development;create database portus_development;use  portus_development;source /var/lib/mysql/[portus_development_only_users.txt]
(https://github.com/SUSE/Portus/files/520766/portus_development_only_users.txt);"

**Login :**

portus/portus1234

**reproduce:**

1、login 
2、go to admin/users page
3、you will see there is something wrong ( If the first user isn't "00004444", try to login again)

**Comment by mssola** [comment]
I still cannot reproduce this. That being said, as suggested by @tboerger I'll introduce the `order` method just to make sure that order is guaranteed. Apparently with this it should work for your right (ordering by username) ?

**Comment by AEGQ** [comment]
Yes , when I use **.order(:username)**, It still works :)

**Comment by mssola** [comment]
#1083 should fix this for you then :wink:
