### ISSUE TITLE
Same description for KEY_PATH and PASSWORD on config review page

### ISSUE THREAD

**Issue by phaldan** [SUSE/Portus#1095]
When I first run portus only with database config and open it via https on my browser, portus shows the 'Please review your configuration' page. The description for the following config values are the same, only the environment variable are different:
* Fix secret encryption private key path value
* Fix secret portus password

Description for both is `You need to set the secret encryption private key path value for Portus to work.` The description on the first one is correct, but the second one should contain an explanation about the `portus_password` config value.

I am using portus 2.1.1 with a docker setup.

**Comment by mssola** [comment]
Good catch! See PR #1097 for a fix
