### ISSUE TITLE
Allow environment variables for values in config.yml

### ISSUE THREAD

**Issue by phaldan** [SUSE/Portus#1101]
Currently only values within `config/database.yml` and `config/secrets.yml` can be defined by environment variables. It would very helpfull, especially with container setups, that also all values within `config/config.yml`can be defined by environment variables.

I know that there is also a `config-local.yml`, which is merged with the `config.yml`, and that could make this feature request more complicated. Another approach could be not to define environment variables within the yml file instead each value could be overridden one by one after the merge with existing environment variables.

**Comment by mssola** [comment]
This is already available (see [this section from the documentation](http://port.us.org/docs/Configuring-Portus.html#override-specific-configuration-options)). So, for example, if you wanted to disable the signup page you could set the following environment variable:

    $ export PORTUS_SIGNUP_ENABLED=false

Therefore I will close this issue. If you have any more questions, feel free to comment on this issue :wink:
