### ISSUE TITLE
Error when redering activity stream on admin dashboard after user has been deleted

### ISSUE THREAD

**Issue by AndreasKrause** [SUSE/Portus#1106]
The following process leads to an error when rendering the admin dashboard activity stream:
- create user
- assign user to team
- delete user

The activity stream then fails to render the add member event of the the deleted user emitting this output:

```
portus-web      | App 157 stdout: Started GET "/admin/dashboard" for 10.180.43.80 at 2016-10-25 05:46:03 +0000
portus-web      | App 157 stdout: Processing by Admin::DashboardController#index as HTML
portus-web      | App 157 stdout:   Rendered public_activity/namespace/_change_visibility.html.slim (3.1ms)
portus-web      | App 157 stdout:   Rendered public_activity/namespace/_change_visibility.html.slim (2.1ms)
portus-web      | App 157 stdout:   Rendered public_activity/team/_add_member.html.slim (3.3ms)
portus-web      | App 157 stdout:   Rendered public_activity/user/_delete.html.slim (1.2ms)
portus-web      | App 157 stdout:   Rendered public_activity/user/_delete.html.slim (1.1ms)
portus-web      | App 157 stdout:   Rendered public_activity/user/_delete.html.slim (1.1ms)
portus-web      | App 157 stdout:   Rendered public_activity/team/_remove_member.html.slim (2.5ms)
portus-web      | App 157 stdout:   Rendered public_activity/team/_add_member.html.slim (2.5ms)
portus-web      | App 157 stdout:   Rendered admin/dashboard/index.html.slim within layouts/application (26.3ms)
portus-web      | App 157 stdout: Completed 500 Internal Server Error in 32ms (ActiveRecord: 3.3ms)
portus-web      | App 157 stdout:
portus-web      | App 157 stdout: ActionView::Template::Error (undefined method `display_username' for nil:NilClass):
portus-web      | App 157 stdout:      7:     .description
portus-web      | App 157 stdout:      8:       h6
portus-web      | App 157 stdout:      9:         strong
portus-web      | App 157 stdout:     10:           = "#{activity_owner(activity)} added user #{activity.recipient.display_username} "
portus-web      | App 157 stdout:     11:         = "with role #{activity.parameters[:role]} to the "
portus-web      | App 157 stdout:     12:         = link_to activity.trackable.name, activity.trackable
portus-web      | App 157 stdout:     13:         |  team
portus-web      | App 157 stdout:   app/views/public_activity/team/_add_member.html.slim:10:in `_app_views_public_activity_team__add_member_html_slim___3943678674634899904_35324520'
portus-web      | App 157 stdout:   app/views/admin/dashboard/index.html.slim:75:in `block in _app_views_admin_dashboard_index_html_slim___4160765437940232171_70271074503400'
portus-web      | App 157 stdout:   app/views/admin/dashboard/index.html.slim:74:in `_app_views_admin_dashboard_index_html_slim___4160765437940232171_70271074503400'
portus-web      | App 157 stdout:
portus-web      | App 157 stdout:
portus-web      | App 157 stdout: Processing by ErrorsController#show as HTML
portus-web      | App 157 stdout:   Parameters: {"status"=>"500"}
portus-web      | App 157 stdout:   Rendered errors/500.html.erb within layouts/errors (0.0ms)
portus-web      | App 157 stdout:   Rendered errors/_status_title.html.slim (0.0ms)
portus-web      | App 157 stdout: Completed 500 Internal Server Error in 6ms (Views: 5.4ms | ActiveRecord: 0.0ms)
```

**Comment by AndreasKrause** [comment]
Issue #899 is somehow related to this problem: The activity stream should reflect what happened the very moment the event occured.

**Comment by holgerreif** [comment]
In PR #1041 the userid in activity stream is set to nil (app/controllers/admin/users_controller.rb) however the templates in view/public_activity are not prepared to show the username for userid nil. 
Furthermore, the activity of a removed user should really be shown in audit log: this behaviour actually changes the the audit log, depending on whether it was taken before or after user removal - this is bad!

**Comment by CVTJNII** [comment]
This is a pretty serious bug, I hit it accidentally and can see this flooring a production install easily.  Please prioritize this issue, thanks.

**Comment by mssola** [comment]
Sorry for the delay, but I can also reproduce this and I'm already working on a fix.

> Issue #899 is somehow related to this problem: The activity stream should reflect what happened at the very moment the event occured.

Agreed. This will be the issue that I will tackle next, since it affects the very definition of an audit log.

> Furthermore, the activity of a removed user should really be shown in audit log: this behaviour actually changes the the audit log, depending on whether it was taken before or after user removal - this is bad!

Agreed. That being said, the information to be preserved is the user name, which is what we are also using for other resources (e.g. deleted repositories). Storing other stuff like IDs would not be helpful. I'll submit my PR soon enough, since I still want to perform more testing on this.

**Comment by holgerreif** [comment]
> Agreed. That being said, the information to be preserved is the user name.

Havn't checked how this is currently handled. Same must be done for namespaces (as Flavio pointed out in #899), teams and all other objects subject to removal.

I spent some thoughts on the following idea tables holding names and their corresponding ideas are extended to hold a "status" attribute. 

As an example a  removed user gets not deleted from the database but the attribute is set to "removed" (or something else). Once the user enrolls again admin might decide whether the old user is reinstantiated or a new one is created.

However looking at [`models/user.rb`](https://github.com/SUSE/Portus/blob/master/app/models/user.rb) I guess this would require major rework (cannot use the destroy method of user object, index_users_on_username wouldn't be UNIQUE anymore).

Independent from the above proposal I'd try to not reuse IDs, That way, an information might be missing ("no name for this id") but it will never be wrong ("this id has name B while at thime of event it had name A").

**Comment by mssola** [comment]
> As an example a removed user gets not deleted from the database but the attribute is set to "removed" (or something else). Once the user enrolls again admin might decide whether the old user is reinstantiated or a new one is created.

This is somewhat similar to what we are doing with the `disable users` feature. That being said, I wouldn't want to implement a "remove" feature if the resource itself doesn't really get deleted in the database. This is not about disk space (I don't think that a regular Portus deployments takes too much DB disk space), but about doing the expected thing (I'm sure if we did that people would complain that we are not really removing resources in the database).

So, the current way of handling things is to actually remove the resource, but before doing so, update activities so the activities list does not miss anything.
