### ISSUE TITLE
feature request: split user_permission/manage_namespace

### ISSUE THREAD

**Issue by AndreasKrause** [SUSE/Portus#1109]
As of Portus 2.1 user_permission/manage_namespace/enabled=false enforces both, only administrators can manage namespaces (which is fine) and only administrators can add webhooks for namespaces.

The feature request is to split this permission in a way that only administrators can manage namespaces if user_permission/manage_namespace/enabled is set to false, but still users are able to manage webhooks for a particulat namespace. This permission could be linked to the "Owner" role of the associated team.

**Comment by mssola** [comment]
Makes sense

**Comment by holgerreif** [comment]
There is another right, which is tied to `user_permission/manage_namespace/enabled` and should be separated: The right to edit the description of the namespace.

The main thing I'm concerned about namespace management is the polution with miss-spelled names, just-test-names or miss-taken names.

Maybe it would make sense to have the following different settings for `user_permission/manage_namespace/enabled`:
  * `none`: user cannot do anything
  * `modify` (or `edit`): user is allowed to add webhooks and description (and what else?) and is allowed to delete a namespace (although later could be linked to `create` right) 
  * `create`: user is allowed to create a new namespace

**Comment by mssola** [comment]
Seems like a good idea :+1:

**Comment by mssola** [comment]
A couple of things after #1806 was merged.

> The right to edit the description of the namespace.

I discarded this, because it's too specific. It shouldn't be too bad that it's under `manage_namespace`.

As for the other split (between create and manage), this has already been implemented in other releases and it's already available in `2.3`.

Thanks for the feedback :clap:
