### ISSUE TITLE
Push fails with "unauthorized" message - docker compose setup on Docker for Mac

### ISSUE THREAD

**Issue by genei09** [SUSE/Portus#1110]
---
## BUG REPORT INFORMATION

Running the compose script, setting up Portus, and logging into the registry is functional.  When trying to push images or run curl against the registry an unauthorized message is returned.

**Steps to reproduce the issue:**
1. install latest Docker For Mac (1.12.1 build: 12133)
1. a setup insecure registries in preferences for 127.0.0.1:5000 and localhost:5000
2. clone this repo
3. ./compose-setup.sh -e localhost
4. docker login localhost:5000 (to verify you can't login)
5. docker inspect portus_registry_1 to get the registries docker network ip
6. setup portus from web interface (http://localhost:3000) use that IP for the registry
7. docker login localhost:5000 (verify that you can now login)
8. attempt to push an image
9. curl http://<uname>:<password>@<registry_ip>:5000/v2/

**Describe the results you received:**

response is Unauthorized

**Describe the results you expected:**

image is pushed to the registry

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 45
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: JIBC:LGTI:2BUF:ILL5:ZJFL:PXAB:JQXN:JFYU:IRC3:QHKA:EGDG:MFXF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 53
 System Time: 2016-10-25T14:57:42.207512218Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.1:5000
 localhost:5000
 127.0.0.0/8
```

**Comment by mssola** [comment]
Hi

> ./compose-setup.sh -e localhost

Are you sure that this is the value that you want to use ? Usually it's the IP as given by the default docker bridge (docker0).

>  docker login localhost

You must provide the URL of your registry.

**Comment by genei09** [comment]
"docker for mac" uses localhost to communicate with containers.  localhost works perfectly for reaching the Portus web interface and for logging into the registry.  It is only when attempting to push that I encounter an issue.

I considered that the reference in Portus setup to the registries docker network IP might not line up with the use of localhost or 127.0.0.1.  So I added the containers hash to /etc/hosts on all the containers and my mac.  I reconfigured portus to use the hash to identify the registry, and it was able to communicate.  I was able to login to the registry from my mac.  However the push still fails with the same message.

**Comment by mssola** [comment]
Could you paste the exact logs being written by both the registry and portus containers ?

**Comment by genei09** [comment]
where is portus logging in the latest container version (I figure it's easier to ask than go hunting)?

**Comment by genei09** [comment]
In my original repo I accidentally left off the port 5000 for the login command.  I've updated the original post to reflect this reality.

**Comment by genei09** [comment]
I had to edit the registry config and change localhost:3000 to <portus docker ip>:3000 and localhost:5000 to <registry docker ip>:5000.

I got the IPs by running `docker inspect <container> | grep \"IPAddress\"`

**Comment by mssola** [comment]
With the examples we provide now this shouldn't happen :+1: Check out the documentation on [how to deploy](http://port.us.org/docs/deploy.html) portus for more info
