### ISSUE TITLE
Faster creation of teams and namespaces

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1112]
It might be useful to have a way to create teams and namespaces faster. That is, if you are planning to create teams and namespaces that are pretty similar and that they have a similar team members list.

**Comment by holgerreif** [comment]
Cool idea, would have been convinient for a migration.. 
And it sounds like a job for `portusctl`.

**Comment by holgerreif** [comment]
I just found out, why it is cool: I made a similiar proposal recently #1024 :-)
Furthermore I suggest looking again over #763 and decide whether a formal API with a well defined subset of the functionality might be desirable and should be used for this proposal underneath `portusctl`

**Comment by mssola** [comment]
This is already handled through #1403 and #1412.
