### ISSUE TITLE
New user signup and admin create user fields inconsistent

### ISSUE THREAD

**Issue by CVTJNII** [SUSE/Portus#1115]
On the new user page at /users/sign_up the field order is
- email
- username
- password
- password confirmation

However, on /admin/users/new the order is
- username
- email
- password
- password confirmation

Note the email/username reversal.  This is a relatively minor nuisance but it has tripped me in tests where I was destroying and recreating Portus VMs and started to get muscle memory on the user creation pages.  It would be nice if they could be made consistent.

**Comment by mssola** [comment]
Agreed
