### ISSUE TITLE
SMTP settings inhereting bad defaults

### ISSUE THREAD

**Issue by CVTJNII** [SUSE/Portus#1117]
I suspect this is is larger than SMTP, but limiting the report to where I know the bug is.

Take the following SMTP local-config for a host without auth:

```
$ cat config-local.yml 
email:
  smtp:
    enabled: true
    address: "foo.local"
    port: 25
```

Now, running the portus:info task to print the config:

```
$ docker run -v $(pwd)/config-local.yml:/portus/config/config-local.yml portus_web rake portus:info
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: http://

Portus version: 2.2.0-dev
Portus has evaluated the following configuration:

---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: true
    address: foo.local
    port: 25
    user_name: username@example.com
    password: "****"
    domain: example.com
```

Note that it has a username and a password which are incorrect inherited defaults.  This will cause email failures if SMTP Auth isn't required.

As I test I tried deleting the defaults from the config.yml file:

```
diff --git a/config/config.yml b/config/config.yml
index f559ecf..dfc7d89 100644
--- a/config/config.yml
+++ b/config/config.yml
@@ -13,11 +13,11 @@ email:
   # (defaults to: /usr/sbin/sendmail -i -t).
   smtp:
     enabled: false
-    address: "smtp.example.com"
-    port: 587,
-    user_name: "username@example.com"
-    password: "password"
-    domain: "example.com"
+#    address: "smtp.example.com"
+#    port: 587,
+#    user_name: "username@example.com"
+#    password: "password"
+#    domain: "example.com"

 # If enabled, then the profile picture will be picked from the Gravatar
 # associated with each user. See: https://en.gravatar.com/
```

However this made the problem worse:

```
$ docker run -v $(pwd)/config-local.yml:/portus/config/config-local.yml cvtjnii/portus:2.1.1-mod rake portus:info
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: http://
No smtp username supplied, not using smtp authentication

Portus version: 2.1.1
Portus has evaluated the following configuration:

---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: true
```

It appears that to merge settings in config-local.yml the key must be present in config.yml.  Setting the to null also doesn't resolve the issue, resulting in this confusing output:

```
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: true
    address: foo.local
    port: 25
    user_name:
    -
    -
    -
    password: "****"
    domain:
    -
    -
    -
```

I suppose this necessitates not using local overrides and controlling config.yml, but it would be nice to be able to remove these attributes.

**Comment by mssola** [comment]
With the `config-local.yml` file what you are doing is to override some default values. So in your case you are only overriding the `enabled`, `address` and `port` fields. So this is working as expected. When using SMTP you are supposed to at least also set the user name, but maybe we can remove this restriction if your SMTP server does not use authentication. Would that work for you ?

**Comment by CVTJNII** [comment]
So I see this as a general problem which is two fold.  When using config-local.yml:
- You cannot unset defaults for keys you do not need (i.e. auth settings if your MTA doesn't require auth)
- You cannot add new keys for settings not present in the default.

For example, here is a config for an unauthenticated, non-SSL, internal MTA:

```yaml
email:
  from: portus@portus.domain
  name: Portus
  reply_to: no-reply@domain
  smtp:
    enabled: true
    enable_starttls_auto: false
    address: internalmailer.domain
    port: 25
    domain: portus@portus.local
```

To enable this the user cannot use config-local because, using config-local, the username and password keys will still exist enabling incorrect auth and the enable_starttls_auto key will not be set.  (And yes, I know this option is a bad thing, I use it as an example.)

I see both of these being resolvable by allowing config-local.yml to add keys to the config, and commenting out dummy default config values from the main config file.  This way if the user doesn't need a value it won't be there to begin with, and if they do need something not in config.yml they can have it in config-local.yml and it will add the new key to the final config.  I believe this is the behavior most would expect when they read that the result is a merging of config.yml and config-local.yml.

**Comment by mssola** [comment]
Moving to 2.4 as the 2.3 release is about to be released.

**Comment by mssola** [comment]
I've tried to reproduce this on 2.3, so it's already fixed I suppose. If you have more issues on this regard don't hesitate and submit more comments :wink:
