### ISSUE TITLE
How do I make a user admin?

### ISSUE THREAD

**Issue by denis-singh** [SUSE/Portus#1124]
How do I add a user to the admin group? I want this user to be able to push to the default namespace.
Currently only the admin account can do that

**Comment by holgerreif** [comment]
Promoting a user to admin is described here:

http://port.us.org/features/3_teams_namespaces_and_users.html#adding-more-admin-users

You reach this site via Admin (left menu) -> Users (top menu)

**Comment by mssola** [comment]
Thanks for stepping in @holgerreif :+1: 

@denis-singh I'll close this issue, but feel free to write more comments if you have any more doubts.
