### ISSUE TITLE
token signed by untrusted key with id : "PTWT:FNJE:7TW7:ULI7:DZQA:JJJI:RDJQ:2M76:HD6G:ZRSC:VPIF:O5BU"

### ISSUE THREAD

**Issue by zzlyzq** [SUSE/Portus#1126]
I am using the portus master branch with my own docker registry v2.3.1, and I met the following issue.

the docker registry's config uses the crt that signed by letsencrypt.

![screenshot 2016-11-29 22 28 10](https://cloud.githubusercontent.com/assets/1989900/20713651/18d52e66-b684-11e6-924d-857fe1220e40.png)
![screenshot 2016-11-29 22 30 01](https://cloud.githubusercontent.com/assets/1989900/20713652/18deb62a-b684-11e6-8083-7a36920a40d1.png)

**Comment by zzlyzq** [comment]
I find this https://groups.google.com/forum/#!topic/portus-dev/j4X53gRsTNk, and in test way.

**Comment by zzlyzq** [comment]
yes, i think i fixed this. I used git clone from the master branch, and compose-setup.sh -f portus.ops.ac.cn to run this app with four docker containers.

The point is compose-setup.sh will generate the crt file called "compose/registry/portus.crt", we should add the crt to private registry config file with the auth port called "rootcertbundle"。

After that：
1. I can run add my private registry on the web and all checked ok
2. I can use docker login with my private registry

before

**Comment by mssola** [comment]
@zzlyzq I'm glad that it works for you. Is it fine if we close this issue then ?

**Comment by zzlyzq** [comment]
sure, i close it .
