### ISSUE TITLE
Anonymous browsing of public namespaces

### ISSUE THREAD

**Issue by Djelibeybi** [SUSE/Portus#1129]
Currently, public namespaces and repos allow non-authenticated pulls but there is no way to browse the content.

It would be great if instead of a login screen, Portus showed all publicly available namespaces and repos on the registry and had a login option to view private and personal namespaces.

**Comment by mssola** [comment]
Originally #290 contained this (even though it also contained other stuff that has already been implemented), and I still think that this is needed. I'll keep this issue open to track this particular aspect. Thanks for reminding me of this :sweat_smile:
