### ISSUE TITLE
Update puma version in requirement ?

### ISSUE THREAD

**Issue by Seb-Solon** [SUSE/Portus#1132]
Hi there, 

Actually the puma version is 2.14 (Gemfile.lock), however this version contains a bug when using chain certificate (it will only send the first one, not the whole chain).

Do you have any objection in removing/updating the version of puma in this file? I have tested with 3.6.2, it seems to work but maybe this is a big gap version for you. 

Do you want me to do a PR to remove the line / change the version to 3.6.2 ? I am not sure on how you perform your test for such changes.

Regards!

**Comment by mssola** [comment]
Hey @Seb-Solon, I updated the gem to 3.6.2 and everything works fine. Thanks for the heads up 👍

**Comment by Seb-Solon** [comment]
Thanks for the fix 😄
