### ISSUE TITLE
insufficient scope for _catalog

### ISSUE THREAD

**Issue by lauriholmas** [SUSE/Portus#1134]
I'm trying to call _catalog in a private registry with portus as the auth & auth. ( I have my portus and registry services named as their urls, not sure if required, but it works with it atleast ) 

I call the registry, and get a 401 Unauth but I see the bearer realm etc from the headers:
`curl -I https://registry-url/v2/_catalog`
Result: 
```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://portus-url/v2/token",service="registry-url",scope="registry:catalog:*"
X-Content-Type-Options: nosniff
Date: Tue, 13 Dec 2016 12:33:14 GMT
Content-Length: 134
```

I pick up the realm from the header, and make a token request to portus: 
```
curl -i --user user:tokenFromPortusWebUi https://portus-url/v2/token?
service=registry-url&scope=registry:catalog:*
```
Result: 
`{"token":"lengthyStringContainingToken","expires_in":300,"issued_at":"2016-12-13T13:18:39+00:00"}`

I then proceed to call the initial _catalog url by adding the token in the authorization header: 
`curl -I -H "Authorization: Bearer lengthyStringContainingToken" https://registry-url/v2/_catalog`
Result:
```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://portus-url/v2/token",service="registry-url",scope="registry:catalog:*",error="insufficient_scope"
X-Content-Type-Options: nosniff
Date: Tue, 13 Dec 2016 13:19:28 GMT
Content-Length: 134
```

The expected results would be a listing of images available to that user. 

The user I am using to make the call with happens to be an admin, so I would assume he should have sufficient access. I can't find anything about allowing/disallowing _catalog calls, and I would assume users would see the catalogs that their visibility allows them to see.

**Comment by jMonsinjon** [comment]
Same issue....
Any news ?

**Comment by fr-butch** [comment]
If you split token by dots you can decode this parts with base64. In second part  field "access" is empty for `scope="registry:catalog:*"`.
Example:
```
{
"iss":"<realm>",
"sub":"<user>",
"aud":"<realm>",
"iat":1489055819,
"nbf":1489055814,
"exp":1489056119,
"jti":".......",
"access":[]}
```

But it must contain scope specific data: `"access":[{"type":"repository","name":"some/thing","actions":["pull"]`

**Comment by kayrus** [comment]
I have the same issue

**Comment by sujjit1991** [comment]
Hi , I requested the  access token using the same command 

curl -i --user user:tokenFromPortusWebUi https://portus-url/v2/token?
service=registry-url&scope=registry:catalog:*

but the result is quite different 


!DOCTYPE html><html><head><title>Portus</title><link rel="stylesheet" media="all" href="/assets/application-9bf189edb6b30009b53dd9b0f49fc59d.css" /><script src="/assets/application-febd0e81a3221047d447ed25f2d0b036.js"></script><meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="K8WWYMbkXJZyCRTntmcCE57ekVmENweaq58OGAtay539MIwJPA5Uubf4mg+eS22Y11oVbH/XJ8HNxwOCV+d8Rw==" /><meta content="width=device-width, initial-scale=1" name="viewport" /><link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57" /><link href="/favicon/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60" /><link href="/favicon/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72" /><link href="/favicon/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76" /><link href="/favicon/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114" /><link href="/favicon/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120" /><link href="/favicon/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144" /><link href="/favicon/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152" /><link href="/favicon/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180" /><link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png" /><link href="/favicon/android-chrome-192x192.png" rel="icon" sizes="192x192" type="image/png" /><link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png" /><link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png" /><link href="/favicon/manifest.json" rel="manifest" /><link color="#205683" href="/favicon/safari-pinned-tab.svg" rel="mask-icon" /><link href="/favicon/favicon.ico" rel="shortcut icon" /><meta content="Portus" name="apple-mobile-web-app-title" /><meta content="Portus" name="application-name" /><meta content="#da532c" name="msapplication-TileColor" /><meta content="/favicon/mstile-144x144.png" name="msapplication-TileImage" /><meta content="/favicon/browserconfig.xml" name="msapplication-config" /><meta content="#205683" name="theme-color" /></head><body class="login"><div class="container-fluid"><div class="row-0"><div class="center-panel"><div class="col-md-4 col-sm-2 col-xs-1"></div><div class="col-md-4 col-sm-8 col-xs-10"><div class="oops"><img class="broken-lighthouse" src="/assets/layout/portus-error-b5eb83a252ddf33490aafb5547beadd2.png" alt="Portus error" /><h1><strong>Oh no!</strong></h1><h3>Page not found!</h3></div></div><div class="clearfix"></div></div><div class="row-0"><div class="col-sm-8 col-sm-offset-2 error-fixes"><i class="fa fa-exclamation-circle"></i>The page you are looking for does not exist.</div></div></div></div></body></html>



 and when I am checking the portus container logs 

actionController::RoutingError (No route matches [HEAD] "/v2/token,service=registry.com:5000,scope=registry:catalog:*"):
5/11/2017 2:29:22 PM  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
5/11/2017 2:29:22 PM  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
5/11/2017 2:29:22 PM  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
5/11/2017 2:29:22 PM  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
5/11/2017 2:29:22 PM  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
5/11/2017 2:29:22 PM  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
5/11/2017 2:29:22 PM  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
5/11/2017 2:29:22 PM  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
5/11/2017 2:29:22 PM  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
5/11/2017 2:29:22 PM  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
5/11/2017 2:29:22 PM  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
5/11/2017 2:29:22 PM  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
5/11/2017 2:29:22 PM  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
5/11/2017 2:29:22 PM  railties (4.2.2) lib/rails/engine.rb:518:in `call'
5/11/2017 2:29:22 PM  railties (4.2.2) lib/rails/application.rb:164:in `call'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/commonlogger.rb:31:in `call'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/configuration.rb:78:in `call'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/server.rb:541:in `handle_request'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/server.rb:388:in `process_client'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/server.rb:270:in `block in run'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/thread_pool.rb:106:in `call'
5/11/2017 2:29:22 PM  puma (2.14.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
5/11/2017 2:29:22 PM
5/11/2017 2:29:22 PM
5/11/2017 2:29:22 PMProcessing by ErrorsController#show as */*
5/11/2017 2:29:22 PM  Parameters: {"status"=>"404"}
5/11/2017 2:29:22 PM  Rendered errors/404.html.slim within layouts/errors (0.0ms)
5/11/2017 2:29:22 PM  Rendered errors/_status_title.html.slim (0.0ms)
5/11/2017 2:29:22 PMCompleted 404 Not Found in 1ms (Views: 1.0ms | ActiveRecord: 0.0ms)
5/11/2017 2:29:22 PM[74] 34.206.145.33 - - [11/May/2017:19:29:22 +0000] "HEAD /404 HTTP/1.1" 404 - 0.0054
5/11/2017 2:29:43 PMStarted HEAD "/v2/token,service=registry.com:5000,scope=registry:catalog:*" for xx.xx.xxx.xx at 2017-05-11 19:29:43 +0000
5/11/2017 2:29:43 PM
5/11/2017 2:29:43 PMActionController::RoutingError (No route matches [HEAD] "/v2/token,service=registry.sandcsw.com:5000,scope=registry:catalog:*"):
5/11/2017 2:29:43 PM  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
5/11/2017 2:29:43 PM  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
5/11/2017 2:29:43 PM  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
5/11/2017 2:29:43 PM  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
5/11/2017 2:29:43 PM  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
5/11/2017 2:29:43 PM  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
5/11/2017 2:29:43 PM  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
5/11/2017 2:29:43 PM  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
5/11/2017 2:29:43 PM  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
5/11/2017 2:29:43 PM  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
5/11/2017 2:29:43 PM  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
5/11/2017 2:29:43 PM  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
5/11/2017 2:29:43 PM  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
5/11/2017 2:29:43 PM  railties (4.2.2) lib/rails/engine.rb:518:in `call'
5/11/2017 2:29:43 PM  railties (4.2.2) lib/rails/application.rb:164:in `call'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/commonlogger.rb:31:in `call'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/configuration.rb:78:in `call'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/server.rb:541:in `handle_request'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/server.rb:388:in `process_client'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/server.rb:270:in `block in run'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/thread_pool.rb:106:in `call'
5/11/2017 2:29:43 PM  puma (2.14.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
5/11/2017 2:29:43 PM
5/11/2017 2:29:43 PM
5/11/2017 2:29:43 PMProcessing by ErrorsController#show as */*
5/11/2017 2:29:43 PM  Parameters: {"status"=>"404"}
5/11/2017 2:29:43 PM  Rendered errors/404.html.slim within layouts/errors (0.0ms)
5/11/2017 2:29:43 PM  Rendered errors/_status_title.html.slim (0.0ms)
5/11/2017 2:29:43 PMCompleted 404 Not Found in 2ms (Views: 1.2ms | ActiveRecord: 0.0ms)
5/11/2017 2:29:43 PM[74] xx.xx.xxx.xx - - [11/May/2017:19:29:43 +0000] "HEAD /404 HTTP/1.1" 404 - 0.0036
Disconnected


can anyone help me am i doing anything wrong.

**Comment by mssola** [comment]
This will work once I improve my [hackweek](https://github.com/mssola/Portus/tree/hackweek_security_scanning) branch and merge it into `master` 😉

**Comment by mssola** [comment]
This should already be fixed. Submit a new issue with further details if this is not the case for either `master` or `v2.3` branches. Thanks 👍
