### ISSUE TITLE
Replace code climate coverage

### ISSUE THREAD

**Issue by ryanfox1985** [SUSE/Portus#1136]
Hi,

you are using Codeclime to calculate the application coverage, do you know [coveralls.io](https://coveralls.io/features)? I think that coveralls.io has good integration with Github and better notifications than Codeclimate.

Regards.

**Comment by mssola** [comment]
Codeclimate is working fine for us, and we have more pressing issues than investigating more on this. So I'll have to close this issue. For future questions, make sure to use our [mailing list](https://groups.google.com/forum/#!forum/portus-dev)
