### ISSUE TITLE
Disable personal namespace for users

### ISSUE THREAD

**Issue by hellivan** [SUSE/Portus#1137]
As already stated in #676, it would be nice to have an option that allows to disable personal namespace for certain users. 

We would need such a feature to handle pure read-only users. Such users by default should not be able to push to any namespace. Having a personal namespace for each user however, grants push privileges (at least for the personal namespace) to each portus user.

Possible solutions would be to either to add a config option that allows to disable personal namespaces, or an option in the users administration that allows the administrator to revoke push permissions for the user's personal namespace.

**Comment by mssola** [comment]
See discussion in #1528 since there are a couple of conflicts to sort out.

**Comment by mssola** [comment]
Marking as fixed due to #1705. Further work will be continued as mentioned in [this comment](https://github.com/SUSE/Portus/issues/1528#issuecomment-366190848).
