### ISSUE TITLE
Portus 2.1 Docker image unavailable on Docker Hub

### ISSUE THREAD

**Issue by gpenin** [SUSE/Portus#1139]
Portus 2.1 has been released on September 2016 but is still unavailable as a Docker image on Docker Hub. Is there any release plan ?

**Comment by broegner** [comment]
I just pulled the opensuse/portus:head image and using it the UI tells me to be "Version: 2.1.0-dev". Unfortunately the [new image / tags removal feature](http://port.us.org/features/removing_images.html) is not part of that build. Would really nice to get that running by just pulling another Docker image.

**Comment by decayofmind** [comment]
+1

**Comment by crunchydave** [comment]
+1

**Comment by blaketmiller** [comment]
+1

What's the status on this? I love Portus, and I'd love to be on the latest version (now 2.2)! I'm in an environment where I am only able to run RHEL, so it's Docker or nothing for me.

**Comment by Djelibeybi** [comment]
`opensuse/portus:head` on Docker Hub is pretty recent. Was built about 4 hours ago of this comment.

**Comment by blaketmiller** [comment]
I'm a bit unfamiliar with development practices for Portus – is head considered relatively stable?

**Comment by Djelibeybi** [comment]
I'm using it, but I'm hardly a large data set. :) YMMV, etc.

**Comment by mssola** [comment]
@Djelibeybi @blaketmiller `opensuse/portus:head` contains the master version of Portus, so bear in mind that it's not really meant for production (maybe staging).

The current state is that we are fixing some issues on the RPM, so it can be better used in the final Docker image (see #1191, #1192, #1194). The goal is to provide an official docker image which has the best of both worlds (minimalistic but still has all the security/reliability feedback from OBS). We are re-doing what we did after some internal discussions and other discussions with members of the community (see #1027 and #912).

I hope we have something ready rather soonish.

**Comment by hiscal2015** [comment]
+1 
I'm expecting version 2.2 production image release

**Comment by hiscal2015** [comment]
@mssola When can be production v2.2 on docker hub?

**Comment by mssola** [comment]
This has already been fixed. The sum things up:

- For 2.1 and 2.2 you have their respective docker images in [here](https://hub.docker.com/r/opensuse/portus/tags/). This image is the same as always (with apache in it).
- The `head` (and the future 2.3) has effectively changed to the new layout as you can see in [this commit](https://github.com/openSUSE/docker-containers/commit/8d1108d782123d1cd08d3d82bf7f77b15c9109c4). So, check out the [README file](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus) again for the changes. The summary is that we greatly simplified the image, stripping away apache in favor of Puma. You can find examples of deployment in the PR #1254 (I still need to polish it and there might be some rough edges though).

Sorry for the wait. Feel free to write more comments here if you have any other doubt!
