### ISSUE TITLE
External hostname vs hostname

### ISSUE THREAD

**Issue by schancel** [SUSE/Portus#1154]
I'm running into a similar issue as https://github.com/SUSE/Portus/issues/774 when trying to run portus in docker compose and Docker for Mac.

It's clear from the logs that "hostname" needs to be configured to the service specified in the registry.  However, in the web UI, when you click advanced, it says:

```
Portus uses the hostname field to communicate with the registry, but this may be on an internal network and inaccessible to the client. Clients may connect to the registry by a name different to the hostname above, for example if it is behind a reverse proxy. This field must be set to prevent Portus from ignoring registry events originating from this external hostname.
```

In the docker-compose setup though, this hostname is _not_ what portus should use to communicate with the registry.  It should instead use "registry" under docker-compose v2.

It seems(?) like the web-ui should be changed to have two fields:  
1) Service name
2) Address to talk to the registry on.

**Comment by mssola** [comment]
Agreed.

**Comment by jordanjennings** [comment]
Is this resolved with the "External Registry Name" field that's now available in the registry settings under "Show Advanced"? I'm not sure if this was available at the time this issue was opened.

**Comment by mssola** [comment]
I think so. Moreover, things have changed in Portus (e.g. docker-compose setup). so this might not be relevant anymore.

@schancel I'll close this issue, but feel free to re-open it if you think this still applies 😉
