### ISSUE TITLE
"Recent activities" show image deleted from portus user but no image was deleted

### ISSUE THREAD

**Issue by truongdo** [SUSE/Portus#1160]
Hi,

The "Recent activities" panel some time shows "deleted" action from portus user and followed by another "pushed" action,
![pic alt](http://i.imgur.com/9ychvLM.png "opt title")
Although this does not cause any problem, I don't understand why it happens?

**Comment by GerardSoleCa** [comment]
Same here using master branch cloned 1 week ago.

Sync does not populate correctly all the images of the registry. If I have some time, I'll try to debug.

**Comment by HartS** [comment]
This looks to be related to #1184

**Comment by mssola** [comment]
Duplicate of an issue grouped in #1599.
