### ISSUE TITLE
.page not working correctly

### ISSUE THREAD

**Issue by lonewulf** [SUSE/Portus#1164]
- Using Portus 2.2

I have some issues seeing all namespaces on the admin page, I debugged it down to:
irb(main):014:0> admin_ns = Namespace.not_portus.where(global: false)
....
irb(main):015:0> admin_ns.count
=> 33
irb(main):017:0> admin_ns.page(1).count + admin_ns.page(2).count
=> 33
irb(main):018:0> (admin_ns.page(1) & admin_ns.page(2)).count
=> 5

Which means page 1 and page 2 have 5 items in common, and a total of 33 items, so I have 5 namespaces missing from being shown

**Comment by mssola** [comment]
I can reproduce this. A quick test showed me that by just ordering it by `created_at` fixes this issue. I'll continue investigating. Thanks for the report!

**Comment by mssola** [comment]
@lonewulf could you tests PR #1183, and check that it works for you ?
