### ISSUE TITLE
defunct ruby processes left behind

### ISSUE THREAD

**Issue by lauriholmas** [SUSE/Portus#1167]
Hello,
I am running Portus in the image from https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus. 
There is a lot of defunct ruby processes left behind. 

wwwrun     121  0.0  0.0      0     0 ?        Z    07:07   0:00 [ruby] <defunct>
wwwrun     249  0.0  0.0      0     0 ?        Z    07:12   0:00 [ruby] <defunct>
wwwrun     259  0.0  0.0      0     0 ?        Z    07:12   0:00 [ruby] <defunct>
wwwrun     275  0.0  0.0      0     0 ?        Z    07:12   0:00 [ruby] <defunct>
wwwrun     562  0.0  0.0      0     0 ?        Z    07:20   0:00 [ruby] <defunct>
wwwrun     570  0.0  0.0      0     0 ?        Z    07:20   0:00 [ruby] <defunct>
wwwrun     580  0.0  0.0      0     0 ?        Z    07:20   0:00 [ruby] <defunct>

I don't know how big a problem those are, but there are a lot of those. After running for a few days there are hundreds or thousands of those. 

~~Maybe not related to this issue, but my portus was not displaying new images pushed into the registry, after resetting ( fully terminating instance which was running the portus docker image and rebuilding a new instance), the new images now appear.~~ Edit: that previous thing was due to a missing db:migrate, the defunct duby processes still remains. My guess is that those ruby processes left behind are the catalog refreshing jobs. Could it be related? Are those harmful?

**Comment by jordimassaguerpla** [comment]
Hi. We would need a bit more information. How are you starting the docker image? Could you give us more information on these process? i.e. run "ps axjf"

**Comment by lauriholmas** [comment]
I'm starting the image with docker-compose -f /path/to/docker-compose.yml up -d
The image is self-built to attach proxydata to the container, but other than that no changes. 

Output of "ps axjf" attached. 
[ps_dump.txt](https://github.com/SUSE/Portus/files/770893/ps_dump.txt)

**Comment by nikolaiderzhak** [comment]
We have got like 4,000+ of that ruby zombies. How bad is it ? And why it happens ?

**Comment by mssola** [comment]
> We have got like 4,000+ of that ruby zombies. How bad is it ? And why it happens ?

What version of Portus is that ? How did you deploy it ?

Just wondering because I don't think this issue is relevant anymore (we are using Puma now instead of Apache, and that should not really happen anymore).

**Comment by lauriholmas** [comment]
I am using Portus by building container mage  from https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus using branch portus-2.2. ( old apache it seems, but there is no branch for 2.3)

**Comment by mssola** [comment]
There is no branch for 2.3 just yet, we'll create it soon. For now you'll have to test this with the `head` tag, which is a bit behind of the `master` branch but you'll be able to check whether this is something affecting you there as well.

**Comment by mssola** [comment]
We've fixed this situation since my [last comment](https://github.com/SUSE/Portus/issues/1167#issuecomment-352014240). I'll close this issue once we create the branch for 2.3, which should happen in the following days.

**Comment by mssola** [comment]
The v2.3 branch has been created already, and the Docker image for it is available as `opensuse/portus:2.3`. Closing 👍
