### ISSUE TITLE
Sync existing docker repo with portus

### ISSUE THREAD

**Issue by kayrus** [SUSE/Portus#1170]
For some reason portus doesn't show/sync the data which is located in existing registry.

When I run `bundle exec rails r bin/client.rb catalog` it prints all the repos which I have in existing registry:

```
$ bundle exec rails r bin/client.rb catalog
[Mailer config] Host:     registry.mydomain.com
[Mailer config] Protocol: https://
[{"name"=>"busybox", "tags"=>["latest"]}, {"name"=>"docker-gc", "tags"=>["latest"]},
... ... ...
{"name"=>"word2vec", "tags"=>["14", "15", "16", "12", "6", "21", "24", "17", "11", "22", "10", "18", "8", "latest", "4", "7", "5", "20", "9", "23", "13"]}]
Size: 99
```

portus logs contain auth log for each request:

```
Started GET "/v2/token?account=portus&scope=repository%3Aword2vec%3Apull&service=registry.mydomain.com%3A444" for 172.17.0.1 at 2017-02-06 15:47:02 +0000
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"portus", "scope"=>"repository:word2vec:pull", "service"=>"registry.mydomain.com:444"}
Completed 200 OK in 107ms (Views: 0.2ms | ActiveRecord: 32.4ms)
```

docker logs:

```
... ... ...
time="2017-02-06T15:44:34Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.6.3 http.request.host="registry.mydomain.com:444" http.request.id=735be1d8-dd47-40b7-b267-650ce62fb91d http.request.method=GET http.request.remoteaddr="172.17.0.1:55568" http.request.uri="/v2/word2vec/tags/list?n=100" http.request.useragent=Ruby instance.id=767877e1-fcc2-426a-8a40-4ec6dc7b95d9 vars.name=word2vec version=v2.5.1 
172.17.0.1 - - [06/Feb/2017:15:44:34 +0000] "GET /v2/word2vec/tags/list?n=100 HTTP/1.1" 401 140 "" "Ruby"
time="2017-02-06T15:44:34Z" level=info msg="response completed" go.version=go1.6.3 http.request.host="registry.mydomain.com:444" http.request.id=1e4ed089-3739-48b2-aa61-287cb5a5ceb9 http.request.method=GET http.request.remoteaddr="172.17.0.1:55578" http.request.uri="/v2/word2vec/tags/list?n=100" http.request.useragent=Ruby http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.210185ms http.response.status=200 http.response.written=132 instance.id=767877e1-fcc2-426a-8a40-4ec6dc7b95d9 version=v2.5.1 
172.17.0.1 - - [06/Feb/2017:15:44:34 +0000] "GET /v2/word2vec/tags/list?n=100 HTTP/1.1" 200 132 "" "Ruby"
```

But it doesn't show anything in the web interface.

**Comment by kayrus** [comment]
Looks like `bundle exec rails r bin/client.rb catalog` is not how I should run the sync. Crono is not what I need right now. Is there any rake job which just synchronizes the repo?

**Comment by JoKre17** [comment]
Hey kayrus,

can you tell me where I can find the portus logs?
I am running portus as a docker container as well and i can only achieve the portus_web_1, portus_crono_1 and portus_db_1 log with "docker logs portus_X_1"

And the mounted Portus directory contains a log folder which is empty except a 0 Byte sized development.log file.

Except this, I am struggling at the same point, that not every repository is imported. Ruby code says there are the following lines in catalog_job.rb:
"catalog.each do |r|
      if r["tags"].blank?
        Rails.logger.debug "skip upload not finished repo #{r["name"]}"
      else
        repository = Repository.create_or_update!(r)
        dangling_repos.delete repository.id unless repository.nil?
      end
    end"
which logs a repository, if the tags json component is empty. But so far I did not find any Rails logs.

**Comment by kayrus** [comment]
@JoKre17  I use `docker logs` functionality to fetch the logs.

**Comment by mssola** [comment]
I believe this is fixed. Check out the new options for the [synchronization part](https://github.com/SUSE/Portus/blob/master/config/config.yml#L293). If you are facing further issues after this, please tell us so in the issue #1599.
