### ISSUE TITLE
Users not allowed to push to Global Registry

### ISSUE THREAD

**Issue by toughIQ** [SUSE/Portus#1178]
I am running Portus 2.2.0 with Registry 2.6.0 and LDAP Users.

I have a strange thing here:
With my user, I am the admin, I can push to my main registry. Other people/accounts cant do this.
They get this error when pushing: 
```
denied: requested access to the resource is denied
unauthorized: authentication required
```
Everything else works as designed. Personal Namespaces, Team Spaces. Even pulling from the main registry with "only logged in users can pull" works fine. The `docker login` command also works for other users than my admin user.

It seems that just pushing to the main registry results in "not authorized" for all other people than admin.

Any ideas on this?

Thanks, Chris

**Comment by toughIQ** [comment]
Or did I miss that only Admins are supposed/allowed to push to the Global Registry?

**Comment by mssola** [comment]
Exactly. See: http://port.us.org/features/3_teams_namespaces_and_users.html#kinds-of-namespaces. I'm closing this, but feel free to write more comments if you have further doubts on this.

**Comment by toughIQ** [comment]
Thanks, @mssola. This is fine by me. I was just a little confused, since I used the registry a while just with my user and got confused, when I let other people in. But it makes sense to only have admins push images to the global registry...avoids getting messed up with stuff ;-)

**Comment by bweston92** [comment]
Logged in as an admin I cannot push to global registry. In fact I can even push to name spaces I can only pull.
