### ISSUE TITLE
Unable to view docker  images on Portus UI

### ISSUE THREAD

**Issue by Roshan56** [SUSE/Portus#1182]
Hi,

I have configured Portus on Centos 7 successfully I am able to push image to registry without any problem but I am not able to see docker images on UI. Its not sync properly. Please find the belows logs for the same.

Docker Version:

docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.47 GiB
Name: registry.ufoeng.com
ID: AYDG:4BNI:GOPS:2W5Z:7JHM:WOCG:ACOI:F3UB:HPTK:MQOP:PUE3:2FPL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

Docker-Compose Version:

docker-compose version 1.10.0, build 4bd6f1a

$ docker push registry.ufoeng.com:5000/admin/busybox
The push refers to a repository [registry.ufoeng.com:5000/admin/busybox]
38ac8d0f5bb3: Pushed 
latest: digest: sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e size: 527

**Error Logs**

**On portus_registry_1**
time="2017-02-13T14:27:02Z" level=error msg="retryingsink: error writing events: httpSink{http://web:3000/v2/webhooks/events}: error posting: Post http://web:3000/v2/webhooks/events: dial tcp 68.64.155.71:3000: i/o timeout (Client.Timeout exceeded while awaiting headers), retrying" 
time="2017-02-13T14:27:02Z" level=warning msg="httpSink{http://web:3000/v2/webhooks/events} encountered too many errors, backing off" 
time="2017-02-13T14:27:08Z" level=info msg="PurgeUploads starting: olderThan=2017-02-06 14:27:08.765890868 +0000 UTC, actuallyDelete=true" 
time="2017-02-13T14:27:08Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=0"

**On portus_crono_1**

Crono terminated with status: 1. Trying again in 10 seconds.
[Mailer config] Host:     registry.ufoeng.com
[Mailer config] Protocol: http://
  Crono::CronoJob Load (0.4ms)  SELECT  `crono_jobs`.* FROM `crono_jobs` WHERE `crono_jobs`.`job_id` = 'Perform CatalogJob every 600 seconds' LIMIT 1
   (0.2ms)  BEGIN
  Crono::CronoJob Exists (0.4ms)  SELECT  1 AS one FROM `crono_jobs` WHERE `crono_jobs`.`job_id` = BINARY 'Perform CatalogJob every 600 seconds' LIMIT 1
  SQL (0.3ms)  INSERT INTO `crono_jobs` (`job_id`, `created_at`, `updated_at`) VALUES ('Perform CatalogJob every 600 seconds', '2017-02-13 14:06:26', '2017-02-13 14:06:26')
   (0.9ms)  COMMIT
I, [2017-02-13T14:06:26.004800 #19]  INFO -- : Loading Crono 0.9.0
I, [2017-02-13T14:06:26.004853 #19]  INFO -- : Running in ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
I, [2017-02-13T14:06:26.004875 #19]  INFO -- : Jobs:
I, [2017-02-13T14:06:26.005045 #19]  INFO -- : 'CatalogJob' with rule 'every 600 seconds' next time will perform at 2017-02-13 19:46:26 +0530
I, [2017-02-13T19:46:26.004867 #19]  INFO -- : Perform CatalogJob
  Registry Load (0.6ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1000
Exception: execution expired
I, [2017-02-13T19:46:28.035704 #19]  INFO -- : Finished CatalogJob in 2.03 seconds
  Crono::CronoJob Load (0.6ms)  SELECT  `crono_jobs`.* FROM `crono_jobs` WHERE `crono_jobs`.`id` = 1 LIMIT 1
I, [2017-02-13T19:56:26.006871 #19]  INFO -- : Perform CatalogJob
  Registry Load (0.5ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1000
Exception: execution expired
I, [2017-02-13T19:56:28.016744 #19]  INFO -- : Finished CatalogJob in 2.01 seconds
  Crono::CronoJob Load (0.4ms)  SELECT  `crono_jobs`.* FROM `crono_jobs` WHERE `crono_jobs`.`id` = 1 LIMIT 1

Thanks,
Roshan

**Comment by Roshan56** [comment]
Hi

Resolved the issue myself for centos 7

Thanks 
Roshan

**Comment by oroc95** [comment]
Hi 
What was the issue ?

**Comment by Roshan56** [comment]
Hello,

Its actually ntp server issue. I have manually set timezone and restart the containers and its working fine.

Thanks,
Roshan
