### ISSUE TITLE
crono continues to delete and add images to portus 

### ISSUE THREAD

**Issue by mikekuriger** [SUSE/Portus#1184]
I've had this problem pretty much forever since we've started using portus over a year ago.  The issue is the when crono runs, it deletes a bunch of tags. Next time it runs, it re-adds them.  This happens over and over.  In our production portus we don't run crono at all due to this issue.  In my test environment the issue is still present in the latest release 2.2.0

**Comment by lonewulf** [comment]
Which version of the docker registry are you running ?
I don't have this issue at all with v2.2.0 and registry v2.5.1

**Comment by mikekuriger** [comment]
I'll give 2.5.1 a try.  I get this error with 2.3, 2.4, and 2.5.   I believe it's due to a timeout issue, as our registry is very large.  This patch for lib/portus/registry_client.rb seems ot have done the trick though

# diff registry_client.rb registry_client.rb.ori 
140,142c140,144
<         res = perform_request("#{repo}/tags/list")
<         if res.code.to_i == 200
<           result << JSON.parse(res.body)
---
>         begin
>           ts = tags(repo)
>           result << { "name" => repo, "tags" => ts } unless ts.blank?
>         rescue StandardError => e
>           Rails.logger.debug "Could not get tags for repo: #{repo}: #{e.message}."

**Comment by mssola** [comment]
@mikekuriger thanks for reporting! If that patch works for you, would you want to submit a PR with that ? I can help you with testing in the PR discussion if you want 😉

**Comment by Vad1mo** [comment]
I see that same issue also with the latest registry 2.5.1. 
Its always a delete followed by a push.  Strange is that the cron job runs every 10 minutes but the push/delete cycle is once a week.

One more thing to note here is the following log statement from the cron job:
```
Could not get tags for repo: acme/rundeck: 
Code: 404
Reported by Registry:
{"code"=>"NAME_UNKNOWN", "message"=>"repository name not known to registry", "detail"=>{"name"=>"acme/rundeck"}}
``` 

Interestingly Rundeck was deleted via Portus but apparently it was still there. I looked up the DB but couldn't find any entry that could lead portus to the conclusion to search for rundeck

**Comment by Alebmurillo** [comment]
Is there any update on this? I have the same issue.

**Comment by Vad1mo** [comment]
maybe #1292 is related with the patch. that otherwise works as expected

**Comment by mssola** [comment]
Closing in favor of #1599.
