### ISSUE TITLE
The placeholder of the search input element should be white

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#119]
This way it distinguishes more with the background, and it follows the same style as the search element itself.

**Comment by cyntss** [comment]
@mssola I tried to work this out but i havent found a solution so far.. other than replacing the entire placeholders...which is a bad idea since all the inputs are white. I will keep looking for a solution to this.

**Comment by mssola** [comment]
Doesn't [this](https://css-tricks.com/snippets/css/style-placeholder-text/) work ?

**Comment by cyntss** [comment]
@mssola no it is exactly what i did, but it isnt working for a singular input, it only works when i apply it to the general layout. There must be some solution but for now i prefer to focus on other things and then I will take care of this issue

**Comment by mssola** [comment]
sure
