### ISSUE TITLE
Remove users in Portus 2.1

### ISSUE THREAD

**Issue by aperdizs** [SUSE/Portus#1248]
Hello!

I want to remove users in Portus 2.1 but I don´t find this option. There isn't a buttom in Admins->Users

Could you help me?

thank you!!!

**Comment by krishnak9** [comment]
I think this is the procedure ...
Press the Users as highlighted.
![1](https://cloud.githubusercontent.com/assets/16056610/23862488/20c764f8-0833-11e7-9afe-803e7fe75bd7.png)
And then remove the user that you wanted.
![2](https://cloud.githubusercontent.com/assets/16056610/23862531/3e50189e-0833-11e7-96c2-9437a85de6f7.png)

**Comment by aperdizs** [comment]
Yes Krishank9. I think it, but this button doesn't appear in my portus dashboard.

could I remove an users in other way? :-S

**Comment by mssola** [comment]
@aperdizs have you enabled delete support ? http://port.us.org/docs/Configuring-Portus.html#delete-support

**Comment by mssola** [comment]
Closing. If you have more doubts, please leave more comments.
