### ISSUE TITLE
Portus doesn't support Tag case sensitivity and makes the UI stop updating

### ISSUE THREAD

**Issue by Alebmurillo** [SUSE/Portus#1262]
The docker registry won't allow uppercase in a image name but it does on tags, but Portus doesn't support this feature. When Portus tries to insert a new tag with the same name as another one but with different upper-lowercase combination, it fails the insert and it doesn't continue updating the rest of the Catalog that the registry sent, so the ui never gets updated and the db insert is failing every minute.

What I had to do to support Tags case sensitivity (Because the registry does I want to be able to do it) is to change the collation of the name column of the tags table in the portus db from utf8_genetal_ci to utf8_bin. It would be nice if the default database creation came with this collation since the beginning.

Thanks, 
Ale

**Comment by mssola** [comment]
Thanks for reporting 👍

**Comment by jmellor** [comment]
We have hit this bug twice now.  Identifying when this bug stops the indexing is tricky, and the workaround is really hackey.  Its a showstopper in real use.

**Comment by rikkuness** [comment]
Just experienced this myself, lots of cases of the crono process throwing exceptions on a CatalogJob trying to `INSERT` both `LATEST` and `latest` etc.

**Comment by raghu999** [comment]
+1 Experienced the same

**Comment by mssola** [comment]
@Alebmurillo @jmellor @rikkuness @raghu999 PR #1494 should do the trick. I've tried to document the issue as much as possible. Feel free to try it out and check if it fixes your issue (it does for me 😉)
