### ISSUE TITLE
Crono pollutes web console debug output

### ISSUE THREAD

**Issue by HartS** [SUSE/Portus#1263]
When running Portus in debug mode, every time Crono runs, it will pull manifests for every tag in every repository. Since we don't process pull events, we get one message like this in our logs for each tag of each repository, every time Crono runs:

```
Started POST "/v2/webhooks/events" for 172.18.0.1 at 2017-03-24 23:09:21 +0000
Processing by Api::V2::EventsController#create as JSON
Incoming event:
{
  "id": "699537fb-5b25-4d05-a56f-af258558a58b",
  "timestamp": "2017-03-24T23:09:21.258581076Z",
  "action": "pull",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 527,
    "digest": "sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f",
    "length": 527,
    "repository": "ns1/busybox",
    "url": "http://172.17.0.1:5000/v2/ns1/busybox/manifests/sha256:32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f"
  },
  "request": {
    "id": "2c2012dd-be5b-476b-a735-2ac5220f5587",
    "addr": "172.18.0.1:36416",
    "host": "172.17.0.1:5000",
    "method": "GET",
    "useragent": "Ruby"
  },
  "actor": {
    "name": "portus"
  },
  "source": {
    "addr": "0a3867778ee1:5000",
    "instanceID": "b247a918-0bbf-41a2-87d9-f471aa287553"
  }
}
Unsupported 'pull' event (supported: ["push", "delete"])
Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
```

This is very noisy, especially because we may set Crono to be more frequently than once every 10 minutes in development.

In the future, if we do decide to handle the pull events (for example, to count the number of pulls, [like docker hub does](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=10000&q=portus)), we will still want to ignore this class of pull events from Crono.

**Comment by mssola** [comment]
This has already been fixed meanwhile I believe.
