### ISSUE TITLE
Sidebar links don't work.

### ISSUE THREAD

**Issue by HartS** [SUSE/Portus#1265]
The links in the sidebar of the dashboard are currently broken due to click intercepts which get bound to them from [dashboard.js](https://github.com/SUSE/Portus/blob/d5d33ecce2332e3313e2b5c7cf55409c13e8d4c4/app/assets/javascripts/dashboard.js), e.g.:
```
  $('#starred a').on('click', function (e) {
    e.preventDefault();
    $(this).tab('show');
  });
```
These intercepts are intended for the links within the tabs themselves, rather than the tab contents (to toggle display of the 'all', 'starred', and 'personal' tabs). Because the IDs which are selected by these intercepts are being given to the tab contents rather than the element containing the links in the tab header, the links to namespaces and repositories within the tab contents can't be followed.

![portus-dashboard-sidebar-bug](https://cloud.githubusercontent.com/assets/11763190/24381605/fe114c70-1305-11e7-83f9-3ba0887b5e9f.png)

**Comment by mssola** [comment]
Fixed with #1289.
