### ISSUE TITLE
Cannot add back a "removed user" because of pre-existing namespace

### ISSUE THREAD

**Issue by eldios** [SUSE/Portus#1269]
## BUG EXPLANATION
Hello Portus-devs,
During one of our tests in our Portus instance, I created a new user and then removed it.
Of course that left the namespace in place as part of other bug/feature already discussed elsewhere.

The "problem" is that if I try to add back that same user, I get back the very logical error/consequence

`Username cannot be used: there is already a namespace named 'test-username'`

## STEPS TO REPRODUCE
0- login to Portus and go in the admin section
1- create a new user
2- delete the user created at step #1
3- try to add again the user created at step #1

## VERSION INFO
Portus version 2.2 running from the official Docker containers (https://hub.docker.com/r/opensuse/portus/)

**Comment by mssola** [comment]
Thanks for reporting 👍

**Comment by eldios** [comment]
This is the specific other issue, "related" to this issue: https://github.com/SUSE/Portus/issues/767

**Comment by eldios** [comment]
@mssola any idea on when this will be fixed? Was this already assigned to a release/milestone?
Thanks

**Comment by mssola** [comment]
This should be fixed for the next version. The release schedule is still to be written. Sorry for the inconvenience...
