### ISSUE TITLE
Portus 2.2.0 can't create registry

### ISSUE THREAD

**Issue by m407** [SUSE/Portus#1270]
On a clean docker image with [openSUSE Portus 2.2.0](https://build.opensuse.org/package/show?project=Virtualization%3Acontainers%3APortus%3A2.2&package=portus)
installed as
`
portusctl setup --local-registry --secure=false --db-name=portus --db-password=portus --db-host=localhost  --ssl-certs-dir=/etc/ssl/servercerts
`

MariaDB and docker-distribution-registry are run side-by-side with  Portus using systemd. Tables in db look right.
But attempt to add registry fails with such an error in apache error log:
`
App 660 stdout:   Parameters: {"utf8"=>"�~\~S", "authenticity_token"=>"qis/4AYx4LZFEhFKCd/x3kO5PGsK46wrnFqubCbEYGcZFW9etHHdx1Es6g8H9EXeiRY+H6KJ5U5hurvN/wDJug==", "registry"=>{"name"=>"local", "hostname"=>"localhost:5000", "use_ssl"=>"0", "external_hostname"=>""}, "commit"=>"Create"}
App 660 stdout: Completed 500 Internal Server Error in 64ms (ActiveRecord: 8.2ms)
App 660 stdout:
App 660 stdout: ActiveModel::MissingAttributeError (can't write unknown attribute `visibility`):
App 660 stdout:   app/models/registry.rb:205:in `create_namespaces!'
App 660 stdout:   app/controllers/admin/registries_controller.rb:40:in `create'
`

It is possible to create registry manualy in db. But creating namespace leads to a similar problem.

**Comment by m407** [comment]
In dockerised environment **portusctl setup** does not inint database properly.

**Comment by so0k** [comment]
I'm having this issue and can't find out how to fix this, any suggestions @m407 ?

**Comment by m407** [comment]
@so0k 
I'm patching portus setup code
```bash
sed -i "s|dockerized?|false|g" portusctl/lib/configurator.rb
```

**Comment by so0k** [comment]
@m407 thanks for fast response, I was actually using https://quay.io/repository/nordstrom/portus -turns out it was portus 2.1
I switched to https://hub.docker.com/r/opensuse/portus/tags/ - tag 2.2 and my problems were solved :)

**Comment by mssola** [comment]
This is no longer valid since you can now use [openSUSE/portusctl](https://github.com/openSUSE/portusctl). Further work will go into the API. Thanks 👍
