### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by gvenka008c** [SUSE/Portus#1271]
We have the latest version of Portus running on our environment. We want to persist the data when we rebuild the images. What are the volumes that needs to be exposed from container to externally mounted volumes for each of the containers?

portus_web_1
portus_crono_1
portus_db_1

**Comment by toughIQ** [comment]
@gvenka008c 
I have Portus running and have the following volumes defined:

web&crono: 
/certificate.pem:/certs/registry.crt:ro
/key.pem:/certs/registry.key:ro

db (mysql):
/portusdb:/var/lib/mysql

I use Rancher for orchestration and use the built in Loadbalancer for SSL offloading and routing.

**Comment by gvenka008c** [comment]
@toughIQ Thanks. How do you retain the user info / namespace / permissions? When I rebuild the images, i loose all these info. I have the below volume mounted for db.

```
 db:
    volumes:
     - /srv/mysql:/var/lib/mysql
```

**Comment by toughIQ** [comment]
@gvenka008c That sounds strange. I took a look at my DB and it seems, that every information regarding Users, Namespaces, etc is in the DB.
So if the DB persists its data, which looks like yours does, everything should stay permanent.
Is your Registry persistent?

**Comment by mssola** [comment]
The `docker-compose` setup has changed quite a lot. Moreover, we've provided a set of production-ready examples in `examples/compose`. Check them out, since they will probably answer your questions 😉 

Closing this now, but feel free to leave more comments if you have more doubts.
