### ISSUE TITLE
Delete Image Button only available for owners of a user group

### ISSUE THREAD

**Issue by tsiepe** [SUSE/Portus#1273]
It is currently possible to configure Portus such that a recycling bin button appears to the right of each tag of an Image.
However, this button can only be configured for the "Owner" of a team. It cannot be made visible for other team members e.g. for those acting in the role "Contributor".
It would be nice to be able to either configure that on a per-user Basis or at least on a per-role basis.

**Comment by mssola** [comment]
I'm not sure this makes sense. Removing an image or a tag is effectively administrating a repository. So, only an admin of the team should be able to do it.

**Comment by tsiepe** [comment]
Although I understand what you're saying our approach to project work appears to be quite different in that we deem everybody - be it an admin or not - to be responsible for keeping the repo clean.

Following the same logic everyone can effectively contribute to the repo by pushing images (hence the role contributor). Now, if we allow them to push images we should also allow them to clean up after themselves again.

That is why I placed the request in the first place.

Would you be willing to reconsider my proposal, please?

Thanks.

 

 

Gesendet: Montag, 10. April 2017 um 16:13 Uhr
Von: "Miquel Sabaté Solà" <notifications@github.com>
An: SUSE/Portus <Portus@noreply.github.com>
Cc: tsiepe <tsiepe@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [SUSE/Portus] Delete Image Button only available for owners of a user group (#1273)


I'm not sure this makes sense. Removing an image or a tag is effectively administrating a repository. So, only an admin of the team should be able to do it.

**Comment by mssola** [comment]
Makes sense. Adding as a possible enhancement 😉

**Comment by mssola** [comment]
We are in code freeze. Delaying to 2.4...

**Comment by vitoravelino** [comment]
As discussed in private, the solution from the user perspective would be a new configuration option under `delete`, e.g.:

```yaml
delete:
  enabled: true     # already exixts
  contributor: true # new option
```

Documenting this to help whenever we implement this feature.
