### ISSUE TITLE
Show portus version in web UI

### ISSUE THREAD

**Issue by kayrus** [SUSE/Portus#1280]
I couldn't find anything which shows current portus version running

**Comment by mssola** [comment]
It should be in the bottom of the page. If you don't see it, can you tell me how did you deploy Portus ?

**Comment by kayrus** [comment]
I've deployed it using master branch. Here is what I see now.
![screenshot_20170410_162722](https://cloud.githubusercontent.com/assets/4047483/24866520/9ff84106-1e0a-11e7-984a-d3f9770a1b2f.png)

**Comment by mssola** [comment]
> I've deployed it using master branch.

What do you exactly mean by that ? 😅 You could've deployed this with docker-compose, vagrant, bare metal, etc. For example, I develop in bare metal and this is what I see:

![lala](https://cloud.githubusercontent.com/assets/767943/24914297/1f56fd92-1ed4-11e7-983d-8c3d790e3ba3.png)

**Comment by kayrus** [comment]
I wonder why I don't see it. Ok, looks like this is my side issue. Thanks.
