### ISSUE TITLE
command to delete all tags of a image except latest tag in portus

### ISSUE THREAD

**Issue by sujjit1991** [SUSE/Portus#1286]
Hi, I need a command to delete all the tags of an image keeping the latest tag. (in PowerShell)

**Comment by mssola** [comment]
I don't quite understand your question. If you want to delete all tags except for one, you can simply click on the trash icon that is available for each tag.

Is this a request to improve the UX of this ? If that's the case, I have a branch on my fork that will improve the situation.

>  I need a command to delete all the tags of an image keeping the latest tag. (in PowerShell)

That looks unrelated to the title, no 😕 ? If you want to do it for your registry, you will have to use Portus' UI (in the branch I mentioned before I started to work on an API that could be used, but that's for the future 😉). So, from the CLI there is not many ways of achieving this (maybe this is doable with [reg](https://github.com/jessfraz/reg) ? I haven't tested it though).

**Comment by sujjit1991** [comment]
HI @mssola  we are using portus version 2.0  and I am unable to find delete option in the UI and in the config file the delete config is set to true del=true,  the are many tags in the repo which I want to delete using docker CLI, I've tried using API request 
curl -v -raw - Xdelete  https://registry.com:5000/v2/namespace/repository/manifesst/tag but there is a 401 error for authorisation asking for the access token and I have logged into the register before using this API request,

HTTP/1.1 401 Unauthorized
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Www-Authenticate: Bearer realm="https://registry.com:443/v2/token",service="registry.com:5000",scope="repository:sujjit/alphine:*"
< X-Content-Type-Options: nosniff
< Date: Wed, 10 May 2017 04:15:31 GMT
< Content-Length: 147
<
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Name":"sujjitdesai/alphine","Action":"*"}]}]}
* Curl_http_done: called premature == 0
* Connection #0 to host registry.com left intact

can you suggest me any way deleting the tags using CLI  and if there is any method can you please explain in detail how to use that function or API.

**Comment by mssola** [comment]
> portus version 2.0

This, right here is your problem 😉 Image/tag deletion is only available since Portus 2.1 ([see documentation](http://port.us.org/features/removing_images.html)).

Also, as I said in my previous comment, you will have other problems by curl'ing since we do not provide an API just yet. Thus, in Portus 2.1 or later you can remove images/tags from the UI, but not from the CLI.

**Comment by sujjit1991** [comment]
@mssola  sorry we are using v 2.1 portus but I still don't find the delete icon in the portus UI , I checked both the config files of registry and portus  the delete option is set to true and I was able to connect to the registry using curl but authorization bearer token is needed from portus web ui ,  I am using this curl command
 curl -i --user sujjitdesai https://registry.com:443/v2/token",service="registry.com:5000",scope="registry:catalog:*

but I am getting the result as 

<!DOCTYPE html><html><head><title>Portus</title><link rel="stylesheet" media="all" href="/assets/application-9bf189edb6b30009b53dd9b0f49fc59d.css" /><script src="/assets/application-febd0e81a3221047d447ed25f2d0b036.js"></script><meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="VXRIRUCYY3KrJrvfq3R4xZGMbis3PCIjkul1Txz7vRRqGoGS7dU1TIbtN04GaxNqV7orf7xlgVwtnP5uHPfbAw==" /><meta content="width=device-width, initial-scale=1" name="viewport" /><link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57" /><link href="/favicon/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60" /><link href="/favicon/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72" /><link href="/favicon/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76" /><link href="/favicon/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114" /><link href="/favicon/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120" /><link href="/favicon/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144" /><link href="/favicon/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152" /><link href="/favicon/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180" /><link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png" /><link href="/favicon/android-chrome-192x192.png" rel="icon" sizes="192x192" type="image/png" /><link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png" /><link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png" /><link href="/favicon/manifest.json" rel="manifest" /><link color="#205683" href="/favicon/safari-pinned-tab.svg" rel="mask-icon" /><link href="/favicon/favicon.ico" rel="shortcut icon" /><meta content="Portus" name="apple-mobile-web-app-title" /><meta content="Portus" name="application-name" /><meta content="#da532c" name="msapplication-TileColor" /><meta content="/favicon/mstile-144x144.png" name="msapplication-TileImage" /><meta content="/favicon/browserconfig.xml" name="msapplication-config" /><meta content="#205683" name="theme-color" /></head><body class="login"><div class="container-fluid"><div class="row-0"><div class="center-panel"><div class="col-md-4 col-sm-2 col-xs-1"></div><div class="col-md-4 col-sm-8 col-xs-10"><div class="oops"><img class="broken-lighthouse" src="/assets/layout/portus-error-b5eb83a252ddf33490aafb5547beadd2.png" alt="Portus error" /><h1><strong>Oh no!</strong></h1><h3>Page not found!</h3></div></div><div class="clearfix"></div></div><div class="row-0"><div class="col-sm-8 col-sm-offset-2 error-fixes"><i class="fa fa-exclamation-circle"></i>The page you are looking for does not exist.</div></div></div></div></body></html>

I tried to use the csrf token as bearer token but I am getting

$ curl -I -H "Authorization: Bearer 8z6hheYSH4I+OBW8em+JL2DsymC6i5j22yVHcD+6Xx3Jc+mRADo9R45FKMvuzlg3nJRA3wWkU3j5xJPvl9bIZQ==" https://registry.com:5000/v2/_catalog
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
Www-Authenticate: Bearer realm="https://registry.com:443/v2/token",service="registry.com:5000",scope="registry:catalog:*",error="invalid_token"
X-Content-Type-Options: nosniff
Date: Thu, 11 May 2017 04:20:42 GMT
Content-Length: 134


I  am unable to generate bearer token from portus web UI , can you help me why am I unable to generate bearer token with a command or method manually to access the registry. if there is any command or method please provide me. Thank you.

**Comment by mssola** [comment]
> sorry we are using v 2.1 portus but I still don't find the delete icon in the portus UI , I checked both the config files of registry and portus the delete option is set to true

This is really odd. Could you tell me how have you deployed Portus ? (container, rpm, git branch, ...) And if so, the specific version ? (if it's from a git branch, the specific commit).

Also, just in case, could you run (prefix it with `portusctl` if you are using the RPM):

    $ rake portus:info

**Comment by sujjit1991** [comment]
HI @mssola sorry for the late reply we deployed portus in container and  we are using portus and i used opensuse/portus:head image 

I tried to list the repos in my name space using the command 
curl -v https://registry.private.com:5000/v2/sujjit/alpine/tags/list



HTTP/1.1 401 Unauthorized
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Www-Authenticate: Bearer realm="https://registry.private.com:443/v2/token",service="registry.private.com:5000",scope="repository:sujjit/alpine:pull"
< X-Content-Type-Options: nosniff
< Date: Fri, 16 Jun 2017 18:08:25 GMT
< Content-Length: 157

and made a token request from portus using the realm 

 token=`curl -u veadala "https://registry.private.com:443/v2/token?",service="registry.private.com:5000",scope="repository:sujjit/alpine:pull" | grep -o "token.*\"," | sed 's/.*token"://' | sed 's/"//g' | sed 's/,//g'`

after getting the token 
curl -v -H "Authorization: Bearer $token" https://registry.private.com:5000/v2/sujjit/alpine/tags/list

HTTP/1.1 401 Unauthorized
< Content-Type: application/json; charset=utf-8
< Docker-Distribution-Api-Version: registry/2.0
< Www-Authenticate: Bearer realm="https://registry.private.com:443/v2/token",service="registry.private.com:5000",scope="repository:sujjit/alpine:pull",error="invalid_token"
< X-Content-Type-Options: nosniff
< Date: Fri, 16 Jun 2017 18:16:26 GMT
< Content-Length: 157
< 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"sujjit/alpine","Action":"pull"}]}]}
* Connection #0 to host registry.private.com left intact


can you please help me, whats wrong with the above procedure.

**Comment by mssola** [comment]
As I said before, this won't work from the CLI (this is available on the PR #1289).

Are you still having the same issue that you don't have the delete icon (even for master now) ? Make sure that you have the right environment variable set when deploying the Portus container (in this case `PORTUS_DELETE_ENABLED` to true).

**Comment by sujjit1991** [comment]
@mssola I have the delete option now, thanks for providing me the information.

**Comment by mssola** [comment]
Closing this issue then.
