### ISSUE TITLE
Webpack::Rails::Manifest

### ISSUE THREAD

**Issue by nujev** [SUSE/Portus#1291]
![portus](https://cloud.githubusercontent.com/assets/220681/26599124/18cd35ba-453d-11e7-9bf5-e645a26d2590.png)

**Comment by jsilvaigor** [comment]
+1

**Comment by mssola** [comment]
Duplicate of #1245 and #1260. You need to run webpack in order to produce the manifest.json. This needs to be added in the documentation, and also be integrated into the different supported setups so this step is automatically handled. Sorry for the trouble.

**Comment by nujev** [comment]
Thanks for the help
