### ISSUE TITLE
clarification needed to make crono works on official docker image for portus 2.2

### ISSUE THREAD

**Issue by bmillemathias** [SUSE/Portus#1296]
Hello,

(I know github is not place to ask for support but perhaps the clarification could lead to some documentation improvement)

I'm confused because I don't know if crono is run automatically or not in the official portus docker image (`opensuse/portus:2.2`).
From http://port.us.org/features/1_Synchronizing-the-Registry-and-Portus.html one can read 
>  If you are using … Docker setups, you will not have to deal this. A systemd service file has been provided for this.

Even though the file `/usr/lib/systemd/system/portus_crono.service` is present systemd is not running in the container. I can of-course manually launch `/usr/sbin/portus_crono` but this is not the point. 

In the projet [openSUSE/docker-containers](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus) there is a variable `PORTUS_INIT_COMMAND` but it seems to applies only in `master` branch but not on branch `portus-2.2`.

Could you clarify this point ?

thanks

**Comment by mssola** [comment]
This has changed quite a lot (e.g. we have removed crono entirely!). Check out the examples we provide, and the [how to deploy](http://port.us.org/docs/deploy.html) portus page. Thanks for bringing up this topic!
