### ISSUE TITLE
Ldap backend: assign Admin role based on a ldap filter

### ISSUE THREAD

**Issue by bmillemathias** [SUSE/Portus#1298]
Hello,

With ldap backend it is easy to limit acces to the registry using a filter (for instance `cn=portus-users,ou=groups,dc=domain,dc=com`)
It'd be easier if there was a filter parameter in the ldap options to get the global admin users; that would allow to put admin users in `cn=portus-admins,ou=groups,dc=domain,dc=com`.

**Comment by kumy** [comment]
Youhou!!!! :champagne:

**Comment by bmillemathias** [comment]
> 
> 
> Youhou!!!! champagne

Indeed :). bisous
