### ISSUE TITLE
the portus UI can not see the pushed images

### ISSUE THREAD

**Issue by xiaonizi-github** [SUSE/Portus#1303]
hey,i want to ask an question:
1, I pushed a image to 192.168.111.131:5000 by docker command;
2,I logined to the portus by an account(the same account);
3,I can not see the pushed images,why?should i make some config?

**Comment by aleksejlopasov** [comment]
@chenliping972385283 Your registry has to be configured to push notifications to portus

**Comment by chenliping972385283** [comment]
@aleksejlopasov how to  be configured to push notifications to portus?

**Comment by chenliping972385283** [comment]
@aleksejlopasov hey,I have noticed to portus,following this command
1，docker exec -it portus bash
2，RAILS_ENV=production CATALOG_CRON="10.seconds" bundle exec crono
but it is unuseful.  what should i do ?
my environment:   centos7, registry:2.3.1, mariadb:10.0.3, ruby:2.3.1

**Comment by chenliping972385283** [comment]
i have see the logs ,that occured Cannot render console from 192.168.111.131! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255,and level=error msg="retryingsink: error writing events: httpSink{http://192.168.111.131:3000/v2/webhooks/events}: error posting: Post http://192.168.111.131:3000/v2/webhooks/events: dial tcp 192.168.111.131:3000: getsockopt: no route to host (Client.Timeout exceeded while awaiting headers), retrying" ,,,why??

**Comment by aleksejlopasov** [comment]
I use rancher to build my registry using 3 containers (suse portus, docker registry, mysql db)
So in registry there is an env var REGISTRY_NOTIFICATIONS_ENDPOINTS set to: 
```
- name: portus
  url: http://portus/v2/webhooks/events
  timeout: 500
  threshold: 5
  backoff: 1
```

**Comment by aleksejlopasov** [comment]
If you don't understand how to link all these services, try this article https://hub.docker.com/r/sshipway/portus/
this is fork of original Portus with explanations

**Comment by mssola** [comment]
@chenliping972385283 did you solve your issues ?

**Comment by mssola** [comment]
Closing as a stale. Check that your configuration was properly set. We are now providing quite some examples on this repo that might help you out :+1:

**Comment by ehsanrocket** [comment]
https://github.com/SUSE/Portus/issues/2243#issuecomment-593288139
this works for me 
setting the `PORTUS_BACKGROUND_SYNC_STRATEGY=update-delete` in background section of the docker-compose file
