### ISSUE TITLE
Bootsrtap typeahead missing error with opensuse/portus:head

### ISSUE THREAD

**Issue by timhaak** [SUSE/Portus#1304]
Css sass error when using docker image opensuse/portus:head

<img width="836" alt="screenshot 2017-06-22 16 30 32" src="https://user-images.githubusercontent.com/271607/27439531-6a000038-5768-11e7-9d46-0dc9cd5a2147.png">

**Comment by aleksejlopasov** [comment]
+1
The same problem
That's why I use v2.2
Though... As I've understood 'head' means 'v2.3' that is not tagged as stable release
I would appreciate if this issue was fixed

**Comment by timhaak** [comment]
Yes also using v2.2 

Though currently unable to delete images which I hoped was fixed in 2.3.

**Comment by aleksejlopasov** [comment]
@timhaak
Everything works, you just have to enable deletion from both sides - your portus and your registry. Set env var  portus_delete = true or configure it using the config.yml file.
Then enable deletion in your registry with config option delete: enable in "storage" section (sorry, I don't remember exactly where the config is located)

**Comment by timhaak** [comment]
@aleksejlopasov I have those enabled I'm getting a missing token error :(.

Which others have gotten and if I read correctly has been patched. 

Could not delete tag on the registry: Cannot obtain authorization token: #<Net::HTTPNotFound:0x000000037b8178>

**Comment by aleksejlopasov** [comment]
so, is it gonna be fixed? 
And one more question: you have recently fixed this https://github.com/SUSE/Portus/issues/1302
and your PR was merged with master branch. Will this issue be fixed in docker containers with versions 2.1/2.2? or we have to wait for 2.3 release?

**Comment by mssola** [comment]
@timhaak note that `portus:head` is prone to be unstable, but anyways the way to deploy it has changed it since the 2.2 times... You can check the PR #1254 for some examples (e.g. docker-compose setup has changes quite a lot).

> And one more question: you have recently fixed this #1302
and your PR was merged with master branch. Will this issue be fixed in docker containers with versions 2.1/2.2? or we have to wait for 2.3 release?

I've just cherry-picked this commit into the `v2.2` branch, so it will available once the Docker image gets rebuilt on the Docker hub.

**Comment by aleksejlopasov** [comment]
@mssola thanks. Do you have any roadmap? I mean estimated v2.3 release date

**Comment by psyhomb** [comment]
Anything new on this, I'm experiencing the same problem?

**Comment by mssola** [comment]
> @aleksejlopasov  I mean estimated v2.3 release date

Nothing for sure, but early november is a likely candidate.

> @psyhomb Anything new on this, I'm experiencing the same problem?

This should already be fixed. Could you re-check again ? I just fixed an issue on the Docker image...

**Comment by psyhomb** [comment]
Thanks for the quick answer @mssola 

Can you please give me some inputs regarding production ready `docker-compose.yml` file, because I see a quite few of them and to be honest I'm not really sure which one should I use?

- `./docker-compose.yml` development
- `./examples/compose/docker-compose.insecure.yml` without HTTPS support
- `./examples/compose/docker-compose.yml` with HTTPS support

Right now I'm trying with `./examples/compose/docker-compose.yml` file but I'm getting Internal Server Error (output provided) whenever I try to access the login page and that's probably because, I'm guessing, it doesn't have predefined frontend part (`webpack` container) inside the compose file?

I also tried with `./docker-compose.yml` file that already has `webpack` container definition, 
**and it worked**, but this one is using development tag, basically it's not production ready and also it does not have HTTPS support... 

I'm pretty much confused, so it would be nice if you can provide me some inputs on how should I run it.

```
portus_1    | [73] * Listening on ssl://0.0.0.0:3000?cert=/certificates/portus.crt&key=/certificates/portus.key
portus_1    | [73] Use Ctrl-C to stop
portus_1    | [73] - Worker 0 (pid: 76) booted, phase: 0
portus_1    | [73] - Worker 1 (pid: 80) booted, phase: 0
portus_1    | Started GET "/" for 172.16.97.16 at 2017-07-27 23:46:52 +0000
portus_1    | Processing by Auth::SessionsController#new as HTML
portus_1    | Redirected to https://ops-kube-registry.test.local:3000/users/sign_up
portus_1    | Completed 302 Found in 17ms (ActiveRecord: 1.7ms)
portus_1    | Started GET "/users/sign_up" for 172.16.97.16 at 2017-07-27 23:46:53 +0000
portus_1    | Processing by Auth::RegistrationsController#new as HTML
portus_1    |   Rendered shared/_notification.html.slim (14.0ms)
portus_1    |   Rendered shared/_notification.html.slim (0.3ms)
portus_1    |   Rendered shared/_notifications.html.slim (23.9ms)
portus_1    |   Rendered devise/registrations/new.html.slim within layouts/authentication (69.8ms)
portus_1    | Completed 500 Internal Server Error in 204ms (ActiveRecord: 1.7ms)
portus_1    |
portus_1    | ActionView::Template::Error (Could not load compiled manifest from /srv/Portus/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /srv/Portus/public/assets/webpack/manifest.json)):
portus_1    |     3:   head
portus_1    |     4:     title Portus
portus_1    |     5:     = stylesheet_link_tag 'application', media: 'all'
portus_1    |     6:     = javascript_include_tag(*webpack_asset_paths("application"))
portus_1    |     7:     = csrf_meta_tags
portus_1    |     8:     meta content="width=device-width, initial-scale=1" name="viewport"
portus_1    |     9:     link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"
portus_1    |   app/views/layouts/authentication.html.slim:6:in `_app_views_layouts_authentication_html_slim__4152944950837944291_54128220'
portus_1    |   app/controllers/auth/registrations_controller.rb:16:in `new'
portus_1    |
portus_1    |
portus_1    | Processing by ErrorsController#show as HTML
portus_1    |   Parameters: {"status"=>"500"}
portus_1    |   Rendered errors/500.html.erb within layouts/errors (2.0ms)
portus_1    | Completed 500 Internal Server Error in 31ms (ActiveRecord: 0.0ms)
portus_1    | Error during failsafe response: Could not load compiled manifest from /srv/Portus/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /srv/Portus/public/assets/webpack/manifest.json)
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/webpack-rails-0.9.10/lib/webpack/rails/manifest.rb:82:in `rescue in load_static_manifest'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/webpack-rails-0.9.10/lib/webpack/rails/manifest.rb:80:in `load_static_manifest'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/webpack-rails-0.9.10/lib/webpack/rails/manifest.rb:63:in `load_manifest'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/webpack-rails-0.9.10/lib/webpack/rails/manifest.rb:55:in `manifest'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/webpack-rails-0.9.10/lib/webpack/rails/manifest.rb:46:in `manifest_bundled?'
portus_1    |   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/webpack-rails-0.9.10/lib/webpack/rails/manifest.rb:29:in `asset_paths'
...
```
Thanks

**Comment by psyhomb** [comment]
I'm getting similar error

![screenshot from 2017-07-28 03-33-46](https://user-images.githubusercontent.com/1824874/28698743-a87679f2-7345-11e7-8f3d-14c7bbb5a8e9.png)

**Comment by psyhomb** [comment]
I just realized my problem was that I was using a wrong port  to access WebUI, so I just changed the port (3000 => 443) and everything is working as it should.

changed from
- Access WebUI over URL => `https://ops-kube-registry.test.local:3000`
to
- Access WebUI over URL => `https://ops-kube-registry.test.local`

**Comment by mssola** [comment]
Closing then. If you are experiencing this same issue on current master, please feel free to write more comments.
