### ISSUE TITLE
Portus cannot run on centos7

### ISSUE THREAD

**Issue by smile326** [SUSE/Portus#1305]
I have clone the latest version of Portus.
CentOS Linux release 7.3.1611 (Core) .
Docker version is 1.12.6.
docker-compose version is 1.14.0.

when i run ./compose-setup.sh -f -e 192.168.0.138,the message like this:

###########
# WARNING #
###########

This deployment method is intended for testing/development purposes.
To deploy Portus on production please take a look at: http://port.us.org/documentation.html

The setup will destroy the containers used by Portus, removing also their volumes.
Going to remove portus_registry_1, portus_web_1, portus_crono_1, portus_db_1
Removing portus_registry_1 ... done
Removing portus_web_1 ... done
Removing portus_crono_1 ... done
Removing portus_db_1 ... done
Creating portus_db_1 ... 
Creating portus_db_1 ... done
Creating portus_web_1 ... 
Creating portus_crono_1 ... 
Creating portus_crono_1
Creating portus_web_1 ... done
Creating portus_crono_1 ... done
Creating portus_registry_1 ... done
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
Waiting for mariadb to be ready in 5 seconds
Starting portus_db_1 ... done
Starting portus_db_1 ... done
 failed, will retry
 [FAIL]
Timeout reached, exiting with error

I have change many ways to try,includ reinstall the system.But it still like this.
please help me.

**Comment by smile326** [comment]
firewalld was closed

**Comment by gopal-gemini** [comment]
It's working fine to me on centos 7.2.1511

**Comment by mssola** [comment]
Note that the `docker-compose` setup has changed greatly. Try again. For now I'll close this issue, but feel free to leave more comments.
