### ISSUE TITLE
On Ubuntu - Webpack::Rails::Manifest::ManifestLoadError in Auth::Registrations#new

### ISSUE THREAD

**Issue by Geekays** [SUSE/Portus#1307]
I expected that the Portus installation will take care of the dependencies. However I'm getting this when I browse to the site - 

![image](https://user-images.githubusercontent.com/5683341/27760032-da8684b8-5e5b-11e7-9088-97e5b47e5340.png)

**Comment by mssola** [comment]
Duplicate of #1245.
