### ISSUE TITLE
Portus Page opening with an error

### ISSUE THREAD

**Issue by qubusp** [SUSE/Portus#1308]
```Webpack::Rails::Manifest::ManifestLoadError in Auth::Registrations#new



    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag(*webpack_asset_paths("application"))
    = csrf_meta_tags
    meta content="width=device-width, initial-scale=1" name="viewport"
    link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"


```
I was playing around with the compose-setup because it was all i needed for my private purposes and came across that.

**Comment by whulyx** [comment]
Ubuntu 16.04
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
apt-get install nodejs
npm install -g webpack yarn
yarn install
webpack --watch --config config/webpack.js (this step need to be done in the Protus path, you can see there is a config dir)

**Comment by mssola** [comment]
Note that this is now done automatically in some environments like the docker-compose and vagrant in development mode. For other development setups, check the new page from the [wiki](https://github.com/SUSE/Portus/wiki/The-frontend-of-Portus).
