### ISSUE TITLE
How to delete a namespace or a repository?

### ISSUE THREAD

**Issue by whulyx** [SUSE/Portus#1310]
I see the three point in the left of a namespce or a repository, but when I click it, there is nothing happened.
How can I delete a namespace or a repository?

**Comment by mssola** [comment]
> I see the three point in the left of a namespce or a repository, but when I click it, there is nothing happened.

See #1314

> How can I delete a namespace or a repository?

It's not possible for now... See #767.

I'm closing this issue, but feel free to leave more comments if you have any doubts.
