### ISSUE TITLE
Docker Hub does not have latest code from master in the head tag

### ISSUE THREAD

**Issue by jordanjennings** [SUSE/Portus#1343]
Based on the documentation on these pages:

https://hub.docker.com/r/opensuse/portus/
https://github.com/SUSE/Portus/wiki/OBS-projects

I _think_ that the `head` tag is supposed to have the latest code from master. Is that correct? If so, then something isn't configured correctly because it seems to be building with code from March.

In the build log for the `head` tag I see:

```
(14/14) Installing: portus-2.3.0~dev+gitdb5f821b84baa2a68db2d624618116d9859c386b-145.1.x86_64 [.
```
 There's a commit ID in there of db5f821 which is from March 9th.

If `head` isn't actually supposed to be master, can you add a build for the master branch that uploads to Docker Hub?

**Comment by jordanjennings** [comment]
Based on the comment in #1135 this is now fixed and I see the `head` image was built from commit 9d71cd5. Thank you!

**Comment by mssola** [comment]
Now it does. The build in OBS was broken for quite some time... Sorry for the trouble
