### ISSUE TITLE
Question: does this work with AWS' ECR

### ISSUE THREAD

**Issue by yawboateng** [SUSE/Portus#1344]
i am currently using AWS' container registry and was wondering if its possible to front it Portus? Im mostly intreated with the coreOS Clair integrations.

**Comment by mssola** [comment]
Since docker distribution supports AWS, then it should be possible. I'm going to close this issue, but feel free to write more comments if you have more doubts on this topic. Otherwise, for general questions, please use the [mailing list](https://groups.google.com/forum/#!forum/portus-dev)
