### ISSUE TITLE
Changes to docker compose example

### ISSUE THREAD

**Issue by soedar** [SUSE/Portus#1360]
I would like to propose some changes to the docker compose examples, and would like to get some feedback on whether these changes are worth implementing:

1. Move more environment variables to the `.env` file. It would allow the `docker-compose.yml` file to be more "standardized", with runtime configuration for each platform be set without modifying the `docker-compose.yml` file. For example, `PORTUS_SECRET_KEY_BASE` can be moved to the .env file.

2. Remove `links`, depending on the minimum supported version of Docker Compose. A relatively recent version of Docker Compose will create a Docker Network associated to the project, with an internal (virtual) DNS. This means that all the containers within the same Docker Network will be able to access each other via their service name.

3. Use nginx to cache static assets instead of serving assets via volume sharing. Currently a volume is shared between the `portus` and `nginx` container, and the nginx container is serving the static assets in the volume. It seems like we can reduce some complexity if we set `RAILS_SERVE_STATIC_FILES=true` for `portus`, and define nginx to cache the static assets returned by the `portus` container. We will incur a one time penalty to the rails server when we initially request for the assets, but imho that is a insignificant penalty.

If this seems okay, I'll work on this and open a PR with these changes.

**Comment by mssola** [comment]
> Move more environment variables to the .env file. It would allow the docker-compose.yml file to be more "standardized", with runtime configuration for each platform be set without modifying the docker-compose.yml file. For example, PORTUS_SECRET_KEY_BASE can be moved to the .env file.

Sounds good to me.

> Remove links, depending on the minimum supported version of Docker Compose. A relatively recent version of Docker Compose will create a Docker Network associated to the project, with an internal (virtual) DNS. This means that all the containers within the same Docker Network will be able to access each other via their service name.

Looks good to me. But when doing it be sure to document the minimum required versions of both Docker and docker-compose (and make sure that they are not the latest release, but some older).

> Use nginx to cache static assets instead of serving assets via volume sharing. Currently a volume is shared between the portus and nginx container, and the nginx container is serving the static assets in the volume. It seems like we can reduce some complexity if we set RAILS_SERVE_STATIC_FILES=true for portus, and define nginx to cache the static assets returned by the portus container. We will incur a one time penalty to the rails server when we initially request for the assets, but imho that is a insignificant penalty.

I actually did this on purpose 😁 I wanted to show examples that share the volume with NGinx (might be desirable for some users), and other examples that serve the assets with puma directly (for example the one for development, or the insecure example). Maybe the documentation could be improved on this regard, but we have already explained it [here](https://github.com/SUSE/Portus/tree/master/examples/compose#serving-static-assets).

**Comment by soedar** [comment]
Actually, upon experimenting, it seems we might have to keep links.

Upon startup, nginx will attempt to resolve the hostname of the upstream services. If the hostname cannot be resolved at the startup, nginx will just die. Adding the `links` seems to create an implicit `depends_on`, and only create the nginx container after registry and portus container comes up (so the dns resolution will not fail).

There are 2 ways moving forward:
1. Keep links
2. Set `resolver 127.0.0.11;` in the nginx config, under server. This allows nginx to delay the resolution of the hostname by using the internal dns docker dns server.

For single host setup, links will be sufficient. However in swarm mode, `links` and `depends_on` options are ignored. If we choose to keep links, we can update the documentation to make sure that the example would probably not work in swarm mode without changes.

> I actually did this on purpose :grin: I wanted to show examples that share the volume with NGinx (might be desirable for some users), and other examples that serve the assets with puma directly (for example the one for development, or the insecure example). Maybe the documentation could be improved on this regard, but we have already explained it here.

Alright, that makes sense.

**Comment by mssola** [comment]
> For single host setup, links will be sufficient. However in swarm mode, links and depends_on options are ignored. If we choose to keep links, we can update the documentation to make sure that the example would probably not work in swarm mode without changes.

This example is meant for a simple single host setup. So I think we have two options:

1. We leave things as they are, but write some comments on actions to be performed to make it work for a multi-node setup.
2. We leave things as they are with a comment stating that this only works for a single setup because of X, and then we provide an example with Docker Swarm.

I'm actually a bit out-of-date when it comes to Docker Swarm, so personally I'd feel more comfortable with option 1. That being said, if you can provide an example with Docker Swarm that can be reproduced in any setup, it would be totally welcomed 😃

**Comment by soedar** [comment]
Okay, sounds good. 

I don't mind taking a crack at option 2, but I'll probably take some time to get it done. :)

**Comment by mssola** [comment]
I think we can close this issue. Lots of changes happened to our examples since then, and people have contributing with more examples. Moreover, in our documentation we also state some cool [deployments](http://port.us.org/docs/deploy.html) like the Kubernetes setup :wink:
