### ISSUE TITLE
How to persist my user data

### ISSUE THREAD

**Issue by k19810703** [SUSE/Portus#1361]
I deployed by docker-compose , every time I restart them , my data seems lost , it requires me to create admin user , how to fix this?

**Comment by mssola** [comment]
> I deployed by docker-compose , every time I restart them , my data seems lost , it requires me to create admin user , how to fix this?

Well, you should do this with volumes. I guess that you are using the development version of the `docker-compose.yml` file (the one in the root of the project). If you want to read an example closer to production, check the `examples/compose` directory. Those `docker-compose.yml` files define volumes so it will persist.

Moreover, for questions like this please go to the [mailing list](https://groups.google.com/forum/#!forum/portus-dev). The issues section is only to be used for existing bugs or requesting new features.

I'm closing this issue now, but feel free to write more comments on this issue if you have more doubts on this.
