### ISSUE TITLE
docker push to portus is not working

### ISSUE THREAD

**Issue by Geekays** [SUSE/Portus#1380]
I installed portus on a VM on port 3000 and the registry on 5000. This seems to work fine when I go to the web ui.

However when I do the following:

```
docker pull jenkins:latest
docker login myportus.hosts.vms.com:3000 -u admin -p
docker tag jenkins:latest myportus.hosts.vms.com:3000/admin/jenkins:latest
docker push myportus.hosts.vms.com:3000/admin/jenkins:latest

```
it fails. The error that I get is a big HTML file and a HTTP 404.

The error says `**"Routing Error" - No route matches [PUT] "/v1/repositories/admin/jenkins"**`

Can someone help?

**Comment by mssola** [comment]
You should use the hostname and the port of your registry, not the ones from portus. This is specified in the documentation in various places, like for example [here](http://port.us.org/docs/first-steps.html#log-in-and-out).

I'm going to close this issue, but feel free to leave more comments 😉 . Moreover, next time that you have a question, please use the [mailing list](https://groups.google.com/forum/#!forum/portus-dev).
