### ISSUE TITLE
Where is the compose-setup.sh see in the video ?

### ISSUE THREAD

**Issue by nicodmf** [SUSE/Portus#1381]
As it, this is a pain to install with simplicity, no doc for the ssl and no easy authentification process. Can you update the documentation or the video to have an easy and nice installation ?

**Comment by mssola** [comment]
That script no longer exists. Instead you should perform the following:

    $ docker-compose up

I've created #1383 to avoid this confusion. Could you check it out and tell me whether this makes things clearer ? 😄

**Comment by nicodmf** [comment]
In this page http://port.us.org/ in the video in the bottom.

**Comment by mssola** [comment]
@nicodmf This should be covered in #1385 👍

**Comment by nicodmf** [comment]
thanks :)
