### ISSUE TITLE
connect portus to my docker registry using username and password

### ISSUE THREAD

**Issue by vagharsh** [SUSE/Portus#1393]
After i successfully installed portus:head with the docker-compose method ( nginx, portus ) i want to connect it to my private registry in my network. the docker registry admin gave me username and password but still no clear documentation on how to connect it. i am getting `Exception: Cannot find bearer realm` every 10 minutes. any help will be appreciated. 
my docker version is 1.12.6 and the docker is installed on CentOS is these information matters.

**Comment by Vad1mo** [comment]
The UI and the registry are kind of bonded together. This means that the registry is asking the UI for user to authenticate. The UI is logging in to the registry with its first default user `portus`. 

See here : https://docs.docker.com/registry/spec/auth/token/

So if you have alredy a plain vanilla registry you have to change the config according to the setting described in the docs especially the auth.token part.

http://port.us.org/docs/How-to-setup-secure-registry.html

You can place your registry and ui config in the issue, so we might see the error in your config.

**Comment by vagharsh** [comment]
the docker registry has been setup and i don't have the luxury to change it. its been setup with a username and password authentication, on port 443.

so as i understood from what you said then i need to configure my portus UI with the docker registry username and password ? and where should i use the auth.token ?

**Comment by Vad1mo** [comment]
I am not entirely sure if it will work as you expect. If you look at the [diagram](https://docs.docker.com/registry/spec/auth/token/) closely. You will notice that the registry is asking the Auth Service(Portus) if the provided username:password is correct. When you change the username:password in Portus to the one you have, then your registry will still communicate with your current auth service and not with portus. 

I that works then you have a second issue to solve, Because portus want receive any notifications about image pushes/changes so you need run cron jobs every minute that fetches the latest changes.

auth.token is a setting in the registry config.

What kind of registry are you using and why don't you have access to it?

**Comment by vagharsh** [comment]
i am using registry:2 , i have access to the registry but i can't do any changes in it .

**Comment by Vad1mo** [comment]
you can try the change the password and see how far you get with the Portus cron job.

**Comment by vagharsh** [comment]
change what's password ? i have tried to setup a user with the same credentials of the docker registry and setup the portus to check for the my registry but there was no luck . .i can not change the registry password though, if that's what you meant.

**Comment by Vad1mo** [comment]
password of the user `portus` in Portus. But looking at the code Portus is looking for the user with the name portus and not with the user of if = 1.  So if you want to make it work you need to have a user called `portus`in your current auth service, otherwise you need to change to portus code

**Comment by vagharsh** [comment]
apparently my registry was setup with `htpasswd` and not with `token` ( auth server ) so i think in that case Portus won't be able to work with it

**Comment by lonewulf** [comment]
You *do* need to change the registry config, it should not be 'protected' by htpasswd and have to correct configuration bits to work with portus (specifically the auth: token part, for reference: https://docs.docker.com/registry/configuration/#list-of-configuration-options)

You should then configure portus with the same service/issuer and the key corresponding to the cert used in the registry, only then the registry will work with portus.

**Comment by vagharsh** [comment]
is it easy to migrate registry data from auth htpasswd to auth token ? we have jenkins and spinaker also using the registry username password , will they be able to connect to the docker using username and password only without token ?

**Comment by Vad1mo** [comment]
yes the flow stays the same, jenkins and spinnaker can use the registry as is. The only thing you should do is to create application tokens and update your jenkins/spinnaker config with the new application specific password.

**Comment by lonewulf** [comment]
you'll have to use the docker login command (using the credentials from an account you created in portus)  before pushing/pulling

**Comment by mssola** [comment]
Hi @vagharsh , I believe this is related to #1418. We are working on it. After fixing that issue I'll check if this fixes your situation as well. Sorry for the inconvenience 😞

**Comment by mssola** [comment]
@vagharsh could you test this with current `opensuse/portus:head` ? (note that some env. variables have changed, check the `examples` directory).
