### ISSUE TITLE
In Repositories the [Previous,1 ,2, N and Next] Pagination link doesn't work (exist)

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1420]
The Previous, Next  and 1,2,3 pagination isn't working on repositories. I only tried repositories maybe its also not working in other views.
 
Not sure if this was already addressed, if so please close.

**Comment by vitoravelino** [comment]
@Vad1mo Do you mean in `/namespaces/:id` or `/repositories`?

**Comment by Vad1mo** [comment]
In /repositories/ it is.

**Comment by vitoravelino** [comment]
From what I could see there's no pagination there. So I guess "pagination doesn't exist" is more suitable than "not working" in the title, right?

**Comment by vitoravelino** [comment]
Thanks, @Vad1mo!
