### ISSUE TITLE
Invalid URL access using sub-prefix

### ISSUE THREAD

**Issue by osallou** [SUSE/Portus#1421]
Hi,
I am using docker-compose for a dev environment, and set in portus service RAILS_RELATIVE_URL_ROOT=/portus
it is installed behind a nginx proxy proxying /portus to the portus container/port with prefix /portus

I can  access and log to the application.
However, in namespaces, I see some requests to http://myapp/namespaces.json , which fails as it is not prefixed with /portus/namespaces.json

All other tabs/requests, not namespace related are correctly prefixed.

Is it a bug in current git or a config issue?

**Comment by vitoravelino** [comment]
It is a bug. Thanks for reporting! I'll try to include the fix on #1416 since it will require some client sides updates.

**Comment by osallou** [comment]
in the meanwhile, as it is for dev, is there any patch or release tag I should use?

**Comment by vitoravelino** [comment]
@osallou Please try again and let us know if you are still facing any issue. Thanks!

**Comment by osallou** [comment]
after getting latest code, I confirm that namspace url is correct with rails_root_url
Thanks
