### ISSUE TITLE
namespace prefix issue

### ISSUE THREAD

**Issue by osallou** [SUSE/Portus#1426]
A previous fix fixed the namspace URL issue when using a prefix.
There is still a problem in Web UI where links to namaspaces are not relative (/namespace/X), removing the expected prefix

![screenshot from 2017-09-20 14-48-17](https://user-images.githubusercontent.com/1024098/30644539-f6ac14a4-9e12-11e7-87bc-ebd4ab0cf7fe.png)

**Comment by vitoravelino** [comment]
You are right again. I fixed this without noticing while I was working on #1416. Hopefully this will be on master until Friday, otherwise I'll submit an isolated patch for this.

Thanks for reporting and sorry for the inconvenience!

**Comment by osallou** [comment]
no problem , can manage with proxy rules in the meanwhile

**Comment by vitoravelino** [comment]
@osallou The fix was merged. Try again and let me know if it worked or not.

**Comment by osallou** [comment]
fix tested and OK!
