### ISSUE TITLE
install&run

### ISSUE THREAD

**Issue by niuhp** [SUSE/Portus#1429]
how can i install and run portus with the Official  images in  https://hub.docker.com/r/opensuse/portus/

**Comment by Evalle** [comment]
Hi @niuhp you can take a look at examples of howto run Portus here https://github.com/SUSE/Portus/tree/master/examples

**Comment by mssola** [comment]
That being said, the current `head` version is broken due to #1418. For now you can use a backup that I have at `mssola/portus:susecon`. It's a bit old, but it works. I'll mark this as a duplicate of #1418, and ping you back once this situation is fixed.

**Comment by mssola** [comment]
This has already been solved by introducing our [examples](https://github.com/SUSE/Portus/tree/master/examples) directory. Moreover, check out our [how to deploy](http://port.us.org/docs/deploy.html) page.
