### ISSUE TITLE
Portus doesn't support health checks 

### ISSUE THREAD

**Issue by Evalle** [SUSE/Portus#1433]
Hi, guys, 
I tried to run **ping** and **health** checks against my Portus instance (_opensuse/portus:head_ docker image): 
- ping check works just fine: 
```
[root@esh:~] curl -X GET -I https://`hostname -f`/_ping
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/plain; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 8789fea8-042d-40b6-aeb3-970bcd87259a
X-Runtime: 0.030898
Transfer-Encoding: chunked
```
- but health check doesn't work: 
```
[root@esh:~] curl -X GET https://`hostname -f`/_health | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2854    0  2854    0     0  16765      0 --:--:-- --:--:-- --:--:-- 16788
parse error: Invalid numeric literal at line 1, column 10
```
basically, it returns the 'Oh no! Something's wrong with our lighthouse.' page. Should we wait for the implementation of health check in the future or am I doing something wrong? 
Thank you for your answer.

Regards, Evgeny

**Comment by mssola** [comment]
That's weird... It works for me in current master... (note that the `opensuse/portus:head` image is currently broken, so you might be using an old one). Could you provide more information. What do the logs say about this ? Any stack trace ?

**Comment by anlek** [comment]
`_ping` or `_health` are not working for me on the current `:latest` tag

```
% curl -X GET -I https://hub.[redacted].com/_ping                       
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 57f70fdb-ff46-4d78-987e-543afea99ff2
X-Runtime: 0.059386
X-Ua-Compatible: IE=edge
X-Xss-Protection: 1; mode=block
Date: Thu, 25 Jan 2018 01:28:13 GMT
Transfer-Encoding: chunked
```

This might have something to do with traefik in front of the service

**Comment by martinsp** [comment]
In this commit https://github.com/SUSE/Portus/commit/fbe7e8d4ef5370d0be8f6ba4b07a45a0b52de0a8 `/_ping` was removed

As of this commit https://github.com/SUSE/Portus/commit/42823308fee4bb84b706214c37c877b94a363365 `/api/v1/_ping` was added

From what I see in code `/api/v1/_ping` and `/api/v1/health` can now be used

**Comment by anlek** [comment]
Those work perfectly! Thanks.
Need to update the docs online (http://port.us.org/features/health.html).
Let me know if I can help with that.

**Comment by mssola** [comment]
@anlek @martinsp @Evalle I've updated the documentation. Thanks for the heads up! 😁
