### ISSUE TITLE
Waiting for mariadb to be ready in 5 seconds

### ISSUE THREAD

**Issue by senorsmile** [SUSE/Portus#1435]
NB: All domains and other proprietary information has been changed below. 

I have set up the containers using docker-compose, customized with some temporary passwords and our own ssl certs.  

I notice that everything is up in docker, but nginx gives the following error:

```
502 Bad Gateway

nginx
```

Looking at the logs, I see a db error:

```
root@vagrant:~# docker logs -f portus
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
Waiting for mariadb to be ready in 5 seconds
 [FAIL]
Timeout reached, exiting with error
```

entered the container and verified things look ok:

```
# docker exec -it portus /bin/bash

wwwrun@469a5221fd6a:/> env | grep PRODUCTION
PORTUS_PRODUCTION_USERNAME=root
PORTUS_PRODUCTION_DATABASE=portus_production
PORTUS_PRODUCTION_PASSWORD=temp password
PORTUS_PRODUCTION_HOST=db
```

Looking at the entrypoint file /init, I see it runs the following:

```
SKIP_MIGRATION=1 portusctl exec rails r /check_db.rb
```

Running that myself I see:
```
[Mailer config] Host:     portus-vagrant.example.com
[Mailer config] Protocol: https://
DB_DOWN
```

Since the root user is locked out, I can't easily change that /check_db.rb file.  So I copy it to ~/test_db.rb and re echo the contents, modifying a couple of lines:

```
rescue Mysql2::Error => e
  puts "DB_DOWN"
  puts e
end
```

No I'm getting the real error:

```
[Mailer config] Host:     portus-vagrant.example.com
[Mailer config] Protocol: https://
DB_DOWN
Can't connect to local MySQL server through socket '/var/run/mysql/mysql.sock' (2 "No such file or directory")
```

It seems that the portusctl is not picking up the environment variables properly?  I don't know where to go from here.  

P.S.:
I have tried the 2.1 and 2.2 opensuse/portus tags on hub.docker.com with the exact same results.

**Comment by Vad1mo** [comment]
Try setting  `export COMPOSE=1`

See here for the details: `../Portus/config/database.yml`

**Comment by senorsmile** [comment]
Aha!

It looks like I'm not in the production environment.  How do I activate that?

**Comment by Vad1mo** [comment]
export `RAILS_ENV`and `RAKE_ENV`to be sure for the cli.

**Comment by senorsmile** [comment]
I set those to no avail. 

I entered the container to verify the environment variables are set:

```
wwwrun@3131f83b11c3:~> env | grep _ENV
DB_ENV_MYSQL_ROOT_PASSWORD=temp password
DB_ENV_MARIADB_VERSION=10.0.23+maria-1~jessie
DB_ENV_MARIADB_MAJOR=10.0
RAILS_ENV=production
DB_ENV_MYSQL_DATABASE=portus_production
RAKE_ENV=production
```

but get the exact same error:
```
Can't connect to local MySQL server through socket '/var/run/mysql/mysql.sock' (2 "No such file or directory")
```

**Comment by Vad1mo** [comment]
What are you trying to run the master branch or an existing docker image?

on master try with the prefix `PORTUS`, e.g. `PORTUS_PRODUCTION_HOST` and so on. see `../Portus/config/database.yml`

**Comment by senorsmile** [comment]
I'm trying to bring portus up for the first time.  I'm not sure if I've found a bug or not.  I'm quite familiar with docker and docker-compose as we deploy many of our applications via docker. 

I've copied this dir: https://github.com/SUSE/Portus/tree/master/examples/compose
and customized the .env and docker-compose.yml to reflect my desired production environment.  

The PORTUS_PRODUCTION_* is already defined in that docker-compose.yml file.

**Comment by Vad1mo** [comment]
What are you trying to run the master branch or an existing docker image?

the current master has a different setup then previous images.

**Comment by Vad1mo** [comment]
also take a look here #1429

**Comment by senorsmile** [comment]
Ahhh!  I see another user with the same exact errors as what I'm seeing linked to https://github.com/SUSE/Portus/issues/1418.  

I'll try out the image at mssola/portus:susecon. 

Is there any plan to lock the images on hub.docker.com instead of rebuilding them every day?  It would be nice to have a stable e.g. 2.0, even if that image was built a year ago.  This is what the official images do. 

E.g.:  https://hub.docker.com/r/library/postgres/tags/
Latest stable is 9.6.5.  That image will never be rebuilt.  If you use the tag 9.6, it'll update when 9.6.6 is released.

**Comment by senorsmile** [comment]
I actually tried head and the db migrations are succeeding!

**Comment by mssola** [comment]
@senorsmile 

> Is there any plan to lock the images on hub.docker.com instead of rebuilding them every day? It would be nice to have a stable e.g. 2.0, even if that image was built a year ago. This is what the official images do.

Yes and no. Our images are based on RPMs and [OBS](https://build.opensuse.org/). This way we can guarantee that fixes and security patches are always present on the images we deliver. We are already working on how we can mitigate these kinds of issues. Sorry for all the trouble...

I'm also going to close this issue since we are already tracking the image issue, and your issue seems to be fixed. If you are not fine with this, please re-open this issue 😉
