### ISSUE TITLE
not dispaly Repository tag information

### ISSUE THREAD

**Issue by jinghuaz** [SUSE/Portus#1438]
I use version:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
opensuse/portus     head                f4e0b921f9a6        8 days ago          225MB
registry            2.6                 be7805d0983f        8 days ago          33.2MB
nginx               alpine              4016750e2b21        2 weeks ago         15.5MB
mariadb             10.0.23             93631b528e67        19 months ago       305MB

BUT not can dispaly repository tag information.
@mssola  can you help me,now i will use for production.
i think the opensuse/portus:head upgrade?

**Comment by mssola** [comment]
I'm not sure I understand your problem. In Portus 2.2 you cannot get more information on each tag, and in master you can only get CVE information of each tag if you have security scanning enabled.

Can you be more exact on what tag information you want to see ?
