### ISSUE TITLE
Docker compose secure example does not change config.yml correctly

### ISSUE THREAD

**Issue by albertoig** [SUSE/Portus#1439]
I am working with portus with docker-compose in a production environtment. I had to change config.yml from portus container the url to get it correctly and login with docker login.

**Comment by mssola** [comment]
Can you tell me whether this works when using `mssola/portus:susecon` ? If so, then you are hitting #1418 (which is the most probable cause).

**Comment by mssola** [comment]
This is most likely fixed. See my comments on #1418 👍
