### ISSUE TITLE
unable to connect to exsiting mariadb instance

### ISSUE THREAD

**Issue by rbryn** [SUSE/Portus#1445]
image: opensuse/portus:2.2
Docker version: 17.06.1-ce

I'm trying to get portus up while using an existing mariadb instance. For some reason I can't seem to get it to connect to an externally defined db.  All I get is the message "Waiting for mariadb to be ready in 5 seconds"

I've confirmed my variables that are posted in the image and confirmed access from portus to the db by telneting to port 3306 from the portus container to the mariadb.

When I run bash-4.3# SKIP_MIGRATION=1 portusctl exec rails r /check_db.rb

I get the following.
[Mailer config] Host:     portus_portus
[Mailer config] Protocol: https://
DB_DOWN

My variables (from within the container) are;

HOSTNAME=45074f082689
TERM=xterm
PORTUS_PASSWORD=secret-test-password
PORTUS_SECRET_KEY_BASE=/run/secrets/portus_secret_key_base
PORTUS_MACHINE_FQDN_VALUE=portus_portus
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PORTUS_PRODUCTION_USERNAME=portus-root
PORTUS_INIT_COMMAND=bin/crono
PWD=/srv/Portus/config
PORTUS_PRODUCTION_DATABASE=portus_production
PORTUS_KEY_PATH=/certificates/portus.key
PORTUS_PRODUCTION_PASSWORD=secret-test-password
SHLVL=1
HOME=/root
PORTUS_PRODUCTION_HOST=internal_mariadb

NOTE: I've tried the PORTUS_PRODUCTION_HOST with and without the :3306 port without success.  I'm not seeing login attempts at all on the mariadb side.

Is there anyway to get additional debugging information to see exactly what might be going on?

**Comment by rbryn** [comment]
Solved this one... in the image: opensuse/portus:2.2 it's using the following in the database.yml

`  adapter: mysql2
  encoding: utf8
  host: <%= ENV['MARIADB_SERVICE_HOST'] %>
  username: <%= ENV['MARIADB_USER'] %>
  password: <%= ENV['MARIADB_PASSWORD'] %>
  database: <%= ENV['MARIADB_DATABASE'] %>`

If I change my env variables to use those, everything works.  appears to be a mismatch in the documentation.

**Comment by mssola** [comment]
Oh, that's probably something worth mentioning on the documentation, because this has changed from 2.2 to master (and the documentation is talking about the current env variables from master...)

**Comment by majidpal** [comment]
Hi - I am facing issue connecting to mariadb database

docker run -d -p 3000:3000 --name=portus -e PORTUS_CHECK_SSL_USAGE_ENABLED=false -e PORTUS_SECRET_KEY_BASE=<password> -e PORTUS_DB_HOST=<ip-add> -e PORTUS_DB_DATABASE=portus_test -e PORTUS_DB_PASSWORD=<pass> -e PORTUS_DB_POOL=5 -e PORTUS_KEY_PATH=/certificates/portus.key -e PORTUS_PASSWORD=<pass> opensuse/portus:2.3

docker run --name mariadb_portus -p 8080:8080 -3306:3306 -e MYSQL_ROOT_PASSWORD=<pass> -e MYSQL_DATABASE=portus_test -d mariadb:10.0.23

Error in portus container logs -
Waiting for mariadb to be ready in 5 seconds

**Comment by mssola** [comment]
@majidpal are you still facing this issue (I saw you on another issue and you said it was all fine) ? If not, have you pulled the latest `head` image ? (or better yet, the `2.3` tag).

Otherwise, I think we can close this issue since it should already be fixed (documentation-wise).

**Comment by majidpal** [comment]
Please close this.
