### ISSUE TITLE
Would it be possible to add access control for the global namespace?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/Portus#1447]
At the moment it seems that only admin users can push to the global namespace - but we do not want to make the persons who should maintain the global namespace admins.. So is there any way how to adjust the rights on the global namespace to control which user / group / team can push there?

**Comment by mssola** [comment]
> but we do not want to make the persons who should maintain the global namespace admins

Anyone that "maintains" is an admin, no ? 😉 

>  So is there any way how to adjust the rights on the global namespace to control which user / group / team can push there?

No, you have to be admin in order to write and administer the global namespace. Note that the global namespace is quite special, and only a handful of people should be able to write into that. What's your use case ? And what's your recommended workflow to fix your use case ?

**Comment by Martin-Weiss** [comment]
> Anyone that "maintains" is an admin, no ? 😉

Unfortunately not - some people should manage the users and teams and namespaces - some others should push images. These are not the same persons.

> What's your use case ?

The challenge is that the admin can do much  more than just upload to the global namespace.
We need a person that can only upload to the gobal namespace and can not do all the other administrative things within portus..

So similar to the rights management on custom created namespaces we would also have the global namespace to get a team assigned and members of that team should be able to push to this namespace.

**Comment by mssola** [comment]
I believe this is already handled in the user permission issues we are working on the 2.4 milestone.

**Comment by yoramshai** [comment]
So in 2.4 non-admin users will be able to push images to the main namespace ?
