### ISSUE TITLE
pagination not working

### ISSUE THREAD

**Issue by osallou** [SUSE/Portus#1454]
Hi,
in my install from source, pagination is not working. What is strange is my container contains only 8 tags but page tells me there are 3 pages (for only 8 ? why not). But when I click on "next" or page 2 or 3, nothing  happens., I remain on page 1. no network message nor console error as you can see in screenshot
![portus](https://user-images.githubusercontent.com/1024098/31645404-307b9418-b2fc-11e7-960c-91d17735698e.png)

**Comment by vitoravelino** [comment]
I'm working on it! I forgot to update this component after I refactored the pagination on the other pages. Thanks!
