### ISSUE TITLE
Trusted header authentication backend

### ISSUE THREAD

**Issue by rikkuness** [SUSE/Portus#1477]
Just wanted to open this up to discussion, what is the consensus on adding trusted headers as an authentication strategy? This would open up some options and allow for example nginx to do client certificate checks and set headers with user details or allow more complex user checks to be offloaded to the proxy layer.

**Comment by mssola** [comment]
Do you have something in mind 😃 ? For now we have worked on a REST API that authenticates through headers: you have to set the `PORTUS-AUTH` header like this: `username:authentication-token`. But you are talking about certificates and such, so what do you have in mind ?

**Comment by rikkuness** [comment]
So the primary use case for me is client certificate authentication to Portus itself, the user still uses a password to `docker login` using application tokens or whatever.

I've seen things in Apache that fake basic auth by doing the client authentication first and then creating a header, but in this case it would need to look up a valid token/password for the user from Portus.

I'm proposing an `Devise::Strategies::Authenticatable` class that just takes a username from a header and allows the person in, granted this puts a dependency on the admin deploying this to be aware that if this setting is turned on the proxy layer **must** ensure that the header cannot be set by and end user.
