### ISSUE TITLE
Ability to bulk delete images in registry

### ISSUE THREAD

**Issue by aleksystasiak** [SUSE/Portus#1479]
I know this was mentioned numerous times. But this functionality is crucial for me. 
Last year I started to test portus in test environment, at the time portus was only solution providing features like access rights management, ldap integration not to mention beautiful frontend.
I've had some trouble on the way but managed to overcome them. Now I'm hitting brick wall.
Testing environment became development and later production. After integrating gitlab ci I'm facing constant problems with free space. The amount of images is simply too large to delete them manually one by one and run garbage collector. I need a way to bulk delete images older than x. Is there any way to do that with portus ? 
I'm unable to authenticate against portus managed registry so third party tools simply do not work.
Is there any solution to this problem available right now ?

**Comment by pbabilas** [comment]
The same problem here, no authentication available in portus no tool to delete images automaticly. Any idea how to work with not enough disk space?

**Comment by aleksystasiak** [comment]
In my case it's a  bare metal setup based on 2.2 portus rpms on OpenSuse

**Comment by mssola** [comment]
That's an interesting topic, and I can relate to this problem... Now the goal of this issue would be how to tackle it in a pragmatic way 🤔 

So, on the top of my head, what I'm thinking is that in the current repositories page (we've recently added a page where all images/tags are listed) you could have a way to filter them in various ways: namespace they belong to, associated team, push time, etc. Then you would select the results and click "Delete". Would that work for you ? (on the REST API we could also add something similar).

**Comment by pbabilas** [comment]
The best way would be create job that will do it for me - any cron that will take all tags by date and delete it. If we have 5k tags selecting it and deleteing manualy will be problematic also :( but better than selecting one by one ;)

**Comment by mssola** [comment]
> The best way would be create job that will do it for me - any cron that will take all tags by date and delete it. If we have 5k tags selecting it and deleteing manualy will be problematic also :( but better than selecting one by one ;)

Oh, so you are thinking more on a background process that cleans up images that meet certain conditions ? That's an interesting idea.

@aleksystasiak what do you think ?

**Comment by aleksystasiak** [comment]
> background process that cleans up images that meet certain conditions

@mssola 
This is exactly what I'm looking for

**Comment by aleksystasiak** [comment]
While frontend addition enabling filtering images for deletion would be nice, at some point you will have to o many images/tags to handle this manually

**Comment by vitoravelino** [comment]
This could go as an admin setting like `Automatically remove repositories older than` and a few options like `Disabled`, `6 months`, `1 year`, `2 years`, etc.

Besides this, I think we should also prioritize the ability to manually delete repositories and namespaces.

**Comment by aleksystasiak** [comment]
I don't want to delete whole repositories, I would rather like to keep image quantity in check by periodically removing older ones.

**Comment by pbabilas** [comment]
Exactly right, automatic settings would be great but not whole repository but tags older than!

**Comment by vitoravelino** [comment]
> Exactly right, automatic settings would be great but not whole repository but tags older than!

Sorry my confusion then. Rephrasing... `Automatically remove tags older than`.

**Comment by Vad1mo** [comment]
We could write a croned frontend for https://github.com/fraunhoferfokus/deckschrubber.

It would be an API wrapper where Portus would send config changes and updates to a running deckschrubber.  Another option would be where we would define the things from deckschrubber in Portus and let the Registry GC do the rest.

**Comment by aleksystasiak** [comment]
So option 1 will only work for compose based docker setup ?

**Comment by Vad1mo** [comment]
yes, Isn't everyone using a compose/k8s like template setup?

**Comment by aleksystasiak** [comment]
Apparently not, I'm using rpms

**Comment by Vad1mo** [comment]
A compose setup would make life easier for many, as we could add more and more features as containers. Clair is already there. Next one could add automated build like hub.docker

**Comment by mssola** [comment]
deckschrubber looks like a good candidate, but I disagree that this would only work for docker-compose, it could very well be a separate process like any other...

That being said, I guess that this only works for registries with no authorization in place, no ? How does deckschrubber handle the whole authentication part ?

If we can workaround this, then nothing would have to be done from the Portus' side besides documentation 😄

**Comment by aleksystasiak** [comment]
Unfortunately it supports only basic auth by passing username and password parameters.
I would never create this issue before exploring all available tools.

**Comment by Vad1mo** [comment]
> deckschrubber looks like a good candidate, but I disagree that this would only work for docker-compose, it could very well be a separate process like any other...

yes, thats right, however in a compose config it would be more transparent and wouldn't need special scripting/systemd treatment.

> That being said, I guess that this only works for registries with no authorization in place, no ? How does deckschrubber handle the whole authentication part ?

You are right I am looking through the code and can't find anything about  auth.

> If we can workaround this, then nothing would have to be done from the Portus' side besides documentation 😄

yes this would be ideal. I try to create a solution that we can plugin into portus or that runs as a sidecar next to portus.

btw. here is another tool that does similar things but is less flexible https://github.com/andrey-pohilko/registry-cli

**Comment by mssola** [comment]
Ok, I'll try to check the different possibilities when I have some time, but if someone else has already a proposal with code, feel free to submit a PR 😉

**Comment by aleksystasiak** [comment]
Is there any progress ? I just added another 200Gig

**Comment by mssola** [comment]
> Is there any progress ? I just added another 200Gig

At least not from my side. This will probably come in a 2.4 release 😉

**Comment by otavio** [comment]
The filter should also allow for some kind of pattern matching for tags.

Here we use CI and it makes tags based on `git describe` so allowing us to keep just the releases after some time window would be perfect.

Something as:

- tag matching '.*-\d+-g.*'
- older than 1 month
