### ISSUE TITLE
JS Polyfills Offline

### ISSUE THREAD

**Issue by rikkuness** [SUSE/Portus#1482]
I'm currently running Portus in a disconnected environment and experiencing some client side weirdness that I think is down to a lack of the polyfills loaded from https://github.com/SUSE/Portus/blob/master/app/views/layouts/application.html.slim#L33 as I've got no connection to polyfill.io. Is there a way we can build some of the required polyfills in or does it specifically 
 require the browser detection features of polyfill.io?

**Comment by vitoravelino** [comment]
Sure. It totally makes sense to keep things offline. That was the simplest and fastest way I found to provide a fallback to some js features. I'll investigate and see what I can do. Thanks for the suggestion! 😄
