### ISSUE TITLE
Portus production error

### ISSUE THREAD

**Issue by wedun** [SUSE/Portus#1483]
Hello.
I try to use insecure compose example and got error
`Access denied for user 'root'@'172.18.0.4' (using password: YES)`
Full log in attach.
Could you please help me with this error.
[error..txt](https://github.com/SUSE/Portus/files/1419216/error.txt)

**Comment by Vad1mo** [comment]
Can confirm, one need to change 

`Crono.perform(CatalogJob).every value`to 
`Crono.perform(CatalogJob).every value.seconds` in crontab.rb

**Comment by mssola** [comment]
Fixed, sorry for the trouble...
