### ISSUE TITLE
Cannot build portus on mac using docker-compose

### ISSUE THREAD

**Issue by dkeidel397** [SUSE/Portus#1498]
I am following the instructions at https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment.

I cloned the portus repo to a local directory on my mac.  I change directories into that directory and I issue the command:

docker-compose up

It indicates that it installs 77/77 componenets and then I get the following output:

(77/77) Installing: patterns-openSUSE-devel_basis-20170518-6.1.x86_64 [.....done]
Output of kbd-2.0.3-3.14.x86_64.rpm %posttrans script:
    Please run mkinitrd as soon as your system is complete.

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.4.1, but your Gemfile specified >= 2.4
ERROR: Service 'portus' failed to build: The command '/bin/sh -c zypper ref &&     zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler            libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 &&     zypper -n in --no-recommends -t pattern devel_basis &&     bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a' returned a non-zero code: 18

I see that these commands are in the Dockerfile and it looks like they were executed just fine in the beginning of the process unless it is not actually being run at that point.  I saw the following output in the beginning after I first issued `docker-compose up`:

Step 7/8 : RUN zypper ref &&     zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler            libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 &&     zypper -n in --no-recommends -t pattern devel_basis &&     bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a

Is there an issue with the zypper command?  Just to repeat I am using docker-compose on a mac.

**Comment by dkeidel397** [comment]
Did a little more debugging by breaking down the long RUN command into parts to see what part actually is causing the error.

I found that it is the bundle portion:  

ERROR: Service 'portus' failed to build: The command '/bin/sh -c bundle install --retry=3' returned a non-zero code: 18

**Comment by dkeidel397** [comment]
I modified the Docker file RUN command to get a better idea of which part of the piped command is causing the error.  Modified the RUN command by splitting it up to look like the following:

RUN zypper ref && \
    zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler \
           libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 && \
    zypper -n in --no-recommends -t pattern devel_basis
RUN bundle install --retry=3 && \
    zypper -n rm wicked wicked-service autoconf automake \
           binutils bison cpp cvs flex gdbm-devel gettext-tools \
           libtool m4 make makeinfo && \
    zypper clean -a

I still received the same ERROR as expected, but I think it is safe to say that the portion of the RUN command that is failing is the bundle portion.  Here is the error message:

Step 8/9 : RUN bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a
 ---> Running in 042795f84a95
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.4.1, but your Gemfile specified >= 2.4
ERROR: Service 'portus' failed to build: The command '/bin/sh -c bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a' returned a non-zero code: 18

Is there an issue with running bundle the way it is being run as:

/bin/sh -c bundle install --retry=3

**Comment by vitoravelino** [comment]
Hi @dkeidel397, sorry for the delay. The problem is because `ruby2.4-rubygem-bundler` package in openSUSE has an old version of bundler that doesn't support the constraint `ruby >= 2.4`. 

So, for now what you can do is just remove that line from the `Gemfile` and run `docker-compose build portus` again. That should work. Sorry for the inconvenience.

**Comment by dkeidel397** [comment]
No problem.  Thanks for getting back to me.  While I was waiting for a response I changed the line in the Gemfile to ruby "2.4.1" (and also removed the line completely from the Gemfile) which got me past the ERROR, but now when I run docker-compose up, I am getting ERROR messages that complain of things like:

Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..

Gem::RemoteFetcher::FetchError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A (https://rubygems.org/gems/rake-12.2.1.gem)
An error occurred while installing rake (12.2.1), and Bundler cannot continue.
Make sure that `gem install rake -v '12.2.1'` succeeds before bundling.

The weird thing is that the gem it mentions is different every time I run `docker-compose up` OR `docker-compose build portus`.

Seems others have complained about this issue here:
http://railsapps.github.io/openssl-certificate-verify-failed.html

I am a little fearful of modifying the ssl setting on my mac, so wanted to see what you or others thought before I go down that road.

**Comment by vitoravelino** [comment]
That one I never saw. 😕
