### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#150]

**Comment by flavio** [comment]
Stuff to keep in mind: some usernames accepted by LDAP might not be acceptable by Docker naming conventions for namespaces.

**Comment by mssola** [comment]
And by the way, [here](https://github.com/plataformatec/devise/wiki/How-To:-Authenticate-via-LDAP) it is the link to the Devise wiki explaining how can we actually achieve this.

**Comment by rqc** [comment]
Is LDAP support in the works or are you looking for volunteers?

**Comment by flavio** [comment]
@mssola is on vacation right now. He planned to start working on that next week AFAIK. No code has been written yet.

You can coordinate with him once he's back.

**Comment by RoryHunter** [comment]
+1 interested in this.

**Comment by mssola** [comment]
@rqc as @flavio said, no code has been written yet, but I plan to start working on it ASAP.

**Comment by sotsy** [comment]
+1
