### ISSUE TITLE
error parsing HTTP 404 response body: unexpected end of JSON input: ""

### ISSUE THREAD

**Issue by roboto-cloud** [SUSE/Portus#1511]
**someone know how fix it?**

```
docker login XXXXXXXX
Username: rbt
Password:
Login Succeeded

docker push XXXXXXXX/rbt/apline:latest
The push refers to a repository [XXXXXXXX/rbt/apline]
2aebd096e0e2: Preparing
error parsing HTTP 404 response body: unexpected end of JSON input: ""
```

**Comment by jordanjennings** [comment]
I have seen this issue when someone tries to push the image to portus rather than to their registry. In other words, if you have portus running on `portus.example.com` and your registry at `registry.example.com` you need to do a docker login to `registry.example.com` and tag and push your image as `registry.example.com/rbt/alpine:latest`

**Comment by mssola** [comment]
Closing. If this is not what @jordanjennings mentioned, please feel free to re-open again and provide more information so we can further investigate this issue. Thanks!

**Comment by japneet-sahni** [comment]
@mssola : We are using Packer to create the docker image and push it to Portus. We are getting below error.
`16:36:02 ==> docker: Running post-processor: docker-tag
16:36:02     docker (docker-tag): Tagging image: sha256:4d53e1ec0f8b6b1787c3afcb3006a5fa120cd45a0d83b1f95c7b4f5da33e8ecb
16:36:02     docker (docker-tag): Repository: portus.XXXX.com/one/slots:latest
16:36:02 ==> docker: Running post-processor: docker-push
16:36:02     docker (docker-push): Logging in...
16:36:02     docker (docker-push): WARNING! Your password will be stored unencrypted in /home/ubuntu/.docker/config.json.
16:36:02     docker (docker-push): Login Succeeded
16:36:02     docker (docker-push): Configure a credential helper to remove this warning. See
16:36:02     docker (docker-push): https://docs.docker.com/engine/reference/commandline/login/#credentials-store
16:36:02     docker (docker-push): Pushing: portus.agilefabric.fr.carrefour.com/onecf/onecarrefour_service_slots:latest
16:36:02     docker (docker-push): The push refers to repository [portus.XXXX.com/one/slots]
16:36:02     docker (docker-push): 62d4b7dc5de6: Preparing
16:36:02     docker (docker-push): 1d31b5806ba4: Preparing
16:36:02     docker (docker-push): error parsing HTTP 404 response body: unexpected end of JSON input: ""
16:36:02     docker (docker-push): Logging out...
16:36:02     docker (docker-push): Removing login credentials for portus.agilefabric.fr.carrefour.com
16:36:02 Build 'docker' errored: 1 error(s) occurred:
16:36:02 
16:36:02 * Post-processor failed: Bad exit status: 1
16:36:02 
16:36:02 ==> Some builds didn't complete successfully and had errors:
16:36:02 --> docker: 1 error(s) occurred:
16:36:02 
16:36:02 * Post-processor failed: Bad exit status: 1
16:36:02 
16:36:02 ==> Builds finished but no artifacts were created.`

**Comment by mssola** [comment]
I just edited your command so the output is more readable :wink: 

I'm not experienced with packer, so this might be something about this tool. That being said, note that a cpmmon pitfall in which these "unexpected end of ..." errors appear are usually when you point to the wrong registry (e.g. you point to Portus' FQDN instead of the registry's).

**Comment by bhaskar423** [comment]
@jordanjennings Still i am getting the same problem is in HTML formal error. 

root@pre-prod2:~# docker push prod.url.io:3000/bhaskar/jenkins 
The push refers to repository [prod.url.io:3000/bhaskar/jenkins]
8354568a627f: Preparing 
1a1fe057280b: Preparing 
2944e476f079: Preparing 
194511af3c83: Preparing 
976e7b347737: Preparing 
c23711a84ad4: Waiting 
90d1009ce6fe: Waiting 
error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Action Controller: Exception caught</title>\n  <style>\n    body {\n      background-color: #FAFAFA;\n      color: #333;\n      margin: 0px;\n    }\n\n    body, p, ol, ul, td {\n      font-family: helvetica, verdana, arial, sans-serif;\n      font-size:   13px;\n      line-height: 18px;\n    }\n\n    pre {\n      font-size: 11px;\n      white-space: pre-wrap;\n    }\n\n    pre.box {\n      border: 1px solid #EEE;\n      padding: 10px;\n      margin: 0px;\n      width: 958px;\n    }\n\n    header {\n      color: #F0F0F0;\n      background: #C52F24;\n      padding: 0.5em 1.5em;\n    }\n\n    h1 {\n      margin: 0.2em 0;\n      line-height: 1.1em;\n      font-size: 2em;\n    }\n\n    h2 {\n      color: #C52F24;\n      line-height: 25px;\n    }\n\n    .details {\n      border: 1px solid #D0D0D0;\n      border-radius: 4px;\n      margin: 1em 0px;\n      display: block;\n      width: 978px;\n    }\n\n    .summary {\n      padding: 8px 15px;\n      border-bottom: 1px solid #D0D0D0;\n      display: block;\n    }\n\n    .details pre {\n      margin: 5px;\n      border: none;\n    }\n\n    #container {\n      box-sizing: border-box;\n      width: 100%;\n      padding: 0 1.5em;\n    }\n\n    .source * {\n      margin: 0px;\n      padding: 0px;\n    }\n\n    .source {\n      border: 1px solid #D9D9D9;\n      background: #ECECEC;\n      width: 978px;\n    }\n\n    .source pre {\n      padding: 10px 0px;\n      border: none;\n    }\n\n    .source .data {\n      font-size: 80%;\n      overflow: auto;\n      background-color: #FFF;\n    }\n\n    .info {\n      padding: 0.5em;\n    }\n\n    .source .data .line_numbers {\n      background-color: #ECECEC;\n      color: #AAA;\n      padding: 1em .5em;\n      border-right: 1px solid #DDD;\n      text-align: right;\n    }\n\n    .line {\n      padding-left: 10px;\n      white-space: pre;\n    }\n\n    .line:hover {\n      background-color: #F6F6F6;\n    }\n\n    .line.active {\n      background-color: #FFCCCC;\n    }\n\n    .hidden {\n      display: none;\n    }\n\n    a { color: #980905; }\n    a:visited { color: #666; }\n    a.trace-frames { color: #666; }\n    a:hover { color: #C52F24; }\n    a.trace-frames.selected { color: #C52F24 }\n\n      #route_table {\n    margin: 0;\n    border-collapse: collapse;\n  }\n\n  #route_table thead tr {\n    border-bottom: 2px solid #ddd;\n  }\n\n  #route_table thead tr.bottom {\n    border-bottom: none;\n  }\n\n  #route_table thead tr.bottom th {\n    padding: 10px 0;\n    line-height: 15px;\n  }\n\n  #route_table thead tr.bottom th input#search {\n    -webkit-appearance: textfield;\n  }\n\n  #route_table tbody tr {\n    border-bottom: 1px solid #ddd;\n  }\n\n  #route_table tbody tr:nth-child(odd) {\n    background: #f2f2f2;\n  }\n\n  #route_table tbody.exact_matches,\n  #route_table tbody.fuzzy_matches {\n    background-color: LightGoldenRodYellow;\n    border-bottom: solid 2px SlateGrey;\n  }\n\n  #route_table tbody.exact_matches tr,\n  #route_table tbody.fuzzy_matches tr {\n    background: none;\n    border-bottom: none;\n  }\n\n  #route_table td {\n    padding: 4px 30px;\n  }\n\n  #path_search {\n    width: 80%;\n    font-size: inherit;\n  }\n\n  </style>\n\n  <script>\n    var toggle = function(id) {\n      var s = document.getElementById(id).style;\n      s.display = s.display == 'none' ? 'block' : 'none';\n      return false;\n    }\n    var show = f

**Comment by vitoravelino** [comment]
I think you are pushing to the wrong address. Registry runs on port `5000`. Try `docker push prod.url.io:5000/bhaskar/jenkins` and let us know what happen.

**Comment by vitoravelino** [comment]
@bhaskar423 I think you are pushing to the wrong address. Registry runs on port `5000`. Try `docker push prod.url.io:5000/bhaskar/jenkins` and let us know what happen.

**Comment by bhaskar423** [comment]
@vitoravelino this is the user name : bhaskar

i have a doubt here after first installation we have to give the **Name** and **hostname**. 
in **Host name** what i have to give on this if i give my server domain remote is getting fail i thing this may be a problem for the following error.

root@pre-prod:/etc/docker# docker push 192.89.9.90:5000/bhaskar/nginx:latest
The push refers to repository [192.89.9.90:5000/bhaskar/nginx]
3c0285ad7db9: Preparing 
2978900fe42b: Preparing 
ef68f6734aa4: Preparing 
denied: requested access to the resource is denied
root@pre-prod:/etc/docker# docker push 192.89.9.90:5000/bhaskar/nginx:latest

**Comment by vitoravelino** [comment]
Did you `docker login -u bhaskar 192.89.9.90:5000`? You should get `Login Succeeded` message. If it's still not working, try to logout with `docker logout 192.89.9.90:5000` and try to login again. It should work.

**Comment by bhaskar423** [comment]
@vitoravelino Thanks for fast reply. 
root@pre-prod:~# docker login -u bhaskar 192.89.9.90:5000
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
root@pre-prod:~# docker push 192.89.9.90:5000/bhaskar/nginx:latest
The push refers to repository [192.89.9.90:5000/bhaskar/nginx]
3c0285ad7db9: Preparing 
2978900fe42b: Preparing 
ef68f6734aa4: Preparing 
denied: requested access to the resource is denied
root@pre-prod:~# docker logout
Not logged in to https://index.docker.io/v1/
root@pre-prod:~# docker logout 192.89.9.90:5000
Removing login credentials for 192.89.9.90:5000
root@pre-prod:~# docker login -u bhaskar 192.89.9.90:5000
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded

I did same before also, please help me.
i think host name may not allow me to push the image.
