### ISSUE TITLE
Any news about when the new release will be out?

### ISSUE THREAD

**Issue by psyhomb** [SUSE/Portus#1514]
I was wondering is there any news about when the new release will be out => v2.3 (in development)

Thanks

**Comment by mssola** [comment]
We wanted to release it this past november, but we are still working on high priority bugs. Hopefully in the following weeks we can release a proper release candidate.

**Comment by mssola** [comment]
Yeah. Take a look at this [Helm chart](https://github.com/kubic-project/caasp-services/tree/master/contrib/helm-charts/portus) 👍

**Comment by hbastosc** [comment]
Thanks for the update. After this new release is the plan to keep releasing new updates each year? Or is there any plans to update the application more frequently?

**Comment by mssola** [comment]
The original idea is to release more often, but I got involved in [other projects](https://github.com/kubic-project) for quite some months and couldn't spend as much time as I intended. Now this should be solved, so we should be able to release more often. After the 2.3 release I'll try to be more realistic about the 2.4 release...

**Comment by otavio** [comment]
Wouldn't be better to postpone the unfinished features to 2.4 release and get 2.3 out soon?

**Comment by vitoravelino** [comment]
> Wouldn't be better to postpone the unfinished features to 2.4 release and get 2.3 out soon?

The problem wasn't unfinished features but issues with packaging while upgrading the ruby version. As soon as we confirm that everything is being built properly in OBS, we'll merge #1593 and probably launch 2.3. @mssola can give more detailed information about it.

**Comment by mssola** [comment]
@otavio all the packaging issues have been fixed since last week. We are now polishing things out on pending issues and such, but we should be branching 2.3 really soon (and all features have already been postponed to 2.4).

For the next release we'll try to keep it simpler so we can release earlier, but for 2.3 we had a couple of unplanned features that have changed the deployment part of Portus quite dramatically and this has impacted us on the timing 😅

**Comment by otavio** [comment]
> @otavio all the packaging issues have been fixed since last week. We are now polishing things out on pending issues and such, but we should be branching 2.3 really soon (and all features have already been postponed to 2.4).

Great news @mssola; it makes sense to get it published soon.

> For the next release we'll try to keep it simpler so we can release earlier, but for 2.3 we had a couple of unplanned features that have changed the deployment part of Portus quite dramatically and this has impacted us on the timing :sweat_smile:

I see. Keeping it small give some great benefits, especially a shorter upgrade path for users and it should help people to keep it continuously update.

**Comment by mssola** [comment]
I've updated the documentation with notes on the next release. We have also sorted out milestones for forthcoming releases and the v2.3 release has already been branched out (there's a Docker hub tag and a git branch).
