### ISSUE TITLE
Upload Docker images including MariaDB into Portus registry occur error

### ISSUE THREAD

**Issue by Junyouwei** [SUSE/Portus#1519]
Hi,

I met one issue about Docker image uploading.
When I push docker image into Portus registry, once contains MariaDB, then uploading image will be failed. and the error information as below:
docker@RDDashboard:/opt/docker/dashboard$ docker push archive.docker-registry.eecloud.nsn-net.net/ossdashboard/dashboard_web
The push refers to a repository [archive.docker-registry.eecloud.nsn-net.net/ossdashboard/dashboard_web]
7f7efcb1838c: Layer already exists
d9cc55120cee: Layer already exists
4cfb33089bfa: Layer already exists
1e0ea159a3a9: Layer already exists
46d1cfdcff17: Layer already exists
bd7dcb3e1bc1: Layer already exists
98816c9818bb: Pushing [==================================================>] 333.6 MB
30339f20ced0: Layer already exists
0eb22bfb707d: Layer already exists
a2ae92ffcd29: Layer already exists
**unauthorized: authentication required”**

anyone knows this?
Thanks in advance.
attanched file is tcpdump.
from  10.140.3.249 to 10.144.1.10, through 10.144.1.10, uploaded to Portus Registry.
10.144.1.10 is gateway, even if don't use gateway, the same problem met.

OS: 14.04.1-Ubuntu
Docker: 1.13.1-cs1

**Comment by Vad1mo** [comment]
I guess its an timout, in the config you can increate the timout. `jwt_expiration_time ` (default its set to 5 minutes). Sometimes on slow connections and big images it is not enough.

**Comment by Junyouwei** [comment]
actually I tried other images that bigger than that.
and it is OK.
I compared many times, and get the conclusion that it is: once installs Mariadb, then this images can't be uploaded.

**Comment by Vad1mo** [comment]
what is you backend Disk, S3 or Swift?

**Comment by Junyouwei** [comment]
it's CEPH, 
SWIFT is not used in our openstacks currently that can be defined as S3, block storages and images storages.

**Comment by Vad1mo** [comment]
docker registry does not support CEPH as a storage driver.
It should be one of those from the list: https://docs.docker.com/registry/storage-drivers/

**Comment by Vad1mo** [comment]
can you paste your docker registry config here, **not portus**

**Comment by Junyouwei** [comment]
you mean Docker file?
I install MariaDB in image and commit it.

**FROM dashboard_python:2.8
ENV http_proxy http://10.144.1.10:8080
ENV https_proxy https://10.144.1.10:8080
ENV PYTHONUNBUFFERED 1

CMD mkdir /Dashboard
WORKDIR /Dashboard
ADD . /Dashboard
#RUN pip install -r requirements.txt

EXPOSE 80
CMD ["sh","start.sh"]**

**Comment by Vad1mo** [comment]
The configuration of your *Docker Registry*. It is the **config.yml** file. 
Like this: https://docs.docker.com/registry/configuration/#list-of-configuration-options

**Comment by Junyouwei** [comment]
yml file like below:

version: '2'
services:
  mysql:
    build: mysql
    ports:
      - 3306
    volumes:
      - /opt/docker/datadir:/var/lib/mysql
      - /opt/docker/custom:/etc/mysql/conf.d
  web:
    build: productgo
    ports:
      - 80
    links:
      - mysql
      - etcd
  etcd:
    image: quay.io/coreos/etcd:v2.2.0
    mem_limit: 128m
    ports:
      - 24001:4001
      - 22379:2379
      - 22380:2380
    hostname: 10.110.3.22
    environment:
      - GOMAXPROCS=2
    command:
      -name dashboard
      -advertise-client-urls http://10.110.3.22:22379,http://10.110.3.22:24001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://10.110.3.22:22380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster dashboard=http://10.110.3.22:22380
      -initial-cluster-state new
  confd_ha:
    build: confd-haproxy
    ports:
      - 8000:80
    environment:
      - backends=10.110.3.22:22379
      - etcd

**Comment by Junyouwei** [comment]
The image which has problem is the build **productgo**

**Comment by Junyouwei** [comment]
web:
build: productgo
ports:
- 80
links:
- mysql
- etcd

**Comment by Vad1mo** [comment]
Sorry I can't help. You din't provide an answer to my questions. Apart from that, the provided doesn't contain anything related to Portus or the Docker Registry.

**Comment by Junyouwei** [comment]
Yes, I only can provide my docker image configuration. for Portus part, I've no idea for that.
I'm wondering is there any similar case and find similar solution for that.
Thanks a lot for your support.

**Comment by Junyouwei** [comment]
according to the investigation and comparison, once contains mariadb into image, then this images can not  be pushed into Portus registry.

**Comment by Vad1mo** [comment]
I suspect if the registry is using the swift storage, then this is a common issue swift registry issue.
Try *Docker build --nocache  --pull -t yourmariadb* if it works then it's the storage.
