### ISSUE TITLE
Remove/replace outdated content

### ISSUE THREAD

**Issue by vitoravelino** [SUSE/Portus#1525]
We've evolved a lot the past months and some stuff changed. We need to keep our docs up to date to our latest release (or keep multiple versions of it?) to avoid confusion from new users.

- The video in the index page is pretty outdated.
- What else?

**Comment by mssola** [comment]
I think this is fixed with #1702, and it's probably a duplicate of #1691.

@vitoravelino what do you think? Can we close this?

**Comment by vitoravelino** [comment]
Yeah, I was gonna mention that in the PR. :sweat_smile:
