### ISSUE TITLE
Only allow Portus administrators to push images

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1528]
There is an use case in which only Portus administrators should be able to push new images. We should find a workflow in order to accommodate this and implement it.

**Comment by mssola** [comment]
This kind of conflicts with #1137. If we only allow administrators to push images, then personal namespaces kind of become redundant. So, I propose to fix this in two steps:

1. We fix this issue by, through a configuration option, disallowing any non-admin user to push images.
2. We then go to fix #1137 by adding another configuration option.

The end result would be:

- If only admins can push and personal namespaces are disabled, then overall only administrators would be able to push.
- If only admins can push and personal namespaces are enabled, then users would be able to push into their own personal namespaces but not anywhere else. This would be a good idea to prevent pushes in a repository where the admin has added a contributor by mistake.
- If the `only admin` option is disabled and personal namespaces are enabled, then we are in the same situation as we are now.

Even if personal namespaces are disabled, I wouldn't just remove them, just in case they are not enabled back again, or the admin considers tidier to push certain images to some users so they can at least pull from there.

After all this, a good enhancement (for another issue) would be to come up with a coherent UI. Basically, if only administrators can push, then lots of functionalities in regards to teams and team members simply become redundant. We could have checks for that. Something that just occurred to me: if you try to add a contributor, then the user would be added as a viewer instead, and a warning would be returned explaining why that happened.

**Comment by mssola** [comment]
Another idea would be, when fixing #1137, keep the two options that I mentioned in [my comment](https://github.com/SUSE/Portus/issues/1528#issuecomment-366188198) in a single one. So you'd be able to set it like:

- admin-only: only administrators will be able to push.
- allow-personal: only administrators will be able to push but personal namespaces would be available for regular users.
- default: the current behavior.

This is probably less confusing 😋

**Comment by vitoravelino** [comment]
I couldn't agree more with your statements. :+1:
