### ISSUE TITLE
#<Mysql2::Error: Unknown MySQL server host 'db' (-3)>

### ISSUE THREAD

**Issue by nunterr** [SUSE/Portus#1538]
crono_1       | + '[' 1 -ge 128 ']'
crono_1       | + echo 'Crono terminated with status: 1. Trying again in 10 seconds.'
crono_1       | + sleep 10
crono_1       | Crono terminated with status: 1. Trying again in 10 seconds.
portus_1      | Unknown MySQL server host 'db' (-3)
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:89:in `connect'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/mysql2-0.4.7/lib/mysql2/client.rb:89:in `initialize'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
portus_1      | /usr/lib64/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
portus_1      | /usr/lib64/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'

**Comment by Vad1mo** [comment]
What are you trying to do?

The error is clear: **Unknown MySQL server host 'db' (-3)**

**Comment by nunterr** [comment]
I was not successfully deployed in the docker-compose up times error

**Comment by nunterr** [comment]
Try to modify the BD connection, but it doesn't seem to be the problem here

**Comment by nunterr** [comment]
I was not successfully deployed in the docker-compose up times error，Try to modify the BD connection, but it doesn't seem to be the problem here @Vad1mo

**Comment by nunterr** [comment]
@
<img width="1279" alt="wx20171215-001332 2x" src="https://user-images.githubusercontent.com/13696064/34002152-d3a001b6-e12c-11e7-8305-262bf7178e24.png">

**Comment by Vad1mo** [comment]
so you did `docker-compose up` having the error in the beginning is IMHO. The DB needs a few seconds to startup. If you do `docker-compose down && docker-compose up` do you see the error again?

**Comment by nunterr** [comment]
I will always make a mistake. I can't connect to the database. I don't know where the specific problem is

**Comment by mssola** [comment]
@nunterr how are you trying to deploy Portus ? I figure it's with docker-compose, but could you submit the `docker-compose.yml` file you are using ? Maybe this way we can figure what's wrong 😉

**Comment by nunterr** [comment]
I was deployed using the master version of the default  @docker-compose.yml, without changing the content

**Comment by mssola** [comment]
It appears to be a networking issue overall. For example, the `webpack` process does not have internet access either. There's something fishy about this. What OS are you using ? Can you confirm that from within a container (e.g. use `docker exec` to manually ping something) you can reach other containers or the outside world ?

**Comment by mssola** [comment]
Closing, since this appears to be a networking issue. Moreover, we've updated the docker-compose file, so you might want to update it (e.g. crono is no longer there). Thanks!
