### ISSUE TITLE
Cannot login to Portus running in Docker container on Openstack VM host

### ISSUE THREAD

**Issue by cherrishccl** [SUSE/Portus#1539]
I had installed the Portus on the openstack compute node and seen that all the docker containers were running.
Then I tried to login the Portus from Openstack VM host,but faild:
Error response from daemon: Get http://192.168.1.12:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
How to fix it?
Thank you.

**Comment by mssola** [comment]
I'm honestly not sure 😕 This looks like there's some kind of networking issue. It depends on your configuration and how you have deployed everything. Could you check whether the different VMs are reachable ?

Plus, when you say "login", you mean like "docker login" right ? Not from the web UI.

**Comment by cherrishccl** [comment]
@mssola Yes,I think so,there's some kind of networking issue.I had deployed every ，and woked well on other computers(not openstack vm) when executed this command "docker login".Thanks.

**Comment by mssola** [comment]
Could you enter into more detail about your deployment method ? As in, configuration files, open ports, what is the expected workflow, etc. Also, provide logs if possible.

**Comment by mssola** [comment]
Closing since I think this is not related to Portus itself. If you have any more details, feel free to let us know. Thanks!
