### ISSUE TITLE
No new release since January

### ISSUE THREAD

**Issue by hbastosc** [SUSE/Portus#1545]
Hi, 

Just wanted to ask if there is any intentions to create releases in the near future. There hasn't been any new release since January but there do seem to be a lot of commits from the development team.

**Comment by martinsp** [comment]
See https://github.com/SUSE/Portus/issues/1514#issuecomment-352024678 for some details

**Comment by mssola** [comment]
Theoretically in November there should've been a release candidate, but some bugs had to be attended before and they took longer than expected. As I mentioned in #1514, hopefully in the following weeks we can have something more stable.

I'll close this issue in favor of #1514 if you don't mind, but feel free to write more comments if you have any more doubts.
