### ISSUE TITLE
Portus源码里面没有compose-setup.sh脚本

### ISSUE THREAD

**Issue by mansoncui** [SUSE/Portus#1552]
Portus源码里面没有compose-setup.sh脚本

**Comment by mssola** [comment]
> There is no compose-setup.sh script in the Portus source code

Yeah, that's right. You only need to call:

```
$ docker-compose up
```

Where did you find a reference to `compose-setup.sh` ? We should remove it...

**Comment by lanmingle** [comment]
今天我取消 star 了，这玩意使用起来复杂，安装麻烦到要死，反正我到 examples 里面使用  docker-compose up 从来没有启动成功过（生成私有秘钥等都干了），就特么不能简单还特么多的借口，兄弟保重。

**Comment by mssola** [comment]
I'll close this issue then (if I Google Translate translated this properly 😅). Bear in mind that you can create self-signed certificates with a simple command:

```
$ openssl req  -nodes -new -x509  -keyout portus.key -out portus.crt
```

And then, in `examples/compose`, you can move these certificates into the `secrets` directory and execute:

```
$ docker-compose -f docker-compose.insecure.yml up
```
