### ISSUE TITLE
Improve dashboard messages when updating resource

### ISSUE THREAD

**Issue by lightlace** [SUSE/Portus#1578]
At the moment, i'm working on the implementation of a "Name" field for the webhooks in Portus. #1340 
For testing purposes i changed the name of a webhook from "foobar" to "foobarhook".
The dashboard recognizes that, but it says "$USER updated "foobar" under the $NAMESPACE namespace."

So, it might be irritating to see the old webhook name under "Recent activities".
Therefore a special message like "$USER has updated the name of the webhook $OLD_WEBHOOK_NAME to $NEW_WEBHOOK_NAME".

**Comment by vitoravelino** [comment]
Maybe rename it to "Improve dashboard messages when updating resource"? Then you can put the webhook as an example.
