### ISSUE TITLE
docker-compose: Step 7/8  Error

### ISSUE THREAD

**Issue by DevilMayCrySamsara** [SUSE/Portus#1579]
[root@GitlabServer Portus]# docker-compose up
Building portus
Step 1/8 : FROM opensuse/ruby:2.4
 ---> 31544e184a5c
Step 2/8 : MAINTAINER SUSE Containers Team <containers@suse.com>
 ---> Using cache
 ---> e4ac37142751
Step 3/8 : ENV COMPOSE 1
 ---> Using cache
 ---> 8ba5361ef02a
Step 4/8 : EXPOSE 3000
 ---> Using cache
 ---> 42bedede76fd
Step 5/8 : WORKDIR /srv/Portus
 ---> Using cache
 ---> 1b6993dfd5c3
Step 6/8 : COPY Gemfile* ./
 ---> Using cache
 ---> 727b158fc61e
Step 7/8 : RUN zypper ref &&     zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler            libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 &&     zypper -n in --no-recommends -t pattern devel_basis &&     bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a
 ---> Running in b475e677497a
Retrieving repository 'NON OSS' metadata [...Repository 'NON OSS' is invalid.
[NON OSS|http://download.opensuse.org/distribution/leap/42.3/repo/non-oss/suse/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'NON OSS' because of the above error.
error]
Retrieving repository 'NON OSS Update' metadata [....error]
Repository 'NON OSS Update' is invalid.
[NON OSS Update|http://download.opensuse.org/update/leap/42.3/non-oss/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'NON OSS Update' because of the above error.
Retrieving repository 'OSS' metadata [..error]
Repository 'OSS' is invalid.
[OSS|http://download.opensuse.org/distribution/leap/42.3/repo/oss/suse/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'OSS' because of the above error.
Retrieving repository 'OSS Update' metadata [.....error]
Repository 'OSS Update' is invalid.
[OSS Update|http://download.opensuse.org/update/leap/42.3/oss/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'OSS Update' because of the above error.
Retrieving repository 'ruby' metadata [......

Warning: Digest verification failed for file 'a6803df074f22e2bd5f452cab7c41a5986e9f1cf649d6b5a2be609e1e019a42c-primary.xml.gz'
[/var/cache/zypp/raw/rubyyQcFtb/repodata/a6803df074f22e2bd5f452cab7c41a5986e9f1cf649d6b5a2be609e1e019a42c-primary.xml.gz]

  expected a6803df074f22e2bd5f452cab7c41a5986e9f1cf649d6b5a2be609e1e019a42c
  but got  80535312e29e3abc1f8a6a16a4e920a44e4518a8765b0786b22f476127e2daa7

Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.

However if you made certain that the file with checksum '8053..' is secure, correct
and should be used within this operation, enter the first 4 characters of the checksum
to unblock using this file on your own risk. Empty input will discard the file.

Unblock or discard? [8053/...? shows all options] (discard): Cannot read input: bad stream or EOF.
If you run zypper without a terminal, use '--non-interactive' global
option to make zypper use default answers to prompts.
error]
Repository 'ruby' is invalid.
[ruby|https://download.opensuse.org/repositories/devel:/languages:/ruby/openSUSE_Leap_42.3] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ruby' because of the above error.
Could not refresh the repositories because of errors.
ERROR: Service 'portus' failed to build: The command '/bin/sh -c zypper ref &&     zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler            libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 &&     zypper -n in --no-recommends -t pattern devel_basis &&     bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a' returned a non-zero code: 4

**Comment by DevilMayCrySamsara** [comment]
CentOS Linux release 7.4.1708

**Comment by DevilMayCrySamsara** [comment]
CentOS Linux release 7.4.1708

**Comment by mssola** [comment]
This doesn't happen to me on openSUSE Leap 42.3. Maybe it was a networking issue ? Could you try again ? Otherwise I'd need more context 😅

**Comment by Nick-Harvey** [comment]
I remember running into something similar a few weeks back and while It's a bit hackish, this is what my dockerfile looks like and it builds successfully

```
FROM opensuse/ruby:2.4
MAINTAINER SUSE Containers Team <containers@suse.com>

ENV COMPOSE=1
EXPOSE 3000

WORKDIR /srv/Portus
COPY Gemfile* ./
COPY init rpm-import-repo-key /
COPY portusctl.x86_64.rpm /

# Let's explain this RUN command:
#   1. First of all we refresh, since opensuse/ruby does a zypper clean -a in
#      the end.
#   2. Then we install dev. dependencies and the devel_basis pattern (used for
#      building stuff like nokogiri). With that we can run bundle install.
#   3. We then proceed to remove unneeded clutter: first we remove some packages
#      installed with the devel_basis pattern, and finally we zypper clean -a.
RUN zypper ref && \
	chmod +x /rpm-import-repo-key /init && \
	/rpm-import-repo-key 55A0B34D49501BB7CA474F5AA193FBB572174FC2 && \
	zypper ar -f obs://Virtualization:containers:Portus/openSUSE_Leap_42.3 portus && \
	zypper ref && \
	zypper -n in /portusctl.x86_64.rpm &&\
    zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler \
           libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 && \
    zypper -n in --no-recommends -t pattern devel_basis && \
    bundle install --retry=3 && \
    zypper -n rm wicked wicked-service autoconf automake \
           binutils bison cpp cvs flex gdbm-devel gettext-tools \
           libtool m4 make makeinfo && \
    zypper clean -a

ADD . .
ENTRYPOINT ["./init"]
```

Essentially what I've done is merge the dockerfile from the [official docker image](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus) with the latest dockerfile and it builds properly on my machine (fedora 27). With the latest master, I'm not sure the portusctl is still needed but, just to be safe copy that bin and the rpm-import-repo-key file in, and it should work.

**Comment by DevilMayCrySamsara** [comment]
OK, I'll try. Thank you for your reply.

**Comment by DevilMayCrySamsara** [comment]
@Nick-Harvey  sorry  COPY init rpm-import-repo-key /     ，i have no init directory ,so happens
Step 7/11 : COPY init rpm-import-repo-key /
ERROR: Service 'portus' failed to build: lstat init: no such file or directory

**Comment by DevilMayCrySamsara** [comment]
@mssola   Docker version 17.05.0-ce, build 89658be    ,What more information do you need?
At first I also suspected that it was a network problem, but based on the wrong message, I visited the address,I can access this address on the browser: http://download.opensuse.org/update/leap/42.3/non-oss/,

**Comment by mssola** [comment]
There must be something wrong on the packaging side of Docker for CentOS 🤔 Have you tried with a Docker from another provider ?

Also, for more info, this is what I'm using right now:

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.5
 Git commit:   f4ffd2511ce9
 Built:        Tue Dec 19 03:46:53 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   f4ffd2511ce9
 Built:        Sat Oct 21 17:27:07 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by Nick-Harvey** [comment]
@DevilMayCrySamsara you have to copy that rpm-import-repo-key file and that init file from https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus and put it in your local portus repo. That should work, but let me know if it doesn't

**Comment by DevilMayCrySamsara** [comment]
@mssola   sorry, i have update docker  ,and now info:
[root@GitlabServer Portus]# docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:25:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
but ,it has the same error......it seems doesn't work

**Comment by DevilMayCrySamsara** [comment]
@Nick-Harvey  em, where is portusctl.x86_64.rpm?  i found init file  by your way, but rpm-import-repo-key file   has been removed ,i create a file named "rpm-import-repo-key",and  the file content  writted by  the past file,  but  i can't find portusctl.x86_64.rpm.......

**Comment by mssola** [comment]
@DevilMayCrySamsara could you try with a Docker provided by somewhere else. I wonder if this might be something about how this Docker has been packaged 🤔
