### ISSUE TITLE
Question: How do social logins (Github, Google, etc.) log into the registry? 

### ISSUE THREAD

**Issue by Nick-Harvey** [SUSE/Portus#1591]
If you enable social logins via the config file, the user can authenticate to portus UI just fine, but what password do they use when running "docker login" ?

**Comment by Vad1mo** [comment]
I need to  check it. But IMHO it was implemented in a way that a comlex random password is generated. So if a user wants to login with his password he needs to reset it first.

But I'll check the code to see how its implemented

**Comment by Nick-Harvey** [comment]
Thanks! I appreciate it very much :) 

I'm doing the same thing from my side and trying to get a better grasp on how auth works in portus. One idea I have in my head is that when the user creates and account with omni-auth, they're presented with a form to set their username and actual name. It might be a good idea for the user to set a registry password in that same form, but I imagine that would create a complicated password reset process.

**Comment by mssola** [comment]
The code is around the controllers with names like `app/controllers/auth/omniauth_*`, but ultimately, what you are asking can be seen in `User.create_from_oauth`. Its current implementation is:

```ruby
  def self.create_from_oauth(params, data)
    params.merge! data["info"].slice("email")
    params.merge! data.slice("provider", "uid")
    params[:password] = Devise.friendly_token[0, 20]
    User.create params
  end
```

That means that a random password will be created for you. Then, if you want a proper password, you have to go to your profile page and update the password.

> I'm doing the same thing from my side and trying to get a better grasp on how auth works in portus. One idea I have in my head is that when the user creates and account with omni-auth, they're presented with a form to set their username and actual name. It might be a good idea for the user to set a registry password in that same form, but I imagine that would create a complicated password reset process.

I don't think it should be too difficult to implement and it makes total sense 👍

**Comment by Vad1mo** [comment]
When we implemented that feature, we skipped the password on purpose.
We traded usability in favour of completeness  to provide smooth initial login and user experience.

The fact that the user has the option to change his username before he registers is an admission to  the situation that a new personal namespace is created that can't be changed afterwards. 
 
Also with *Application tokens* the situation isn't that bad,  and this option is IMHO easier when it comes to pushing from command line.

**Comment by mssola** [comment]
I see. I'll keep this issue open then, to remind me that I should update the documentation with this explanation. Thanks @Vad1mo ! 👏

**Comment by marc0s** [comment]
> Also with Application tokens the situation isn't that bad so one doesn't need the password at all. This option is IMHO easier when it comes to pushing from command line or CI/CD.

I like this, how can these application tokens be used with `docker login`? Is this possible at all?

Thanks

**Comment by Vad1mo** [comment]
@marc0s, yes just login with you github account and in your profile create a token. Use that token for `docker login -u marc0s -p <token>`

**Comment by marc0s** [comment]
@Vad1mo thanks it worked! I was previously testing with the `application` as username, I don't know why I didn't though on using just my username... Anyway, it worked flawlessly!

**Comment by marc0s** [comment]
Just tell me if this is not the issue/place to ask but, can I bind the OAuth2-logged in users (which I have already restricted to a domain, using Google as provider) to an existing team somehow?  I'd like to give them some default permissions, at least so they can browse what's currently there. Thanks!

**Comment by emrahcetiner** [comment]
@Vad1mo  tokens can't viewing after generated. how to view it later?

**Comment by Vad1mo** [comment]
if you click on generate token, you should be able to see the token popping up as a message. There you can cop&paste it

**Comment by mssola** [comment]
Fixed by #1957.

**Comment by raolivei** [comment]
What do I actually enter as `Current password` for my Google account (using google_auth2)?

**Comment by raolivei** [comment]
> if you click on generate token, you should be able to see the token popping up as a message. There you can cop&paste it

Where specifically can we see this *Generate Token* option?

**Comment by raolivei** [comment]
@mssola @Vad1mo 
I set my google_oauth2 account and I am able to connect to Portus UI.
In the UI, more specifically in `http://<portus:port>/users/edit`, What do I actually enter as `Current password` for my Google account? It was said that a random password was assigned but this password is not shown for the user at login creation moment in Portus (on purpose, as @Vad1mo mentioned). So how can I see the randomly assigned password and use it in the `Current password` field, in order to change my password?

> if you click on generate token, you should be able to see the token popping up as a message. There you can cop&paste it

Where specifically can we see this **Generate Token** option?

I am looking for a way to `docker login` using google_oauth2 accounts.

**Comment by raolivei** [comment]
> if you click on generate token, you should be able to see the token popping up as a message. There you can cop&paste it

Sorry but this is not accurate (or I am making a terrible mistake), but to create a Personal Access Token -- which is the only token option I see -- you should go to Github Settings (top right by clicking your profile) >> Developer settings >> Personal access tokens.

Also, even after creating the token for my GitHub user, connecting to Portus using github oauth... and trying to change the password but again, the token is invalid for the portus user.

Could someone provide clear steps on how to change password for Google oauth/Github oauth in order to `docker login`?
