### ISSUE TITLE
No provider of 'ruby2.5-devel' found.

### ISSUE THREAD

**Issue by tomthetommy** [SUSE/Portus#1597]
Hi,

So I'm using the examples found in https://github.com/SUSE/Portus/tree/master/examples/compose

But can't due to the known issue of https://github.com/SUSE/Portus/issues/1574

When I try to build the docker image myself, I get the following errors:

Sending build context to Docker daemon  7.335MB
Step 1/8 : FROM opensuse/ruby:2.5
manifest for opensuse/ruby:2.5 not found

So I changed it to opensuse/ruby:latest and now get the following error:

Reading installed packages...
'nodejs' not found in package names. Trying capabilities.
'ruby2.5-devel' not found in package names. Trying capabilities.
No provider of 'ruby2.5-devel' found.

Where do I go from here?

Tom

**Comment by Vad1mo** [comment]
the review https://github.com/SUSE/Portus/pull/1593#pullrequestreview-89297974 mentioned it. however you can build it manually meanwhile you can build the image yourself 

https://github.com/openSUSE/docker-containers

**Comment by Vad1mo** [comment]
However even if you manage to build your Ruby 2.5 yourself. Portus image won't build.  This issue prevents from testing the latest master. 

This is a major issue that needs to be addressed.

**Comment by tomthetommy** [comment]
I've tried it, and it's just a cluster fudge of errors. I've also tried a rebuild from master of the portus image and it's erroring on "
/bin/sh: bundle: command not found"

I've added it myself, and there's more errors following it. 

I'll await the fixes and then start again.

**Comment by Vad1mo** [comment]
@mssola and @vitoravelino could you check on the packaging problem?

**Comment by tomthetommy** [comment]
What I mean't to say was, I added the bundle exec into the bin manually as it wasn't present in the ruby image.

But yeah, more errors follow so I'll wait on it.

**Comment by mssola** [comment]
I pushed the `opensuse/ruby:2.5` image yesterday because I was using a local version all the time and I forgot to push it 😅 Now I also realized that it's missing some links. Now I'm building & testing and I'll push everything so the development image works again... Sorry for the trouble 😞

**Comment by mssola** [comment]
PR #1602 should've fixed your issues. That being said, Docker hub has not built `opensuse/ruby:2.5` yet, so we'll have to wait until that to confirm that this is fixed (or you can build it locally 😉).

Moreover, we have already branched out 2.3 and the Docker hub tag has been created, so you can use `opensuse/portus:2.3` (which is the release candidate).
