### ISSUE TITLE
Fix remaining issues on the synchronization of the registry

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1599]
There are some pending issues from the synchronization of the registry. This issue tries to be an aggregate of old issues.

#### Crono deletes everything

Some issues pointed out that old crono might remove all the contents. See #663.

#### Crono is adding & removing images

See issues: #1184, #1261, #1160 and #1232.

**Comment by Vesli** [comment]
Hey mssola, how is this issue going on?

Here at my company I wanted to have a go with Portus and fortunately we are using it for our staging environment only at the moment.

I say fortunately because we are running it directly on an OpenSuse machine and over the weekend Portus deleted all the images, from its DB and from the registry!

I saw that for some people it pushes it again after some time, but on our case it did nothing of the sort.

I'm on Portus 2.2 and registry 2.6.
Should I move for the docker version instead or stop using Portus for now?

Thanks!

**Comment by mssola** [comment]
> I say fortunately because we are running it directly on an OpenSuse machine and over the weekend Portus deleted all the images, from its DB and from the registry!

That is ... bad 😞 Could you possibly collect the logs, and possibly get into more detail on your deployment strategy. Even if it's a bit old, it might help us to fix this situation.

> I'm on Portus 2.2 and registry 2.6. Should I move for the docker version instead or stop using Portus for now?

Well, I'd advise in favor of this solution. Bear in mind that we are in the process of releasing the 2.3 version, so you might want to take a look at this (since moreover it has some deployment changes). Check our [examples](https://github.com/SUSE/Portus/tree/master/examples/compose) directory for some production-ready examples (just use `opensuse/portus:2.3` instead of `opensuse/portus:head`, since there are no stability guarantees for `2.3` 😉).

**Comment by marc0s** [comment]
I'm using `portus:head` and `registry:2.6` and I'm hitting this issue.  Any workaround in the meantime?
What I see in the logs is
```
background_1  | Net::OpenTimeout: connection timed out.
background_1  | [catalog] Could not fetch manifest for 'redacted/image2' with tag 'latest': Net::OpenTimeout: connection timed out.
background_1  | Net::OpenTimeout: connection timed out.
background_1  | [catalog] Could not fetch manifest for 'redacted/image2' with tag 'latest': Net::OpenTimeout: connection timed out.
background_1  | [catalog] Removed the tag 'latest'.
background_1  | [catalog] Removed the image 'image2'.
background_1  | [catalog] Created the tag 'latest'.
``` 
Each of the images is around 650MB and there are just 5 of them (is a recently created registry).

Thanks!

**Comment by mssola** [comment]
@marc0s see [this comment](https://github.com/SUSE/Portus/issues/1664#issuecomment-364395126). This might even fix this issue (we'd need to identify some corner cases when enabled, but it should fix the situation for most people).

**Comment by mssola** [comment]
We merged  a PR yesterday (#1675) which fixes most issues (and works around existing ones). The image has not been built yet on the docker hub (it's in "Queue" for quite some time now ...), but once that is built you'll be able to pull that and have a better experience with this piece of Portus 😉

**Comment by mssola** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [portus: Fix remaining issues with synchronization and the registry](https://trello.com/c/wxgUJfeO/667-portus-fix-remaining-issues-with-synchronization-and-the-registry)

**Comment by mssola** [comment]
See #1787 for some fixes on the `update-delete` policy. After some further tests, we will add these fixes into a new patch-level release (`2.3.3`) so everyone can pull the fixes right away.

**Comment by mssola** [comment]
> See #1787 for some fixes on the update-delete policy. After some further tests, we will add these fixes into a new patch-level release (2.3.3) so everyone can pull the fixes right away.

This has already been cherry picked into the `v2.3` branch and now it's part of the `2.3` docker image.

**Comment by mssola** [comment]
I've deployed a Portus instance for a day, and after messing with it a couple of times, everything seems reliable. I'll do a couple of more tests and I'll take another look at the code, but if everything is fine I'll simply close this issue. Feedback is welcome :smile:

**Comment by mssola** [comment]
I believe this can be closed. Let's create new issues for possible regressions or new bugs on this.
