### ISSUE TITLE
The API calls should honor the RAILS_RELATIVE_URL_ROOT path

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1608]
If `RAILS_RELATIVE_URL_ROOT` has been specified, then the API calls should prefix this value in the path.

**Comment by mssola** [comment]
See [this comment](https://github.com/SUSE/Portus/issues/1408#issuecomment-359386591).

**Comment by mssola** [comment]
Fixed with #1610.

**Comment by phasenohr** [comment]
Thanks @mssola for this quick fix
Almost everything is fixed but the URLs asking for `assets` are still not taking into account `RAILS_RELATIVE_ROOT` This bug was present already months ago but I did not report it.

**Comment by vitoravelino** [comment]
@phasenohr Can you give us more details? I mean, what's happening with which the assets?

**Comment by phasenohr** [comment]
I have `RAILS_RELATIVE_ROOT = /apps/portus/` therefore I access Portus via http://server/apps/portus/

For example, the symbols used next to _LDAP Login_ on the login page or next to _Dashboard, Namespaces, Repositories etc..._ on the main page are not displayed as the font files are not accessible.

When I go to http://server/apps/portus/, there are calls from the browser to urls like
http://server/assets/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff instead of http://server/apps/portus/assets/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff (which is indeed a valid url)

In addition to the calls to `fontawesome-webfont-xxx.woff`, I noticed other calls to http://server/assets instead of http://server/apps/portus/assets include `assets/layout/bg-xxxxx.png`, `assets/raleway-xxxxxx.woff2`, `assets/fontawesome-webfont-xxxxx.woff2`

**Comment by ghaberek** [comment]
I'm having the same issue as @phasenohr after deploying Portus from the latest image on [DockerHub](https://hub.docker.com/r/opensuse/portus/).

I've got `RAILS_RELATIVE_URL_ROOT` set to `/portus` and `RAILS_SERVE_STATIC_FILES` set to `true`. 

Everything seems to function correctly, but the application is not correctly referencing the path to things in `/assets`, which should be `/portus/assets`.

In the examples below (formatted for emphasis), the stylesheet and script paths are correct, but all of the other icon references are not. The FontAwesome URLs in the CSS are also incorrect.

If this has been corrected, then I'm having a hard time understanding what I'm doing wrong.

**HTML example**

    <head>
      <title>Portus</title>
      <link rel="stylesheet" media="all" href="/portus/assets/application-20f67d7832e7f80743d80b935441f204ab9a5cfdbfbc155027f330d6397aed28.css" />
      <meta name="csrf-param" content="authenticity_token" />
      <meta name="csrf-token" content="VyOPLrBvn4ILPxdn52Wc5+II51iSiF84A1dfq1PGWR/NF6c6KqSKsF3kdmNDLJvUPkMONcdTCceCa6xD/TtMcw==" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57" />
      <link href="/favicon/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60" />
    ...
      <link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png" />
      <link href="/favicon/manifest.json" rel="manifest" />
      <link color="#205683" href="/favicon/safari-pinned-tab.svg" rel="mask-icon" />
      <link href="/favicon/favicon.ico" rel="shortcut icon" />
      <meta content="Portus" name="apple-mobile-web-app-title" />
      <meta content="Portus" name="application-name" />
      <meta content="#da532c" name="msapplication-TileColor" />
      <meta content="/favicon/mstile-144x144.png" name="msapplication-TileImage" />
      <meta content="/favicon/browserconfig.xml" name="msapplication-config" />
      <meta content="#205683" name="theme-color" />
      <script src="/portus/assets/unmanaged-6cf4a1295ff6946a5e84e7ccee9d29838b7d173552a385e3f59eb5215abfbe73.js"></script>
      <script src="/portus/assets/webpack/application-76abd0e6b2530af98dd1.js"></script>
    </head>

**CSS example**

    @font-face {
      font-family: 'FontAwesome';
      src:url("/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot");
      src:url("/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot?#iefix") format("embedded-opentype"),
          url("/assets/fontawesome-webfont-2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe.woff2") format("woff2"),
          url("/assets/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff") format("woff"),
          url("/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf") format("truetype"),
          url("/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg#fontawesomeregular") format("svg");
      font-weight: normal;
      font-style: normal
    }

**Comment by Vad1mo** [comment]
can you try with `RAILS_SERVE_STATIC_FILES=false` I think this feature is missing in 2.3 ?

**Comment by ghaberek** [comment]
Nope, sorry. Same problem when changing it to `false`.

**Comment by CondormanFr** [comment]
I have the same issue that describe by @ghaberek with the docker head image.
