### ISSUE TITLE
Task portus:assets:compile needs development gems

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1612]
The task `portus:assets:compile` needs development gems.  This dependency make it hard to create a bundle for prod in a ci/cd system. because it needs to add all gems then `portus:assets:compile` and then remove dev and test gems again. In docker envs this is not possible in one step in two steps it doesn't make sense.

I don't know how to resolve it other then suggest adding annotate and other dependencies into production.

**Comment by mssola** [comment]
You shouldn't be executing this task in production. All assets have already been bundled/minimized/... in the `public` directory (notice that we leave out lots of gems on purpose, so the final Docker image is as small as possible and only has what is needed for production). What's the use case for this ?

**Comment by Vad1mo** [comment]
I am building a custom image and wanted to compile the assets as they aren't checked in git. 

I also don't want to do it in the CI system (docker hub automated build) but rather when creating the image, If I have to setup a build Environment I need to do it outside. 
I have the opinion that it should not be needed to create a build environment in order to create an image  as all can be done the Dockerfile together with multistage builds.

**Comment by Vad1mo** [comment]
thanks for the update, I am not very happy with the current setup. Because as its the only way how ruby works, I can now workaround it.

**Comment by mssola** [comment]
See [my comment](https://github.com/SUSE/Portus/issues/1616#issuecomment-364137294).
