### ISSUE TITLE
portus background - Cannot obtain authorization token

### ISSUE THREAD

**Issue by Vesli** [SUSE/Portus#1618]
Was my bad about the config.

**Comment by Nick-Harvey** [comment]
What was the config error? Could be helpful for others :)

**Comment by Vesli** [comment]
It was the password badly specified! 
The portus password wasn't identical in the 2 containers (or simply wrong in both, don't really remember) thus I deleted the user Portus in the DB and recreated it.

Nevertheless the background is still not working, regarding:
#1589
