### ISSUE TITLE
OpenID Connect not actually implemented

### ISSUE THREAD

**Issue by mcharris** [SUSE/Portus#1619]
According to the documentation Portus should be able to support OpenID Connect when it is not supported by the current implementation. The gem that was added is omniauth-openid which only supports OpenID and not OpenID Connect. Please note, these are two different things.

**Comment by Vad1mo** [comment]
Hmm, thank you for the info. Indeed it should be OIDC.

We will provide an PR.

**Comment by mssola** [comment]
@Vad1mo do you think it's an easy thing to provide ? Or we should postpone this to 2.4 ?

**Comment by mcharris** [comment]
@Vad1mo I am currently working on a pull request for adding OpenID Connect. The issue is that there isnt a rubgems.com package that is updated/maintained for OIDC with omniauth. The closest one is gem https://github.com/hhorikawa/omniauth-openid-connect. 

Essentially I would need to add
`gem 'omniauth-openid-connect', :git => 'https://github.com/hhorikawa/omniauth-openid-connect'` to the Gemfile. That just doesnt seem like a good solution. For my needs I've been contemplating adding omniauth-saml instead since it will fix my problem and it is maintained by omniauth.io.

**Comment by Vad1mo** [comment]
alright, did you look at https://github.com/m0n9oose/omniauth_openid_connect its more or less up to date. 

Go forward with the PR, I will have some time next week for testing.

**Comment by mcharris** [comment]
@Vad1mo I did but decided against it since it wasnt updated for that last 2 years. I will use that though unless I run into an issue.

**Comment by Vad1mo** [comment]
Hello @mcharris, sorry it seems I messed up with cope and paste. Looking again at the openid connect situation, it seems like indeed https://github.com/hhorikawa/omniauth-openid-connect
is the best and most up to date available option. 

Sorry for the confussion

**Comment by mcharris** [comment]
Pull request #1633 open. Let me know if you have any questions. I might close the pull request if it fails travis tests.

**Comment by mssola** [comment]
@Vad1mo & @mcharris if you don't mind we can leave this for 2.4, since the PR seems quite big (that is, you can submit PRs as usual, but I won't cherry pick it to 2.3)

**Comment by Vad1mo** [comment]
Fine for me, unless 2.4 is not in 2019 :D

**Comment by mssola** [comment]
@mcharris have you worked on this anymore ?

**Comment by trunet** [comment]
can you use https://github.com/m0n9oose/omniauth_openid_connect instead?

**Comment by Vad1mo** [comment]
We could work on that issue and integrate https://github.com/m0n9oose/omniauth_openid_connect

**Comment by mssola** [comment]
Fixed by #2154
