### ISSUE TITLE
All ajax requests are adding a double slash in front of the host

### ISSUE THREAD

**Issue by anlek** [SUSE/Portus#1625]
Running the docker-compose version and when I click on "Namespaces" a request fires to:
`http://hub.[redacted].com//api/v1/namespaces` (note the double slashes after the `.com`).
If I run the same request with a single slash (aka: `http://hub.[redacted].com/api/v1/namespaces`) it works just fine.

Namespaces aren't the only issue, every ajax request hits the double slashed URL. Any ideas?
I'm running Portus v2.3 (docker `:latest` tag)

You can see my docker-compose file here: https://gist.github.com/anlek/9799564391dc1bf61a59fe624e6df632

I don't have any custom config files for Portus

**Comment by anlek** [comment]
just found that my `window.API_URL` is `"//hub.[redacted].com/"`. Not sure if that helps though :(

**Comment by anlek** [comment]
OK, after another hour at this, I think it's `traefik`'s way of setting up the HTTP_HOST env variable that's got an extra `/` in it or something like that. The odd thing is some API calls seem to not do double slashes (like namespace name validation call) but others seem to have an issue (like the team name validation).

**Comment by vitoravelino** [comment]
I'm aware that this was happening but didn't know it was an issue. I'm going to investigate it.

**Comment by anlek** [comment]
Awesome, thank you so much. Will this be on the `:head` branch of docker now?

**Comment by anlek** [comment]
`:head` works perfectly! Thank you so much for the fix!
