### ISSUE TITLE
404 error accessing Portus UI

### ISSUE THREAD

**Issue by majidpal** [SUSE/Portus#1626]
Have used docker image  opensuse/portus:2.3 and mariadb:10.0.23 but facing issue while accessing UI. Below error -

Started GET "/assets/application-20f67d7832e7f80743d80b935441f204ab9a5cfdbfbc155027f330d6397aed28.css" for  at 2018-01-25 02:00:23 +0000
Started GET "/assets/webpack/application-cf07f57053f06e4d93e5.js" for 10.236.179.117 at 2018-01-25 02:00:23 +0000

ActionController::RoutingError (No route matches [GET] "/assets/webpack/application-cf07f57053f06e4d93e5.js"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

Processing by ErrorsController#show as */*
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (13.1ms)
  Rendered errors/_status_title.html.slim (3.0ms)
Completed 404 Not Found in 54ms (Views: 50.3ms | ActiveRecord: 0.0ms)

**Comment by vitoravelino** [comment]
Hi,

Are you using `docker-compose`? Are all the containers running? What's your setup?

**Comment by majidpal** [comment]
I am not using docker compose. I have used portus and mariadb images on
same server.



docker run -d -p 3000:3000 --name=portus -e
PORTUS_CHECK_SSL_USAGE_ENABLED=false -e

PORTUS_SECRET_KEY_BASE=test -e PORTUS_DB_HOST=XXXXXXXX -e

PORTUS_DB_DATABASE=portus_test -e PORTUS_DB_PASSWORD=test -e
PORTUS_DB_POOL=5 -e

PORTUS_KEY_PATH=/certificates/portus.key -e PORTUS_PASSWORD=test -e

PORTUS_ANONYMOUS_BROWSING_ENABLED=true -e
PORTUS_FIRST_USER_ADMIN_ENABLED=true -e

PORTUS_SIGNUP_ENABLED=true opensuse/portus:2.3




docker run --name mariadb_portus -p 8080:8080 -3306:3306 -e
MYSQL_ROOT_PASSWORD=test -e

MYSQL_DATABASE=portus_test -d mariadb:10.0.23

**Comment by vitoravelino** [comment]
I suppose that you already ran `portus:assets:compile` rake task, right? Can you try to set `RAILS_SERVE_STATIC_FILES=true`?

**Comment by majidpal** [comment]
i have not run any commands explicitly. I just created portus container
with command I gave. I dont have any experience in ruby. Can you help me
where I have to run this commands?

**Comment by vitoravelino** [comment]
Just set env variable `RAILS_SERVE_STATIC_FILES=true` just like you did for the other values. This will tell rails to serve the static content and the 404 should not happen (I hope so).

**Comment by majidpal** [comment]
Ok. Thanks Victor. So will it be like PORTUS_RAILS_SERVE_STATIC_FILES=true
??

**Comment by vitoravelino** [comment]
No, just `RAILS_SERVE_STATIC_FILES=true`.

**Comment by majidpal** [comment]
Great. it worked. Thank you.
