### ISSUE TITLE
Add max entries tags to config file

### ISSUE THREAD

**Issue by TechCatOther** [SUSE/Portus#1637]
Now only 3 entries show in UI. It will be nice to set it customizable. For example 10 or more. 

![default](https://user-images.githubusercontent.com/378937/35502586-7f1afe58-04ee-11e8-802a-afa3a7999973.png)

**Comment by vitoravelino** [comment]
I'm gonna mark this as duplicate since I've already created #1375. I thought that I had increased that to 10... 😕

**Comment by mssola** [comment]
I cannot reproduce this on master. I just pushed four different tags for a repository and they are shown in the same page. For context, are they sharing the same digest ? (as in, are there some tags which are coupled together ?)

**Comment by TechCatOther** [comment]
I use old 2.3-dev rev from 19 Dec. Update to 2.3 from dockerhub. Now 10 images shows in list. Thanks, for help!
