### ISSUE TITLE
Appliance: link on the landing page is wrong

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#164]
How to reproduce:
  * during YaST 1st boot set the name of the machine to: `portus.test.lan`
  * complete the installation
  * visit `http://portus.test.lan`
  * Click on the button at the bottom of the page

=> I am redirected to `https://portus.suse.example.com` instead of `https://portus.test.lan`.

**Comment by flavio** [comment]
**Note well:** everything is fixed after I run `/etc/init.d/portus-firstboot portus.test.lan`

**Comment by jordimassaguerpla** [comment]
this is a side effect of https://github.com/SUSE/Portus/issues/182
