### ISSUE TITLE
vulnerability scanner is always in pending state

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1649]
The vulnerability scanner is always in the pending state. The DB is loaded the connections is established, however for all the images the status are pending.  Also there is noting in the logs of Background or Portus.

Where is it possible to find out more about the current status what is happening with Clair?

**Comment by Vad1mo** [comment]
I managed to process a few images. However its still not clear why some images are in **pending** or **in progress** state. I suspect if the background job failed for what ever reason, it is stuck there forever.

**Comment by mssola** [comment]
One idea is that when you got a Mysql2::Error in #1657 then the scanner did not mark tags as done. #1670 and #1671 should alleviate these situations.

Thus, after both these PRs are merged, I'll mark this issue as "needs info", so we can get more details on the issue.

**Comment by mssola** [comment]
Pull requests have been merged. Please report back whether the changes alleviate your issues.

**Comment by Vad1mo** [comment]
Verified, LGTM

**Comment by pam-** [comment]
hi @Vad1mo i'm currently running into this issue with version `2.3`. Regarding your [comment](https://github.com/SUSE/Portus/issues/1649#issuecomment-363252174): how are you able to process images despite a bunch of them being pending?

I've restarted `clair` a few times and pushed new images but no luck.
