### ISSUE TITLE
Proposal to change endpoint swagger_doc to openapi-spec

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1652]
I am proposing to change to endpoint `/api/swagger_doc` to `/api/openapi-spec` 

- OpenAPI = Specification
- Swagger = Tools for implementing the specification

see: https://swagger.io/blog/difference-between-swagger-and-openapi/

I can quickly provide a PR

**Comment by mssola** [comment]
> I can quickly provide a PR

Sure!
