### ISSUE TITLE
Missing DB GEMs during runtime.

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1655]
I think some gems are not included to the application runtime.

in the file `application.rb` as it is now it states in Line 6:

```rb
Bundler.require(*Rails.groups)
```

Here we are always loading only the development/production gems however the DB gems are in their own group and thus not loaded:

I my code Dockerfile I have to set `ENV["RAILS_GROUPS"] = "mysql"` in order to make sure mysql is also loaded.

**Comment by mssola** [comment]
You're right... What I don't understand is why it's working for me ... 😕
