### ISSUE TITLE
The Vulnerabilities field is to small.

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1657]
When scanning **[node:8](https://hub.docker.com/_/node/)** I get this error:

```
 /usr/local/bundle/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query': Mysql2::Error: Data too long for column 'vulnerabilities' at row 6: UPDATE `tags` SET `tags`.`vulnerabilities`
```

I don't think its a good idea to store then in one field. But thats another issue.

**Comment by mssola** [comment]
I remember that we avoided this by reducing the amount of data being stored. Maybe we should make the column larger...

> I don't think its a good idea to store then in one field. But thats another issue.

👍

**Comment by mssola** [comment]
> I don't think its a good idea to store then in one field. But thats another issue.

Moved this idea into #1669.
