### ISSUE TITLE
Appliance: certificate does not take host name into consideration

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#166]
How to reproduce:
 * during YaST 1st boot set the name of the machine to: portus.test.lan
 * complete the installation
 * visit http://portus.test.lan
 * download the certificate

## Minor issue

The name of the file is `portus.suse.example.com` instead of `portus.test.lan`.

## Real issue

The common name inside of the certificate is set to `portus.suse.example.com` instead of `portus.test.lan`.

**Comment by flavio** [comment]
**Note well:** everything is fixed after I run `/etc/init.d/portus-firstboot portus.test.lan`

**Comment by flavio** [comment]
I had to reinstall the appliance, I have not been able to reproduce the issue. Maybe I caused the issue by letting the image stuck 8 minutes waiting for input on the network configuration dialog...

@jordimassaguerpla feel free to close it if you cannot reproduce that

**Comment by jordimassaguerpla** [comment]
this is a side-effect of https://github.com/SUSE/Portus/issues/182
