### ISSUE TITLE
Store vulnerabilities in a more clever way

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1669]
Right now the security scanning stores all its data into a text column of the tag. We have had issues where this text column was too small (e.g. #1657). One solution was to simply expand this text column, but it feels too hacky.

Thus, we should find a way to store these vulnerabilities in a more clever way, so we avoid these situations. One approach would be to create a "vulnerabilities" table containing the relevant info for each vulnerabilities, and then have pointers to this table.

**Comment by Vad1mo** [comment]
@mssola do you think I is feasible to deliver this feature in the 2.4 release. IMHO a proper vulnerability domain model is the foundation to provide further improvements and advanced solutions that we can target in 2.5 like proposed in #1761

**Comment by mssola** [comment]
I think so. It's on the "To do" column and I really intend to deliver this one :+1:

**Comment by mssola** [comment]
@Vad1mo everything has been merged on this. Thanks for insisting on this :+1:
