### ISSUE TITLE
Appliance: sshd does not allow password logins

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#167]
I know this is more secure, but makes everything easier for the final user.

sshd configuration should have this line:
```
PasswordAuthentication yes
```

instead of having
```
PasswordAuthentication no
```

**Comment by jordimassaguerpla** [comment]
This is because this is the default for running into an openstack cloud. I am not sure if enabling that can be a problem for uploading this appliance to an openstack cloud.

**Comment by jordimassaguerpla** [comment]
We discussed that and agreed to leave it as it is but add info into the wiki, which I already did.
