### ISSUE TITLE
appliance: issue when running portus-firstboot script

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#168]
How to reproduce:
  * complete the 1st boot installation
  * run the following command: `/etc/init.d/portus-firstboot portus.test.lan`

The following error message is printed (note well, I added `set -x` to have more debugging details):
```bash
++ echo 'Disabling firstboot'
Disabling firstboot
++ mv /portus-firstboot /portus-firstboot.disabled
mv: cannot stat ‘/portus-firstboot’: No such file or directory
```

To fix that just change the end of the script to something like that:
```bash
echo "Disabling firstboot"

if [ -f /portus-firstboot ]; then
  mv /portus-firstboot /portus-firstboot.disabled
fi
```

This file is not inside of this repo, that's why I'm not creating a PR.

**Comment by flavio** [comment]
Note well: nothing bad happens because of this message, it can just be confusing for customers.

**Comment by flavio** [comment]
I had to reinstall the appliance, I have not been able to fix the issue. Maybe I caused the issue by letting the image stuck 8 minutes waiting for input on the network configuration dialog...

@jordimassaguerpla feel free to close it if you cannot reproduce that

**Comment by flavio** [comment]
However the fix to the firstboot script is still required.

**Comment by flavio** [comment]
oh.. maybe try running the script more than one time...

**Comment by jordimassaguerpla** [comment]
https://build.opensuse.org/package/rdiff/Virtualization:containers:Portus/PortusAppliance?linkrev=base&rev=51

**Comment by jordimassaguerpla** [comment]
thanks for reporting it.
