### ISSUE TITLE
background can't connect to db and main portus failed to load command...

### ISSUE THREAD

**Issue by Vesli** [SUSE/Portus#1695]
So, I just lost access to my registry sync with portus (fortunately we can go back to amazon) as I wanted to upgrade portus and portus-background with the 2.3 and I have new errors - I'm using a container orchestration (rancher here).

Portus image:

> ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `namespaces` CASCADE
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:510:in `drop_table'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/schema_statements.rb:219:in `create_table'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:482:in `create_table'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
21/02/2018 17:14:59/srv/Portus/db/schema.rb:55:in `block in <top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:41:in `instance_eval'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:41:in `define'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:61:in `define'
21/02/2018 17:14:59/srv/Portus/db/schema.rb:14:in `<top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:221:in `load_schema_for'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:238:in `block in load_schema_current'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:237:in `load_schema_current'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:237:in `block (3 levels) in <top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:241:in `block (3 levels) in <top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
21/02/2018 17:14:59
21/02/2018 17:14:59Caused by:
21/02/2018 17:14:59Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:510:in `drop_table'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/schema_statements.rb:219:in `create_table'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:482:in `create_table'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
21/02/2018 17:14:59/srv/Portus/db/schema.rb:55:in `block in <top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:41:in `instance_eval'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:41:in `define'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/schema.rb:61:in `define'
21/02/2018 17:14:59/srv/Portus/db/schema.rb:14:in `<top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:221:in `load_schema_for'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:238:in `block in load_schema_current'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:278:in `block in each_current_configuration'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:277:in `each_current_configuration'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:237:in `load_schema_current'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:237:in `block (3 levels) in <top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:241:in `block (3 levels) in <top (required)>'
21/02/2018 17:14:59/srv/Portus/vendor/bundle/ruby/2.5.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
21/02/2018 17:14:59Tasks: TOP => db:schema:load
21/02/2018 17:14:59(See full trace by running task with --trace)
21/02/2018 17:14:59bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
21/02/2018 17:14:59RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rake db:setup
21/02/2018 17:14:59  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
21/02/2018 17:14:59  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
21/02/2018 17:14:59  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
21/02/2018 17:14:59  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
21/02/2018 17:14:59  /srv/Portus/packaging/suse/portusctl/lib/cli.rb:260:in `rake'
21/02/2018 17:14:59  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
21/02/2018 17:14:59  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
21/02/2018 17:14:59  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
21/02/2018 17:14:59  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
21/02/2018 17:14:59  packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
21/02/2018 17:14:59Error at setup time

Background:

> 21/02/2018 17:05:46[Database] Timeout reached, exiting with error. Check the logs...
21/02/2018 17:05:46Traceback (most recent call last):
21/02/2018 17:05:46	10: from bin/rails:12:in `<main>'
21/02/2018 17:05:46	 9: from bin/rails:12:in `require'
21/02/2018 17:05:46	 8: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
21/02/2018 17:05:46	 7: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
21/02/2018 17:05:46	 6: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
21/02/2018 17:05:46	 5: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
21/02/2018 17:05:46	 4: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
21/02/2018 17:05:46	 3: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
21/02/2018 17:05:46	 2: from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
21/02/2018 17:05:46	 1: from /srv/Portus/bin/background.rb:8:in `<top (required)>'
21/02/2018 17:05:46/srv/Portus/lib/portus/db.rb:40:in `wait_until': Timeout reached for 'ready' status (Portus::DB::TimeoutReachedError)
21/02/2018 17:05:46bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
21/02/2018 17:05:46RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/background.rb
21/02/2018 17:05:46  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
21/02/2018 17:05:46  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
21/02/2018 17:05:46  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
21/02/2018 17:05:46  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
21/02/2018 17:05:46  /srv/Portus/packaging/suse/portusctl/lib/cli.rb:272:in `exec'
21/02/2018 17:05:46  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
21/02/2018 17:05:46  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
21/02/2018 17:05:46  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
21/02/2018 17:05:46  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
21/02/2018 17:05:46  packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
21/02/2018 17:06:00[Mailer config] Host:     portus.heyolly.com:3000
21/02/2018 17:06:00[Mailer config] Protocol: https://
21/02/2018 17:06:06[Database] Not ready yet. Waiting...
21/02/2018 17:06:16[Database] Not ready yet. Waiting...

It's really interesting because I changed nothing to my config and before the portus:2.3 was working perfectly well!
But now the background seems to have "improve" and the main portus... Well, you see the logs :)

Any ideas?

**Comment by Vad1mo** [comment]
You might need to trigger a manual migration. `bundle exec rake db:migrate` in the portus container

**Comment by Vesli** [comment]
I'll try, but usually you can't access a non working container from an orchestration service, as it tries to restart the container

**Comment by Vesli** [comment]
Ok, if I delete and recreate the DB there is no specific error from the main portus, except a:

> Started GET "/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=docker.company.com%3A5000" for 34.240.76.201 at 2018-02-21 17:22:11 +0000
21/02/2018 17:22:11Processing by Api::V2::TokensController#show as JSON
21/02/2018 17:22:11  Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"docker.company.com:5000"}
21/02/2018 17:22:11Completed 401 Unauthorized in 137ms (ActiveRecord: 5.8ms)

**Comment by Vesli** [comment]
Ok, good news actually - I don't have any more errors with an empty DB. I'm trying to setup back my environment and will keep you updated

**Comment by Vesli** [comment]
So sad, the background is back with his initial error. 
Sorry in the end it's just a duplicate of a previous problem I have with the background not working #1589 .
