### ISSUE TITLE
Copied pull command to clipboard with external dns name 

### ISSUE THREAD

**Issue by yoramshai** [SUSE/Portus#1719]
### Description
I have installed Portus in K8s that communicate with the registry over the k8s internal  network and using internal dns that not exposed outside the k8s cluster.

when I'm clicking on the image tag in order to copy the pull command I'm getting the next line -->   
docker pull portus-registry:443/ubuntu:latest 

in the advanced setting I already provide the registry external DNS, any way to configure it to take the external dns name ?

### Steps to reproduce

1. navigate to  repositories and click on one of them 
2. Then click on one of the tags then you will get the Internal dns  

### Deployment information
portus 2.3 on k8s

**Comment by vitoravelino** [comment]
Thanks for reporting this!
