### ISSUE TITLE
Make logging level configurable

### ISSUE THREAD

**Issue by embik** [SUSE/Portus#1720]
We are using a load balancer in front of our Portus deployment. To ensure it is updated with the current backend status (whether our Portus pods are available or not) we're doing a HTTP check every second. 

Unfortunately, this produces a lot of logs within our Portus containers. I have not found any possibility to limit logging to warnings and errors (as the load balancer already logs all connections anyway). Ruby on Rails seems to provide such configuration, but not via environment variables.

Is it possible to expose the log level in Portus' config file? Or, if there *is* another way to configure it, update the docs with that?

**Comment by Vad1mo** [comment]
@embik are you doing the health checks on `/api/v1/health` if so be aware that the response takes um to 30 sec. to complete. If you do this check to often you can bring down your instance. 

You can change the general log level with the env var `PORTUS_LOG_LEVEL`

> config.log_level defines the verbosity of the Rails logger. This option defaults to :debug for all environments. The available log levels are: :debug, :info, :warn, :error, :fatal, and :unknown.

**Comment by embik** [comment]
I'm not, but thanks for the heads up! `PORTUS_LOG_LEVEL` is what I'm looking for, thanks a lot. Might be worth to add it [here](http://port.us.org/docs/Configuring-Portus.html).

**Comment by mssola** [comment]
Thanks for the feedback.

> I'm not, but thanks for the heads up! PORTUS_LOG_LEVEL is what I'm looking for, thanks a lot. Might be worth to add it here.

I've opened #1721 for this :+1:
