### ISSUE TITLE
[FEATURE] Multi Login Backend

### ISSUE THREAD

**Issue by arogarth** [SUSE/Portus#1731]
It would be nice to implement multiple, parallel login backends. That you can use LDAP und DB together.

We need to use LDAP for our internal use and DB-Users to deliver container to external persons.

**Comment by mssola** [comment]
@arogarth it sounds very similar to #801 (which we will provide for 2.4). Is that what you mean? If so, we can close this as a duplicate :wink:

**Comment by mssola** [comment]
I'm currently working on #801 and I now I see that this issue has a slight twist that might be useful to implement in the near future. I'll keep it as an improvement from my work on #801 that should come in 2.5. Thanks for the feedback :+1:
