### ISSUE TITLE
ERROR: Service 'portus' failed to build: The command '/bin/sh -c zypper ref && 

### ISSUE THREAD

**Issue by lyc20140320** [SUSE/Portus#1742]
when i run "docker-compose up -d", the error happened

You need to install GraphViz (http://graphviz.org/) to use this Gem.

For more information about Ruby-Graphviz :
* Doc : http://rdoc.info/projects/glejeune/Ruby-Graphviz
* Sources : http://github.com/glejeune/Ruby-Graphviz
* Mailing List : http://groups.google.com/group/ruby-graphviz

Last (important) changes :
Ruby-Graphviz no longer supports Ruby < 1.9.3
  package golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp 172.217.160.113:443: i/o timeout)
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 172.217.160.113:443: i/o timeout)
ERROR: Service 'portus' failed to build: The command '/bin/sh -c zypper ref &&     zypper -n in --no-recommends ruby2.5-devel            libmysqlclient-devel postgresql-devel            nodejs libxml2-devel libxslt1 git-core go1.9 &&     zypper -n in --no-recommends -t pattern devel_basis &&     gem install bundler --no-ri --no-rdoc -v 1.16.0 &&     update-alternatives --install /usr/bin/bundle bundle /usr/bin/bundle.ruby2.5 3 &&     update-alternatives --install /usr/bin/bundler bundler /usr/bin/bundler.ruby2.5 3 &&     bundle install --retry=3 &&     go get -u github.com/vbatts/git-validation &&     go get -u github.com/openSUSE/portusctl &&     mv /root/go/bin/git-validation /usr/local/bin/ &&     mv /root/go/bin/portusctl /usr/local/bin/ &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a' returned a non-zero code: 1

**Comment by mssola** [comment]
> dial tcp 172.217.160.113:443: i/o timeout

It looks like a connection issue. Make sure you can access internet from this machine. You can try with:

```
$ go get -u github.com/vbatts/git-validation
$ go get -u github.com/openSUSE/portusctl
```

Which are the commands being performed during build. Or simply try to build the image again, you connection might be flaky. I removed my local images and tried this locally and it works.
