### ISSUE TITLE
LDAP not working with Portus 2.3.1

### ISSUE THREAD

**Issue by lonewulf** [SUSE/Portus#1746]
Hi, I'm trying to do a mock upgrade from 2.2.x to 2.3.1 and the ldap bind isn't working anymore:

I get : "translation missing: en.devise.failure.user.ldap_bind_failed"
I double checked the bind dn and bind password in the config and it's correct.

The account ended up locked so I guess there is something wrong with the password not being used correctly to bind the account.

(I've made a tcp dump of the process and can't find the password anywhere in the bind request packet)

Regards,

**Comment by lonewulf** [comment]
I compared to a tcpdump of a manual ldapsearch bind, I can see the password in the simple authentication part of the bind request packet, so there is definetly a problem with either portus ignoring the password in the config file or the ldap library not passing it during the bind...

**Comment by lonewulf** [comment]
Managed to make it work passing it with an environment variable instead of in the config file.

Still, didn't work when configured via config-local.yml

**Comment by hiscal2015** [comment]
+1, I have the same issue.

**Comment by hiscal2015** [comment]
@lonewulf How can you pass it by environment variable?

**Comment by lonewulf** [comment]
We use docker to run portus so we pass it via an environment file, you have to put the password in the PORTUS_LDAP_AUTHENTICATION_PASSWORD env variable.

**Comment by hiscal2015** [comment]
@lonewulf It works, thanks. I have one more issue when migrating 2.2 to 2.3, that is, 2.3 requests mysql in utf8 character, but this is not required in 2.2, did you experience this issue?

**Comment by lonewulf** [comment]
@hiscal2015 I did, had to convert the database and tables to utf-8, with the right collate type too.
