### ISSUE TITLE
Namespaces counter on the admin page should ignore special namespaces

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#175]
How to reproduce:
  * start a new instance of portus
  * create an account
  * go to the admin tab

The UI reports 2 namespaces are available, this is true because there's one for the global namespace, plus one for the user.

I think it special namespaces should be excluded from the count.

**Comment by mssola** [comment]
It makes sense to do this for teams (as described in #174 and #176), but to me this should not apply for namespaces. As an admin, I'd be interested to know how many repositories the global namespace has, for example. And the same for personal namespaces.

So to me, the actual behavior is alright.

**Comment by flavio** [comment]
Agreed
