### ISSUE TITLE
Clarify 2.3.1 release

### ISSUE THREAD

**Issue by lobeck** [SUSE/Portus#1750]
There's a release 2.3.1 containing a CVE fix, however it's not listed in the changelog and there's no updated docker image.

Is there a reason why these steps were skipped or is the docker image not affected?

**Comment by mssola** [comment]
@lobeck we have written down what happened here: http://port.us.org/2018/04/04/portus-2.3-x.html. Sorry for the delay (I was on vacations :grin:)
