### ISSUE TITLE
X.509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by rensg001** [SUSE/Portus#1770]
### Description

Hi, i try to deploy portus using official image. I used openssl to generate a self-signed certificate and signed it with a private authority. but when i login my private registry and push a image, the registry log print some error message: 

time="2018-04-07T07:49:07Z" level=error msg="retryingsink: error writing events: httpSink{https://portus.test.com/v2/webhooks/events}: error posting: Post https://portus.test.com/v2/webhooks/events: x509: certificate signed by unknown authority, retrying"
time="2018-04-07T07:49:07Z" level=warning msg="httpSink{https://portus.test.com/v2/webhooks/events} encountered too many errors, backing off"
time="2018-04-07T07:49:10Z" level=error msg="retryingsink: error writing events: httpSink{https://portus.test.com/v2/webhooks/events}: error posting: Post https://portus.test.com/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying"
time="2018-04-07T07:49:10Z" level=warning msg="httpSink{https://portus.test.com/v2/webhooks/events} encountered too many errors, backing off"

I think i must let registry trust my private certificate, but i don't known how to do it. anybody can give me some advice???

### Steps to reproduce

1. git clone portus project and checkout tags/2.3
2. copy self-signed certificate and ca certificate to examples/compose/secrets directory. set the MACHINE_FQDN variable in the .env file.
3. docker-compose up
4. docker login from client and push some image to registry
5. And this happened!

add: I saw the init script in examples/compose/registry directory and i copy my private ca.crt file to /usr/local/share/ca-certificates, but it didn't work.
add: the registry version is 2.6

**Comment by rensg001** [comment]
finally, i use registry:2.3 instead. copy ca.crt file to /usr/local/share/ca-certificates directory and run update-ca-certificates. push a image to portus.test.com. the registry accept my self-signed certificate.

**Comment by luckyf** [comment]
Starting with registry v2.6 it should be possible to use a custom certificate for notifications.
Maybe the certificate should be mounted into another location.
I created an [issue ](https://github.com/docker/distribution/issues/3182) at the offical docker repository to get help what location should be used.

@mssola may you know anything where we should put our certificates?
