### ISSUE TITLE
Portus PORTUS_BACKGROUND=true and database empty

### ISSUE THREAD

**Issue by felixPG** [SUSE/Portus#1777]
Hi All:

I enabled the background process with env **PORTUS_BACKGROUND=true**.
The problem is when the database are empty  and NOT READY because PORTUS on bootstrap does not create the database yet, so, error:
```
[Database] Not ready yet. Waiting...
/srv/Portus/lib/portus/db.rb:40:in `wait_until': Timeout reached for 'ready' status 
[Database] Timeout reached, exiting with error. Check the logs...
```
Database are not ready because PORTUS launch background proccess before the database creation on bootstrap.
How I could solve this?

Regards

**Comment by seanhoughton** [comment]
You need to run two containers, one without the worker setting and one with it set to true. If you just run the worker you won't actually have a Portus server running to init the DB.

**Comment by mssola** [comment]
This issue sadly slipped through...

> You need to run two containers, one without the worker setting and one with it set to true. If you just run the worker you won't actually have a Portus server running to init the DB.

Exactly :+1:

I'll close this issue now, but feel free to leave more comments if you have further doubts on this issue.

**Comment by anandr781** [comment]
What flag should I use to docker run Portus in server mode so that it will bootstrap the database.

**Comment by mssola** [comment]
@anandr781 no flag, actually. See [this examples](https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.insecure.yml#L4)
