### ISSUE TITLE
Repository cannot be in different namespaces

### ISSUE THREAD

**Issue by DirkHeinke** [SUSE/Portus#178]
A repository is moved from one NS to another, if you retag it and push it again. It should stay in both NS as it is also available in both NS in the registry.

**Comment by flavio** [comment]
That should be working right now. Are you reporting a bug?

**Comment by DirkHeinke** [comment]
Didn't worked for me in my test setup. But perhaps it is an issue on my side. Does it work for you?

**Comment by mssola** [comment]
In order to reproduce this, I've done the following:

1. Push two tags to the global namespace.
2. Locally re-tag one to put it in my personal namespace and push it.
3. In Portus I can see that the two tags from the global namespace have been moved to my personal namespace.
