### ISSUE TITLE
Portus registry Exited

### ISSUE THREAD

**Issue by jroberto1987** [SUSE/Portus#1780]
Sorry for my english I'm using google to try to send my question.

I'm using stable portus using docker-compose.insecure.yml, however at the time of execution the registry container gets as Exited:

root @ docker: ~ / COMPOSE_PORTUS / compose / registry # docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
d51e873d3671 registry: 2.6 "/entrypoint.sh / etc ..." 12 seconds ago Exited (2) 11 seconds ago compose_registry_1
65387c254eda opensuse / portus: head "/ init" 12 seconds ago Up 11 seconds 3000 / tcp compose_background_1
d19c36c6c7c7 opensuse / portus: head "/ init" 13 seconds ago Up 12 seconds 0.0.0.0:3000->3000/tcp compose_portus_1
f7a2628a6af2 mariadb: 10.0.23 "/docker-entrypoint...." 13 seconds ago Up 13 seconds 3306 / tcp compose_db_1

And in the web pagus of the portus I can not set the hostname is always giving this error:
registry
Hostname
registry.teste.com.br:5000
SocketError: connection refused. You can skip this check by clicking on the "Skip remote checks" checkbox.

Is anyone experiencing this problem?

**Comment by mssola** [comment]
Take a look at the documentation of the [examples](https://github.com/SUSE/Portus/tree/master/examples/compose#insecure-example). Your hostname, on docker usually is `172.17.0.1`, unless you are doing something differently from docker-compose's default.

**Comment by sadeghmohebbi** [comment]
if FQDN has not DNS A record, you should add it by hosts inside docker-compose like below (change PLACE_YOUR_PUBLIC_IP to your machine public ip)
```
# change version
version: '3.4'

services:
    portus:
        extra_hosts:
            - "${MACHINE_FQDN}:PLACE_YOUR_PUBLIC_IP"
        # ... other stuff
```
