### ISSUE TITLE
Support for /v2/_catalog calls on non-admin accounts

### ISSUE THREAD

**Issue by crimoniv** [SUSE/Portus#1818]
### Description

Current implementation forbids `/v2/_catalog` calls to **non-admin** users ([source](https://github.com/SUSE/Portus/blob/v2.3/app/policies/registry_policy.rb#L13)). Can it be modified to -at least- show repositories in which the user has pull rights?

### Steps to reproduce

1. Configure namespaces' visibility:
    - **global namespace**: anyone can pull
    - **ns1**: logged-in users can pull
    - **ns2**: **ns2-team** members can pull

2. Call `/v2/_catalog` with an **admin user**:
```
~$ REGISTRY=xxx
~$ SCOPE="registry:catalog:*"
~$ TOKEN=$(curl -s --user "admin:xxx" "https://${REGISTRY}/v2/token?service=${REGISTRY}&scope=${SCOPE}" | jq -e -r '.token')
~$ curl -s -H "Authorization: Bearer ${TOKEN}" "https://${REGISTRY}/v2/_catalog"
{"repositories":["hello-world", "ns1/hello-world", "ns2/hello-world"]}
```

3. Call `/v2/_catalog` with a **non-admin user**:
```
~$ TOKEN=$(curl -s --user "user:xxx" "https://${REGISTRY}/v2/token?service=${REGISTRY}&scope=${SCOPE}" | jq -e -r '.token')
~$ curl -s -H "Authorization: Bearer ${TOKEN}" "https://${REGISTRY}/v2/_catalog"
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
```

- **Expected behaviour**: the user -who does not belong to any team- should be able to see `hello-world` and `ns1/hello-world`
- **Actual behaviour**: `401 Unauthorized`

### Deployment information

**Deployment method**: `docker-compose`
**Portus version**: `opensuse/portus:2.3` (ID: `9cbab1e53959`)

**Comment by mssola** [comment]
I'm really not sure about this one. Calling `/v2/_catalog` semantically speaking means that you want to fetch *all* the catalog. When this request goes to Portus, it's all or nothing: there's no way to filter this, the registry will return everything on success.

Hence, technically speaking it might not be doable from the Registry's standpoint with this setup. That being said, why don't you use Portus' API for this? Take a look at the documentation [here](http://port.us.org/docs/API.html). It will allow you, for any user, to fetch the namespaces available, images, etc. The API is not finished yet, so feedback is welcome if you need something more from it :smile:

**Comment by crimoniv** [comment]
Yay! The Portus API seems to do exactly what I were trying to achieve :smiley:

As you pointed out, it is more related to the Registry than to Portus, so I guess this issue can be closed. Thanks @mssola!
