### ISSUE TITLE
GUI consistency

### ISSUE THREAD

**Issue by ignuki** [SUSE/Portus#1829]
### Description

This is a just minor QoL thing, but the web interfaces of any of the resources for the admin user are not consistent when they are accesed differently. For example, if I log in as admin and go to the "teams" tab, I can see the "Create new team" link: 

![screenshot-2018-5-23 portus 1](https://user-images.githubusercontent.com/11045073/40426089-6fc63a98-5e9a-11e8-8a08-201695951b8b.png)

But if instead I go throgh the "Admin" tab and then go into "Teams", the link is not there:

![screenshot-2018-5-23 portus 2](https://user-images.githubusercontent.com/11045073/40426179-affd3292-5e9a-11e8-80c5-a1ad4ae2459b.png)
 
Again, nothing too important, Portus is pretty great as it is right now.

I'm using the portus:head image, with Portus v2.4.0

**Comment by vitoravelino** [comment]
This was true a while back. There's no admin menu item anymore. We worked on a few PRs [0] to solve those inconsistencies.

I definitely recommend you to pull the latest image. It's looking much better.

Thanks for worrying about that! Feedback is always welcome. :wink: 

[0] #1785 #1786 #1783 #1784

**Comment by ignuki** [comment]
Oh wow, that's great, thanks!
