### ISSUE TITLE
How to export all images with tag and updated Date?

### ISSUE THREAD

**Issue by gopal-gemini** [SUSE/Portus#1868]
I want to get the list of all images with namespace and its tag, date.  Is there any way to get it?

I tried portus API but it gets a list of namespace or tags but required single report with all.

**Comment by mssola** [comment]
What do you mean exactly? As far as I know, you could do something like: Call `/api/v1/namespaces`, and for each ID call `/api/v1/namespaces/{id}/repositories`. This will give you the list of all repositories with their tags, vulnerabilities, updated date, etc.

Is that what you want?

**Comment by gopal-gemini** [comment]
@mssola 
Is there any way to list all the repository and corresponding Tags?
I want to list like below
<namespace>/<repository>/<tags>

**Comment by mssola** [comment]
I see two things here. First of all, if you already have the namespace, then you can simply call: `/api/v1/namespaces/{id}/repositories`. This will give you a JSON response like so:

```json
[
  {
    "id": 1234,
    "name": "repo",
    "full_name": "namespace/repo",
    "namespace": "namespace",
    "tags": [
      "latest"
    ],
    ...
  }
]
```

If you want to fetch this for all namespaces, then you'll first have to fetch the list of namespaces, and then call that other API method for each of them.

Now, another use case, which I think is the one you want, is to simply list all that you've got on the registry. This is already doable within the API of Docker distribution (see the [_catalog](https://github.com/docker/distribution/blob/master/docs/spec/api.md#get-catalog) method). So you are already covered directly by the registry if you are only interested on listing names.

If you want something more (e.g. not just names, but also timestamps, list of vulnerabilities, ...), then the answer is that we do not provide such an API method yet. Is this what you are looking for? or the `_catalog` method is enough?
