### ISSUE TITLE
[QUESTION/SECURITY PROBLEM] Does user that owns portus@portus.com owns your on premise registry ?

### ISSUE THREAD

**Issue by kiorky** [SUSE/Portus#1878]
### Description

If someone gains or has access to portus@portus.com inbox, he can then access to any portus registry with default setup for the portus hidden user by resetting his password via email.
I think this is a major security flaw and that user should have at least a non routable DEFAULT mail or no mail at all, and maybe additionally some code inside the app that forid=1 doesnt allow mail reset without an explicit config setting.

### Steps to reproduce

NA

### Deployment information
NA

cc @regilero

**Comment by mssola** [comment]
I wouldn't say that it's a security bug, but it's indeed quite fishy. Giving this user an email was more of a hack than anything else and, in fact, Portus does no longer require email for users upon creation. So, I propose the following course of action:

1. We try to get rid off the email from the portus user.
2. Once that is done, we should provide a migration task from 2.3 to 2.4 that removes the email from the portus user.
3. Forbid the portus user from resetting the password and similar.

What do you think?

Thanks for reporting :clap: (and sorry for taking quite a while to reply)

**Comment by kiorky** [comment]
No the email is still a good thing as the admin should have a way to reset this password easily, and using a reset password feature is pretty natural when the admin set it already a bit ago.

Just that this default email is a problem if unset/unknown, BUT once it is setted, it is fine.

Maybe it can stay here as-is, this would also avoid to plan any database migration and then have a check in the resetpassword routine to never ever send to that hardcoded ``portus@`` (via a constant).

But, i still maintain that it is a security problem, and a big, every Op will tell you that :)

**Comment by mssola** [comment]
@kiorky hopefully #1896 addresses all the points you've raised :+1: 

> No the email is still a good thing as the admin should have a way to reset this password easily, and using a reset password feature is pretty natural when the admin set it already a bit ago.

Notice that this is a hidden user, and its password was handled as a deployed secret (see the `PORTUS_PASSWORD` note [here](http://port.us.org/docs/deploy.html)). Hence, if you want to update this password, it should be done in the same way: by updating the secret and restarting portus. This is now addressed with #1896.

> Just that this default email is a problem if unset/unknown, BUT once it is setted, it is fine.

Agreed. The email itself wasn't the problem :+1: 

> Maybe it can stay here as-is, this would also avoid to plan any database migration and then have a check in the resetpassword routine to never ever send to that hardcoded portus@ (via a constant).

I went for a simpler approach: the portus user is prevented from resetting the password through the "I forgot my password" feature :wink: 

> But, i still maintain that it is a security problem, and a big, every Op will tell you that :)

Agreed :+1: I'll also backport it to the `v2.3` branch when merged.

We can continue this discussion on the PR if you want :+1:
