### ISSUE TITLE
Is Portus able to run on RHEL OS?

### ISSUE THREAD

**Issue by mailzyok** [SUSE/Portus#1882]
Hi,

We want to build a docker image in which Portus is running on RHEL OS. Is it possible?

Thanks,
yzha

**Comment by Vad1mo** [comment]
yes, this will work. You need to create your own image. You can take Portus alpine or any other on github as reference.   I am sure there are some out there at least for fedora.

**Comment by mailzyok** [comment]
Thank you @Vad1mo for quick answer. Additional quesions maybe you can also help.

1. Does Portus support HA deployment on K8S?
2. Is security scanning tool configurable? Besides Clair, Does Portus support integration to any scanning softwares?
3. Does Portus support content trust tool, for example Notary?

Sorry for so many questions.

/yzha

**Comment by mailzyok** [comment]
Really appreciate your prompt answer @Vad1mo .  We will have a try on HA deployment on K8S.

/yzha

**Comment by mssola** [comment]
@mailzyok can we close this issue? It appears that @Vad1mo already answered all your questions right? (thanks @Vad1mo :smile: !!)

**Comment by mailzyok** [comment]
Yes, @mssola  please close it. We are now trying the Portus deployment on K8S via helm chart. There are some problems, but we are trying to fix it by ourself firstly. Will open another issue if support needed.

Thanks.
yzha
