### ISSUE TITLE
Wrong Timezone

### ISSUE THREAD

**Issue by rgawron** [SUSE/Portus#1885]
I deployed Portus from docker-compose.yml ( examples/compose/docker-compose.yml ) 
In repository I see my timezone and time from server timezone - so this is ok, but when I go in to repository name I see date and time when my image was pushed and this is other timezone. 

Example:
Server timezone is CEST
Repositories (date / time updated ) is CEST
In Repository name where I see tag / author / and pushed time is UTC.

How can I change this timezone ?

**Comment by vitoravelino** [comment]
That's a bug apparently. Thanks for reporting it!
