### ISSUE TITLE
CSRF Issues with 2.4-dev (opensuse/portus:head)

### ISSUE THREAD

**Issue by tankbusta** [SUSE/Portus#1889]
### Description

You cannot create comments using Portus 2.4-dev due to an issue with CSRF validation.

### Steps to reproduce

1. Ensure you have at least one image pushed to the registry
1. Navigate to the page containing the tags and comments fields.
1. Attempt to post a comment. You'll get an empty notification but notice in dev tools, a failed HTTP request with the status code 422.

The server log showing the error 
```
portus_1      | Started POST "/repositories/2/comments.json" for 172.18.0.8 at 2018-07-18 22:15:48 +0000
portus_1      | Processing by CommentsController#create as JSON
portus_1      |   Parameters: {"comment"=>{"body"=>"test"}, "repository_id"=>"2"}
nginx_1       | 10.10.120.187 - - [18/Jul/2018:22:15:48 +0000] "POST /repositories/2/comments.json HTTP/2.0" 422 0 "https://<URL>/repositories/2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
portus_1      | Can't verify CSRF token authenticity
portus_1      | Completed 401 Unauthorized in 0ms (ActiveRecord: 0.0ms)
portus_1      |
portus_1      | ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
portus_1      |   app/middleware/catch_json_parse_errors.rb:11:in `call'
```

### Deployment information

* Portus is deployed with `docker-compose` using a slightly modified version from `examples/compose`

**Portus version**:  `2.4.0-dev@d643078bbf8d10a521f02edfcbabd70aac96ebc3`

**Comment by vitoravelino** [comment]
This issue was fixed but the image on docker hub is outdated.

**Comment by tankbusta** [comment]
Is this the docker file for creating a new image? https://github.com/SUSE/Portus/blob/master/docker/Dockerfile It looks like it just pulls down a package from SUSE servers?

**Comment by vitoravelino** [comment]
Yeah... The problem is that the RPM is also not being built just like the image on docker hub because our integration tests are failing on master branch. Once that is fixed, everything goes back to normal again.

**Comment by tankbusta** [comment]
Are there steps on how to build an image from the ground up? Or should I just wait for the integration tests to be fixed?

**Comment by vitoravelino** [comment]
> Are there steps on how to build an image from the ground up?

Not documented.

> Or should I just wait for the integration tests to be fixed?

Ideally yes.

**Comment by mssola** [comment]
> This issue was fixed but the image on docker hub is outdated.

Not anymore, the `head` tag is now updated :smile: 

> Is this the docker file for creating a new image? https://github.com/SUSE/Portus/blob/master/docker/Dockerfile It looks like it just pulls down a package from SUSE servers?

This is the Dockerfile for development purposes. The ones used to generate these images are located [here](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus). As you can see, they simply install the RPM from our [OBS project](https://build.opensuse.org/project/show/Virtualization:containers:Portus). Two days ago we fixed an unrelated problem we were having on the build, and now the pipeline is good.

Could you try again with the updated image and report back ?

Sorry for any inconvenience :sweat_smile:

**Comment by tankbusta** [comment]
I pulled down the latest image and did a clean deploy but I'm getting an empty page while viewing the "Registry" page despite no errors.

<img width="1630" alt="screen shot 2018-07-26 at 09 27 28" src="https://user-images.githubusercontent.com/592749/43272053-4b64aefc-90b6-11e8-8eb7-ed916062bb64.png">

```
nginx_1       | 10.10.112.112 - - [26/Jul/2018:15:27:18 +0000] "GET /users/edit HTTP/2.0" 200 2404 "https://<redacted>/users/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
portus_1      | Started GET "/admin/registries" for 172.18.0.8 at 2018-07-26 15:27:21 +0000
portus_1      | Processing by Admin::RegistriesController#index as HTML
portus_1      | Redirected to https://<redacted>/admin/registries/new
portus_1      | Completed 302 Found in 3ms (ActiveRecord: 0.3ms)
nginx_1       | 10.10.112.112 - - [26/Jul/2018:15:27:22 +0000] "GET /admin/registries HTTP/2.0" 302 128 "https://<redacted>/users/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
portus_1      | Started GET "/admin/registries/new" for 172.18.0.8 at 2018-07-26 15:27:22 +0000
portus_1      | Processing by Admin::RegistriesController#new as HTML
portus_1      |   Rendered admin/registries/new.html.slim within layouts/application (2.1ms)
portus_1      |   Rendered shared/_config.html.slim (0.1ms)
portus_1      |   Rendered shared/_header.html.slim (0.7ms)
portus_1      |   Rendered shared/_aside.html.slim (0.8ms)
portus_1      |   Rendered shared/_search.html.slim (0.2ms)
portus_1      |   Rendered shared/_notification.html.slim (0.0ms)
portus_1      |   Rendered shared/_notifications.html.slim (0.3ms)
portus_1      | Completed 200 OK in 18ms (Views: 10.7ms | ActiveRecord: 0.5ms)
nginx_1       | 10.10.112.112 - - [26/Jul/2018:15:27:23 +0000] "GET /admin/registries/new HTTP/2.0" 200 2061 "https://<redacted>/users/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
```

**Comment by vitoravelino** [comment]
I'm closing this since the original reported issue does not happen anymore. 

The issue you are facing now is similar to #1902. I guess the discussion can be continued there.
