### ISSUE TITLE
Webpack service crashing at start

### ISSUE THREAD

**Issue by Hugo1380** [SUSE/Portus#1892]
### Description

The engine "node" is incompatible with Webpack. Webpack can't be install so the container crashing. (I think)

### Steps to reproduce

1. Start Portus with `docker-compose up`

- **Expected behavior**: All services starting
- **Actual behavior**: Webpack service crashing

```
webpack_1     | [1/4] Resolving packages...
webpack_1     | [2/4] Fetching packages...
webpack_1     | info fsevents@1.2.4: The platform "linux" is incompatible with this module.
webpack_1     | info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
webpack_1     | error webpack@4.16.1: The engine "node" is incompatible with this module. Expected version ">=6.11.5".
webpack_1     | error Found incompatible module
webpack_1     | info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
webpack_1     | yarn run v1.6.0
webpack_1     | $ webpack --watch --config config/webpack.js
webpack_1     | /bin/sh: 1: webpack: not found
webpack_1     | error Command failed with exit code 127.
webpack_1     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
portus_webpack_1 exited with code 1
```

### Deployment information

**Deployment method**: With docker-compose.yml at the repo root.

**Configuration**:
- In a container:
  - Using the development `docker-compose.yml` with no modification.

**Portus version**: Master : 7358f3a

**Comment by mssola** [comment]
I was able to reproduce it by cleaning up the old image I had for the `webpack` service and starting again. Maybe the Docker image got updated upstream or something like that... Thanks for reporting :+1:

**Comment by Hugo1380** [comment]
Thanks, that work ! :)
