### ISSUE TITLE
No route matches [GET] "/repositories/tagsPath/1"

### ISSUE THREAD

**Issue by hamelsveld** [SUSE/Portus#1900]
Hi,

on the latest release in docker I can't get the Claire report to open due to the following error:

No route matches [GET] "/repositories/tagsPath/1"

Rails.root: /srv/Portus

Application Trace | Framework Trace | Full Trace

Anyidea how to fix this?

**Comment by vitoravelino** [comment]
Fix was submitted. Thanks for reporting it!

**Comment by hamelsveld** [comment]
what release should I use because it's not in the master right?

**Comment by vitoravelino** [comment]
You can either wait for the next `head`, `2.4` or build the image on your own.
