### ISSUE TITLE
Registry was successfully created. (NOT the actual case)

### ISSUE THREAD

**Issue by hamelsveld** [SUSE/Portus#1909]
I've now done the following:

Git clone ....
changed the .env file and changed the FQDN to match the IP adress of the host
docker-compose down
docker-compose up

then when it started I can create an Admin account no problem
then when I want to add the registry it tells me "Registry was successfully created." but I keep getting this registry creation screen and that's it. 

Then I've done a 
docker-compose down
docker-compose build
docker-compose up

Same result .... 

Changed the docker-compose.yml and changes the versions from "develop" to latest and same results.... after a build, run ...

Can you please tell me whats wrong?

**Comment by vitoravelino** [comment]
Apparently there still some regression introduced recently. Thank you for reporting it!

**Comment by hamelsveld** [comment]
Let me know when I can do some re-testing!

**Comment by vitoravelino** [comment]
@hamelsveld Issue is fixed. Try it now. Docker image head tag should be updated soon.
