### ISSUE TITLE
deleting of repo does not work

### ISSUE THREAD

**Issue by hamelsveld** [SUSE/Portus#1913]
removing labels from checked-in images or removing repo's does not work.. gui seems to hang.

**Comment by vitoravelino** [comment]
I wasn't able to reproduce it.

**Comment by vitoravelino** [comment]
I was able to remove tag separately (checking a tag and clicking on delete tag button) and also the repo at once (clicking on delete repository button).

To delete a comment you need to hover the comment and a link will appear on the top right of the comment. I was also able to delete it.

Any error on console or devtools?

**Comment by hamelsveld** [comment]
No errors but let me dig in to it a bit... did see that Vue is running in development mode. that you might want to change later as well :)

**Comment by vitoravelino** [comment]
> did see that Vue is running in development mode.

How are you running your instance?

**Comment by hamelsveld** [comment]
Right now I just done a git pull, build and compose up... did not change anything

Met vriendelijke groet,
 
Sven v Hamelsveld
_________________________

Warning: I either dictated this to my mobile device, or I typed it clumsily. Expect typos, auto corrections and weirdness.

**Comment by vitoravelino** [comment]
> Right now I just done a git pull, build and compose up... did not change anything

This is development mode. That's why you are getting that message.

**Comment by hamelsveld** [comment]
What do I need to do to change that? Make the release :latest?

**Comment by vitoravelino** [comment]
It depends on your deployment strategy. There are some content at http://port.us.org/docs/deploy.html that might help you.

**Comment by hamelsveld** [comment]
when I create a new repo and try to delete the repo nothing happens. However when I then press delete tags it deletes the tags and the repo "Repository removed with all its tags."

now I've still 3 repo's left with no images in there and no tags ... those are non deletable .. :)

**Comment by vitoravelino** [comment]
You are saying that when you go to `/repositories` you see 3 entries and all of them displays `0` on the tags column?

**Comment by hamelsveld** [comment]
<img width="1211" alt="screen shot 2018-07-27 at 17 09 23" src="https://user-images.githubusercontent.com/16137728/43329153-e83cb3aa-91bf-11e8-85ef-cb4b569ecbb4.png">

**Comment by hamelsveld** [comment]
yes

**Comment by vitoravelino** [comment]
Well... that's weird. I never faced that kind of issue.

**Comment by lohmuller** [comment]
the "latest" tag dont count in Portus

**Comment by hamelsveld** [comment]
okay I've rebuild a few time with he latest release and can't recreate the issue anymore so think we can close this one.
