### ISSUE TITLE
error 500 when I try go to /repositories url

### ISSUE THREAD

**Issue by lohmuller** [SUSE/Portus#1916]
I'm using portus with the example of docker-compose insecurity (http), version 2.3 (latest)

I have pushed a image with root user (portus) to registry and now the "repositories" have an error...
I'm loged as a admin user (all users have the same error) 

All other pages are working normally

logs:
```
portus_1      | Started GET "/repositories" for ~~~  at 2018-07-27 20:30:07 +0000
portus_1      | Processing by RepositoriesController#index as HTML
portus_1      | Completed 401 Unauthorized in 12ms (ActiveRecord: 2.2ms)
portus_1      | 
portus_1      | NoMethodError (API::Entities::Tags missing attribute `vulnerabilities' on #<Tag:0x00000000063ce820>):
portus_1      |   app/controllers/repositories_controller.rb:16:in `index'
portus_1      |   app/middleware/catch_json_parse_errors.rb:11:in `call'
portus_1      | 
portus_1      | 
portus_1      | Processing by ErrorsController#show as HTML
portus_1      |   Parameters: {"status"=>"500"}
portus_1      |   Rendered errors/500.html.erb within layouts/errors (0.0ms)
portus_1      |   Rendered errors/_status_title.html.slim (0.0ms)
portus_1      | Completed 500 Internal Server Error in 1ms (Views: 0.9ms | ActiveRecord: 0.0ms)

``` 

all another

**Comment by mssola** [comment]
I was not able to reproduce this with the latest image of the `2.3` tag. Have you added any extra env. variable in the example compose file? Could you paste what does `portusctl exec portus:info` prints inside of the Portus container?

**Comment by lohmuller** [comment]
I'm using portus in a container
``bash
$ portusctl exec portus:info

bundler: command not found: portus:info
Install missing gem executables with `bundle install`
bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
```
```bash
$ bundle install

OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bundle\": executable file not found in $PATH": unknown
```

Have another way to give the info to you?
The docker-compose Is the same, but i added a config-local.yml
 ```yml
signup:
  enabled: false

anonymous_browsing:
  enabled: false
```

**Comment by mssola** [comment]
> Have another way to give the info to you?

Could you try with `portusctl rake exec portus:info`?

**Comment by lohmuller** [comment]
:( 
```bash
$ portusctl rake exec portus:info

rake aborted!
Don't know how to build task 'exec' (see --tasks)
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rake exec portus:info
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/cli.rb:274:in `rake'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
```


the error is in this line... 
```
  def index
    @repositories = policy_scope(Repository).all
    @repositories_serialized = API::Entities::Repositories.represent(
      @repositories,
      current_user: current_user,
      type:         :internal
    ).to_json
    respond_with(@repositories)
  end
```
Is possible add an Exception Handler? How can I show the data/error in this line? Thanks!

**Comment by mssola** [comment]
> :(

Sigh... I was confused with the newest version of portusctl. The following will work for sure:

```
$ portusctl rake portus:info
```

As for the error, it looks weird, because the `vulnerabilities` method should be exposed for tags :thinking: By the way, we recently updated the Docker image. Could you remove the one you have and pull again the `2.3` tag?

**Comment by lohmuller** [comment]
Portus (app_portus_1)
```bash
$ portusctl rake portus:info

[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: "'false'"
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: ~~.~~~.com
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial

Portus version: 2.3.4@db91be2fad362c4dd5ff9c87a8ae0d9669dc8811
```
I dont know if this info is useful (I hid the machine_fqdn) 
i'm using the last version

I think when I pushed some data give an error and need be handler in this method

**Comment by lohmuller** [comment]
Ah! this API url give me error too
http://~~~.~~~.com/api/v1/repositories/6
```json
{"error":"Internal server error: API::Entities::Tags missing attribute `vulnerabilities' on #\u003cTag:0x0000000005cdd3b8\u003e"}
```
this too
http://~~~.~~~.com/api/v1/repositories/6/tags/grouped
```json
{"error":"Internal server error: API::Entities::Tags missing attribute `vulnerabilities' on #\u003cTag:0x0000000005cdd3b8\u003e"}
```

I think the problem is with some "tag" data... and the code can't handler and give crash in all <o>

**Comment by lohmuller** [comment]
Is there any command to sync Portus with the Registry again?

**Comment by lohmuller** [comment]
:( no answers... I think I need clean the registry/portus and push all again... and hope to it not happen again

**Comment by lohmuller** [comment]
@vitoravelino still with errors :( 

my config-local.yml
```yml
signup:
  enabled: false

anonymous_browsing:
  enabled: false

background:
  registry:
    enabled: true

  sync:
    enabled: true
    strategy: update-delete


```

**Comment by victor** [comment]
Hi @lohmuller . You've got the wrong @victor. Please check your mentions more carefully. Thanks

**Comment by lohmuller** [comment]
@mssola any news or need more info about? :(

**Comment by lohmuller** [comment]
No updates :\ 
This post still with label "needs info" but no answer from team.
I think I need find another way to manager my registry, portus give me only errors in repositories

**Comment by mssola** [comment]
@lohmuller I still cannot reproduce your issue (with the same configuration, and with the SQL dump you gave us), and I'm really not sure why this is happening (the tag model really has the `vulnerabilities` method, and the API entity also has a `vulnerabilities` attribute defined, so the exception makes no sense...). As for using an example, you haven't changed anything when it comes to volumes or stuff like that, right?

I guess that using the new `2.4` tag won't affect this result, but you could always try :sweat_smile:

**Comment by lohmuller** [comment]
I believe it is error about corrupted data when I pushed the image to registry.
When try to login or go repositories the code cant handler the error when loading "vulnerabilities" attribute.

I think the code needs an error handler in this line about attribute vulnerabilities:
 app/controllers/repositories_controller.rb:16:in `index'
 app/middleware/catch_json_parse_errors.rb:11:in `call'

**Comment by cmeisinger** [comment]
Possibly relevant.  I'm running into the same issue and noticed this.  It looks like a missing column in the MySQL DB.

```background_1  | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query': Mysql2::Error: Unknown column 'tags.vulnerabilities' in 'field list': UPDATE `tags` SET `tags`.`vulnerabilities` = '---\n- :clair\n- []\n', `tags`.`scanned` = 2 WHERE `tags`.`digest` = 'sha256:915f390a8912e16d4beb8689720a17348f3f6d1a7b659697df850ab625ea29d5' (ActiveRecord::StatementInvalid)```

**Comment by lohmuller** [comment]
@cmeisinger what column?

This is my dump in table vulnerabilities
```
--
-- Table structure for table `vulnerabilities`
--

DROP TABLE IF EXISTS `vulnerabilities`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `vulnerabilities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `scanner` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `severity` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `link` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `fixed_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `metadata` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `description` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_vulnerabilities_on_name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `vulnerabilities`
--

LOCK TABLES `vulnerabilities` WRITE;
/*!40000 ALTER TABLE `vulnerabilities` DISABLE KEYS */;
/*!40000 ALTER TABLE `vulnerabilities` ENABLE KEYS */;
UNLOCK TABLES;
```

**Comment by lohmuller** [comment]
Why @cmeisinger deleted the post?

@mssola any news? ._.
