### ISSUE TITLE
Making background process less aggressive in Portus v2.3

### ISSUE THREAD

**Issue by zstyblik** [SUSE/Portus#1920]
### Description

* Portus v2.3 running in Docker 
  * background process in a separate container
  * update policy is set to `update`
* Docker Registry v2.6.x - also running in Docker

Docker Registry(DR) seems to be suffering from memory issues ever since update to Portus v2.3. I suspect that this is due to the fact that background process is hammering DR and there could be, or probably is, a memory leak in DR's pagination.

I was looking around here and there, but nobody seems to be suffering from a such issue(which is a bit surprising and confusing at the same time).

I'm wondering whether there is a way to dial down, to be less aggressive, background process at least a bit.

**EDIT**: Also, please, can somebody clarify whether webhook DR -> Portus is still necessary since there is a background process scanning DR now?

Thank you.

**Comment by zstyblik** [comment]
Thanks @mssola. I'll give a try to `on-start`. In the meantime, I've verified that when background process is stopped, memory usage of DR goes down by half in the matter of minutes.

**Comment by zstyblik** [comment]
Well, it seems that notifications from DR don't work. They fire, portus sends 202 back, however new tags and images don't show up in Portus. And I see webhook being fired over and over again which leads me to believe it does not work, it's stuck in the loop :\

**Comment by mssola** [comment]
Could you paste some logs of the background process?

**Comment by zstyblik** [comment]
I've settled on `on-start` and direct connection from DR to Portus for webhooks. It seems that DR doesn't like nginx in the way for some reason despite the fact nginx logs show 202 and DR doesn't log any errors. Maybe I'll try to create similar setup one day without SSL to debug it.

As for logs, there is not much to show, because previous of Portus v2.3 did not show the structure of the even, I think. All you could see in the logs was:

```
[catalog] Created the tag 'some-docker-tag'.
```
and:

```
Started POST "/v2/webhooks/events" for 172.17.0.1 at 2018-07-31 11:48:53 +0000
Processing by Api::V2::EventsController#create as JSON
Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
```

Thank you for assist @mssola.
