### ISSUE TITLE
REST API:　api/v1/users/bootstrap NOT found

### ISSUE THREAD

**Issue by mailzyok** [SUSE/Portus#1929]
Hi,

Could you help to provide an example of REST API api/v1/users/bootstrap, i want to use this API to create a initial user. But the response is 404 not found. I know i didn't add the parameters, but the response should not be 404 not found, which indicates the API path doesn't exist.

curl -X POST -i --cacert /root/nginx.crt https://portus-portus-nginx:443/api/v1/users/bootstrap
HTTP/1.1 404 Not Found
Server: nginx
Date: Sat, 04 Aug 2018 13:57:46 GMT
Content-Type: application/json
Content-Length: 21
Connection: keep-alive
Vary: Accept-Encoding, Origin
Cache-Control: no-cache
X-Request-Id: 07e235a8-ee9e-40e7-a357-c21fd62caefb
X-Runtime: 0.001536

{"error":"Not found"}

Thanks,
yzha

**Comment by vitoravelino** [comment]
Which version of Portus are you using? 

This endpoint will be introduced in `2.4`, so it's only available on the `head` docker image or `master` branch.

**Comment by mailzyok** [comment]
Thanks @vitoravelino , the release 2.3.3 is used for now. That is the reason.

/yzha
