### ISSUE TITLE
No route matches [GET] "/users/sign_out" 

### ISSUE THREAD

**Issue by hamelsveld** [SUSE/Portus#1931]
Signout does not get the correct url path

No route matches [GET] "/users/sign_out"

Using the tag :latest

**Comment by mssola** [comment]
I can reproduce this and I'll investigate as soon as possible. Thanks for the heads up :+1:

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
is this backported to the stable branch? Running docker image 2.3.5 seems to have the issue!

**Comment by vitoravelino** [comment]
It's available in the 2.4 release.
