### ISSUE TITLE
Allow team removal and migration of namespaces

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1944]
### Description

After closing #767, now the path is clear for team removal. Some considerations:

1. We should warn users first by giving them three options:
  1.1. Nuke: remove all namespaces, repositories, tags, etc. hanging from the team.
  1.2. Migration and nuke: transfer all namespaces into another team, and then nuke the team itself. This depends on #1241.
  1.3. Do nothing: user messed up, do nothing.
2. Global hidden teams should not be removable.

**Comment by mssola** [comment]
I don't think we should include this for 2.5, since that release is already full of other tasks...

**Comment by RjEcho217** [comment]
I deleted a team and a blank namespace now my dashboard UI only shows this 

![image](https://user-images.githubusercontent.com/22623934/57151558-3e106400-6d9f-11e9-802f-6a4ecfe06727.png)

**Comment by mssola** [comment]
@RjEcho217 could you share the logs? Also, what version are you using?
