### ISSUE TITLE
[git-remote-http] <defunct>

### ISSUE THREAD

**Issue by hamelsveld** [SUSE/Portus#1950]
Hi,

sinds the latest release I've lots and lots (over 2000) of defuncts. 

Might be something you want to look in to 

And yes after a restart of the compose they are all gone and dont become zombie

root      1405  1388 38 Aug15 ?        4-21:26:48 /clair -config /clair.yml
root      1410  1405  0 Aug26 ?        00:00:00 [git-remote-http] <defunct>
root      1465  1405  0 Aug27 ?        00:00:00 [git-remote-http] <defunct>
root      1480  1405  0 Aug24 ?        00:00:00 [git-remote-http] <defunct>
root      1484  1405  0 Aug25 ?        00:00:00 [git-remote-http] <defunct>
root      1494  1405  0 Aug23 ?        00:00:00 [git-remote-http] <defunct>

**Comment by mssola** [comment]
I'm honestly not sure, since Portus does not make git remote calls... How have you deployed this? Is it happening with the latest image (remove and pull again) ? Does this happen when you deploy it in a different way? Thanks for the feedback :+1:

**Comment by hamelsveld** [comment]
Hi,
it happens when I use the compose file. and it's not the Portus container doing this but Clair. So restarting the Clair container dus remove the defuncts.

**Comment by mssola** [comment]
So I guess we can close this bug, since it appears to be a bug on Clair's side. Re-open though if you don't feel this way. Thanks for the feedback :+1:
