### ISSUE TITLE
Any backup option for entire registry?

### ISSUE THREAD

**Issue by gopal-gemini** [SUSE/Portus#1951]
Do we have any option to the backup registry? I mean want to backup all the images inside the registry? or any option to backup entire portus with a database?

**Comment by Vad1mo** [comment]
- You should backup the database with the common database backup tools, that exist. They are rock solid purposely designed for that use cases.
- If your registry is on a filesystem then using common existing backup tools of you choice. If your images are with a cloud provider you normally use their functionality like versioning or tools designed for that storage backend. 

It would be too much to expect from Portus.

**Comment by mssola** [comment]
Exactly as @Vad1mo said. Portus' scope is to be an authoritzation service and an UI for the registry. What you are proposing is then out of scope of the project, and there are other rock-solid tools that already achieve what you want.
