### ISSUE TITLE
Connect Portus with Private Docker Registry V2

### ISSUE THREAD

**Issue by galeenk** [SUSE/Portus#1959]
hi, I've success to install portus and docker registry v2 (nginx, registry) and I've input repositories in portal portus with my own private docker registry v2 like this pictures 

![6](https://user-images.githubusercontent.com/11450368/45070566-05c76180-b0fc-11e8-8cb6-0732b9339828.PNG)

but I have a problem .. my portus and my own docker registry v2 , like have no sync at all .. 

![7](https://user-images.githubusercontent.com/11450368/45070616-550d9200-b0fc-11e8-9da2-0877117d068e.PNG)

even though I've an image in my private docker registry v2 

![8](https://user-images.githubusercontent.com/11450368/45070682-b7669280-b0fc-11e8-9ec0-0f44489066a7.PNG)

and the question is.. how connect or sync it? thanks

**Comment by mssola** [comment]
Maybe you are not running the [background](http://port.us.org/docs/deploy.html) process? This is the process in charge (among other things) of updating the DB upon registry notifications (e.g. a new tag has been pushed). How have you deployed all this? Have you followed any example? (e.g. [the insecure but simpler](https://github.com/SUSE/Portus/tree/master/examples/compose) one)

**Comment by galeenk** [comment]
hai, thank for your advice, .. yap i've read and follow the instruction .. here my docker running 
![9](https://user-images.githubusercontent.com/11450368/45302594-eedea000-b53d-11e8-8e6f-6a47701907ac.PNG)

but, i didn't find or am i missing something to connect between port us and my private docker registry v2 ?

**Comment by galeenk** [comment]
great, thank you very much!!! now i can access to the portal portus ..

**Comment by galeenk** [comment]
@mssola thank for your help ! now i can access my portal portus. 

but i've an issue again 😄 

should i prepare 2 domain for my registry and portus? like registry.xxx.xx => portus & images.registry.xxx.xx => registry ? or just one domain like registry.xxx.xx => portus & registry

when i prepare for single domain, i got issue like this.. 

> my portus is fine also i can login via docker login CLI but i can't  to docker push it into my registry ..
root@docker-registry:/opt/docker/Portus/examples/compose# docker login registry.codigo.id
Username: portus
Password:
Login Succeeded
root@docker-registry:/opt/docker/Portus/examples/compose# docker tag alpine:3.8 registry.codigo.id/alpine
root@docker-registry:/opt/docker/Portus/examples/compose# docker push registry.codigo.id/alpine
The push refers to repository [registry.codigo.id/alpine]
df64d3292fd6: Preparing
error parsing HTTP 404 response body: unexpected end of JSON input: ""

> and when i want to connect registry via web, show error like this .. 
![11](https://user-images.githubusercontent.com/11450368/45469064-24f46d80-b752-11e8-8ccf-9a1610dffd92.PNG) 
*i use 443 because i've ready direct to https with acmetool & letsencrypt .

when i use different domain to, its seems like same issue.. 

do i miss something?

**Comment by mssola** [comment]
It's all a matter of tweaking NGinx in the proper way. The error you pasted is probably because the domain:port is probably not talking to the registry, or there is a problem with proxying. Make sure that the combination of host:port only talks to the registry process (i.e. not portus), and that the registry process can talk back to portus at the proper host:port that you've set.

It's the same for multiple domains, although it requires less trickery on the NGinx part.
