### ISSUE TITLE
Disable users

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#196]
Right now we cannot remove users. So, in order to work around this, I propose to be able to block users. Blocking users would mean that said blocked users won't be able to login again (until the admin un-blocks them).

**Comment by mssola** [comment]
Note that his should be re-evaluated after we fix the issue #197.

**Comment by eotchi** [comment]
Changing description to avoid confusion. 
The user should be "disabled", not "blocked". 
Reasoning behind this is, such a functionality shouldn't be reserved only to admins, but the user itself must be able to disable itself if required. 
This feature is a temporary workaround until https://github.com/SUSE/Portus/issues/198 is implemented.
