### ISSUE TITLE
Allow automatic creation of unknown namespaces

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1961]
### Description

In some places we've found that it's actually useful to create namespaces automatically. This happens, for example, in the `sync` task when we start portus for the first time and the registry is already full of images, in which some of them are inside of namespaces. So, Portus should be able to create these namespaces, even if a team has not created it.

##### Creating a new team of administrators

I propose to create a team of administrators. All namespaces being automatically created will be created within this team. After that, after #1241 is implemented, administrators would, in turn, assign these created namespaces into proper teams whenever they feel it's needed.

##### Re-using the hidden global team

Another possibility is to simply use the global hidden team (the one created for the portus user). This has the inconvenience that there are already quite some assumptions built in the code about this team, but at least we wouldn't create yet another global admin team.

### Dependencies

- [ ] #1241: created namespaces would be assigned to the admins team, and so they should be able to be re-assigned when all pieces are put together.

**Comment by vitoravelino** [comment]
Unless there's another reason for a global admin team, I would go with the reuse of the hidden global team. Then we can advise the user that the namespace is "orphan" and it would be nice to assign it to a proper team.

**Comment by mssola** [comment]
We should also take ideas discussed in #751 :+1:
