### ISSUE TITLE
Moving to a new FQDN, any advice?

### ISSUE THREAD

**Issue by marc0s** [SUSE/Portus#1974]
### Description

We have been happily running a Portus instance for over a year.  Requirements changed and we now need to move it into another network setup and this incurs in a DNS name change.

Apart from having to re-tag images in the registry as it's linked to its public URL, any other Portus-related advice you can give me?

Thanks in advance!

**Comment by mssola** [comment]
That's a good question :grin: Other than what you mentioned, I guess that changing configuration on your reverse proxy, changing the FQDN on your SSL certificates, making sure that the different containers trust this new host, etc.

Also, from the UI we don't allow the change of the registry hostname, so you'll have to update that on the DB directly, I guess (and we should probably support it...).

I think that's all.

**Comment by marc0s** [comment]
Thanks @mssola!

I forgot about the registry hostname defined for portus, will write it down.  Not a nightmare to update it on the DB directly.

Will tell you if we find any quirk on monday when moving :grin:

**Comment by marc0s** [comment]
We successfully migrated our network setup yesterday without any hassle.  No additional actions other than the ones stated above were needed.
:tada:
