### ISSUE TITLE
Large image upload results in failure: 'authentification required'

### ISSUE THREAD

**Issue by kiorky** [SUSE/Portus#1978]
### Description
Large image upload results in failure: 'authentification required' from docker client

### Steps to reproduce

1. have an image that need > 5 min upload
2. docker push

- **Expected behavior**: image pushed
- **Actual behavior**:  "failure authentification required"

**Portus version**: head (docker)

I saw http://port.us.org/docs/Configuring-Portus.html#advanced-registry-options and increased my timeout settings (right now the upload test is on its way) but i think that the proper way to fix this is to increase the default ``5min`` ``jwt_expiration_time`` timeout to something way bigger as it's definitivly too slow for uploading images > 1gb with slow connections.

**Comment by mssola** [comment]
> I saw http://port.us.org/docs/Configuring-Portus.html#advanced-registry-options and increased my timeout settings (right now the upload test is on its way) but i think that the proper way to fix this is to increase the default 5min jwt_expiration_time timeout to something way bigger as it's definitivly too slow for uploading images > 1gb with slow connections.

There was even an opened issue proposing to dynamically tune this expiration time, but it's a hard cookie.

That being said, raising the expiration time might lead to security issues and, honestly, I don't know what a "good" default might be on this case: 5 minutes feels like it's taking quite some time already, but of course there are always other scenarios in which this default falls too short.

It looks like you are still pushing. Give us an update once it's done :wink:

**Comment by kiorky** [comment]
1/ Well i think that 15 or 20 minutes as a default is safer.

2/ i need to reconfigure the registry and after do the upload test, IRL stuff made me away, i try to make it now and update here in turn.

**Comment by kiorky** [comment]
1/ increasing jtw token expiration time worked here to fix large uploads (so long upload time).

**Comment by mssola** [comment]
Ok, so I'll raise this value to 15 minutes, which should be fine.

**Comment by kiorky** [comment]
thx !
