### ISSUE TITLE
How to recover portus deleted image tags

### ISSUE THREAD

**Issue by gopal-gemini** [SUSE/Portus#2005]
We have installed Portus using "head" version last month ( not sure the exact version number because upgraded with latest stable version Version: 2.3.5@35b9c801bf5275537a8bd8152d2f5769d6c24b09), the images got deleted automatically from portus. I see that the blobs layers are still available in the blobs folder.  

I do not see the issues after upgraded with stable but How do we recover the deleted images tag and bring back it available? 

last bug report 
https://github.com/SUSE/Portus/issues/1160

**Comment by mssola** [comment]
> I do not see the issues after upgraded with stable but How do we recover the deleted images tag and bring back it available?

So the thing is that blobs weren't deleted (and you haven't run the garbage collector that you can find inside of the docker registry, right?). In this case, then the only thing you are missing is the manifest that Portus deleted. You could just push the images up again, and it should already re-use the blobs you had uploaded before the delete. This is the way to go imho.

> got deleted automatically from portus

I'd need logs and the configuration to give you a better response :sweat_smile:

**Comment by maleficxp** [comment]
Same issue affects me. 
Portus deletes images itself. 
I found, that each image was deleted after 30 day it was added, It looks like, the garbage collector did it, but it is not enabled in my config (I use default config):
```
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
```
Portus version: 2.5.0-dev@c98a51eb0cc2ee772c19ee64269d2a86ec0fe0dc

portus-background container log:
```
[catalog] Removed the tag 'latest'.
[catalog] Removed the image 'cuda10'.
Handling 'delete' event:
{
  "id": "be4128a1-299f-4479-a46a-dd2d86f3fbcf",
  "timestamp": "2019-01-10T12:17:28.108994516Z",
  "action": "delete",
  "target": {
    "digest": "sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d",
    "repository": "dwx315410/cuda10"
  },
  "request": {
    "id": "9c7d04e3-0c02-4aaa-b32d-ba9dbdb5c5dd",
    "addr": "172.18.0.5",
    "host": "docker.matis.huawei.com",
    "method": "DELETE",
    "useragent": "Ruby"
  },
  "actor": {
    "name": "portus"
  },
  "source": {
    "addr": "f196d255bd82:5000",
    "instanceID": "cc9e6a8f-62a7-45a1-9711-9d3cd222fe14"
  }
}
```
registry container log:
```
time="2019-01-10T12:17:26Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=docker.matis.huawei.com http.request.id=a6f1618a-5ce4-4580-8bdb-92949e7e4f57 http.request.method=DELETE http.request.remoteaddr=172.18.0.5 http.request.uri="/v2/dwx315410/cuda10/manifests/sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d" http.request.useragent=Ruby instance.id=cc9e6a8f-62a7-45a1-9711-9d3cd222fe14 vars.name="dwx315410/cuda10" vars.reference="sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d" version=v2.6.2
time="2019-01-10T12:17:26Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=docker.matis.huawei.com http.request.id=a6f1618a-5ce4-4580-8bdb-92949e7e4f57 http.request.method=DELETE http.request.remoteaddr=172.18.0.5 http.request.uri="/v2/dwx315410/cuda10/manifests/sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d" http.request.useragent=Ruby instance.id=cc9e6a8f-62a7-45a1-9711-9d3cd222fe14 vars.name="dwx315410/cuda10" vars.reference="sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d" version=v2.6.2
172.18.0.1 - - [10/Jan/2019:12:17:26 +0000] "DELETE /v2/dwx315410/cuda10/manifests/sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d HTTP/1.0" 401 156 "" "Ruby"
...
time="2019-01-10T12:17:28Z" level=info msg="response completed" go.version=go1.7.6 http.request.host=docker.matis.huawei.com http.request.id=9c7d04e3-0c02-4aaa-b32d-ba9dbdb5c5dd http.request.method=DELETE http.request.remoteaddr=172.18.0.5 http.request.uri="/v2/dwx315410/cuda10/manifests/sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d" http.request.useragent=Ruby http.response.duration=13.694751ms http.response.status=202 http.response.written=0 instance.id=cc9e6a8f-62a7-45a1-9711-9d3cd222fe14 version=v2.6.2
172.18.0.1 - - [10/Jan/2019:12:17:28 +0000] "DELETE /v2/dwx315410/cuda10/manifests/sha256:302496805dadfe2804ff60d8fa835e488f447c6422d0f897d0a4b12e8a366b9d HTTP/1.0" 202 0 "" "Ruby"
```

**Comment by vitoravelino** [comment]
@maleficxp this bug was fixed at https://github.com/SUSE/Portus/pull/2018. Your image is probably older than that. Also, we've imlemented the suggestions of https://github.com/SUSE/Portus/issues/2051. If you upgrade your instance you can take advantage of that too.

**Comment by vitoravelino** [comment]
To be honest I think we can close this issue. What do you think, @mssola?

**Comment by mssola** [comment]
Agreed. Thanks @vitoravelino for the heads up :+1:
