### ISSUE TITLE
patch level missing in docker tag for portus 2.4

### ISSUE THREAD

**Issue by Bonko** [SUSE/Portus#2008]
### Description

The Portus 2.4 release on [Dockerhub](https://hub.docker.com/r/opensuse/portus/tags/) is missing a tag with the exact patch level (`2.4.0`). As it helps us to know exactly which version is running (especially when it is run multiple times) and the 2.3 release already had these specific tags it would be a great help if you reintroduce these tags.

### Deployment information
**Portus version**: 2.4

**Comment by mssola** [comment]
Done! Sorry for any inconvenience. I'll also update the documentation because apparently we don't say much about patch-level releases :sweat_smile:

**Comment by mssola** [comment]
> I'll also update the documentation because apparently we don't say much about patch-level releases

Done! See [this](http://port.us.org/docs/deploy.html) on version-specific tags :yum:
