### ISSUE TITLE
LDAP documentation for method is wrong

### ISSUE THREAD

**Issue by Stealthfox** [SUSE/Portus#2013]
### Description

The LDAP documentation at http://port.us.org/docs/Configuring-Portus.html refers to setting ldap: method which doesn't work. It should be ldap: encryption: method.

### Steps to reproduce

1. Specify an environment variable for PORTUS_LDAP_METHOD for simple_tls
2. Run Docker container
3. Get 401 unauthorized with very little debugging information

- **Expected behavior**: LDAP authentication works
- **Actual behavior**: 401 unauthorized

**Portus version**: 2.4

**Comment by mssola** [comment]
Thanks for the heads up :+1:

**Comment by mssola** [comment]
The documentation has been updated. Thanks for your feedback :clap:
