### ISSUE TITLE
Can not lookup application_token by calling  Rest Api

### ISSUE THREAD

**Issue by Coding365** [SUSE/Portus#2014]
### Description

Can not lookup application_token by calling Rest Api --- /api/v1/users/{id}/application_tokens

### Steps to reproduce

1. Use the Postman to call /api/v1/users/{id}/application_tokens
2. I can see the result like:
[
  {
    "id": 0,
    "application": "string"
  }
]
but there is no fields "plain_token"

Please, the issue confuse me a few days.

**Comment by vitoravelino** [comment]
@Coding365 did you create the application token? If yes, how?

**Comment by Coding365** [comment]
Thanks. I worked out the issue with another way. I store the application token in my own DB when i create it.

**Comment by vitoravelino** [comment]
Oh, yeah... The application token is only showed once after it's created. You should store it on your own after that. I'll close it then. Thanks! :)
