### ISSUE TITLE
portus-background is running garbage collection regardless of config settings

### ISSUE THREAD

**Issue by ArcticSnowman** [SUSE/Portus#2015]
### Description

After much digging I have found that the garbage collector background process seems to be running regardless of what the settings in config-local.yml or reported by `portusctl exec rake portus:info`

## Logs

``` 
  (0.4ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:24:46.335802')
   (0.5ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:25:46.430286')
   (0.4ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:26:46.511819')
   (0.5ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:27:46.593673')
   (0.4ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:28:46.680927')
   (0.6ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:29:46.759457')
   (0.5ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:30:46.836754')
   (0.4ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:31:46.912175')
   (0.4ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:32:46.988272')
   (0.5ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:33:47.073733')
   (1.6ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:34:47.145806')
   (0.5ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`marked` = 0 AND (updated_at < '2018-09-24 15:35:47.224036')

```

### Deployment information

**Deployment method**: 
Helm deployment to kubernetes based on https://github.com/GrantStreetGroup/portus-helm

**Configuration**:

```yml
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
```

**Portus version**: 
`Portus version: 2.4.0@2.4.0`

**Comment by ArcticSnowman** [comment]
The one possibility I can see to why `delete.garbage_collector.enabled` is not honored, when comparing to the other background task, is the `_` in the config name...   I tried with the 'background.sync.enabled` and the setting was honored...

**Comment by ArcticSnowman** [comment]
Ok think I found the issue in 
https://github.com/mssola/cconfig/blob/master/lib/cconfig/hash_utils.rb#L35-L43

```
      def enabled?(feature)
        cur   = self
        parts = feature.split(".")

        parts.each do |part|
          cur = cur[part]
          return false if !cur || cur.empty?
          return true  if cur.key?("enabled") && cur["enabled"].eql?(true)
        end

````
The above is a recursive function that splits the key on '.' and checks each level of an 'enabled' key

So take the config 

```
delete:
  enabled: true
  garbage_collector:
    enabled: false
```

Calling `APP_CONFIG.enabled?('delete.garbage_collector')` , the code will check for the key 'delete.enabled' first before looking at 'delete.garbage_collector.enabled'

**Comment by ArcticSnowman** [comment]
One suggestion is to move the `garbage_collector` from `delete` to the `background` section of the config.

**Comment by mssola** [comment]
> One suggestion is to move the garbage_collector from delete to the background section of the config.

This was considered on the original design, but bear in mind that this will only work if the `delete` option is enabled. Since there was this strong relation, we thought of simply having that section inside of the `delete` section.

**Comment by ArcticSnowman** [comment]
Well with cconfig update we have a fix...
