### ISSUE TITLE
Avoid that garbage_collector deletes images that are still in use

### ISSUE THREAD

**Issue by Bonko** [SUSE/Portus#2051]
### Description

When having the newly introduced garbage_collector enabled, all tags older than the specified time are deleted, regardless if there are any (possible) used tags left.

This results in complete repositories that get deleted when images are not build regularly.

It would be a great help to ensure that tags that are still used are not deleted.
Using the `tag` parameter does not help here.

Ideas that came to my mind for this:
* check if the tag was still accessed (pulled) during the specified  `older_than` timeframe before deleting
* add an option "keep_latest_x_tags" which lets you specify to always keep the newest X tags

**Portus version**: 2.4

- [X] Implementation #2095 
- [x] Documentation #2100

**Comment by mssola** [comment]
Makes total sense. Thanks for the feedback :+1:
