### ISSUE TITLE
missing index in scan_results table

### ISSUE THREAD

**Issue by dimuskin** [SUSE/Portus#2053]
### Description

I finally updated our registry server from 2.2 to 2.4. 
after the update, the vulnerability scan is started,it takes approx 20 hours and creates >1.5M records in scan_results. After that, serious performance problems began (mariadb cpu usage >95% and high load on server).

I enabled slow_query_log and found that all slow queries looks like:

`SELECT DISTINCT vulnerabilities.* FROM vulnerabilities INNER JOIN scan_results ON vulnerabilities.id = scan_results.vulnerability_id WHERE scan_results.tag_id = XXXX `

Looks like `scan_results` table missing proper index. I fixed it by:

`create INDEX index_scan_results_on_vulnerability_id_and_tag_id on scan_results (vulnerability_id, tag_id)`

Now server working more and more faster :)

**Comment by mssola** [comment]
Thanks for the heads up :clap: ! I've already submitted a PR (#2057) fixing this situation.
