### ISSUE TITLE
Ports conflicting in the Vagrant setup

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#21]
I'm using Vagrant 1.7.2 and by just calling `vagrant up` I get the following error from the `portus` node:

```
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 44242 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 80, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```

I thought to pass the extra-argument `auto_correct`, but that was not quite working. However if in the Vagrantfile I change all the `config.vm.network` config lines to `node.vm.network`, everything seems to work.

Am I missing something or this is really a bug on the Vagrant config ?

**Comment by flavio** [comment]
Fixed with 786ce01538a22918c2aeeceab0f6a48c3a217811. Thanks for having noticed that.
