### ISSUE TITLE
Upgrading from 2.4.0 -> 2.4.1 results in empty namespace/repositories/users

### ISSUE THREAD

**Issue by beatsandpics** [SUSE/Portus#2106]
### Description

After the upgrade all namespaces/registries/users/teams are emtpy.
The only value shown is the "recent activities" in the dashboard.
(Cleared browser cache, tried different browsers)

Login did still work with a dedicated user also did docker cli work with all users. Seems to be manly a rendering issue.

--> Reverting to 2.4.0 and all looks fine again.

**Comment by opopops** [comment]
you're right, thank you!

For Me the problem was due to the **portus-static** volume, shared between portus and nginx, I have to stop and remove portus and nginx containers, then remove portus-static volume en re-up compose and now all is OK!

**Comment by vitoravelino** [comment]
Another way to solve this is to run `docker-compose down -v` that will remove the declared and anonymous volumes.

I've submitted a PR (#2110) that includes a section in the upgrading page to let users know about this issue.

I'm going to close this but feel free to reopen if the issue persists. Thank you!
