### ISSUE TITLE
Deleting Namespace With Changed Visibilty Breaks UI

### ISSUE THREAD

**Issue by aecooper** [SUSE/Portus#2124]
### Description

When the delete namespace operation is performed existing entries in the activities table get overwritten (when observed the entries were changed from namespace to registry and other seemingly corrupt values inserted into the rows. This results in the web UI breaking.

### Steps to reproduce

1. Start Portus with a clean and empty database and registry.
2. Perform initial log in so as to create the first admin user.
3. Log in as that admin user.
4. Register the docker registry.
5. Create a team (name doesn't matter).
6. Create a namespace (name doesn't matter but I used dockerhub).
7. Change the visibility of the newly created namespace to world readable.
8. Delete the namespace.
9. Click on the dashboard.
10. Broken light house is displayed with the oops message.

- **Expected behavior**: I expected the dashboard to be displayed showing the recent actions that had been performed and for it to continue operating correctly.
- **Actual behavior**: Instead the oh something is wrong page was displayed and the UI became inoperable.

### Workaround

1. Either restore the database from backup and manually remove the namespace using the mysql command line.
OR
2. Using the mysql command line delete the contents of the activities table with delete from activities;.

An exception stack trace is shown in the log file but when the dashboard is being displayed and is reacting to the json parsing error due to the corruption (thus this is a symptom and not the problem). When the delete operation is performed nothing out of the ordinary is reported.

Unfortunately this is on an isolated system so I can't easily get actual logs to you.

### Deployment information

**Deployment method**: Deployed using the standard docker image and the docker-compose file out of the examples directory ( Portus/examples/compose/docker-compose.yml). We are using self signed certs and https.

### Docker Versions And Host Environment

Host: Ubuntu 18.04 LTS x86_64 patched to late december.
Docker: Docker-CE version 18.09.0 build 4d60db4
Docker Images:
    opensuse/portus 2.4.1 (portus:info gave: 2.4.1@ddc403833c8975a8975a83aa93d01baa4bc10acd40c1b)
    mariadb 10.0.23
    registry 2.6 (2e2f252f3c88)
    nginx:alpine (aae476eee77d)

This issue also happened on 2.4 and 2.4.0.

 Many thanks in advance,

Tony.

**Comment by vitoravelino** [comment]
It's probably related to activities. If you visit the other pages, everything is working, right?

**Comment by aecooper** [comment]
I've just tried it. Yes that's correct.

However unfortunately when you log in you are presented with the dashboard it stops people logging in (unless they are savvy enough to append /namespaces or /repositories in which case they can then continue to use the rest of the UI). It's certainly related to malformed entries being inserted/updated into that table.

I was wondering can the dashboard be disabled in the meantime?

**Comment by vitoravelino** [comment]
> I was wondering can the dashboard be disabled in the meantime?
Not really. The only problem is the dashboard (initial) page, everything else is working as expected. Don't worry about using your registry as you want.

I'll try to submit a fix later today if I'm able to reproduce it.

**Comment by aecooper** [comment]
Awesome - many thanks. If you can't reproduce it I'll try on my system at home and then I'll be able to send you all the grizzly details as necessary.

**Comment by vitoravelino** [comment]
Reproduced. Working on it. Thanks!

**Comment by aecooper** [comment]
Great news :-), many thanks for that.
