### ISSUE TITLE
Push, pull issue

### ISSUE THREAD

**Issue by cisco06** [SUSE/Portus#2133]
Hello!
I can push to a private namespace, however I'm not member of namespace's team. Why can I this?
Thanks!

**Comment by vitoravelino** [comment]
Were the user an admin or a regular one? Admin can do anything they want to.

**Comment by cisco06** [comment]
I also can push image with regular and root user, if the user is not member of the team.

**Comment by cisco06** [comment]
I deploy in swarm cluster. Here is the docker-compose.yml:

version: '3.6'

services:
  db:
    image: mariadb:latest
    deploy:
      mode: replicated
      replicas: 1
      labels: [registry_db]
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 44412:3306

  registry:
    image: registry:2
    volumes:
      - ./images:/var/lib/registry
      - ./conf/registry.yml:/etc/docker/registry/config.yml:ro
      - ./tls:/certs:ro
    deploy:
      mode: replicated
      replicas: 1
      labels: [registry]
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints: [node.role == manager]
    ports:
     - 5000:5000

  portus:
    image: opensuse/portus:latest
    deploy:
      mode: replicated
      replicas: 1
      labels: [portus]
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints: [node.role == manager]
    environment:
      PORTUS_LOG_LEVEL: "debug"
      PORTUS_SECRET_KEY_BASE: "62810c63..."
      PORTUS_PASSWORD: "password"
      PORTUS_KEY_PATH: "/certificates/mydomain.key"
      PORTUS_PUMA_TLS_KEY: "/certificates/mydomain.key"
      PORTUS_PUMA_TLS_CERT: "/certificates/star_mydomain.pem"
      PORTUS_PUMA_HOST: "host_IP:3000"
      PORTUS_CHECK_SSL_USAGE_ENABLED: "true"
      RAILS_ENV: "production"
      RAILS_SERVE_STATIC_FILES: "true"
      PORTUS_DB_HOST: "host_IP"
      PORTUS_DB_DATABASE: "portus_production"
      PORTUS_DB_USERNAME: "root"
      PORTUS_DB_PASSWORD: "password"
      PORTUS_DB_POOL: 5
      PORTUS_DB_PORT: 44412
    ports:
      - 3000:3000
    volumes:
      - ./certs:/certificates:ro
      - ./config/config.yml:/srv/Portus/config/config-local.yml
    depends_on:
      - registry
      - db

  background:
    image: opensuse/portus:latest
    deploy:
      mode: replicated
      replicas: 1
      labels: [portus_background]
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints: [node.role == manager]
    environment:
      PORTUS_MACHINE_FQDN: "portus.example.com"
      PORTUS_BACKGROUND_REGISTRY_ENABLED: "true"
      PORTUS_BACKGROUND_SYNC_ENABLED: "true"
      PORTUS_BACKGROUND_SYNC_STRATEGY: "update-delete"
      PORTUS_SECRET_KEY_BASE: "62810c63..."
      PORTUS_KEY_PATH: "/certificates/mydomain.key"
      PORTUS_PASSWORD: "password"
      PORTUS_BACKGROUND: "true"
      PORTUS_DB_HOST: "host_IP"
      PORTUS_DB_DATABASE: "portus_production"
      PORTUS_DB_USERNAME: "root"
      PORTUS_DB_PASSWORD: "password"
      PORTUS_DB_POOL: 5
      PORTUS_DB_PORT: 44412
    volumes:
      - ./certs:/certificates:ro
      - ./config/config.yml:/srv/Portus/config/config-local.yml
    depends_on:
      - portus
      - db
      - registry


Furthermore I configured LDAP to portus in /config/config.yml


registry.yml:

version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  host: https://registry.example.com:5000
  secret: 62810c63...
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/star_mydomain.pem
    key: /certs/mydomain.key
    rootcertbundle: /certs/star_mydomain.pem

**Comment by cisco06** [comment]
Thanks! I tried it with auth token and registry notification endpoint environment variables, but now Portus is not connect to registry. I can't push, pull or delete images.
...
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://portus.example.com:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: portus.example.com
      REGISTRY_AUTH_TOKEN_ISSUER: portus.example.com
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/star_mydomain.pem
      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://portus.example.com:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
...
If I view https://portus.example.com:3000/v2/webhooks/events I got error message: The page you are looking for does not exist.
What is the problem? Can you help me?
