### ISSUE TITLE
Can't use these buttons

### ISSUE THREAD

**Issue by cisco06** [SUSE/Portus#2134]
What are these buttons? I not push or pull images from web ui whit these buttons.
![capture](https://user-images.githubusercontent.com/47029399/51745032-f0020b00-20a1-11e9-8251-eda8273b65fb.JPG)

**Comment by vitoravelino** [comment]
These are really old stuff used to just give information about what you can do with that repository. The buttons doesn't do anything, just show this popover thing. This was replaced with proper text on the new repository overview section that will be released in `2.5`.
