### ISSUE TITLE
Creating team 'TEAM_NAME' via API/UI -> Portus also creates the team 'TEAM_NAME0'

### ISSUE THREAD

**Issue by bnohad** [SUSE/Portus#2142]
### Description
When creating team 'X', Portus also creates a hidden team with the name 'X0'

### Steps to reproduce

1. Create a team 'team-1'
2. Then try to create the team 'team-10'
3. API returns http status code '422', UI shows the message: 'Name is reserved or has already been taken'

- **Expected behavior**: the team 'team-10' should be created successfully
- **Actual behavior**: Portus claims the team already exists & prevents the team creation

### Deployment information
Portus is deployed on a K8S cluster in GKE
using the image: 'opensuse/portus:2.4.1'

**Portus version**: Both 2.4 & 2.4.1

**Comment by mssola** [comment]
I cannot reproduce this in neither `2.4.2` nor `head`. Could you set the log level to [debug](http://port.us.org/docs/debugging.html#log-level) and paste the logs?

**Comment by vitoravelino** [comment]
I'm going to paste the same thing I said in #2143.

> I'm not saying that this is wrong but with those steps this is not reproducible. 
> 
> My guess is that this is somehow related to users created previously and their data still being attached to some entity that could not be wiped and it's causing conflict. Without the exact steps it's kinda hard for us to understand the issue and come up with a fix.
