### ISSUE TITLE
Creating namespace 'some-namespace' -> Portus also creates the namespace 'some_namespace'

### ISSUE THREAD

**Issue by bnohad** [SUSE/Portus#2143]
### Description

When creating namespace 'a-b' in Portus, another namespace with the name 'a_b' is created 

### Steps to reproduce

1. Create a namespace 'my-namespace'
2. Then try to create the namespace 'my_namespace'
3. Portus returns the following error: 'Name has already been taken'

- **Expected behavior**: Portus should create both namespaces successfully
- **Actual behavior**: The creation of the 2nd namespace 'a_b' fails

### Deployment information
Deployed on K8S cluster in GKE
using image: 'opensuse/portus:2.4.1'

**Portus version**: Both 2.4 & 2.4.1

**Comment by mssola** [comment]
I cannot reproduce this in neither `2.4.2` nor `head`. Could you set the log level to [debug](http://port.us.org/docs/debugging.html#log-level) and paste the logs?

**Comment by vitoravelino** [comment]
I'm not saying that this is wrong but with those steps this is not reproducible. 

My guess is that this is somehow related to users created previously and their data still being attached to some entity that could not be wiped and it's causing conflict. Without the exact steps it's kinda hard for us to understand the issue and come up with a fix.

**Comment by kurthaegeman** [comment]
When Portus is asked to create a namespace with hyphens in it, it considers the hyphen to be an illegal character and will create a namespace with the hyphen replaced by an underscore. So in your use case:
* you ask to create 'my-namespace'
* Portus creates 'my_namespace'
* you ask to create 'my_namespace'
* Portus reports the name is already taken

I have reported this a while a ago, and submitted a [pull request](https://github.com/SUSE/Portus/pull/2130) with a proposed fix, as hyphens should be allowed in registry namespaces.
