### ISSUE TITLE
Google+ API shutdown: google_oauth2 authentication failure. invalid_credentials: OAuth2::Error

### ISSUE THREAD

**Issue by raolivei** [SUSE/Portus#2144]
### Description

Google is shutting down Google+ API but Portus relies on it in order to authenticate with google_oauth2. We should remove this dependency and pray for God there's another API that has the same scopes that Portus need to authenticate.

Unfortunatelly, it looks like Portus is only expecting scopes provided by Google+ API.

from Portus container logs, right after trying to authenticate thru the portal:

``` bash
Error when trying to use google_oauth2 without Google+ API enabled: 
-- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, 
{"errors"=>[{"domain"=>"usageLimits", "reason"=>"accessNotConfigured", "message"=>"Access Not Configured. Google+ API has not been used in project 1037554284121 before or it is disabled. 
Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=1037554284121 then retry. 
```

### Steps to reproduce

1. Change your config-local.yml to support google_oauth2 and enter valid ID and credentials.
2. After deployment, try to authenticate with your pre-configured Google account.

**Comment by vitoravelino** [comment]
I guess that by just upgrading omniauth-google-oauth2 to the latest version will fix this. Thanks for reminding us about that!

**Comment by raolivei** [comment]
Would you guy please clarify on how to implement omniauth-google-oauth2 to the code?

**Comment by mssola** [comment]
@raolivei I'm not sure I understand the question :sweat_smile: The implementation is provided by the omniauth-google-oauth2 gem. In #2146 we have upgraded the gem to a version which no longer uses the Google+ API.

Other than that, the omniauth code is being handled in the [Auth::OmniauthCallbacksController](https://github.com/SUSE/Portus/blob/master/app/controllers/auth/omniauth_callbacks_controller.rb) and the [Auth::OmniauthRegistrationsController](https://github.com/SUSE/Portus/blob/master/app/controllers/auth/omniauth_registrations_controller.rb). The omniauth backends are enabled depending on the configuration. This is being checked at [config/initializers/device/oauth.rb](https://github.com/SUSE/Portus/blob/master/config/initializers/devise/oauth.rb).

Hope this helps.

**Comment by Bonko** [comment]
The API will be shut down tomorrow. As it seems that the release of 2.5 will take some time, is there any chance of backporting this to 2.4?

**Comment by vitoravelino** [comment]
> The API will be shut down tomorrow. As it seems that the release of 2.5 will take some time, is there any chance of backporting this to 2.4?

It was already backported as stated in https://github.com/SUSE/Portus/pull/2146#issuecomment-460986085.

**Comment by Bonko** [comment]
@vitoravelino thanks, I did not see it. but its still missing a docker patch release. I will continue this in your linked pull request
