### ISSUE TITLE
Registry events not processed after upgrade

### ISSUE THREAD

**Issue by Typz** [SUSE/Portus#2148]
### Description

We are migrating a registry from portus 2.2 to portus 2.4, and enabling clair security scanning in the process. This registry stores around 1000 tags.

When starting the application, we can see clair kicking in, and security scanning is performed on all the existing tags. This process takes hours (around 6 to 8 hours), and no registry event is processed in this time frame.

### Steps to reproduce

1. Initialize a registry with many images
2. Enable clair security scanning
3. Before scan of all tags has completed, push a new image to registry

- **Expected behavior**: the tag appears in Portus within a few seconds
- **Actual behavior**: the tag does not appear.

If the container is re-starter, then the tag will indeed appear.
(And the tag will probably appear once the initial scan is complete, though I have not reached that point yet)

### Deployment information

**Deployment method**: docker-compose similar to the exemples
**Portus version**: official opensuse/portus:2.4.2 container

### Analysis

Looking at the code, I can see that the background process calls each background task in sequence. And the security scan process analyses all the 'pending' tags synchronously: which can take a very long time.

I am wondering how to fix this:
* A work-around may be to run multiple background containers, each for different background task (e.g. move the security scanning to another container which does this task only)
* A better fix may be to limit the number of containers which are processed at once by the security task. This would delay analysis though, as it would still way for 10 seconds between each 'batch'.
* To overcome this last limitation, the whole scheduling in bin/background.rb would need to be rewritten to take into account "split" tasks (e.g. there is still work at the end of a task), and account for actual elapsed time instead of the number of times sleep() has been called.
* Ideally, a better fix would be to use asynchronous api for clair, so that the background task simply starts the security scan and a webhook is used to notify the completion of analysis.

**Comment by Typz** [comment]
One easy fix would be to use one thread per background task in bin/background. Is there a reason not to do this?
Otherwise may we'd be better off using a scheduling gem instead of rewriting one from scratch...

**Comment by dszmolka** [comment]
We have the same issue, even without security scanning enabled. Background sync strategy is set to update-delete however and we do have a lot of images. New registry events are not processed until a sync run is finished, would too appreciate if registry events processing could be moved to be able to run separately from the other processes. Is there a feature request for this already?
