### ISSUE TITLE
The wave on the login/signup pages is not responsive to the screen size

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#215]
There should be an image containing a "wave" on the bottom of the page for both the login and the signup pages. If you have a screen that is large enough, you can see the tip of this "wave":

![wave](https://cloud.githubusercontent.com/assets/767943/8594279/b70819c6-263f-11e5-9725-1712b36b7b1f.png)

However, if you resize the window so the vertical vs horizontal ratio gets bigger on the vertical side, you'll get the following:

![wave1](https://cloud.githubusercontent.com/assets/767943/8594414/bf62d902-2640-11e5-9302-375667117dc0.png)

In this case, we can perfectly see the wave. I believe that this is inconsistent, and therefore a bug. The wave should always be shown.

**Comment by cyntss** [comment]
I would change the title of this bug because it isnt inconsistency between both screens but a bug in the responsiveness of the wave.

**Comment by cyntss** [comment]
Here how the Login looks on small screen:

![image](https://cloud.githubusercontent.com/assets/5013096/10452997/3449d910-71a9-11e5-9482-1dada56f8aa1.png)

**Comment by cyntss** [comment]
![image](https://cloud.githubusercontent.com/assets/5013096/10454122/938b4f9a-71b2-11e5-881f-604757da96dd.png)
![image](https://cloud.githubusercontent.com/assets/5013096/10454132/9f74e640-71b2-11e5-9d82-ab9e087ec82e.png)

Fixed in f8a0a74e9a55d066166f8a8769d7c93b84e4b61f

**Comment by mssola** [comment]
@cyntss that looks really cool, but maybe the placeholders should be white. We had a contribution recently that added a cross-platform mixin that change the placeholder color named `input-placeholder`. It's implemented in app/assets/stylesheets/mixins.scss

**Comment by flavio** [comment]
Really nice @cyntss! However I agree with @mssola about the placeholders

**Comment by cyntss** [comment]
Sure no problem. I didnt like it white because it was too noticeable, but I also was expecting to receive this feedback haha.. so yes, i will change it now.
