### ISSUE TITLE
Portus Background HTTP 401

### ISSUE THREAD

**Issue by jreker** [SUSE/Portus#2157]
I have set up a portus instance on docker with the docker-compose example here from github.

I changed the certs so that it is working for me. Everything seems to work except the background service/container. In the log i can see that there is a HTTPUnauthorized error:

```
registry_1    | 172.23.0.1 - - [26/Feb/2019:08:34:27 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
portus_1      | Started GET "/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=<- DOCKER HOST FQDN ->" for 172.23.0.6 at 2019-02-26 08:34:27 +0000
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"<- DOCKER HOST FQDN ->"}
portus_1      | **Completed 401 Unauthorized in 25ms** (ActiveRecord: 2.9ms)
nginx_1       | 172.23.0.1 - portus [26/Feb/2019:08:34:28 +0000] "GET /v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=<- DOCKER HOST FQDN -> HTTP/1.1" 401 52 "-" "Ruby"
```
I dont know what the problem is. I thought that this can be a problem with obtaining the auth token. But when i make a GET request to "/v2/token" i will get a token. That means for me that it is working.

Does somebody have an idea how i can go on troubleshooting or how i can solve the problem so that the background portus is also working? What am i doing wrong?

**Comment by TechCatOther** [comment]
What address do you set for registry? I think that problem may be in nginx routing auth traffic and registry traffic. Try to set 443 port, 80 or 5000.

My compose works same. Background task sometimes ask registry without authentication - get 401. Then auth and get all. Token expired?

**Comment by jreker** [comment]
We can close this issue now. It works now. I dont know the exactly cause of that.
I started completly new with the configuration.
