### ISSUE TITLE
can't login into registry

### ISSUE THREAD

**Issue by orest-gulman** [SUSE/Portus#2158]
what i did:
1. clone https://github.com/SUSE/Portus.git
2. cd Portus ; run docker-compose
3. Create user; add registry

When trying to login to registry, get an error:
`Error response from daemon: Get http://192.168.36.86:5000/v2/: Get http://172.17.0.1:3000/v2/token?account=ogulman&client_id=docker&offline_token=true&service=172.17.0.1%3A5000: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awa
iting headers) (Client.Timeout exceeded while awaiting headers)`

Pls help, to solve the issue.

**Comment by orest-gulman** [comment]
solved by changing ACHINE_FQDN in /Portus/.env.
`ACHINE_FQDN=192.168.36.86
REGISTRY_PORT=5000`

**Comment by sgnd** [comment]
@orest-gulman hi, what is the IP? local IP or Public IP?

**Comment by orest-gulman** [comment]
Hi @sgnd, in my case it was local.
