### ISSUE TITLE
background container exiting after push large image

### ISSUE THREAD

**Issue by orest-gulman** [SUSE/Portus#2159]
When I trying to push images, images pushed well, tags creates, but when I tryed to push large image(11GB), backgroung contaiter exited, and tag didn't creates. 
Logs from background container:
`RegistryEvent Update All (0.4ms)  UPDATE `registry_events` SET `registry_events`.`status` = 1 WHERE `registry_events`.`event_id` = 'b5b22a2e-14ff-477f-aafd-3922e1025c80'
Handling 'push' event:
{
  "id": "b5b22a2e-14ff-477f-aafd-3922e1025c80",
  "timestamp": "2019-03-04T11:16:23.526850731Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1793,
    "digest": "sha256:ba8a13f470a01d07d8311d017005bdfafa5d0e5bd8b68278d5c9ffb24baf12ba",
    "length": 1793,
    "repository": "images",
    "url": "http://192.168.36.86:5000/v2/images/manifests/sha256:ba8a13f470a01d07d8311d017005bdfafa5d0e5bd8b68278d5c9ffb24baf12ba",
    "tag": "dotnet"
  },
  "request": {
    "id": "33142a4b-1e80-44d6-8f99-f3ccd21b477a",
    "addr": "192.168.36.72:53645",
    "host": "192.168.36.86:5000",
    "method": "PUT",
    "useragent": "docker/18.09.2 go/go1.10.6 git-commit/6247962 os/windows arch/amd64 UpstreamClient(Docker-Client/18.09.2 \\(windows\\))"
  },
  "actor": {
    "name": "ogulman"
  },
  "source": {
    "addr": "96512a9602b9:5000",
    "instanceID": "9da1a4e4-7b78-4feb-8ceb-1efe46f85c0e"
  }
}
  Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = '192.168.36.86:5000' LIMIT 1
  Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`global` = TRUE LIMIT 1
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'ogulman' LIMIT 1
  Repository Load (0.4ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`namespace_id` = 1 AND `repositories`.`name` = 'images' LIMIT 1
  Tag Exists (0.5ms)  SELECT  1 AS one FROM `tags` WHERE `tags`.`repository_id` = 2 AND `tags`.`name` = 'dotnet' LIMIT 1
  Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 1 LIMIT 1
  Registry Load (0.4ms)  SELECT  `registries`.* FROM `registries` ORDER BY `registries`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  Tag Exists (0.5ms)  SELECT  1 AS one FROM `tags` WHERE (name COLLATE utf8_bin = 'dotnet' AND repository_id = 2) LIMIT 1
   (0.3ms)  ROLLBACK
/usr/lib64/ruby/gems/2.6.0/gems/activemodel-5.2.2/lib/active_model/type/integer.rb:53:in `ensure_in_range': 6477403194 is out of range for ActiveModel::Type::Integer with limit 4 bytes (ActiveModel::RangeError) 
        from /usr/lib64/ruby/gems/2.6.0/gems/activemodel-5.2.2/lib/active_model/type/integer.rb:29:in `serialize'
        from /usr/lib64/ruby/gems/2.6.0/gems/activemodel-5.2.2/lib/active_model/attribute.rb:55:in `value_for_database'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/query_attribute.rb:13:in `value_for_database'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/quoting.rb:15:in `quote'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/collectors/substitute_binds.rb:16:in `add_bind'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:741:in `visit_Arel_Nodes_BindParam'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/reduce.rb:15:in `visit'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:198:in `block in visit_Arel_Nodes_Values'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:195:in `each'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:195:in `each_with_index'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:195:in `visit_Arel_Nodes_Values'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/reduce.rb:15:in `visit'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:815:in `maybe_visit'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/to_sql.rb:134:in `visit_Arel_Nodes_InsertStatement'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/reduce.rb:15:in `visit'
        from /usr/lib64/ruby/gems/2.6.0/gems/arel-9.0.0/lib/arel/visitors/reduce.rb:8:in `accept'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/determine_if_preparable_visitor.rb:10:in `accept'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:23:in `to_sql_and_binds'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:153:in `insert'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `insert'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:185:in `_insert_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:732:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/counter_cache.rb:184:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/locking/optimistic.rb:70:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/attribute_methods/dirty.rb:140:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/callbacks.rb:346:in `block in _create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
        from /usr/lib64/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/callbacks.rb:346:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/timestamp.rb:102:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:703:in `create_or_update'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/callbacks.rb:342:in `block in create_or_update'
        from /usr/lib64/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
        from /usr/lib64/ruby/gems/2.6.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/callbacks.rb:342:in `create_or_update'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:273:in `save'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:46:in `save'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:257:in `transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:310:in `block in save'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:309:in `save'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:44:in `save'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:379:in `insert_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/has_many_association.rb:36:in `insert_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:363:in `block (2 levels) in _create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:460:in `replace_on_target'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:284:in `add_to_target'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:362:in `block in _create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:136:in `block in transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
        from /usr/lib64/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:135:in `transaction'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_association.rb:360:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/has_many_association.rb:123:in `_create_record'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/association.rb:190:in `create'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/associations/collection_proxy.rb:350:in `create'
        from /srv/Portus/app/models/repository.rb:155:in `add_repo'
        from /srv/Portus/app/models/repository.rb:103:in `handle_push_event'
        from /srv/Portus/app/models/registry_event.rb:34:in `block in handle!'
        from /srv/Portus/app/models/registry_event.rb:34:in `each'
        from /srv/Portus/app/models/registry_event.rb:34:in `handle!'
        from /srv/Portus/lib/portus/background/registry.rb:30:in `block in execute!'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `each'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches' 
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `loop'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:222:in `in_batches'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
        from /usr/lib64/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/relation/batches.rb:69:in `find_each'
        from /srv/Portus/lib/portus/background/registry.rb:28:in `execute!'
        from /srv/Portus/bin/background.rb:61:in `block (2 levels) in <top (required)>'
        from /srv/Portus/bin/background.rb:58:in `each'
        from /srv/Portus/bin/background.rb:58:in `each_with_index'
        from /srv/Portus/bin/background.rb:58:in `block in <top (required)>'
        from /srv/Portus/bin/background.rb:57:in `loop'
        from /srv/Portus/bin/background.rb:57:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands/runner/runner_command.rb:38:in `load'
        from /usr/lib64/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands/runner/runner_command.rb:38:in `perform'
        from /usr/lib64/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/lib64/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib64/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/lib64/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
        from /usr/lib64/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
        from /usr/lib64/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:12:in `require'
        from bin/rails:12:in `<main>'`

**Comment by orest-gulman** [comment]
It's looks like it depends on a size of images, official python(4.72GB) pushed successed, but when i push mongo(11.3GB) - background container exit, and tag didn't create.
Does anyone has a similar issue?

**Comment by Vad1mo** [comment]
I suspect the expiration of the token that happens. Increase JWT Token time as long as you need to push the 11 GB image

**Comment by orest-gulman** [comment]
i did it before, i changed to 60min

**Comment by orest-gulman** [comment]
always same result - background container Exited
`  Registry Load (0.4ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = '192.168.36.97:5000' LIMIT 1
  Namespace Load (0.2ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`global` = TRUE LIMIT 1
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'ogulman' LIMIT 1
  Repository Load (0.2ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`namespace_id` = 1 AND `repositories`.`name` = 'dockerhub' LIMIT 1
  Tag Exists (0.4ms)  SELECT  1 AS one FROM `tags` WHERE `tags`.`repository_id` = 1 AND `tags`.`name` = 'mongo' LIMIT 1
  Namespace Load (0.2ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 1 LIMIT 1
  Registry Load (0.1ms)  SELECT  `registries`.* FROM `registries` ORDER BY `registries`.`id` ASC LIMIT 1
   (0.8ms)  BEGIN
  Tag Exists (2.2ms)  SELECT  1 AS one FROM `tags` WHERE (name COLLATE utf8_bin = 'mongo' AND repository_id = 1) LIMIT 1
   (1.0ms)  ROLLBACK`

**Comment by vitoravelino** [comment]
@orest-gulman where can I find a large image to try this locally?

**Comment by vitoravelino** [comment]
My suspicion is that the tag size column as integer is not enough.

**Comment by orest-gulman** [comment]
Please try to push mongo images (docker pull mongo).

**Comment by vitoravelino** [comment]
@orest-gulman that's only 131MB/394MB.

**Comment by orest-gulman** [comment]
you can try microsoft/dotnet-framework:4.7.1 =  13.2GB
for example:
`PS C:\scripts> docker tag microsoft/dotnet-framework:4.7.1 192.168.36.56:5000/dotnet:4.7.1
PS C:\scripts> docker push 192.168.36.56:5000/dotnet:4.7.1
The push refers to repository [192.168.36.56:5000/dotnet] 
16a99543e5c1: Pushed
b9bcd6f8aea0: Pushed
2b36bde5f3bf: Pushed
b5f728f7388d: Pushed
1b12c7a83f26: Skipped foreign layer
f358be10862c: Skipped foreign layer
4.7.1: digest: sha256:d500a8f6a6e5192c34d4515bea44a5a722daae49a32c12c6d862cf48320c0a67 size: 1793`
after that background container exits.

**Comment by vitoravelino** [comment]
This one will do the trick. Thanks!

**Comment by vitoravelino** [comment]
@orest-gulman actually, this won't work for me because it's a windows image and I use linux.

**Comment by orest-gulman** [comment]
docker pull ogulman/oracle:base
pls try this one, thanks!
