### ISSUE TITLE
 docker-compose up -d giving following error

### ISSUE THREAD

**Issue by deo999** [SUSE/Portus#2160]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.nginx: 'aliases'
services.background.links contains an invalid type, it should be an array
services.nginx.links contains an invalid type, it should be an array
services.portus.links contains an invalid type, it should be an array
services.registry.links contains an invalid type, it should be an array
services.nginx.networks contains an invalid type, it should be an array, or an object

**Comment by Vad1mo** [comment]
wrong **docker-compose** version.

**Comment by deo999** [comment]
so what is solution

**Comment by Vad1mo** [comment]
update your docker-compose to the latest verison

**Comment by deo999** [comment]
1.24.0-rc1

**Comment by deo999** [comment]
I am trying to add following in docker-compose.yml file:
 nginx:
      image: library/nginx:alpine
      networks:
      default:
      aliases:
       - ${MACHINE_FQDN}

**Comment by Vad1mo** [comment]
The error message says it all 

**The Compose file './docker-compose.yml' is invalid because:**


And here is the position where

**services.background.links contains an invalid type, it should be an array
services.portus.links contains an invalid type, it should be an array
services.registry.links contains an invalid type, it should be an array**

**Comment by deo999** [comment]
@Vad1mo  so can you please simplify what will be the solution???????????/

**Comment by Vad1mo** [comment]
The error message is cristal clear **services.registry.links contains an invalid type, it should be an array**

whatever you have in `services.registry.links` is not correct. I don't know what you have as you didn't provide any context.

**Comment by deo999** [comment]
I am trying to follow this tutorial to install  portus .

**Comment by deo999** [comment]
can u please guide should i have to follow that tutorial or simply git clone and run docker-compose up

**Comment by Vad1mo** [comment]
I would use the official docs http://port.us.org/docs/deploy.html

**Comment by deo999** [comment]
@Vad1mo how to use your docker portus image after pulling it from docker hub what i have to install locally in my machine other than docker.

**Comment by Vad1mo** [comment]
Did you see the deployment examples on https://github.com/SUSE/Portus/tree/master/examples?

**Comment by deo999** [comment]
@Vad1mo  yes i check this just want to deploy on single host first  for example i just run this on machine docker pull opensuse/portus now what next

**Comment by deo999** [comment]
@Vad1mo finally i m able to login into portus and crete username, now i want to push and pull docker image into this registry what to do
