### ISSUE TITLE
registry: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying

### ISSUE THREAD

**Issue by marc0s** [SUSE/Portus#2163]
### Description

The following error is appearing repeatedly in the registry logs since our yesterday upgrade to 2.4:

```registry_1    | 2019-03-14T09:58:01.231650321Z time="2019-03-14T09:58:01Z" level=error msg="retryingsink: error writing events: httpSink{https://registry.redacted.com/v2/webhooks/events}: error posting: Post https://registry.redacted.com/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying"```

### Steps to reproduce

1. Stop all containers with `docker-compose down -v` to remove volumes as well
2. Update `docker-compose.yml` to use 2.4 images
3. Start all containers with `docker-compose up`

- **Expected behavior**: no errors in logs
- **Actual behavior**: The error shown above keeps appearing every ~3 seconds

I started to look at the logs because user reported that a deleted image still appeared in the web (which seems logical if the webhook requests are failing I suppose).

### Deployment information

** deployed using `docker-compose` like in the examples folder

**Configuration**:

- certificates provided by LetsEncrypt
- entering the container and resolving the hostname from it works OK, no apparent connectivity issues in this regard between registry and portus
- no configuration changes with respect to the 2.3 deployment

**Portus version**:  `2.4.2@f4d6914850a43f26049501a49c4dde2af4e8b415` (from docker image 2.4)

**Comment by L30Bola** [comment]
I'm deploying Portus internally and this error started to appear as soon as I had finished to push an image to test if push and pull was working (which are working).
Portus version: `2.4.3@5a616c0ef860567df5700708256f42505cdb9952` (Docker image 2.4.3)

**Comment by mssola** [comment]
@marc0s @L30Bola could you paste logs? The logs from the registry is stating that it cannot access Portus (maybe it's down?)

**Comment by marc0s** [comment]
Hey @mssola, I missed the notification. Will try to get those logs and report them back to you. Thanks!

**Comment by marc0s** [comment]
I restarted all the containers to make sure all of them are up and running and the very same error log appears.

Can't the registry log which event is it trying to post to try to know which action triggers the event?

Another error that repeats itself is
```
registry_1    | 2019-04-11T22:32:12.942885504Z time="2019-04-11T22:32:12Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.redacted.com http.request.id=e3072236-d360-4ba8-9981-0fdd94eeec51 http.request.method=GET http.request.remoteaddr=172.19.0.1 http.request.uri="/v2/namespace/imagetags/list?n=100" http.request.useragent=Ruby instance.id=e7cbd865-9c61-4f26-a3dd-42986c7c6876 vars.name="namespace/image" version=v2.6.2-14-ga66a4c3 
```

I don't know if it might be related.

Thanks and let me know if I can run something else to debug it further.
