### ISSUE TITLE
Support oauth against github enterprise

### ISSUE THREAD

**Issue by gtallan** [SUSE/Portus#2169]
### Description

Currently it seems that Portus only supports oauth authentication using github.com. Since the underlying OmniAuth github strategy does support github enterprise, it's not difficult to add support for this in Portus.

I have a fork with the necessary changes made, which "work for me", but it doesn't yet comply with the contributing guidelines especially in terms of spec tests.

**Comment by mssola** [comment]
> I have a fork with the necessary changes made, which "work for me", but it doesn't yet comply with the contributing guidelines especially in terms of spec tests.

Feel free to submit a PR and we'll see what we can do from it :wink:

**Comment by gtallan** [comment]
Thanks - I think I can see what the test should probably be, based on the similar case for gitlab, but I'm not sure what the test procedure/infrastructure is. I did try digging a little, but the file mentioned in CONTRIBUTING.md, https://github.com/SUSE/Portus/wiki/How-we-test-Portus seems not to exist.

I could add my proposed test with the disclaimer that it's untested, and I'm sure you can correct it as necessary! Will submit a PR.

**Comment by gtallan** [comment]
Sorry I still need to make this pass tests (I think I ran into ruby issues on centos)

**Comment by zachaller** [comment]
We also need github enterprise support, any updates on this?

**Comment by jasonnoble** [comment]
PR is #2171
