### ISSUE TITLE
wild card cert is not woking on registry version 2.6 .. 

### ISSUE THREAD

**Issue by anubhav19ok** [SUSE/Portus#2170]
Hello,
When i push an images to the registry, i can view it in portus.
With the registry output, i gview this error message :

registry_1 | time="2016-07-22T08:34:27.025926519Z" level=error msg="retryingsink: error writing events: httpSink{https://docker-registry.my-company.lan/v2/webhooks/events}: error posting: Post https://docker-registry.my-company.lan/v2/webhooks/events: x509: certificate signed by unknown authority, retrying" 
registry_1 | time="2016-07-22T08:34:27.027221918Z" level=warning msg="httpSink{https://docker-registry.my-company.lan/v2/webhooks/events} encountered too many errors, backing off" 

i am using wild card cert and using registry version 2.6

**Comment by anubhav19ok** [comment]
Hi sinc59,

Are you using the official registry image ? "SSL_TRUST" isn't a used variable by the official image but by this one : https://github.com/h0tbird/docker-registry.

You need to your cacerts to your containers trusted ca store :

    docker pull official registry image 2.3
    docker run with all your config (config.yml, cert & key, etc.)
    docker cp the cacerts you need somewhere in the container
    docker exec -it $your_container bash # bash, or sh
    
    docker run your_container (with all common options you were using with the official image)

**Comment by harish2336** [comment]
Hi sinc59,

Are you using the official registry image ? "SSL_TRUST" isn't a used variable by the official image but by this one : https://github.com/h0tbird/docker-registry.

You need to your cacerts to your containers trusted ca store :

docker pull official registry image 2.3
docker run with all your config (config.yml, cert & key, etc.)
docker cp the cacerts you need somewhere in the container
docker exec -it $your_container bash # bash, or sh

docker run your_container (with all common options you were using with the official image)
