### ISSUE TITLE
Portus UI not showing pushed images

### ISSUE THREAD

**Issue by pashah96** [SUSE/Portus#2172]
i have installed the latest stable version but still not able to see the pushed docker images on the dashboard.

**Comment by pasikarkkainen** [comment]
@pashah96 so what version exactly are you using?

**Comment by pashah96** [comment]
Portus Version 2.4.2
Operating system centos 7

**Comment by pasikarkkainen** [comment]
OK. Latest Portus version is 2.4.3.

**Comment by pashah96** [comment]
Tried that also just

**Comment by mssola** [comment]
How have you deployed this? This usually happens if you missed to run the `background` container. See the documentation page on how to deploy portus [here](http://port.us.org/docs/deploy.html) for more info.

**Comment by TechCatOther** [comment]
In 2.4 it's ok when background work freezing or stuck. Restating help to fix it.

**Comment by RSWilli** [comment]
I had the same problem with Portus, but after checking the logs of the registry, I found out that it was not able to reach Portus' /v2/webhooks/events endpoint, which was falsely configured by myself.

I reconfigured the env variable REGISTRY_NOTIFICATIONS_ENDPOINTS to use the correct address and that fixed it
