### ISSUE TITLE
Error: container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by verwilst** [SUSE/Portus#2176]
### Description

Check out the `CONTRIBUTING.md` file for some considerations before submitting a
new issue.

### Steps to reproduce

1. Start container on Kubernetes cluster with PodSecurityPolicies enabled.
2. Fails to start with error

- **Expected behavior**: Pod in running state
- **Actual behavior**: Pod in failed state with error: "Error: container has runAsNonRoot and image will run as root"

**Portus version**: 2.4.3

Can be fixed be adding a USER variable to your Dockerfile.

**Comment by verwilst** [comment]
After starting the container as non-root, i'm getting this:

```
Generating RSA private key, 3072 bit long modulus
........................................................................................................................++++
................................................................................................++++
unable to write 'random state'
e is 65537 (0x010001)
p11-kit: couldn't create file: /var/lib/ca-certificates/java-cacerts: Permission denied
p11-kit: couldn't make directory writable: /var/lib/ca-certificates/openssl: Operation not permitted
p11-kit: couldn't make directory writable: /var/lib/ca-certificates/pem: Operation not permitted
Died at /usr/lib/ca-certificates/update.d/80etc_ssl.run line 87.
/usr/lib/ca-certificates/update.d/99certbundle.run: line 21: /var/lib/ca-certificates/ca-bundle.pem.new: Permission denied
Waiting for mariadb to be ready in 5 seconds
```

**Comment by mssola** [comment]
Running Portus in rootless mode is something pending to be done. That's certainly something we'd want to have implemented. Thanks for the heads up!

**Comment by verwilst** [comment]
I'm currently creating a Helm chart for github.com/helm/charts based on your own Helm chart. Instead of implementing the docker-registry, nginx, ... myself, i've ripped that stuff out and worked with external dependencies. I can have a podsecuritypolicy in place for now that allows running as root, but I would rather see the actual issue fixed. Is there anything I can do to help? Maybe we can collaborate on how we can fix this and I might find some time to implement it?

**Comment by mssola** [comment]
> I'm currently creating a Helm chart for github.com/helm/charts based on your own Helm chart. Instead of implementing the docker-registry, nginx, ... myself, i've ripped that stuff out and worked with external dependencies.

Oh, that's really nice! Are you doing this in the open? As in, is there any repo I can check to see the development of it?

> I can have a podsecuritypolicy in place for now that allows running as root, but I would rather see the actual issue fixed. Is there anything I can do to help? Maybe we can collaborate on how we can fix this and I might find some time to implement it?

Yeah. For now just set a podsecuritypolicy allowing root until we get this fixed. I'd say that the way to go from this side would be, first of all, to understand what's exactly requiring root right now. After that, we may be able to polish the image so it no longer requires root. This can be done in small and independent pull requests and, when we're done, I'll write an integration test that checks that root is never required. I will try to allocate some time to work on this as well, but if you already have some ideas, pull requests are always welcome :smile: 

Thanks for bringing this up!

**Comment by verwilst** [comment]
I've just pushed my changes to https://github.com/verwilst/charts/tree/feature/portus/stable/portus .
They're nowhere from being useful though at the moment. :-)

**Comment by verwilst** [comment]
I think update-ca-certificates is the culprit for now. Is this really needed? I guess being able to specify your own ca cert should be enough?

**Comment by mssola** [comment]
> I think update-ca-certificates is the culprit for now. Is this really needed? I guess being able to specify your own ca cert should be enough?

Yeah. When you do it though, remember to update documentation (as in, examples and so on)

**Comment by verwilst** [comment]
Can we talk on Slack? Maybe kubernetes.slack.com?

**Comment by verwilst** [comment]
bump
