### ISSUE TITLE
denied: requested access to the resource is denied after pushing images 

### ISSUE THREAD

**Issue by hamzajoundan** [SUSE/Portus#2178]
Hello every one , 
I have a valid certificat for my domaine 172.17.0.1 , Otherwise i get this problem by login into it
"" Error response from daemon: Get https://172.17.0.1:5000/v2/: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Acme, Inc.") ""
I did another domaine called repo.test and it login successfully 
The probleme i Have it when i Push my images into portus :
So i have create a namespace which i called "demo" and i did this : 
--> docker tag hello-world repo.test.local/demo/hello-world
--> docker push repo.test.local/demo/hello-world 
and here is the result i got : ________
The push refers to repository [repo.test.local/demo/hello-world]
af0b15c8625b: Preparing 
denied: requested access to the resource is denied
__________________
I have tried the same thing with : 
--> docker tag hello-world repo.test.local/demo:hello-world
--> docker push repo.test.local/demo:hello-world 
And I had the same problem : 
The push refers to repository [repo.test.local/demo]
af0b15c8625b: Preparing 
denied: requested access to the resource is denied
__________________________________________________
the namespace "demo" is public and it's owned by the administrator 
Can you please help me with that ?

**Comment by vlakshmi70** [comment]
can you share how your config for TLS - docker-compose.yml file, how you generated your key, crt and rootcertbundle, registry/config.yml file and registry/init file and nginx.conf file.
Thanks
