### ISSUE TITLE
Exec /init permission denied when starting container

### ISSUE THREAD

**Issue by mdeboer** [SUSE/Portus#2200]
I upgraded porter using Docker and I now get the following exception:
`starting container process caused "exec: \"/init\": permission denied"`

Docker image used (SHA256): `b276b17f9b65a98ede4cb609f8336ab16482e401a8938db3f5003124420089b7` which is tagged as `opensuse/portus:2.5` and `opensuse/portus:latest`.

I see it hasn't been released either so why tag this with a version or even latest when this isn't stable? 

Version `2.4.3` works fine.

**Comment by bretep** [comment]
I'm also getting this after upgrading

**Comment by invy** [comment]
The same for me. ./init script is lacking executable permission.

**Comment by stefankip** [comment]
Same here, reverted to head.

**Comment by invy** [comment]
> 
> 
> Same here, reverted to head.

FYI: workaround would be to specify the command in your deploy/compose file to call a chmod +x /init first and then the init itself.

**Comment by stefankip** [comment]
Thanks, but for me it's much easier to just revert to head ;-)

**Comment by bretep** [comment]
Yeah, I ended up reverting as well. If the fix is that easy, why not fix it and release again?

**Comment by mdeboer** [comment]
> Yeah, I ended up reverting as well. If the fix is that easy, why not fix it and release again?

Because it's unclear why it occurred as apparently the Dockerfile is fine:

> The same for me. ./init script is lacking executable permission. (Updated to the version tagget 2.5)
> Strangely enough, the Dockerfile contains the line:
> 
> https://github.com/SUSE/Portus/blob/a1b9f2ebfeb84680a9dcd5629195e4c52815735c/docker/Dockerfile#L8
> 
> Or was the image built from other Dockerfile...

However I agree, this should be fixed asap by untagging 2.5 and reverting the latest tag to 2.4.3. I also see no mention anywhere of 2.5 so I think it was unintended to be released already.

**Comment by dkowis** [comment]
Still an actual problem. I guess the tag never got reverted?

**Comment by harmeetsinghghotra** [comment]
Here's how I fixed it:

1) Create a Dockerfile with the following content:

FROM opensuse/portus:2.5
RUN chmod +x /init

2) Built a new docker image with:

docker build . -t opensuse/portus:2.5.1

That's it!

**Comment by tienthanh2509** [comment]
I am workaround by change `entrypoint` from `/init` to `/bin/sh /init` temporary without rebuild 

```yaml
services:
  portus:
    image: opensuse/portus:2.5
    env_file:
      - config/portus.env
    entrypoint:
      - /bin/sh
      - /init
```

**Comment by kovetskiy** [comment]
still appears to be not solved

**Comment by SuperSandro2000** [comment]
@kovetskiy

**Comment by jimmybrancaccio** [comment]
I can confirm this is still not resolved, however using [workaround suggested here](https://github.com/SUSE/Portus/issues/2200#issuecomment-548207473) does get things going.

**Comment by Jean-Baptiste-Lasselle** [comment]
### Successfully repaired `opensuse/portus:2.5` OCI container image

Hi @mdeboer @bretep @invy @stefankip @dkowis   This time it's done, I have a solution to use, all details https://github.com/SUSE/Portus/issues/2241#issuecomment-593370789

:)

I will read any feedback from you with interest

**Comment by Persi** [comment]
This is still an issue with Imagetag 2.5.

**Comment by pciavald** [comment]
this issue still exists...

**Comment by 9-9-9-9** [comment]
Almost 2 years and still no one cares about fixing this

**Comment by tienthanh2509** [comment]
Suggest replacing Portus with Habor, since this project seems to be inactive.

https://landscape.cncf.io/card-mode?category=container-registry&grouping=category&selected=harbor

**Comment by mdeboer** [comment]
+1 for Harbor, works perfectly

**Comment by teksturi** [comment]
Still exits.
