### ISSUE TITLE
Add database indexes

### ISSUE THREAD

**Issue by stefankip** [SUSE/Portus#2202]
I'm running the docker-compose example. My current config is available here: https://gist.github.com/stefankip/82e2e9908feeb5d045420671df1970b6

I added phpMyAdmin because the database is seriously hogging resources. Disk read was constantly at 10MB/s.
Via phpMyAdmin I was able to find out a query was running for a long time, updating the registry_events table, with an event_id in the WHERE clause. FYI this table has over 200.000 records in my case. The set-up is an existing docker registry volume, attached to the registry container from the docker-compose example.
So I added an index for this column, which already helped a lot:

![image](https://user-images.githubusercontent.com/46313552/58456578-d8f12980-8124-11e9-96a1-a8939b4bf12a.png)

But as you can see, the server is still under quite some load. Only when I stop the portus and background containers, the server calms down again.

While writing this, the server did calm down though. Weird stuff.

Anyhow; I guess my point is to add more indexes to the database?

**Comment by stefankip** [comment]
That would be a shame... 👎

**Comment by riker09** [comment]
In my case the table `registry_events` has more than half a million records and this is affecting the overall performance of the server. I will try adding and index and see if that fixes the problem.

**Comment by riker09** [comment]
I'm sorry to inform you that I'm not using Portus anymore. I had added the index as stated above and as far as I can recall I haven't had performance issues after that.

**Comment by stefankip** [comment]
So it seems it is a minor change with a very positive result. It would be nice if someone from the Portus team could look at this issue.

**Comment by stefankip** [comment]
@mssola ping :-)

**Comment by SuperSandro2000** [comment]
I am having the same problem using postgres and I am worried about my drives with this constant load on my disk for no apparent reason. This even happened after I swiped my registry completely empty and set the sync strategy to ``on-start``. Disk usages never ends.

**Comment by stefankip** [comment]
I think I'm going to install a stale bot for the issue tracker where clients of mine create their bug reports. So I don't have to do anything with those reports, just let the stale bot take care of them, then it's like the bugs never even existed! 👎

**Comment by SuperSandro2000** [comment]
Bump

**Comment by stefankip** [comment]
Just let it go. This project is dead...
