### ISSUE TITLE
Activity messages still do not fill all the horizontal space available

### ISSUE THREAD

**Issue by stefankip** [SUSE/Portus#2205]
In relation to #487; the activity messages get cut off way too early.
Example:
![image](https://user-images.githubusercontent.com/46313552/58935151-e03fb500-876c-11e9-85e7-f7e16a7f644d.png)
There is so much space left, and the most important part of the activity message (the last part with tag name) gets cut off.
I'm not sure why there's a `max-width` defined on this line: https://github.com/SUSE/Portus/blob/debd26eaaf2353ae609948492d232ef78bd37b24/app/assets/stylesheets/components/activities.scss#L48

**Comment by stefankip** [comment]
That would be too easy ;-)

**Comment by stefankip** [comment]
Remove stale please :-)

**Comment by SuperSandro2000** [comment]
bump

**Comment by stefankip** [comment]
I'll give up, close this thing and nobody should care.
