### ISSUE TITLE
Using Project JIB to deploy works, but doesn't show up in the UI

### ISSUE THREAD

**Issue by danny2394** [SUSE/Portus#2212]
### Description

I am using an SSL enabled Portus installation using the examples directory with clair-SSL.
In a Maven project I am using Project JiB to build Docker images and push to the private registry.

When I push via mvn compile jib:build, it shows as successfully pushed to Portus and if I try pulling on another machine, I do get the correct image, which means the registry did get the new pushed image.

If I push via docker push ... command, Portus does show it on the UI

**Portus version**: 2.4.3@5a616c0ef860567df5700708256f42505cdb995

**Comment by RjEcho217** [comment]
How did you get SSL to work on portus? My backend doesnt seem to want to use a Self signed cert nor a CA from our domain controller.... very frustrating.

**Comment by danny2394** [comment]
I am using the Nginx to handle the SSL, however I am using publicly trusted certificates. I am not sure if Portus verifies certificates and hence the self-signed ones aren't working.

**Comment by RjEcho217** [comment]
Yeah our internal network doesnt want to pay for one right now while we test if portus will work for us. Ive placed it everywhere I can find the CA certs should go, to no avail. THe front end website works but the backend keeps failing and registry saying they cannot verify. Just curious, did you simply place it in the secrets folder? Or?

**Comment by danny2394** [comment]
I will let you know as soon as I get in to work

**Comment by danny2394** [comment]
I left the actual certificates in the root home directory, and in the secrets folder I do have Portus certificates to work with the backend and also authorize registry but as far as I can remember these are self-signed

**Comment by danny2394** [comment]
This is not fixed
