### ISSUE TITLE
Fix the style for the "Access Denied" page

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#222]
It currently looks like this:

![wave2](https://cloud.githubusercontent.com/assets/767943/8621374/7683ae88-2725-11e5-9b04-a5afac83ebb4.png)

**Comment by cyntss** [comment]
![image](https://cloud.githubusercontent.com/assets/5013096/10459575/7a03b418-71d0-11e5-9941-6780df07cf10.png)

This screen is for the 401 at the moment. We should now take the template generated at views/errors/show.html.erb and generate the ones for the "Access denied" as well as for 404 or 500 errors.

@mssola how do you wanna proceed with this? should you create the templates (from the above mentioned) joining my branch https://github.com/SUSE/Portus/commits/ui-second-iteration and then I make the changes for all the rest of errors?

**Comment by flavio** [comment]
@cyntss nice!

**Comment by cyntss** [comment]
:smiley: thanks @flavio

**Comment by mssola** [comment]
@cyntss this looks really cool! :clap: Now, both the 404 and the 500 errors are available as bare html in the public directory. The access denied page needs some changes because right now it just renders text... I'm going to work on that asap so you have the "Access Denied" page available.

The page on errors/show.html.erb is handled differently, but if you take a look at that, it's just an html page without layout, so you can modify it just like you do with static pages. If you want to take a look at the errors/show.html.erb with proper values, I can show you how to modify the code in portus to fake an error.

And I think that's all.

**Comment by cyntss** [comment]
@mssola that is exactly what I mentioned you in my comment above, the screen I uploaded is what is implemented in the file views/errors/show.html.erb

Please review my commit: https://github.com/SUSE/Portus/commit/d6f42efdc6663ac70d1c5a511193bdb18f7aae84

What I asked you to do is to please use the error template I created from at errors/show.html.erb and create the file for the "access denied" page so I just need to make a small customisation into it.

Thanks for pointing out where the 404 and other error files are located. I found them and will apply the template I made ;)

Please let me know when you can create the page for the Access Denied, if you can join my branch will be easier.
