### ISSUE TITLE
Users can no longer log in, getting an error from an internal IP

### ISSUE THREAD

**Issue by stevenmcastano** [SUSE/Portus#2227]
when I try to execute a `docker login portus.mycompany.com` I'm getting a stranger error message where it seems like it's trying to connect to an internal host. It worked before, but I can't seem to find anything in the configurations that would make this change.

This is the response I get:

```
Username: test.user
Password:
Error response from daemon: Get https://portus.mycompany.com/v2/: Get https://172.17.0.1/v2/token?account=test.user&client_id=docker&offline_token=true&service=172.17.0.1: dial tcp 172.17.0.1:443: connect: connection refused
```

It also won't let me push images anymore.

**Comment by dreadkopp** [comment]
same here

**Comment by AngelSan19** [comment]
how to resolve this issue?
