### ISSUE TITLE
A bot doesn't update the Portus UI (a non-bot user does)

### ISSUE THREAD

**Issue by bertoost** [SUSE/Portus#2229]
### Description

I love the idea of a bot user, which can not login via the web UI. I am using for my CI/CD for example. Very useful.
Therefor I found a weird issue with that...
When my CI/CD pushes a newer image to my private registry, it succeeds correctly and the image is pushed.
But the UI of Portus is not showing the newer image and the timestamps are not updated as well.
When I do the same but then as user, built and pushed from my machine it is working perfectly.

### Steps to reproduce

1. Create a new user
2. Remove the default token, created a new one
3. Configured the user/token as credentials in my CI (Jenkins)
4. Start a job to update image
5. New image successfully pushed to my registry
6. Portus doesn't show it

**Comment by SuperSandro2000** [comment]
Bump

**Comment by bertoost** [comment]
This was due problems in the webhook configuration. It works with a bot user now too
