### ISSUE TITLE
LDAP doesn't get integrated with Portus while running in container

### ISSUE THREAD

**Issue by amirakhan** [SUSE/Portus#2231]
### Description

I have implemented Portus to monitor our docker container images and would like to integrate OpenLDAP however I did changes in config.yml as per the documentation and did restart Portus container from Portainer however I am unable to see the LDAP login page.
I did follow all the documentation and issues raised for LDAP on Github however did not receive much help
Would appreciate if someone can help me here.

**Configuration**:
ldap:
	enable: true

hostname: 10.106.199.89
port: 389

method: "plain"

base: "ou=project1,dc=project,dc=com"

filter: ""

uid: "uid"

authentication:
	enable: true
	bind_dn: "cn=admin,dc=project,dc=com"
	password: "Project"

You can get this information like this:

- In bare metal execute: `bundle exec rake portus:info`.
- In a container:
  - Using the development `docker-compose.yml` file: `docker exec -it <container-id> bundle exec rake portus:info`.

WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.8.0
rake aborted!
Psych::SyntaxError: (/portus/config/config.yml): could not find expected ':' while scanning a simple key at line 110 column 1
/portus/lib/portus/config.rb:15:in `fetch'
/portus/config/initializers/config.rb:4:in `<top (required)>'
/portus/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => portus:info => environment
(See full trace by running task with --trace)

  - Using the [production image](https://hub.docker.com/r/opensuse/portus/): `docker exec -it <container-id> portusctl exec rake portus:info`.

OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"portusctl\": executable file not found in $PATH": unknown

```yml
CONFIG HERE
```

**Portus version**: with commit if possible. You can get this info too with the
above commands.
Portus 2.9.1

**Comment by amirakhan** [comment]
Can someone from Portus help us here please? i am still stuck with an issue.

**Comment by matiasmagallanes** [comment]
Hi, @amirakhan in your configuration you are using "enable" and the correct keyword is "enabled".
Change it and test again.
