### ISSUE TITLE
Docker image tag 2.4 and 2.4.3 do not match...

### ISSUE THREAD

**Issue by ArcticSnowman** [SUSE/Portus#2235]
Docker image tag `2.4` and `2.4.3` do not match...

Surely `2.4` tagged image should match the latest sub-version `2.4.3`?

Or was there a 2.4.4 release made but not tagged in github?

**Comment by xfh** [comment]
I made the same assumption and was confused by the different image digests.

Even worse, the `latest` tag points to a 2.5 DEV version, where as the [README](https://github.com/SUSE/Portus/blob/master/README.md#portus) clearly states at the top:

> Last stable release: 2.4.3 (2.4, 2.4.3 and latest tags from the official Docker image)
