### ISSUE TITLE
[Portus 2.5] automatic creation of unknown namespaces after the first start

### ISSUE THREAD

**Issue by SpeedBlack** [SUSE/Portus#2237]
Hello,

I use portus version 2.5 (HEAD tag).
By reading the following issue: [https://github.com/SUSE/Portus/issues/1961](https://github.com/SUSE/Portus/issues/1961), I thought that namespaces could be created automatically if they didn't exist.
This is true when first initializing Portus with an existing registry.

But I thought it was possible after the first start.
If I push an image into a unknown namespaces, it won't automatically be detected in portus (as an administrator user).
Do you think this is normal behavior or will I have a configuration problem ?

Thanks.

**Comment by Jean-Baptiste-Lasselle** [comment]
@SpeedBlack I am about to automate the same thing, but I will automate namespaces creation using Portus' `REST API`, not by executing a `docker push mydock.somecompany.io:5000/somenamespace/myapp:0.1.2`, where `somenamespace` is the namespace you wwant to create. 

Plus I like the fact that namespaces won't be created if  i just mistyped the namespace while tagging an image , etc... Yeah, really like that.
  
What do you think?

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @SpeedBlack You will find here : https://github.com/SUSE/Portus/issues/2244#issuecomment-584889394   a complete example, tested for portus `2.4.3` (should work with docker image `2.5` as well as `2.4.3`), showing how to completely automate, "silently", namespace creation .

Please confirm as soon as possible, If you would agree on closing this issue, or report here any bug with the code sample I provided on https://github.com/SUSE/Portus/issues/2244#issuecomment-584889394

**Comment by SpeedBlack** [comment]
Hi @Jean-Baptiste-Lasselle,

You can close this issue.
Thank you for that explanation (I'm using another solution now. Portus didn't meet my needs).

Thanks,
Best regards
Romain

**Comment by Jean-Baptiste-Lasselle** [comment]
> Hi @Jean-Baptiste-Lasselle,
> 
> You can close this issue.
> Thank you for that explanation (I'm using another solution now. Portus didn't meet my needs).
> 
> Thanks,
> Best regards
> Romain

Thank you for your closing the issue. Can I ask you which solution you chose instead ? (Harbor?)

**Comment by SpeedBlack** [comment]
Hi @Jean-Baptiste-Lasselle 

Yes, we chose Harbor.

**Comment by Jean-Baptiste-Lasselle** [comment]
> Hi @Jean-Baptiste-Lasselle
> 
> Yes, we chose Harbor.

Hi @SpeedBlack thank you so much for your answer, I currently think a lot about connex matters.
