### ISSUE TITLE
Document resource requirements

### ISSUE THREAD

**Issue by brandonkal** [SUSE/Portus#2245]
It would be helpful if the resource requirements (CPU and RAM) were documented here. I would like to see some guidelines on minimum (i.e. without clair) and recommended resource requirements. This would help in comparing it with Harbor.

Thank you

**Comment by dispensable** [comment]
After struggling two days to deploy Portus I give up. Such little features with nearly 3k commits and 1k issues and still can not make this thing work. The container start with a db init says index length lager than 767 bytes, OK, I set the database to latin1 for index create. Then when I set background process I got utf8-bin collations error and the only solution is use specific command run maria db and dorp the database we use to recreate it ....
So tired with this project, bye.

**Comment by Jean-Baptiste-Lasselle** [comment]
> After struggling two days to deploy Portus I give up. Such little features with nearly 3k commits and 1k issues and still can not make this thing work. The container start with a db init says index length lager than 767 bytes, OK, I set the database to latin1 for index create. Then when I set background process I got utf8-bin collations error and the only solution is use specific command run maria db and dorp the database we use to recreate it ....
> So tired with this project, bye.

Hi @dispensable ,I agree portus is not easy, I currently work on it with others from Community.

One question though : Have you compared the price of a Harbor Licence, or a Redhat Licence (to get  quay.io up n running), with the price of days of work ? 

On my side, I worked more than 30 full days on it, and it still is worth. 

And that's regardless of the fact that I do, have access to source code with Portus, and don't, with other similar proprietary solutions.

**Comment by Jean-Baptiste-Lasselle** [comment]
> on

Idea : set up some loadtests and generate test reports on each release.

**Comment by brandonkal** [comment]
I despise the stale bot.
