### ISSUE TITLE
LdapErr post success LDAP BInding

### ISSUE THREAD

**Issue by lu9cbl** [SUSE/Portus#2247]
i'm having a problem with validate the portus credentials, with AD. 

I'm made a capture with TCPdump and saw these sequence:
1) TCP handshake it's correct.
2) Bindrequest Success.
3) Bind response success.
4) Search request and searchResEntry success.
4) when it's made the user validation, appears and error that says "000004DC: LdapErr: DSID-0C090A4C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839"
5) finish the TCP connection with a FIN/ACK as normal behavior.

Apparently the error was that are not using the binding previous stablished. Has someone a troubleshooting for that?
Thanks a lot.
Mati

**Comment by matiasmagallanes** [comment]
I have the same issue. With Portus 2.5 (and 2.4 too) and Active Directory (Domain Functional Level 2016)

**Comment by SuperSandro2000** [comment]
spam

**Comment by lu9cbl** [comment]
spam???? wtf?

**Comment by SuperSandro2000** [comment]
@lu9cbl I am just reacting to @stalebot which just causes way to much spam on GitHub or closes/stales important issues.

**Comment by SuperSandro2000** [comment]
Bump
