### ISSUE TITLE
Synchronise beetween register and portus UI

### ISSUE THREAD

**Issue by mbellahcene** [SUSE/Portus#2270]
i push alpine images
     - ok for register
     - ok for portus UI

i push ( my build images with Dockerfile )
-------------------------------------------------------
FROM docker

RUN apk add --no-cache --upgrade bash jq git

---------------------------------------------------------------
docker build --no-cache --pull -t docker/docker.dind .
docker tag docker/docker.dind srvportus:5000/docker/docker.dind

--  > KO for UI    -> ok for registry

i push docker
docker tag docker srvportus:5000/docker/
ok for registry  ok for UI

could you help me please

**Comment by kylegoetz** [comment]
see my solution here https://github.com/SUSE/Portus/issues/2275

**Comment by Jean-Baptiste-Lasselle** [comment]
@mbellahcene docker-compose.yml ? .env ? other conf files (`registry.yml`, `nginx.conf` etc...) ?
