### ISSUE TITLE
Portus service not starting for postgres yml

### ISSUE THREAD

**Issue by siyar420** [SUSE/Portus#2272]
### Description
bash cannot find init.rb. I guess fix is to use `bundle exec rails runner /srv/Portus/examples/development/compose/init.rb` 

To reproduce this fix #2271 first.

### Steps to reproduce

1. cp examples/postgresql/docker-compose.yml docker-compose.postgres.yml
2. docker-compose -f docker-compose.postgres.yml up

- **Expected behavior**: All services starting
- **Actual behavior**: portus service not starting

`Attaching to portus_db_1, portus_portus_1, portus_webpack_1, portus_registry_1
portus_1    | bash: /srv/Portus/examples/development/compose/init: No such file or directory
db_1        | 
db_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1        | 
db_1        | 2020-01-13 12:49:12.686 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2020-01-13 12:49:12.686 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2020-01-13 12:49:12.692 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2020-01-13 12:49:12.712 UTC [20] LOG:  database system was shut down at 2020-01-13 12:47:55 UTC
db_1        | 2020-01-13 12:49:12.719 UTC [1] LOG:  database system is ready to accept connections
portus_portus_1 exited with code 127`

### Deployment information

**Deployment method**: With docker-compose.postgres.yml at the repo root.

**Configuration**:

- In a container:
  - Using the development `docker-compose.postgres.yml ` 

**Portus version**: #2228

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @siyar420 :+1:  
* justnoticing I didn't find any `docker-compose.postgres.yml` at root of this repo... 
* https://github.com/SUSE/Portus/tree/master/examples/development/postgresql   ? `PORTUS_DB_ADAPTER` ?
