### ISSUE TITLE
In example docker compose, how does "background" talk to the registry?

### ISSUE THREAD

**Issue by kylegoetz** [SUSE/Portus#2275]
I am running a docker compose very similar to the example with the DB, portus, portus-in-background, and the registry (plus adminer).

The images I push to the registry succeed, but the Portus UI never reflects the changes. If I log in to the DB with adminer, I can see the images in the `registry_events` table.

As per the compose file, `registry` hits the `portus` container with the webhooks. This explains how the events are showing up in the DB. (And the correct namespace exists in Portus that matches the container's namespace when pushed to the registry.)

My understanding is that you only get the updates if you are running the `background` process, which ensures the synchronization of registry and DB+Portus.

I am running `background` as well. However, looking at the compose structure, `background` depends on `portus`, but nowhere is `portus` configured to know about `background`'s existence or URL (which would be `http(s)://background:3000` as `nginx` does not have any mention of `background` in the config you have for it).

Moreover, `background` has nothing configured in it to know how to communicate with `registry`. It depends on the database and portus, but no mention of registry, so how does it ensure the database is synced with the registry?

Is the docker-compose.yml file not set up correctly? Or am I missing something?

**Comment by kylegoetz** [comment]
Well, the answer appears to be that I needed to put in my `docker-compose.yml` file under `background.environment`:

```yml
# Sync config
- PORTUS_BACKGROUND_REGISTRY_ENABLED=true
- PORTUS_BACKGROUND_SYNC_ENABLED=true
- PORTUS_BACKGROUND_SYNC_STRATEGY=update
```

Looks like Portus will only sync with the registry when you first create the containers, but never after that, unless you configure `background` to sync regularly, which the above does.

I suggest this be added to the example, or an explanation given as to why this is missing, as I can't imagine why anyone would only ever want to import a registry's data on first creation rather than keeping it synced going forward. Is the example just for a read-only demo and no read-write demo?

**Comment by Jean-Baptiste-Lasselle** [comment]
> unless

Hi @kylegoetz Thank you so much for your issue : 
* I am currently probably like you, working on building up a real production ready Portus / OCI image registry 
* It is the first time I hear about those configuration variables, though I spent days and hours  across portus docuementation.Iforexample, found a proper way to generated (and rotate) the value of `PORTUS_SECRET_KEY_BASE`, and it was thrilling, but oh my god, when I think of what was said about that n the doc (almost zero, not even the rotate verb or rotation word), cf. [this doc page](http://port.us.org/docs/deploy.html#docker), you Ctrl + F `PORTUS_SECRET_KEY_BASE`....  
* So I am not surprised to learn a new critical aspect of portus, especially important ! . Here worth mentioning, and **why I thank you so much**, is that your point will greatly help me also unveil the [Garbage Collection process](https://github.com/SUSE/Portus/issues/2241#issuecomment-565951218), extremely important for production environments. 

I do agree with you, on your point, support your request, and there is a real need for even more...

**Comment by Jean-Baptiste-Lasselle** [comment]
@kylegoetz honesly, look at https://github.com/SUSE/Portus/issues/2241#issuecomment-586653023  it's crazy :laughing: :rocket:  (biiiiiiig thank you)

**Comment by Jean-Baptiste-Lasselle** [comment]
@kylegoetz about : 

> 
>  why anyone would only ever want to import a registry's data on first creation rather than keeping it synced going forward.
> 

Actually, this is the best business case ever : 
* You already have a registry full of many images
* and you want to keep it all, you just want to switch from `harbor` to `portus`.
* Another thank you cause that's one of the most important business case I wanted to fully automate.
* And.... I don't see any rather, between importing an existing registry, and continuously sync . Actually if I imported first,I certainly want to keep it all in sync,don't you?

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @kylegoetz I want today give more info, interesting  : 

* I assumed, given what you were reporting, that the `SYNC` feature of protus, is disabled by default, so it has to be activated.
* Well it turns out that it's quite the opposite, see https://github.com/SUSE/Portus/issues/2281#issuecomment-587154193

So when you explicitly set your variables, well it did... nothing. So I now even more think that you solved your problem by accident, not by setting those variables you talked about.   

I am really interested in any future tests results you'll feedback here.

And I think I can say now, that I characterized a problem with portus documentation, thansk to your issue, see. : https://github.com/SUSE/Portus/issues/2241#issuecomment-586972528
