### ISSUE TITLE
Portus's UI is wrong timezone

### ISSUE THREAD

**Issue by bienkma** [SUSE/Portus#2292]
I have been using docker for deploying Portus (registry:2.7.1, opensuse/portus:2.4.3). When I pushed an image to Portus and see on Web dashboard I got an invalidating event in the timezone. It's not a system time zone on the container. How can I setting the timezone for the web UI dashboard?

**Comment by bienkma** [comment]
I solved my problem. The Protus get timezone on TZ environment. 
old: docker run -d --name=portus -v /etc/localtime:/etc/localtime:ro opensuse/portus:2.4.3
change to new: docker run -d --name=portus -e "TZ=Asia/Ho_Chi_Minh" opensuse/portus:2.4.3

**Comment by Jean-Baptiste-Lasselle** [comment]
@bienkma thx 4 sharing
