### ISSUE TITLE
Error repo - Docker-compose fails with missing repo error

### ISSUE THREAD

**Issue by zhurkin** [SUSE/Portus#2298]
when "docker-compose" up version 2.5 / 2.4 (git clone --branch v2.5 https://github.com/SUSE/Portus.git or git clone --branch v245 https://github.com/SUSE/Portus.git)

 gets an error

**2.4**

Building repository 'The Go Programming Language (openSUSE_Leap_42.3)' cache [....done]
Retrieving repository 'ruby' metadata [.error]
Repository 'ruby' is invalid.
[ruby|https://download.opensuse.org/repositories/devel:/languages:/ruby/openSUSE_Leap_42.3] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ruby' because of the above error.
Some of the repositories have not been refreshed because of an error.

**in 2.5, there is also**

Retrieving repository 'The Go Programming Language (openSUSE_Leap_15.0)' metadata [.Repository 'devel:tools' is invalid.
[devel:tools|https://download.opensuse.org/repositories/devel:/tools/openSUSE_Leap_15.0/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'devel:tools' because of the above error.

**if you click on the url**

https://download.opensuse.org/repositories/devel:/languages:/ruby/openSUSE_Leap_42.3
https://download.opensuse.org/repositories/devel:/tools/openSUSE_Leap_15.0

**that will be the answer:**

Resource is no longer available!
The requested URL is no longer available on this server and there is no forwarding address. If you followed a link from a foreign page, please contact the author of this page.

If you think this is a server error, please contact the webmaster.

Error 404
download.opensuse.org
Apache/2.4.33 (Linux/SUSE)

**CentOS Linux release 7.7.1908**

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**or**

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-109.gitcccb291.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      cccb291/1.13.1
 Built:           Tue Mar  3 17:21:24 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-109.gitcccb291.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      cccb291/1.13.1
 Built:           Tue Mar  3 17:21:24 2020
 OS/Arch:         linux/amd64
 Experimental:    false

**or**

 **Ubuntu 18.04.3 LTS** 

 Docker version 18.09.7, build 2d0083d
docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false

![3](https://user-images.githubusercontent.com/3272056/80156047-a2898c00-85cb-11ea-812e-c7259973603e.JPG)

**Comment by hemna** [comment]
I get the same errors when running docker-compose up on master or v2.5 branches.

```
Retrieving repository 'devel:tools' metadata [.error]
Repository 'devel:tools' is invalid.
[devel:tools|https://download.opensuse.org/repositories/devel:/tools/openSUSE_Leap_15.0/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'devel:tools' because of the above error.
```

and

```
Retrieving repository 'ruby' metadata [.error]
Repository 'ruby' is invalid.
[ruby|https://download.opensuse.org/repositories/devel:/languages:/ruby/openSUSE_Leap_15.0] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'ruby' because of the above error.
Some of the repositories have not been refreshed because of an error.
```

**Comment by munnaeebd** [comment]
repo 15.0 is not working . I have added and changed the following lines

~~~
vi Dockerfile

RUN sed -i 's/15.0/15.1/g' /etc/zypp/repos.d/*
RUN zypper addrepo https://download.opensuse.org/repositories/devel:/languages:/ruby/openSUSE_Leap_15.1/devel:languages:ruby.repo && \
    zypper addrepo https://download.opensuse.org/repositories/devel:/tools/openSUSE_Leap_15.1/ devel:tools &&
~~~


I am not sure if all the problem is solved or not. installation is going on.

**Comment by Jean-Baptiste-Lasselle** [comment]
> I get the same errors when running docker-compose up on master or v2.5 branches.

Hi @hemma : 
* What you are trying to do, many have tried
* And some succeeded, plus lefft  : 
  * the solution for all issues you are dealing with, one after the other :  https://github.com/SUSE/Portus/issues/2241#issuecomment-593370789 : 
  * and the sum up of what happened, why and when : https://github.com/SUSE/Portus/issues/2261#issuecomment-612624170
