### ISSUE TITLE
Create systemd unit file for portus-cronos

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#261]
We recently started to use `cronos` to handle some background jobs. We have to ensure the cronos service is started automatically inside of the appliance.

I think the cleanest solution is to create a systemd unit file for that.

Note well: cronos must be started in foreground mode otherwise systemd will have troubles handling it.

@jordimassaguerpla: I can help you with that if you want

**Comment by mssola** [comment]
Also update the wiki when this systemd service file gets created: https://github.com/SUSE/Portus/wiki/Synchronizing-the-Registry-and-Portus (the `TODO` on the bottom of the page)

**Comment by jordimassaguerpla** [comment]
I've started some work in:

https://github.com/jordimassaguerpla/Portus/tree/add_crono_systemd

I still need to properly test it but you can see the idea

**Comment by jordimassaguerpla** [comment]
https://github.com/SUSE/Portus/compare/master...jordimassaguerpla:add_crono_systemd?expand=1

**Comment by jordimassaguerpla** [comment]
adding here the packaging guidelines as a reminder on what I have to review to make it openSUSE compliant

https://en.opensuse.org/openSUSE:Systemd_packaging_guidelines
