### ISSUE TITLE
Storage S3

### ISSUE THREAD

**Issue by berrywira** [SUSE/Portus#284]
Hi There!

How to connect docker-registry-frontend with docker registry storage S3, can I?

**Comment by mssola** [comment]
Maybe I'm not following your question, but you can use whatever version of Docker registry (>= 2.1). Since S3 storage is supported there (see [this](https://github.com/docker/distribution/blob/master/docs/storage-drivers/s3.md)), yes, you can.

**Comment by berrywira** [comment]
Thanks for helping me.
