### ISSUE TITLE
Repository tags are not being created with registry version 2.1.1

### ISSUE THREAD

**Issue by vanga** [SUSE/Portus#285]
I am not sure if there are any breaking changes in 2.1.1 from 2.0.1. 

I just updated the registry version in common-compose.yml to 2.1.1. I don't see repository tags in Portus UI, every thing else being same.

This is the version of Portus https://github.com/SUSE/Portus/commit/f84bc786f4419ca829b8799458510b6b478e57c6 I am using.

**Comment by flavio** [comment]
Sorry for the delay, can you provide us more details about your setup? How are you running portus?

**Comment by vanga** [comment]
I just run compose-setup.sh to get the portus setup Up on an EC2 with Ubuntu. 
Btw, I reverted back to registry 2.0.1 because of https://github.com/SUSE/Portus/issues/300 . 
May be this fixed the issue with tags, Tags are being created now.

**Comment by flavio** [comment]
In the meantime we also fixed the issue with the latest version of distribution.

Closing the issue, but feel free to reopen if you have other troubles.
