### ISSUE TITLE
Teams with capital letters in their name cannot be created

### ISSUE THREAD

**Issue by kwk** [SUSE/Portus#295]
I want to create a team with a capital letter in the name.

When you try to create a team, let's say `QA`, you can do so in the Teams menu. The Team shows up in the table below. There's no error reported whatsoever.

But once you leave the team page and come back, the team `QA` is gone.

The same is true for terms like `Quality`, or `Quality Assurance`, but NOT for `quality assurance`.

There should be an error message if you break a convention with the names for teams and the team should not be created.

I'm using the 1.0.1 appliance from here: http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/1.0.1/images/PortusAppliance.x86_64.qcow2

**Comment by flavio** [comment]
This is a known issue that has been fixed sometimes ago.

@jordimassaguerpla should have released an updated appliance in the
meantime. Are you sure you are using the latest one?

Of there's no updated appliance you could either download the one based on
"master" or add the OBS repository containing the updated RPM and run a
`zypper up`.

**Comment by jordimassaguerpla** [comment]
The devel images are in http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/images/

and the master repository is in http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/

We'll release a new appliance very soon with the latest code.

**Comment by flavio** [comment]
Closing
