### ISSUE TITLE
health check failed: please see /debug/health

### ISSUE THREAD

**Issue by schmunk42** [SUSE/Portus#306]
I have similar problems, like described in https://github.com/SUSE/Portus/issues/304

Furthermore, even if I set `HOST` manually.
I will receive this error message after ~20 seconds from the registry container:

    {"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}

Where should I check `/debug/health`? I can not find it neither in the `web` nor the `registry` container.

**Comment by flavio** [comment]
Fixed on master.

To apply the fix on a "broken" system:
```
git clean -xf # warning this will remove all the changes made to your local checkout, including untracked files
./compose-setup.sh
```
