### ISSUE TITLE
Use something else for the user icon when gravatar is disabled

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#312]
Right now we are using the one as given by font-awesome. But it's ugly and it doesn't align with the text that is besides it.

**Comment by brycereitano** [comment]
<img width="405" alt="screen shot 2015-10-03 at 20 28 04" src="https://cloud.githubusercontent.com/assets/1928691/10266173/4307bdd4-6a0e-11e5-8ca8-20f97f56ea99.png">

Before I make a pull request on this, here is what I threw together in a few minutes. Does this look good or would you like to get a different image altogether?

**Comment by mssola** [comment]
This looks really good to me, thanks! Also, make sure that this style also applies for activities ;)

**Comment by flavio** [comment]
+1
