### ISSUE TITLE
Flashy messages don't disappear

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#33]
This is a regression that can be reproduced at the master branch. Basically, when you click the cross of a flashy message to make it disappear, it just erases the contents of it but it doesn't disappear. Like this:

![empty](https://cloud.githubusercontent.com/assets/767943/7494721/b2d06d6c-f409-11e4-9c90-04c8d87d99fc.png)

**Comment by flavio** [comment]
This is going to be fixed once I merge the 'UI' branch into master
