### ISSUE TITLE
The sign up link is not visible with the current background 

### ISSUE THREAD

**Issue by eotchi** [SUSE/Portus#35]
Very minor, but not to be forgotten. 
The current colour of the Sign up link blends too much in the current background. 

![screenshot from 2015-05-06 19 14 51](https://cloud.githubusercontent.com/assets/576621/7498890/4235fd40-f424-11e4-82d2-1fc8e0ae78ff.png)

**Comment by mssola** [comment]
Yes, this only happens with the wallpaper-02.jpg file though. To avoid future problems I suggest doing what Twitter does:
![twitter](https://cloud.githubusercontent.com/assets/767943/7511620/85e8a664-f4a6-11e4-9ccd-51b4bee5c9c9.png)
That is, setting a white background to the div containing the form. This way the link will look just fine regardless of the background image being shown. Note that this also applies to the Sign up page.

What do you think?

**Comment by flavio** [comment]
Nice idea. However the whole theme is just temporary. @eotchi is going to talk with one of our designers tomorrow. Let's see what is going to happen.

**Comment by eotchi** [comment]
Indeed. I should have some more insights by next week. Let's put this on hold for now.

**Comment by cyntss** [comment]
this will be fixed with the merge of the branch https://github.com/SUSE/Portus/tree/front-end-fixes

![image](https://cloud.githubusercontent.com/assets/5013096/8091278/27933728-0fb3-11e5-93cc-c64914474395.png)

**Comment by flavio** [comment]
This is gorgeous :)

**Comment by cyntss** [comment]
fixed with merge of front-end-fixes
