### ISSUE TITLE
First user is not admin

### ISSUE THREAD

**Issue by DirkHeinke** [SUSE/Portus#352]
The first user created in the latest portus build (62.6) is created as a normal user even though the configuration file (/srv/Portus/config/config.yml) says:
```
first_user_admin:
  enabled: true
```

It tried to create a user via the second provided way `rake portus:set_admin` but that fails with:
```
rake aborted!
cannot load such file -- bundler/setup
[...]
```

**Comment by jordimassaguerpla** [comment]
for the rake task to work, you need to do:

bundle="/srv/Portus/vendor/bundle/ruby/2.1.0/bin/bundler.ruby2.1"
export GEM_PATH=/srv/Portus/vendor/bundle/ruby/2.1.0/
pushd /srv/Portus
export SKIP_MIGRATION=yes
export RAILS_ENV=production
$bundle exec rake portus:set_admin

I know it sounds complicated, but we are bundling bundler in /srv/Portus/vendor as well as all the other gems.

**Comment by jordimassaguerpla** [comment]
What you mean with build (62.6) ?

**Comment by mssola** [comment]
This sounds a bit weird. Could you provide more info? In particular:

- Are you sure that your DB had no users before signing up ?
- Could you provide the logs ?
- Do you have a config-local.yml file that might override the default config.yml file ? Are you setting up any special environment variable that might override said option ? (in this case `PORTUS_FIRST_USER_ADMIN`)

**Comment by jordimassaguerpla** [comment]
sorry I forgot to mention you also need to set some environment variables. See the config/database.yml for the env variables you have to set up. I know it looks very complicated set up. we are working on making it simpler.

**Comment by DirkHeinke** [comment]
Okay, so here is what I did:
* Download development image from [here](http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/images/PortusAppliance.x86_64.qcow2) which is currently PortusAppliance.x86_64-0.0.9-Build62.6.qcow2
* Convert the image to vdi `qemu-img convert -O vdi PortusAppliance.x86_64-0.0.9-Build62.6.qcow2 PortusApp62.vdi`
* Creat a new VM with the vdi
* Firstboot asks me for the host, domain name and root pw
* (I need to reset the network in the vm, which may be a problem due to the conversion to vdi)
* Add the ip to my `/etc/hosts` with the correct hostname
* Access https://portus.my.domain
* I get redirected to: https://portus.my.domain/users/sign_up
 * At this point I checked the portus_production table: It contains one user with id 1, username portus **this might be the problem? but I did not created that user**
* If I sign up, I'm not administrator

At this point I enabled ssh password login.
Now I executed the command provided by @jordimassaguerpla and
```
export PORTUS_PRODUCTION_USERNAME=root
export PORTUS_PRODUCTION_DATABASE=portus_production
export PORTUS_PRODUCTION_HOST=localhost
$bundle exec rake portus:set_admin[dirk]
```
Which succeeded. So at least I'm admin now.

@mssola Which logs should I provide?

**Comment by jordimassaguerpla** [comment]
great! We didn't know you were using the appliance that is why we got confused with the build number.

You are right, the problem might be there is already a user called portus that is being used for comunication with the docker registry.

**Comment by mssola** [comment]
Gotcha! After some investigation I realized that the Apache config as provided by the appliance overrides the "first_user_admin" value through an environment variable.

Thanks for your patience! We'll fix this as soon as possible.

**Comment by jordimassaguerpla** [comment]
see:

https://github.com/SUSE/Portus/blob/master/packaging/suse/conf/etc.apache2.vhosts.d.portus.conf#L26

PORTUS_FIRST_USER_ADMIN_ENABLED false

So actually the appliance is working as expected.

Sorry the setup is confusing. We are working on making setting this variables in a more intuitive way.

**Comment by mssola** [comment]
This issue has been fixed in the commit 9c32ed9840a2f04d20c856295864b43289402d7f. You have to use the new `portusctl` tool, that already handles this es expected. Feel free to re-open this.

**Comment by DirkHeinke** [comment]
I think, it would be nice to see some notice about that new tool [here](https://github.com/SUSE/Portus/wiki/Configuring-Portus#creating-the-first-admin-user) or at the http introduction page?

At least that's the place where I read about the users, after starting the appliance as described [here](https://github.com/SUSE/Portus/wiki/Installing-Portus#firstboot)

**Comment by mssola** [comment]
@DirkHeinke this tool has been documented [here](https://github.com/SUSE/Portus/wiki/Installing-Portus#initial-setup). Also notice that this tool is still a WIP :)

**Comment by DirkHeinke** [comment]
But that section does not belong to the appliance? So who could you know, that you should use it? ;)

**Comment by jordimassaguerpla** [comment]
Actually in the appliance you shouldn't have to run it because this tool is being called on firstboot.
However, we encountered 2 issues that we just fixed:

https://github.com/SUSE/Portus/commit/7fca4101caafcdbb4185f7b5effb75bcee7ff189
https://github.com/SUSE/Portus/commit/df57209a19e6de86e426cb58670f148ca10bd568

The next build should contain those issues fixed.

Thanks and please report us back any other issue you find.
