### ISSUE TITLE
Add support for for Roles and type of Namespace icons 

### ISSUE THREAD

**Issue by eotchi** [SUSE/Portus#36]
In the current namespaces tab we should display next to each namespace two additional icons
  - a **Role icon**
  - a **Namespace type** icon

A Role icon  represents the role owned by the user on the namespace (owner | collaborator | viewer).

A Namespace type icon can be of two different types, personal or team. 
As a personal namespace is practically speaking a namespace owned by a team composed by only        one person, the distinction should be done on the number of members the team is composed of.

**Comment by flavio** [comment]
I have problems figuring out which icons to use. Could you take a look at [font awesome icons](https://fortawesome.github.io/Font-Awesome/icons/)?

**Comment by flavio** [comment]
What about adding two new columns named "pull" and "push", then we can have checkboxes underneath. That way we just need an icon for the"owner" role.

**Comment by mssola** [comment]
@flavio @eotchi this has already been fixed by #388, no ?

**Comment by flavio** [comment]
Yes indeed.
