### ISSUE TITLE
Introduce "owned by" team in the namespace detailed view

### ISSUE THREAD

**Issue by eotchi** [SUSE/Portus#37]
By clicking on a namespace presented in the namespace tab, the name of the namespace will be presented in the header of the table:

![screenshot from 2015-05-06 19 35 04](https://cloud.githubusercontent.com/assets/576621/7499318/19ef70a2-f427-11e4-9e89-679e386e9b15.png)

This should be accompanied by a "owned by" followed by the name of the team to which the namespace belongs to.
In the best case (and not strictly necessary), for personal namespaces this could be omitted, not to display entries like 
**Namespace federica owned by federica**

**Comment by mssola** [comment]
@cyntss what do you think about this. What's the best way to accomplish this from a UI/UX point of view ?

**Comment by cyntss** [comment]
Fixed in: ec757f349257ba6b4e6101ea6f8502e7ae3ef072
