### ISSUE TITLE
use docker link

### ISSUE THREAD

**Issue by jas99** [SUSE/Portus#370]
I noticed the project has to be build for now to use it. It will be great if you can do docker compose of prebuild images. I think the project will be very popular that way. I have just started looking into it but don't seem to have access to info about environment variables or may it is; will be goings through docs and sources and will follow with with query if required.

Thx 4 awesome project did i mension :)

**Comment by mssola** [comment]
Hi @jas99, thanks for the interest. This is a topic in which we haven't made a decision yet. We'll keep it in mind.

**Comment by jas99** [comment]
@mssola thx for reply. 
Best of luck with ur independence struggle :+1:

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.

**Comment by jas99** [comment]
@mssola 
Cool!! 
I have been using gitlab for my docker image storage lately; just for feedback.
Thx
