### ISSUE TITLE
LDAP: allow the admin to provide a filter for users

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#379]
A user filter can be provided to constrain the search of users in an LDAP server. This should be easy to achieve with the [Net::LDAP::Filter](http://www.rubydoc.info/gems/ruby-net-ldap/Net/LDAP/Filter) class.

**Comment by dohnto** [comment]
Just to note, the current situation where user is search via `uid` is not general enough. For example in our company, we use `sAMAccountName` for the same purpose and `uid` is missing.
