### ISSUE TITLE
compose-setup.sh breaks when DOCKER_HOST is set to tcp://192.168.99.100:2376

### ISSUE THREAD

**Issue by bartdorsey** [SUSE/Portus#382]
I'm running on OS X and the docker-machine env command outputs the DOCKER_HOST variable in this format:

`tcp://192.168.99.100:2376`

This causes the shell script entry.sh to fail the sed check and never start the registry. 

After fixing entry.sh when I try to login to the registry I get this error:

```
Error response from daemon: no successful auth challenge for http://192.168.99.100:5000/v2/ - errors: [Get http://tcp://192.168.99.100:2376:3000/v2/token?account=bdorsey&service=tcp%3A%2F%2F192.168.99.100%3A2376%3A5000: dial tcp: unknown port tcp/]
```
This also looks like it's being caused by the DOCKER_HOST environment variable being of the tcp:// format.

**Comment by mssola** [comment]
Hi @bartdorsey, with the commit e2b6e1d9f6d698c6c3dd376258509a657b944d7c everything should work for you. Could you try it ? :)

**Comment by mssola** [comment]
Closing this because it has already been fixed. If this is not the case, please re-open this issue.
