### ISSUE TITLE
Use  typeahead  when adding users to a team

### ISSUE THREAD

**Issue by eotchi** [SUSE/Portus#39]
Improve the usability of adding a user to a team. 
Typeahead or similar (*) should be introduced so to suggest a list of valid users matching the current input of the user.

(*) https://twitter.github.io/typeahead.js/examples/

**Comment by flavio** [comment]
On issue #103 @mssola proposed the usage of [chosen](http://harvesthq.github.io/chosen/).

What do you (@mssola) think about typeahead?

**Comment by mssola** [comment]
@flavio I have no preference between any of the proposed solutions. `Chosen` was the one that @cyntss suggested me. So... I don't know :D

**Comment by flavio** [comment]
I'll let you and @cyntss figure out what to use. I have no preference either.

**Comment by brycereitano** [comment]
I was thinking about his feature, but should a non-admin be able to see a list of users? The type-ahead would expose that.

**Comment by flavio** [comment]
Yes that's true, but I don't see that as a big security issue. Do you? Sites like github are doing the same thing; also organizations have already shared addressbooks containing this information...

**Comment by brycereitano** [comment]
I do not, but I thought I would bring it up.

Would you mind if I pick up this issue?

**Comment by flavio** [comment]
Sure, go ahead! :)

**Comment by mssola** [comment]
Note that this also should apply to team names in the "Create namespace" form inside of the namespaces page.
