### ISSUE TITLE
JQuery Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by brycereitano** [SUSE/Portus#391]
On the create new admin page, JQuery is throwing an error. This is on a new instance, using `compose-setup.sh`. This only seems to be happening on the create new admin page.

[Stacktrace](https://gist.github.com/brycereitano/8f835b85b20b786faba2)

<img width="1109" alt="screen shot 2015-10-05 at 09 08 21" src="https://cloud.githubusercontent.com/assets/1928691/10284404/17fb2124-6b41-11e5-9da2-b6b8c5266164.png">

**Comment by mssola** [comment]
Thanks for reporting! This should have been fixed now :)
