### ISSUE TITLE
Exception: uninitialized constant Net::HTTP

### ISSUE THREAD

**Issue by travisghansen** [SUSE/Portus#395]
Running the command:

RAILS_ENV=production CATALOG_CRON="10.minutes" bundle exec crono

in the environment manually results in this problem.

**Comment by travisghansen** [comment]
Just got this as well:

I, [2015-10-06T15:27:20.604927 #10]  INFO -- : Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v1+json", "size"=>45971, ...}
I, [2015-10-06T15:27:20.605039 #10]  INFO -- : Reason: uninitialized constant Net::HTTP

**Comment by mssola** [comment]
I cannot seem to reproduce this. Which ruby version are you using? Could you also paste your Gemfile.lock file, just in case? Thanks.

**Comment by travisghansen** [comment]
@mssola I'm using ruby 2.0.0p598 (2014-11-13) [x86_64-linux] from the epel repository for centos 7.

Running commit 7254dcd697d36186bd1768bd1d52b84fe08abb4a ATM

All of this is running inside a container which I can I can send the Dockerfile if you'd like..

**Comment by travisghansen** [comment]
As an FYI I did hack the client file and manually added:
require 'net\http'

At which point things started working.  I'm not a ruby dev so I'm sure I added it in the 'wrong' spot so didn't bother creating a patch..
