### ISSUE TITLE
auth fails

### ISSUE THREAD

**Issue by jameseck** [SUSE/Portus#396]
Hi,

I'm trying to run portus on a CentOS 7 VM.
I'm using the docker compose method to spin the 3 containers up, but I'm unable to authenticate.

If I try to "docker login" the client gets the  following error:

```
Error response from daemon: no successful auth challenge for http://docker:5000/v2/ - errors: [token auth attempt for registry http://docker:5000/v2/: http://192.168.1.35:3000/v2/token?account=james&service=192.168.1.35%3A5000 request failed with status: 401 Unauthorized]
```

The registry shows the below log message.

```
registry_1 | time="2015-10-06T20:06:22Z" level=warning msg="error authorizing context: authorization token required" http.request.host="docker:5000" http.request.id=bfde14ca-13a3-4332-bfa9-090690022369 http.request.method=GET http.request.remoteaddr="192.168.1.35:58651" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.14.1.el7.x86_64 os/linux arch/amd64" instance.id=cdf7bec5-5f02-4b01-91c0-2ef4d8c85973 version=v2.1.1 
```

Any further requests are met with 503 errors from the registry until I restart the container.

```
registry_1 | 192.168.1.35 - - [06/Oct/2015:20:12:51 +0000] "GET /v2/ HTTP/1.1" 503 125 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.14.1.el7.x86_64 os/linux arch/amd64"
registry_1 | 192.168.1.35 - - [06/Oct/2015:20:12:51 +0000] "GET /v1/_ping HTTP/1.1" 503 125 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.14.1.el7.x86_64 os/linux arch/amd64"
registry_1 | 192.168.1.35 - - [06/Oct/2015:20:12:51 +0000] "POST /v1/users/ HTTP/1.1" 503 125 "" "docker/1.7.1 go/go1.4.2 kernel/3.10.0-229.14.1.el7.x86_64 os/linux arch/amd64"
```

I'm sure it's something obvious but I can't see it for looking.

Any help will be greatly appreciated.

J

**Comment by dohnto** [comment]
Check output of this command:

user=james
password= # your password, note that it should not be production password, use this just for testing

curl -ik --user $user:$password  http://192.168.1.35:3000/v2/token?account=james\&service=192.168.1.35:5000

This should succeed, I suppose that this returns a 401 for you, check the error message. Did you created a admin user via Portus website http://192.168.1.35:3000/ ? Do you use the same credentials?

**Comment by jameseck** [comment]
Hi,

Thanks for the reply.

That command does indeed return 401 for me.

I have created an admin user for portus and I'm trying to auth with that
admin user.  Should I create a separate user?

J

**Comment by dukas** [comment]
Same problem here, both for appliance and zypper added Portus
My setup on rpm-added machine:
* Installed with zypper
from: 
http://download.opensuse.org/repositories/Virtualization:/containers/openSUSE_13.2/
http://download.opensuse.org/repositories/Virtualization:/containers:/Portus/openSUSE_13.2/
using:
```bash
zypper in portus docker docker-distribution-registry
```
* Configs and database generated with:
```bash
portusctl setup --local-registry
```
* Admin user added over webinterface
* Config for registry:
```bash
cat /etc/registry/config.yml 
```
```yaml
version: 0.1
loglevel: info
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /etc/apache2/ssl.crt/portus.domain.dom-server.crt
    key: /etc/apache2/ssl.key/portus.domain.dom-server.key

auth:
  token:
    realm: https://portus.domain.dom/v2/token
    service: portus.domain.dom:5000
    issuer: portus.domain.dom
    rootcertbundle: /etc/apache2/ssl.crt/portus.domain.dom-ca.crt

notifications:
  endpoints:
    - name: portus
      url: https://portus.office.dom/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

* Auth:
```bash
docker login -u none -e none@none.com portus.domain.dom:5000
```
* Docker answer:
```bash
Password: 
Error response from daemon: no successful auth challenge for https://portus.domain.dom:5000/v2/ - errors: [token auth attempt for registry https://portus.domain.dom:5000/v2/: https://portus.domain.dom/v2/token?account=none&service=portus.domain.dom%3A5000 request failed with status: 401 Unauthorized]
```
*  Registry log:
```bash
Oct 07 12:45:30 portus registry[14248]: time="2015-10-07T12:45:30Z" level=warning msg="error authorizing context: authorization token required" http.request.host="portus.domain.dom:5000" http.request.id=d4050496-6e8c-4edc-a303-1bf3057c6420 http.request.method=GET http.request.remoteaddr="172.18.1.101:46941" http.request.uri="/v2/" http.request.useragent="docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.1.6-3-desktop os/linux arch/amd64" instance.id=eb68f714-0db3-4bb1-9a85-9a6b50feeb2c version="v2.1.1+unknown"
Oct 07 12:45:30 portus registry[14248]: 172.18.1.101 - - [07/Oct/2015:12:45:30 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.1.6-3-desktop os/linux arch/amd64"
```
* Portus log:
```bash
I, [2015-10-07T12:45:30.993532 #3384]  INFO -- : Started GET "/v2/token?account=none&service=portus.domain.dom%3A5000" for 172.18.1.101 at 2015-10-07 12:45:30 +0000
I, [2015-10-07T12:45:30.994982 #3384]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2015-10-07T12:45:30.995071 #3384]  INFO -- :   Parameters: {"account"=>"none", "service"=>"portus.domain.dom:5000"}
I, [2015-10-07T12:45:31.106932 #3384]  INFO -- : Completed 401 Unauthorized in 112ms (ActiveRecord: 4.0ms)
```
* Mysql table users:
```mysql
MariaDB [portus_production]> select * from users\G
*************************** 1. row ***************************
                    id: 1
              username: portus
                 email: portus@portus.com
    encrypted_password: $2a$10$eGlvVoya6gsQx8nu1R/4buxzuy3hiYCjUP/eVymRx93KBXgXu7QxS
  reset_password_token: NULL
reset_password_sent_at: NULL
   remember_created_at: NULL
         sign_in_count: 0
    current_sign_in_at: NULL
       last_sign_in_at: NULL
    current_sign_in_ip: NULL
       last_sign_in_ip: NULL
            created_at: 2015-10-07 09:51:05
            updated_at: 2015-10-07 12:44:56
                 admin: 1
               enabled: 1
             ldap_name: NULL
       failed_attempts: 2
             locked_at: NULL
*************************** 2. row ***************************
                    id: 2
              username: none
                 email: none@none.com
    encrypted_password: <hash_here>
  reset_password_token: NULL
reset_password_sent_at: NULL
   remember_created_at: NULL
         sign_in_count: 16
    current_sign_in_at: 2015-10-07 12:45:31
       last_sign_in_at: 2015-10-07 12:45:20
    current_sign_in_ip: 172.18.1.101
       last_sign_in_ip: 172.18.1.101
            created_at: 2015-10-07 09:51:55
            updated_at: 2015-10-07 12:45:31
                 admin: 1
               enabled: 1
             ldap_name: NULL
       failed_attempts: 0
             locked_at: NULL
2 rows in set (0.00 sec)
```

**Comment by jameseck** [comment]
I've just tried again by doing a git pull so I'm using the latest master branch.  I've nuked the docker containers and started over.
Now after I create my admin account, I can't link to the registry.  The gui just returns "no registry found" when I submit the registry details.

If you need any further detail, please let me know what to provide.

Thanks
J

**Comment by dukas** [comment]
Found answer in [#408](https://github.com/SUSE/Portus/issues/408)

**Comment by mssola** [comment]
@jameseck sorry for the delay. The "no registry found" was a regression that we had, sorry about that...

**Comment by jameseck** [comment]
Hi,

Many thanks for the update.

I'm unfortunately still having problems.  It probably doesn't help that I'm very new to docker.

Let me explain what I've done today.
I've destroyed all containers and images on my CentOS 7 VM and reset my git dir to the latest master branch on your repo.
I've run the compose-setup.sh and I have 4 containers running.

[root@docker portus]# docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                              NAMES
8f0b0a6f396a        portus_web          "/usr/bin/supervisor   10 minutes ago      Up 10 minutes       3000/tcp                           portus_crono_1      
7c3d4e012c2b        registry:2.1.1      "/registry/entry.sh"   10 minutes ago      Up 10 minutes       0.0.0.0:5000-5001->5000-5001/tcp   portus_registry_1   
8a5f5de9d638        portus_web          "puma -b tcp://0.0.0   10 minutes ago      Up 10 minutes       0.0.0.0:3000->3000/tcp             portus_web_1        
ff057e9fcdc9        mariadb             "/docker-entrypoint.   14 minutes ago      Up 10 minutes       3306/tcp                           portus_db_1      

I've created an admin user in the web ui and tried to add the registry running inside the other container.
I tried a bunch of different entries for the registry and only found one that worked.  172.17.0.26:5000.  Specifying the hostname of the VM didn't work, even though the portus_web container could resolve the name, it couldn't connect on port 5000.

After entering 172.17.0.26:5000 in the registry box, I get the following error:

Error: registry does not implement v2 of the API. You can skip this check by clicking on the "Skip remote checks" checkbox.

A curl to the registry from portus_web or the VM returns the following error:

oot@8f0b0a6f396a:/portus# curl 172.17.0.26:5000             
{"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}
root@8f0b0a6f396a:/portus# 


I have no idea how to debug what is causing this error.
Are you perhaps able to replicate this on a vanilla CentOS 7 VM?
It seems odd that I'm having issues with mine unless there is some incompatibility with this on EL7.

I really appreciate any assistance you can give me and I would really love to get Portus up and running to test with.  I think it would be a fantastic fit for the company I work with.  We are also frustrated with the limitations of the docker registry and although we have only just started using Docker, we would love to utilise it more and that really relies on having the docker registry secured.

Many thanks

J

**Comment by mssola** [comment]
Hi @jameseck, note that the registry's proper hostname:port combination is stated in the end of the `compose-setup.sh` script.  It should say something like:

```
2 - Add a new registry: choose a custom name, enter $ip:$port as hostname
```

Now, your error is a bit weird :_) Perform:

```
$ docker-compose logs
```

Attach here your logs. Also, to be completely sure that you are starting from scratch:

- Kill all the containers, and remove the `portus_web` image.
- Remove the `docker/environment` and `docker/registry/config.yml` files.

And then execute `compose-setup.sh` again.

**Comment by wolfch** [comment]
Today, I did a git pull, removed the portus containers, ran "docker-compose build" followed by "./compose-setup.sh", then via web UI, added and admin user and when I try to get an auth token, I am getting 401.  This was working a few days ago.

GET http://9.26.164.124:3000/v2/token?service=9.26.164.124%3A5000&scope=registry%3Acatalog%3A*
Accept: application/json
Authorization: Basic Y3dvbGY6cGFzc3dvcmQK
Username: cwolf

 -- response --
401 Unauthorized
X-Frame-Options:  SAMEORIGIN
X-XSS-Protection:  1; mode=block
x-content-type-options:  nosniff
Content-Type:  application/json
Cache-Control:  no-cache
Set-Cookie:  _portus_session=OGpSZzFPaE5Kb3FjNGwxOGJwMU9KVW9tZTExaW9laFo3ZHIxMUlXMFRFdXk0MUtDYlZQcGF0N1RReXM3bm9mWXVndmsycFBqVFNaN0h1bXZ4ZndFOUE9PS0tVjZ5N1NZSkZaZ2dCRXBheFl2Njc3QT09--9a069f7cc618485750199a142827e228abd4f134; path=/; HttpOnly
X-Request-Id:  e64d5083-8c41-403b-8d58-761c1517eaad
X-Runtime:  0.117759
Transfer-Encoding:  chunked

Any ideas?  Thanks

**Comment by flavio** [comment]
Make sure the clocks are synchronized between all the machines

**Comment by wolfch** [comment]
It's not working even when the client is on the same machine as Portus/registry.  I just removed all images/containers and deleted the source, did a "git clone" from scratch and re-ran "compose-setup.sh", re-created the admin user, re-registered the registry and still getting 401 even when trying to get a token from a curl session on the same host as Portus/registry. It was all working last week.

**Comment by flavio** [comment]
Are you using docker 1.9 experimental?

Can you please attach the contents of `logs/development.log`? Have you also took a look at the logs of the registry?

**Comment by wolfch** [comment]
bash-4.1# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64

19a9d50e40ae        library/registry:2.1.1   "/registry/entry.sh"   5 hours ago         Up 5 hours          0.0.0.0:5000-5001->5000-5001/tcp   portus_registry_1

..then in the log/development.log I noticed:

SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = '172.17.42.1:5000' LIMIT 1^[[0m
Denied access on these grounds: Cannot find registry 172.17.42.1:5000
Completed 401 Unauthorized in 105ms (ActiveRecord: 10.2ms)
Exception: Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x007f14581cf728>

but yet, in the Portus GUI it's listed as the fully-qualified host name which resolves to the IP of the host - that 172.17.42.1 is the internal IP (inside the container).  Let me get the log...

**Comment by wolfch** [comment]
The log is now 650MB, so I just attached the last few lines.

When I tried to attached the log, I get:
"Attaching documents requires write permission to this repository. Try again with a PNG, GIF, or JPG."

Note that in addition to having the wrong IP for the registry, there is another, unrelated MySQL error:

Mysql2::Error: Data too long for column 'log' at row 1: UPDATE `crono_jobs` SET `last_performed_at` = '2015-10-21 18:16:29', `log` = 'I, [2015-10-21T12:25:32.676745 #21]  INFO -- : Perform CatalogJob\n...(this string repeated about 20 or 30 times before closing single quote)

I renamed the log as "development_tail_log.jpg" - but obviously, it just a text file - that trick seemed to have worked because I was able to wget it back from the link below.

![development_tail_log](https://cloud.githubusercontent.com/assets/555451/10646462/34085630-7801-11e5-9ced-f65e3577a6e0.jpg)

**Comment by wolfch** [comment]
I hate to be a pest, but is there any update on this issue? Thanks.

**Comment by mssola** [comment]
@wolfch don't be afraid to ping us when an issue seems stalled ;) Now, unfortunately I think that we're facing yet another duplicate of [this](https://github.com/SUSE/Portus/labels/docker-compose). That is, our docker-compose setup is quite broken. I've been busy with other stuff, so I didn't have time to look into it, but I'll try to fix this as soon as possible (hopefully tomorrow). Sorry for any inconvenience.

**Comment by wolfch** [comment]
Ok, I wasn't sure, thanks for getting back to me...

**Comment by kedare** [comment]
Any news about this ? I have exactly the same issue.

**Comment by mssola** [comment]
Hi @kedare, I [started](https://github.com/SUSE/Portus/pull/581) to improve our docker-compose setup, but unfortunately more pressing issues came up and I couldn't fix all the issues we're having in this setup. I'll try to fix this whenever I have the time. Sorry for the inconvenience.

**Comment by guzhifeng** [comment]
Hi, I have exactly the same issue. Hope some solutions...

**Comment by testzlx** [comment]
me too.

**Comment by cyphar** [comment]
I believe this is fixed in #618. Can you try applying it and see if it fixed your problem?

**Comment by cyphar** [comment]
Can you please post which version of `docker-compose` you are using (`docker-compose --version`)?

**Comment by wolfch** [comment]
Hello, I have docker-compose 1.5.1.

**Comment by cyphar** [comment]
@wolfch There's a bug in `docker-compose` 1.5.1 which results in the `docker-compose.yml` not being parsed properly. This results in auth issues. If you update to 1.5.2, this no longer happens (and it may solve your problem).

**Comment by wolfch** [comment]
@cyphar Thanks for the advice.  Other then registry V2 auth issues, are you aware of other issues with 1.5.1?  I ask because it's already being used by a number of people here who are only using registry V1.

**Comment by cyphar** [comment]
Well, the issue with 1.5.1 is that the `DOCKER_HOST` environment variable isn't properly set in the `portus_registry_1` container. So the auto-generation script for `/registry/config.yml` results in the realm and domain being incorrect.

This will result in all authorization attempts failing (and I'm fairly sure they'll fail for any version of the registry, as Portus will deny access in all cases, because the registry is asking for an invalid realm).

**Comment by wolfch** [comment]
Ok, thanks for the additional details!

**Comment by jcrombez** [comment]
Upgrading to docker-compose 1.5.2 didn't fix the problem for me.

**Comment by cyphar** [comment]
@jcrombez: Can you post the logs from the registry as well as (if possible) logs from the Docker server running in Debug mode (`docker daemon --debug=true`)? Please also attach your registry config (and mention what ports your setup are using).

**Comment by jcrombez** [comment]
```
time="2015-12-08T13:06:49Z" level=debug msg="authorizing request" http.request.host="172.17.0.1:5000" http.request.id=c1819742-0230-4af3-a1e0-7d77c2d6c901 http.request.method=GET http.request.remoteaddr="172.17.0.1:43619" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-37-generic os/linux arch/amd64" instance.id=90b2c4ba-ef7d-4472-92f9-8dfabd5c9148 version=v2.1.1 
time="2015-12-08T13:06:49Z" level=warning msg="error authorizing context: authorization token required" http.request.host="172.17.0.1:5000" http.request.id=c1819742-0230-4af3-a1e0-7d77c2d6c901 http.request.method=GET http.request.remoteaddr="172.17.0.1:43619" http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-37-generic os/linux arch/amd64" instance.id=90b2c4ba-ef7d-4472-92f9-8dfabd5c9148 version=v2.1.1 
172.17.0.1 - - [08/Dec/2015:13:06:48 +0000] "GET /v2/ HTTP/1.1" 401 114 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.19.0-37-generic os/linux arch/amd64"
time="2015-12-08T13:06:51Z" level=debug msg="filesystem.List(\"/\")" instance.id=90b2c4ba-ef7d-4472-92f9-8dfabd5c9148 trace.duration=85.879µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=8a2e23a7-cfae-43aa-8c36-93d26301d761 trace.line=123 version=v2.1.1
```

I use composer-setup.sh, and didn't change anything in the configuration.

```yaml
version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /registry_data
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
auth:
  token:
    realm: http://:3000/v2/token
    service: :5000
    issuer: portus.test.lan
    rootcertbundle: /registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://web:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

I can't set my docker host in debug mod for now, i'll try later if it's not enough.

**Comment by jcrombez** [comment]
Ok nevermind, i think config.yml was generated with docker-compose 1.5.1, and when i removed all my containers and recreated it with 1.5.2, the file already existed and was not regenerated. I deleted it, recreated my containers, and it works.

```yaml
version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /registry_data
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
auth:
  token:
    realm: http://172.17.0.1:3000/v2/token
    service: 172.17.0.1:5000
    issuer: portus.test.lan
    rootcertbundle: /registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://web:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

**Comment by cyphar** [comment]
@jcrombez FWIW, yes it's because of the fact that `docker-compose` 1.5.1 will generate a `config.yml` that has incorrect auth realm options (specifically you'll see the following):

```
    realm: http://:3000/v2/token
    service: :5000
```

If you tried to run Portus using `docker-compose` 1.5.1 in the past, you should probably delete `docker/registry/config.yml` and let Portus regenerate it.

**Comment by jcrombez** [comment]
Why can we use the "web" alias in the "notifications.endpoints.url" part of the configuration but we have to use the docker host ip in the "auth.token.realm" ?

I tried using it but : 

```
Error response from daemon: no successful auth challenge for http://172.17.0.1:5000/v2/ - errors: [Get http://web:3000/v2/token?account=jeremy&service=172.17.0.1%3A5000: dial tcp: lookup web: no such host]
```

**Comment by cyphar** [comment]
@jcrombez Because the docker client doesn't resolve `web` to `$DOCKER_HOST`. It doesn't need to be the IP, it needs to be the FQDN or IP which the Docker daemon will use to communicate with Portus and the registry.

**Comment by jcrombez** [comment]
Oh right, i though it was used by the registry directly, but if it's the client who do the auth request, it makes sense that web is not working. Thanks.

**Comment by mateusvtt** [comment]
I got a bug when I was trying to authenticate remotely. I was able to authenticate via "docker login" only if it was on the same host which Portus was installed via docker-compose.

On the same host (registry server):
```
root@portus:~/Portus$ docker login <mypublicip>:5000
Username : user
Password:
Email:  
WARNING: login credentials saved in /home/user/.docker/config.json
Login Succeeded
```
On the other host (some docker-client), I got this bug:
```
root@docker-client:/home/myuser# docker login <mypublicip>:5000 
Username: user
Password: 
Email: 
Error response from daemon: no successful auth challenge for http://<mypublicip>:5000/v2/ - errors: [Get http://172.17.42.1:3000/v2/token?account=user&service=172.17.42.1%3A5000: dial tcp 172.17.42.1:3000: no route to host]
```
172  is a private network of Portus host, so there is no route to it, of course.
172.17.42.1 is the  docker0's interface IP, which is read by **compose-setup.sh** and stored in the **docker/environment** file:
 ```
DOCKER_HOST=172.17.42.1
```
Docker_Host variable is used to build the **docker/registry/config.yml**.
I tried to replace the private IP from config.yml to my public ip:
```
auth:
  token:
#  realm: http://172.17.42.1:3000/v2/token
#  service: 172.17.42.1:5000
    realm: http://200.137.64.154:3000/v2/token
    service: 200.137.64.154:5000
    issuer: portus.test.lan
    rootcertbundle: /registry/portus.crt
```
Also I had to change my hostname via web to <mypublicip>:5000, contrary to what the installation guide said:
```
  2. You will be redirected to a page where you have to register the registry. In this form:
    - Choose a custom name for the registry.
    - Enter 172.17.42.1:5000 as the hostname.
```
Now I am able to login/push/pull to Portus/registry remotely.
I am not sure if this a really bug, or if I was doing something wrong.

**Comment by cyphar** [comment]
@mateusvtt If you explicitly set `DOCKER_HOST=<external ip>` `docker-compose` should work out of the box with your use-case. The issue is that the default is to use the internal IP, but that's really the best we can do for the general case. Although this probably should be documented better. /cc @flavio @mssola

**Comment by mssola** [comment]
I've added documentation in regards to the `DOCKER_HOST` environment variable: https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment#remote-host.

**Comment by mssola** [comment]
Seems that by upgrading to docker-compose 1.5.2 and with some of the fixes available in v2 and master, this issue has been fixed.

/ping @jameseck @wolfch @kedare @guzhifeng @testzlx @dukas. Could you [cleanup your environment](https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment#changing-the-host) and try again ? This issue should be fixed by now.

**Comment by cyphar** [comment]
I'm closing this for now. If it turns out that the issues are still reproducible after taking the above steps, feel free to reopen this with additional information.

/cc @jameseck @wolfch @kedare @guzhifeng @testzlx @dukas
