### ISSUE TITLE
Invalid namespace name - too short

### ISSUE THREAD

**Issue by dohnto** [SUSE/Portus#397]
Hi, I was able to create a namespace `a` via Portus website. However the docker does not support such a short namespace: 

`Invalid namespace name (a). Cannot be fewer than 2 or more than 255 characters.`

Is this a wanted feature or bug?

**Comment by flavio** [comment]
Docker has rules about namespaces, image names and tags. Portus' follows these rules. So it's a feature.

**Comment by dohnto** [comment]
Hm, If you follow docker rules, then how is this possible? You can then have a namespace in Portus but none can create any repo inside, because docker (1. 7. 1) does not allow you that.

**Comment by flavio** [comment]
Oh no, sorry... I misread your initial comment. It also looks like Docker changed the rules for the name..

This is bug on our side.

**Comment by dohnto** [comment]
Will you fix it or shall I dig in? :)

**Comment by flavio** [comment]
Feel free to dig into it :)

**Comment by mssola** [comment]
@dohnto I can push a repo inside of a namespace named "a" with Docker 1.8.2. I'm investigating when did this change occur.

**Comment by dohnto** [comment]
@mssola hm I see, so in that case current behaviour is probably the best and simplest solution.

**Comment by mssola** [comment]
For the tag Docker v.1.7.1, you can find this: https://github.com/docker/docker/blob/786b29d4db80a6175e72b47a794ee044918ba734/registry/config.go#L227. This is no longer the case in docker 1.8. So, current behavior should apply.

**Comment by mssola** [comment]
Note that the naming conventions for namespaces in Portus do not fully match the ones from Docker. That's why I'm opening up the issue #400
