### ISSUE TITLE
The formular for the creation of a namespace or a team constantly disappearing under specific circumstances.

### ISSUE THREAD

**Issue by jloehel** [SUSE/Portus#405]
If a user visits http://example.com:5000/namespaces, then clicks on any namespace and returns to http://example.com:5000/namespaces with the browser back button, the form for the creation will constantly disappear.

![vokoscreen-2015-10-08_13-37-28 avi](https://cloud.githubusercontent.com/assets/2422012/10365253/58591202-6dc2-11e5-8319-66081e2cbfaf.gif)

**Comment by cyntss** [comment]
Fixed in: d85863989cd85092914e4e5f77e8e727e231248a
