### ISSUE TITLE
Cannot create registry 

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#415]
At least with the following parameters, Portus fails when creating a registry:

- name: `Registry`
- hostname: `registry.mssola.cat:5000`
- use_ssl: `true`

**Comment by mssola** [comment]
The error is because when we try to create that registry, a namespace is attempted to be created, which has to pass the following regexp ` [a-z0-9]+(?:[._-][a-z0-9]+)*`. The sanitation of this hostname fails when assigning this hostname as the name for the namespace.

**Comment by gbisheimer** [comment]
I workaround this issue by creating a registry with a valid name like registry.test.lan and then edit the entry to change the hostname
