### ISSUE TITLE
How to specify bind_dn in LDAP configuration

### ISSUE THREAD

**Issue by hannes-brt** [SUSE/Portus#420]
The LDAP configuration has a field for the base_dn, but neither for the bind_dn, nor the binding user's password. How should those be specified?

**Comment by mssola** [comment]
Right now you can't :) See the issue  #378. Right now what you do use to use your login credentials as the authentication method against the LDAP server. I'm already working on this.

**Comment by mssola** [comment]
Hi @hannes-brt, notice that the issue #378 has been finally closed, so your problem should be gone now. If this is not the case, please just re-open this issue.

**Comment by hannes-brt** [comment]
Thanks, @mssola!
