### ISSUE TITLE
portus_web cannot start with volume .:/portus

### ISSUE THREAD

**Issue by depay** [SUSE/Portus#432]
Hi,

i wanna start Portus with ./compose-setup.sh, but it failed. And i found the portus_web container exited with error. Then i remove the volume in docker-compose.yml and it worked.

Another question: since we have add the total dir into docker image on building, why the volume is needed on running?

**Comment by flavio** [comment]
> i wanna start Portus with ./compose-setup.sh, but it failed. And i found the portus_web container exited with error. Then i remove the volume in docker-compose.yml and it worked.

Please provide more details about the failure and your host system. We cannot help you otherwise.

> Another question: since we have add the total dir into docker image on building, why the volume is needed on running?

The compose setup is intended to be used to play with the latest version of Portus or even develop it. Hence we want the latest code to be used by the container.

**Comment by depay** [comment]
@flavio ,thanks...sorry but i finally found selinux making that trouble on my new PC, and i've fixed it...
