### ISSUE TITLE
Protus Error:  ActionView::Template::Error (undefined method `namespace' for nil:NilClass):

### ISSUE THREAD

**Issue by GrantStreetGroup** [SUSE/Portus#443]
While exploring Protus, the following error occured:
```
  Rendered public_activity/repository/_push.html.slim (38.4ms)
  Rendered admin/dashboard/index.html.slim within layouts/application (111.0ms)
Completed 500 Internal Server Error in 133ms (ActiveRecord: 5.6ms)

ActionView::Template::Error (undefined method `namespace' for nil:NilClass):
     8:       .clearfix
     9:         .details
    10:           = "#{activity.owner.username} pushed "
    11:           = link_to activity.trackable.namespace.clean_name, activity.trackable.namespace
    12:           | /
    13:           = link_to "#{activity.trackable.name}:#{activity.recipient.name}", activity.trackable
  app/views/public_activity/repository/_push.html.slim:11:in `_app_views_public_activity_repository__push_html_slim__289445254364775520_70293149306800'
  app/views/admin/dashboard/index.html.slim:70:in `block in _app_views_admin_dashboard_index_html_slim__3885629385063489883_70293526641240'
  app/views/admin/dashboard/index.html.slim:69:in `_app_views_admin_dashboard_index_html_slim__3885629385063489883_70293526641240'


  Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_source.erb (8.3ms)
  Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.1ms)
  Rendered /usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
```

The error occurs in the 'admin' screens

**Comment by mssola** [comment]
Hi @GrantStreetGroup, we need more information. Could you provide the following?

- An explanation of what you did, how can someone reproduce your issue.
- How did you deploy Portus: rpm, docker-compose, vagrant, own setup, etc. ?
- Logs. If you're in development mode, just paste the `log/development.log` file. It might also be useful to provide the `log/crono.log` file and the log of the registry (this last one depends on your setup).
- If possible, could you provide the contents of the DB ?

Thanks!

**Comment by GrantStreetGroup** [comment]
We were running the docker development setup.  Not entirely sure what we were doing. Just testing out pushing stuff to the repo.  Unfortunately the 'development.log' was 10's of Gb and we had to remove it to save space.

I don't have any data as we had to kill off the containers and rebuild the images to continue evaluation.

**Comment by flavio** [comment]
> I don't have any data as we had to kill off the containers and rebuild the images to continue evaluation.

I know that using the compose setup is temping, but this is meant only for development mode. As you can see running that on production can lead to unexpected results (like 10GB of logs). Also the compose setup is not meant to be secure: all the communications between docker client, portus and the docker registry are **not** encrypted. That means your user credentials are sent in plain format over the network.

**Comment by GrantStreetGroup** [comment]
This is a purely development evaluation area..

**Comment by kidhasmoxy** [comment]
Is there a rake job or one shot to fix the issue after it's already happened? I just pulled the latest head last night, but I ran into the issue this morning, and don't want to blow away all activity to get the Admin section back.

**Comment by mssola** [comment]
@kidhasmoxy to be honest, it shouldn't happen... As you can see [here](https://github.com/SUSE/Portus/blob/master/app/views/public_activity/repository/_push.html.slim) we already check now whether it couldn't be found or not. Could you paste the error you're getting ?
