### ISSUE TITLE
Admin: all activities page wrong layout

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#446]
After https://github.com/SUSE/Portus/pull/445 was merged the `admin/activities` has been broken.
![screenshot-portus in da house 2015-10-17 00-56-36](https://cloud.githubusercontent.com/assets/22728/10555079/18c668f2-746a-11e5-8217-d511c41177f7.png)

**Comment by mssola** [comment]
If gravatar support is enabled, this is how it looks:

![error1](https://cloud.githubusercontent.com/assets/767943/10574300/71571f7e-7655-11e5-8c62-542c310de13e.png)

It looks like the views for this page is inconsistent with the rest of the application.

**Comment by cyntss** [comment]
wow..that is strange. I havent seen it before but tomorrow I will take a look at it.

**Comment by cyntss** [comment]
oh now i see it.. that is when you click to "view all". I will fix it asap tomorrow ;)

**Comment by cyntss** [comment]
@flavio I just created the PR to fix this: https://github.com/SUSE/Portus/pull/461

**Comment by mssola** [comment]
Closed with PR #461.
