### ISSUE TITLE
All the pages for the registries should use the same "layout"

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#457]
After the latest UI iteration, we've got the following situation:

New page:
![new](https://cloud.githubusercontent.com/assets/767943/10580684/061d91c8-767f-11e5-90b9-14a722366f08.png)

Edit page:
![edit](https://cloud.githubusercontent.com/assets/767943/10580692/0b3eda18-767f-11e5-9827-c16d56677252.png)

Index page:
![index](https://cloud.githubusercontent.com/assets/767943/10580696/10dcdb28-767f-11e5-9e02-58343f979ba2.png)

As you can see, the new page has its contents inside of a container, while the other preserve the old style. I propose to move both the edit and the index pages to the new style introduced in the new page.

**Comment by flavio** [comment]
+1

**Comment by cyntss** [comment]
Yes, there are many pages that I havent seen. We need to all check if there are more pages without format.

**Comment by cyntss** [comment]
What I need from you people is that you post the location of the file for the sections you find. It is easier for me to find it in the working tree.

**Comment by cyntss** [comment]
I only found those 2 @mssola uploaded, but nothing else, so hopefully that is all. This Issue is fixed with PR https://github.com/SUSE/Portus/pull/462
