### ISSUE TITLE
portusctl: use sha256 to generate certificates

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#458]
Right now it's using sha1, which is not secure enough.

**Comment by jloehel** [comment]
Is it ok, if I modify the bash-script gensslcert temporarily and add the option "default_md  = sha256"?

**Comment by flavio** [comment]
I'm not an expert of the tool we use to generate the certs, but if that works why not? :)

**Comment by mssola** [comment]
Closing because of #1464
