### ISSUE TITLE
How do you setup HTTPs for Portus in a Docker Container...

### ISSUE THREAD

**Issue by GrantStreetGroup** [SUSE/Portus#465]
Any advice on how to turn on https support for Portus in a container?

**Comment by lkoenigsberger** [comment]
+1 
Also can you please provide more information how to build the container and then specify the ENV variables to set up the DB connection? Or do I have to create my own Dockerfile and specify the ENV variables there? Seems to me like this is the way to go, but maybe I'm wrong ;-)

**Comment by mssola** [comment]
Note that docker-compose is meant to be used for development purposes, that's why we haven't setup https in there. Anyways, [here](https://github.com/SUSE/Portus/issues/275#issuecomment-132119468) you can find an example of it.

**Comment by GrantStreetGroup** [comment]
I've decide to go the Nginx route for securing the Portus UI.

**Comment by sshipway** [comment]
If you have a working nginx config, then please post it here.  I've been trying to use an nginx proxy to add SSL to portus, and am unable to do so unless I use port 443 as the port numbers keep being removed.

This is what I've been trying:
````
server {
    listen 443 ssl;
    server_name rancher.container.auckland.ac.nz;
    ssl_certificate     certs/rancher.container.auckland.ac.nz.crt;
    ssl_certificate_key certs/rancher.container.auckland.ac.nz.key;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 8443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://portus:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 900s;
    }
}
````
Then starting with
````
docker run -d --restart=always   --link=portus   --name=portus-ssl \
    -p 8443:443  \
    -v `pwd`/conf.d:/etc/nginx/conf.d  -v `pwd`/certs:/etc/nginx/certs \
    nginx
````

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
