### ISSUE TITLE
Setup requires working dir named `portus` to allow image created use hardcoded value `portus_web` image on docker-compose.yml

### ISSUE THREAD

**Issue by jjperezaguinaga** [SUSE/Portus#469]
While executing `./compose-setup.sh` on a simple docker-enabled machine after just a `git clone`, I got the following error:

```
Pulling crono (portus_web:latest)...
Pulling repository docker.io/library/portus_web
Error: image library/portus_web:latest not found
```

If I do `docker images` I get the following:

```
➜  docker-registry git:(master) docker images
REPOSITORY           TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
dockerregistry_web   latest              4c16c0c6f4ae        About a minute ago   978.5 MB
mariadb              latest              7504612e8279        6 days ago           302.2 MB
registry             2.1.1               7fcb4e2b13fd        8 days ago           220.7 MB
rails                4.2.2               60817b3bf81b        4 months ago         884.7 MB
```

My bet is that the image has a different name, so I'll dig on that.

**Comment by mssola** [comment]
I've cleaned up all the related images and containers, then I've executed `./compose-setup` and everything went fine. Could you provide your docker-compose version, docker version and the logs when executing  `docker-compose logs` ?

**Comment by jjperezaguinaga** [comment]
Sure thing, here's the info.

```
➜  docker-registry git:(master) docker-compose --version
docker-compose version: 1.4.0
➜  docker-registry git:(master) docker --version
Docker version 1.8.1, build d12ea79
```
I'll check if there's an updated version, and I'll also clear up the previous images/containers and try again.

**Comment by jjperezaguinaga** [comment]
Updated all docker toolbox and got the same error.
```
➜  docker-registry git:(master) docker-machine --version
docker-machine version 0.5.0-rc3 (a1e610b)
➜  docker-registry git:(master) docker-compose --version
docker-compose version: 1.5.0rc1
➜  docker-registry git:(master) docker --version
Docker version 1.8.3, build f4bf5c7
```
As additional information, even though it fails, some containers are up:
```
➜  docker-registry git:(master) docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
93528a125402        dockerregistry_web   "puma -b tcp://0.0.0."   7 minutes ago       Up 7 minutes        0.0.0.0:3000->3000/tcp   dockerregistry_web_1
0b3b07b5411e        library/mariadb      "/docker-entrypoint.s"   15 minutes ago      Up 15 minutes       3306/tcp                 dockerregistry_db_1
```
However, if I go to the address I get the following error:
![image](https://cloud.githubusercontent.com/assets/1128312/10661863/daf47708-78b0-11e5-85ad-4ddd7a3966ec.png)

**Comment by mssola** [comment]
Thanks for reporting, I'll take a look at this asap

**Comment by jjperezaguinaga** [comment]
Is the `portus_web` image available? 

```
➜  docker-registry git:(1ea6bef) ✗ docker pull portus_web
Using default tag: latest
Pulling repository docker.io/library/portus_web
Error: image library/portus_web:latest not found
➜  docker-registry git:(1ea6bef) ✗ docker pull library/portus_web
Using default tag: latest
Pulling repository docker.io/library/portus_web
Error: image library/portus_web:latest not found
```

**Comment by mssola** [comment]
@jjperezaguinaga you cannot pull it, because it's being built in this repo. Take a look at the Dockerfile in the root of this project. What's surprising to me is that it's trying to pull it, instead of building it. That's why I'm wondering whether it's an issue from our side or what. I'll investigate this asap.

In the meantime, if you're just setting up Portus for development purposes, or you are just trying it out, maybe you can use the vagrant setup. Sorry about that :_)

**Comment by jjperezaguinaga** [comment]
@mssola I see, let me give a try, thanks for your help :)

**Comment by jjperezaguinaga** [comment]
@mssola I think I know what it is. So when I cloned the repository, I created it inside my own custom named folder (i.e. docker-registry). Since `docker-compose` is building up based on the extended `docker-compose-common.yml` and it goes `..` (see https://github.com/SUSE/Portus/blob/master/docker/compose-common.yml#L2) then it will use the directory name. There's a chance that because your working dir is named `portus` it will build the docker image as `portus_web` and in my case `dockerregistry_web`.

I'm 95% sure this is the cause, so I'm renaming my cwd with portus and should work. If it works, I'll see if I can get a PR that either makes sure the cwd is named portus or that on build we tag the image with the proper name (I think the second option is better). Either way, I'm running the compose script and I'll update again when its done.

**Comment by mssola** [comment]
Thanks for investigating! The second option makes more sense to me :)

**Comment by jjperezaguinaga** [comment]
Yeah, can confirm that the issue was the naming of the working dir. Renaming the issue to reflect actual problem.

**Comment by mssola** [comment]
Cool, thanks for investigating on this :)

**Comment by jjperezaguinaga** [comment]
@mssola Np :) Seems this is an issue with compose that doesn't allow tagging our images on build... see https://github.com/docker/compose/issues/2092 after rabbit holing from https://github.com/docker/compose/issues/541 and https://github.com/docker/compose/pull/457

**Comment by mssola** [comment]
Then we will go for the first solution... Anyways, are you already on it or may I jump on this ? :)

**Comment by mssola** [comment]
@jjperezaguinaga I've created the PR #478, that hopefully addresses this situation.

**Comment by jjperezaguinaga** [comment]
Whoops, was away for 1 day, seems you are already on board and it's already merged, nice!

**Comment by OwenChang** [comment]
The docker-compose.yml.template see: https://github.com/SUSE/Portus/blob/master/compose/docker-compose.yml.template

There is a container called crono, it use portus_web as its image

web:
  build: .
  command: puma -b tcp://0.0.0.0:3000 -w 3
  environment:
    - PORTUS_MACHINE_FQDN_VALUE=EXTERNAL_IP
    - PORTUS_DB_HOST=portus_db_1
  volumes:
    - .:/portus
  ports:
    - 3000:3000
  links:
    - db

crono:
  image: portus_web
  entrypoint: bin/crono
  environment:
    - PORTUS_MACHINE_FQDN=EXTERNAL_IP
    - PORTUS_DB_HOST=portus_db_1
  volumes:
    - .:/portus
  links:
    - db

db:
  image: library/mariadb:10.0.23
  environment:
    MYSQL_ROOT_PASSWORD: portus

registry:
  image: library/registry:2.1.1
  volumes:
    - /registry_data
    - ./compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
    - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
  ports:
    - 5000:5000
    - 5001:5001 # required to access debug service
  links:
    - web
