### ISSUE TITLE
Post installation instructions shows wrong url

### ISSUE THREAD

**Issue by zanbel** [SUSE/Portus#473]
Hey Guys,

This is something minor but thought to let you know.
Installed on mac El Capitan and the instructions displayed after installation are:
Make sure port 3000 and 5000 are open on host tcp://192.168.99.100:2376

Open http://tcp://192.168.99.100:2376:3000 with your browser and perform the following steps:
  1 - Create an admin account
  2 - Add a new registry: choose a custom name, enter tcp://192.168.99.100:2376:5000 as hostname

Perform the following actions on the docker hosts that need to interact with your registry:
 - Ensure the docker daemon is started with the '--insecure-registry tcp://192.168.99.100:2376:5000'
 - Perform the docker login
To authenticate against your registry using the docker cli do:
  docker login -u <portus username> -p <password> -e <email> tcp://192.168.99.100:2376:5000

To push an image to the private registry:
  docker pull busybox
  docker tag busybox tcp://192.168.99.100:2376:5000/<username>busybox
  docker push tcp://192.168.99.100:2376:5000/<username>busybox

This of course doesn't work.
Need to drop the :2376 and tcp://

**Comment by willseward** [comment]
I can confirm this.

```
Open http://tcp://192.168.99.100:2376:3000 with your browser and perform the following steps:
  1 - Create an admin account
  2 - Add a new registry: choose a custom name, enter tcp://192.168.99.100:2376:5000 as hostname

Perform the following actions on the docker hosts that need to interact with your registry:
 - Ensure the docker daemon is started with the '--insecure-registry tcp://192.168.99.100:2376:5000'
 - Perform the docker login
To authenticate against your registry using the docker cli do:
  docker login -u <portus username> -p <password> -e <email> tcp://192.168.99.100:2376:5000

To push an image to the private registry:
  docker pull busybox
  docker tag busybox tcp://192.168.99.100:2376:5000/<username>busybox
  docker push tcp://192.168.99.100:2376:5000/<username>busybox
```
