### ISSUE TITLE
Portus admin dashboard error

### ISSUE THREAD

**Issue by plamer** [SUSE/Portus#476]
Hello,

When I go to `https://portus/admin/dashboard` I get:

    We're sorry, but something went wrong.
    If you are the application owner check the logs for more information.

But I can't see anything in the logs when I go to the page - nothing appears. I'm using `Portus-20150925114852-1.1.x86_64`. Any ideas?

**Comment by mssola** [comment]
Assuming that you have your Portus installation in `/src/Portus`, and that you're running on production, the logs are contained inside of the `log/production.log` file. Moreover, could you give us the version of some of the packages. Particulary, could you paste the output of the following commands ?:

    $ rpm -qi Portus
    $ rpm -qi docker
    $ rpm -qi docker-distribution-registry

Thanks

**Comment by plamer** [comment]
Hey @mssola I've checked the production.log but it only contains lines like this:

    INFO -- : Perform CatalogJob\nI, [2015-10-22T10:50:24.130658 #2854]  INFO -- : Finished CatalogJob in 2.20 seconds\n', `updated_at` = '2015-10-22 10:50:24' WHERE `crono_jobs`.`id` = 1

Nothing when accessing the dashboard. About the versions:

Portus:

    Name        : Portus
    Version     : 20150925114852
    Release     : 1.1
    Architecture: x86_64
    Install Date: Fri 25 Sep 2015 06:56:55 PM UTC
    Group       : System/Management
    Size        : 53524167
    License     : Apache-2.0
    Signature   : RSA/SHA1, Fri 25 Sep 2015 11:57:11 AM UTC, Key ID a193fbb572174fc2
    Source RPM  : Portus-20150925114852-1.1.src.rpm
    Build Date  : Fri 25 Sep 2015 11:56:30 AM UTC
    Build Host  : build82
    Relocations : (not relocatable)
    Vendor      : obs://build.opensuse.org/Virtualization
    URL         : https://github.com/SUSE/Portus
    Summary     : Authorization service and fronted for Docker registry (v2)
    Description :
    Portus targets version 2 of the Docker registry API. It aims to act both as an authoritzation server and as a user interface for the next generation of the Docker registry.


Docker is not installed on this machine.

Docker Registry:

    Name        : docker-distribution-registry
    Version     : 2.1.1
    Release     : 9.1
    Architecture: x86_64
    Install Date: Fri 25 Sep 2015 04:42:33 PM UTC
    Group       : System/Management
    Size        : 12656559
    License     : Apache-2.0
    Signature   : RSA/SHA1, Wed 23 Sep 2015 09:58:01 PM UTC, Key ID a193fbb572174fc2
    Source RPM  : docker-distribution-2.1.1-9.1.src.rpm
    Build Date  : Wed 23 Sep 2015 09:57:38 PM UTC
    Build Host  : cloud118
    Relocations : (not relocatable)
    Vendor      : obs://build.opensuse.org/Virtualization
    URL         : http://www.docker.io
    Summary     : Registry server for Docker
    Description :
    Registry server for Docker (hosting/delivering of repositories and images).
    Distribution: Virtualization:containers / openSUSE_Factory_standard

**Comment by mssola** [comment]
I'm afraid that this is not enough :/ Since you've installed Portus from the rpm, maybe you could update to a newer version (note that we've improved how we log message and what we log, so maybe we get more information this way). Besides that, maybe a DB dump could be useful...

**Comment by bibby** [comment]
I have an error on the admin dashboard using today's master branch.

`undefined method 'namespace' for nil:NilClass`

```
Extracted source (around line #10):
8:      strong
9:        = "#{activity.owner.username} pushed "
10:      = link_to activity.trackable.namespace.clean_name, activity.trackable.namespace
11:      | /
12:      - if activity.recipient.nil?
13:        - if activity.parameters[:tag_name].nil?
```

> Trace of template inclusion: app/views/admin/dashboard/index.html.slim
> 
> Rails.root: /portus
> 
> Application Trace | Framework Trace | Full Trace
> app/views/public_activity/repository/_push.html.slim:10:in
> _app_views_public_activity_repository__push_html_slim__1712567096670256227_70144440636060
> app/views/admin/dashboard/index.html.slim:70:in `block in
> _app_views_admin_dashboard_index_html_slim___1893385324676723056_70144434536340
> app/views/admin/dashboard/index.html.slim:69:in
> _app_views_admin_dashboard_index_html_slim___1893385324676723056_70144434536340

This began after I successfully pushed my first images.

**Comment by mssola** [comment]
@bibby gotcha! This can happen when dangling repos are removed by the catalog job for example. I'm working on it.

**Comment by bibby** [comment]
Works wonderfully now. Thanks!
