### ISSUE TITLE
Typo in hyperlink in installation wiki

### ISSUE THREAD

**Issue by kiambogo** [SUSE/Portus#484]
https://github.com/SUSE/Portus/wiki/Installing-Portus

Under 'Installing the RPM', the link to the Portus release in OpenSuse points to 
`http://software.opensuse/org/package/Portus?search_term=Portus`
and instead should be `http://software.opensuse.org/package/Portus?search_term=Portus`

**Comment by mssola** [comment]
Fixed! Thanks for the tip :)
