### ISSUE TITLE
Switch to PostgreSQL

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#49]
We should use PostgreSQL rather than sqlite.

**Comment by flavio** [comment]
@mssola you mentioned you wanted to tackle this issue. Are you working on that?

**Comment by mssola** [comment]
@flavio Yes, I'll submit a PR as soon as possible ;)

**Comment by flavio** [comment]
Closing, we are going to use MariaDB since it suits our needs and is fully supported on SLE.
