### ISSUE TITLE
How to provide CA certificates to Portus container (for verifying connection to registry)

### ISSUE THREAD

**Issue by JonathonReinhart** [SUSE/Portus#502]
As a follow-on to #498, I'm having trouble figuring out how to provide an additional CA certificate to Portus. So when Portus goes to connect to the registry `/v2/` API, the TLS validation is failing.  As a simple test:

```
jreinhart@docker1 $ docker exec -it registrycompose_web_1 /bin/bash
root@3193559385aa:/portus# curl https://docker-reg.example.com
curl: (60) SSL certificate problem: self signed certificate in certificate chain 
```

I know that normally on a Debian machine, I would copy the certificate to `/usr/local/share/ca-certificates`, and run `update-ca-certificates`.  Trying to run Portus in a container makes this more difficult, so I was wondering if there was some environment variable that would tell rails about the additional CA to trust (instead of going through the system trust).  Or, if there's some easy way to add an additional certificate to the system trust (without having to "build" it in).

Related, but not really helpful here: https://github.com/SUSE/Portus/issues/275#issuecomment-132119468

**Comment by farmerworking** [comment]
You can use nginx to handle `https` and proxy http to `Portus` which is the way I'm using. You should also change `check_ssl_usage --> enabled` in `config.yml` to false

most of the tutorials in the web will tell you to configure the web server(thin, passenger ... ) with certification to handle https

**Comment by JonathonReinhart** [comment]
@farmerworking Thanks, but you're answering a different question. I'm already using NGINX to provide SSL on the server. My question is asking about injecting my CA certificate into the OS, so Portus (acting as a *client* here) can make requests to the registry  (which uses a server cert signed by said CA).

**Comment by flavio** [comment]
No, there are no shortcuts, you have to add the CA at the system level
