### ISSUE TITLE
portus hosted at subpath instead of site root

### ISSUE THREAD

**Issue by thenewguy** [SUSE/Portus#509]
I have been reading through the documentation and code to understand how to best setup portus.  How do I configure portus to know it is located at a subpath?  

Say, docker.foo.com/portus/* and the registry at docker.foo.com/registry/*?  

It looks like docker distribution supports this via the "prefix" option at https://github.com/docker/distribution/blob/master/docs/configuration.md#http  but I can't grasp how to make portus aware of this.  I am trying to understand the whole flow before hacking a demo together.

**Comment by thenewguy** [comment]
So it seems that the docker cli cannot communicate with the registry if it is path prefixed.  So to make this work the url layout must be set to docker.foo.com/portus/* being passed to portus and docker.foo.com/* as a catchall routing to the registry.

Can portus be configured to operate in this fashion?

**Comment by JonathonReinhart** [comment]
I think you could do this with an NGINX proxy sitting in front of both portus and the registry.

**Comment by thenewguy** [comment]
That was what I was putting together in my head but I am not very familiar with ruby and rails so I wasn't too sure if it would be smooth sailing.  Thanks am going to give it a go

**Comment by mssola** [comment]
@thenewguy @flavio has been also experimenting with this, and he has come up with a config that accomplishes exactly this but with Apache. Note that there are some ugly workarounds (for registry's side), and there are still some rough edges. We'll provide more info once we get something perfectly up and running.

**Comment by thenewguy** [comment]
mssola: Do you think you could share it even though it is in a rough state?  It would be helpful to me to know the "correct" direction to be aiming for.

**Comment by thenewguy** [comment]
I missed that @flavio was working on it and not @mssola so my previous comment might be directed at the wrong person.  Thanks for letting me know what you guys are working on @mssola

**Comment by flavio** [comment]
Yeah, I'm going to share the configuration tomorrow

**Comment by thenewguy** [comment]
@flavio awesome

**Comment by flavio** [comment]
I created [this](https://github.com/SUSE/Portus/wiki/Portus-and-Docker-registry-on-the-same-FQDN-using-sub-URI) document explaining the setup.

**Comment by JonathonReinhart** [comment]
That document is excellent. Thanks @flavio.

**Comment by thenewguy** [comment]
@flavio much appreciated

**Comment by thenewguy** [comment]
@flavio I have been working through the example and trying to adapt it to docker compose.  Perhaps it would be a good improvement to change the Dockerfile to use passenger instead of puma.  Then it is simpler to run passenger standalone with a reverse proxy for mapping requests to the appropriate portus or registry container

**Comment by thenewguy** [comment]
Granted, puma might be just fine.  It doesn't seem to be documented as well though.  I am having issues getting portus to recognize it is hosted at a subpath with 
```
portus:
  build: {portus_build_dir}
  command: puma -b tcp://0.0.0.0:3000 -w 3
  environment:
    RAILS_RELATIVE_URL_ROOT: /portus
  links:
   - db
```
I get `Routing Error No Route Matches [GET] "/portus"`

**Comment by thenewguy** [comment]
It doesn't look like passenger standalone has a similar option as PassengerBaseURI for apache anyways.  I just need to figure out what it does under the hood.  Reading about rails I thought the ENV var in the previous comment was supposed to fix the routing issue but it didn't seem to do the trick

**Comment by thenewguy** [comment]
At this point I think I am going to try to run apache in the portus container and work on making the container lean later.

**Comment by kooltux** [comment]
@flavio: thanks for sharing your setup. I'll try it ASAP. 

Meanwhile, I managed to have both portus and docker registry running on same host using 2 SSL certs and 2 virtualhosts on Apache (so I have portus.example.com for the web UI and docker.example.com for the registry, which is not so bad after all). I get also some problems in the handling of notifications between both services, in particular the request made by portus to the registry to get detailed information after an event is not authorized.

**Comment by flavio** [comment]
> Meanwhile, I managed to have both portus and docker registry running on same host using 2 SSL certs and 2 virtualhosts on Apache (so I have portus.example.com for the web UI and docker.example.com for the registry, which is not so bad after all).

That should be easy :)

> I get also some problems in the handling of notifications between both services, in particular the request made by portus to the registry to get detailed information after an event is not authorized. 

You probably have to tune the configuration of the registry and specify make sure the `service` under the auth section. This one must be equal to the hostname of the registry as known by Portus.

**Comment by kooltux** [comment]
>You probably have to tune the configuration of the registry and specify make sure the service under the auth section. This one must be equal to the hostname of the registry as known by Portus.

The config is already as you described. 

From what I see in the logs, portus is not authorized to access to the registry with this query: 
```
GET /v2/devel/busybox/manifests/sha256:<...the sha256...>
```
The registry error message is 
```
"error authorizing context: authorization token required"
```
And on portus side, I get the following error:
```
Could not fetch the tag for target { ... }
Reason: Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x000000065df6a0>
```

What's the mechanism that allows portus to bypass the authorization (or to be authorized) ? Does it internally delivers a token for itself ? If so maybe the initial error occured earlier...

**Comment by flavio** [comment]
Portus authenticate against itself like any other user. There's a `portus` user inside of the database which has the password specified inside of Rails' secrets file.

You can check the connection from Portus to the registry by doing something like:
```
bundle exec rails r bin/client.rb ping
bundle exec rails r bin/client.rb catalog
```

**Comment by kooltux** [comment]
I duplicated the production config to development config (secrets.yml and database.yml) then ran the two test commands:
```
# bin/bundle exec rails r bin/client.rb ping
Registry reachable
```
So the ping seems ok (the registry log says something lilke "authorization token required", which sounds correct).
But 'catalog' fails with the same error as the one I got previously: 
```
# bin/bundle exec rails r bin/client.rb catalog
/srv/Portus/lib/portus/http_helpers.rb:108:in `request_auth_token': Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x00000008437490> (Portus::HttpHelpers::AuthorizationError)
	from /srv/Portus/lib/portus/http_helpers.rb:46:in `perform_request'
	from /srv/Portus/lib/portus/registry_client.rb:92:in `block in add_tags'
	from /srv/Portus/lib/portus/registry_client.rb:91:in `each'
	from /srv/Portus/lib/portus/registry_client.rb:91:in `add_tags'
	from /srv/Portus/lib/portus/registry_client.rb:57:in `catalog'
	from bin/client.rb:20:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```
Today I'm going to try your setup with URL rewriting. Hopefully, I won't get the problem.

**Comment by kooltux** [comment]
I followed your document on the [wiki](https://github.com/SUSE/Portus/wiki/Portus-and-Docker-registry-on-the-same-FQDN-using-sub-URI) and got a partially working setup.

FYI, I branched the docker-distrubution package on Suse OBS to include your PR which is not accepted yet on upstream project docker/docker-distribution: see my [project](https://build.opensuse.org/package/show/home:kooltux/docker-distribution). The download repo is [here](http://download.opensuse.org/repositories/home:/kooltux/openSUSE_13.2/)

What works:
* docker login ok
* docker push ok
* docker pull ok

But there's still a problem for portus to access the registry. In /srv/Portus/logs/production.log, I get:
```
I, [2015-10-30T16:07:15.112410 #22682]  INFO -- : Started GET "/portus/v2/token?scope=repository%3Adevel%2Fbusybox%3Apush%2Cpull&service=127.0.0.1%3A5000" for 46.18.96.42 at 2015-10-30 16:07:15 +0100
I, [2015-10-30T16:07:15.113127 #22682]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2015-10-30T16:07:15.113180 #22682]  INFO -- :   Parameters: {"scope"=>"repository:devel/busybox:push,pull", "service"=>"127.0.0.1:5000"}
I, [2015-10-30T16:07:15.115359 #22682]  INFO -- : Denied access on these grounds: not allowed to  this nil
I, [2015-10-30T16:07:15.115501 #22682]  INFO -- : Completed 401 Unauthorized in 2ms (ActiveRecord: 0.5ms)
```
Given the message "not allowed to this nil", this means that portus doesn't want to deliver a token to 'nil', which means that a param is probably missing...

**Comment by thenewguy** [comment]
I am still struggling to get this working with compose.  Anyone happen to have portus running in a docker container responding correctly when hosted at a sub path?  I've got the reverse proxy in a separate container -> i.e. reverse_proxy is container 1, registry is container 2, db is container 3, and portus is container 4

**Comment by thenewguy** [comment]
So I've been able to get the basics working with compose using the following:

Dockerfile:
```
FROM phusion/passenger-ruby22:0.9.17

ENV COMPOSE=1

# install supervisord, this is required to run cronos
RUN apt-get update && apt-get install -y supervisor

RUN mkdir /portus
WORKDIR /portus

ADD Gemfile* /portus/
RUN gem install bundler && bundle install --retry=3
ADD . /portus

RUN chown -R app:app /portus
RUN ln -s /portus/docker/crono-supervisord.conf /etc/supervisor/conf.d/crono.conf
RUN ln -s /portus/vhost.conf /etc/nginx/sites-enabled/portus.conf
RUN rm /etc/nginx/sites-enabled/default

RUN echo 'env COMPOSE;' > /etc/nginx/main.d/portus-env.conf
```

Nginx vhost:
```
server {

    listen 443 ssl;
    ssl_certificate /tmp/cert;
    ssl_certificate_key /tmp/key;
    
    root /portus/public;
    
    access_log /tmp/log/access.log;
    error_log /tmp/log/error.log;
    
    location /portus {
        passenger_base_uri /portus;
        passenger_app_root /portus;
        passenger_document_root /portus/public;
        passenger_enabled on;
        passenger_user app;
        passenger_app_env development;
    }
    
    location /portus/test {
        return 200 "test"; add_header Content-Type text/plain;
    }
    
    location /v2/ {
        client_max_body_size 0;
        proxy_pass http://registry:5000;
    }

}
```

docker-compose.yml.tmpl:
```
db:
  image: library/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: portus

portus:
  build: {portus_build_dir}
  links:
   - db
   - registry
  ports:
   - "443:443"
  volumes:
   - /var/log/portus:/tmp/log/
   - /path/to/my.cert:/tmp/cert:ro
   - /path/to/my.key:/tmp/key:ro

registry:
  image: registry:2.1.1
```
