### ISSUE TITLE
Is there a way to force a Catalog update

### ISSUE THREAD

**Issue by kidhasmoxy** [SUSE/Portus#513]
I'm trying to debug an issue where I don't seem to get any catalog updates from my existing repo, but the notification updates work just fine. 

Is there a way to execute a catalog update from a rake task or the rails console?

**Comment by clarktlaugh** [comment]
I think I am having a similar problem, though I am also not getting the notification updates to work either.  I see that you closed the issue.  Did you find a resolution?

I can't find any evidence that the crono job is running.
