### ISSUE TITLE
Migrations set index on unique e-mail, which fails when e-mail is blank

### ISSUE THREAD

**Issue by kidhasmoxy** [SUSE/Portus#514]
This issue occurred when using ldap, and the "guess email" option was on but without an attribute. The app was not able to create an address for the user (although it had a valid Base DN), so it left it blank. The first user is routed to their profile page to enter the address as expected. 

Until they do, then no other users can be created, as the user creation method fails when it tries to write a second user with a blank e-mail.

**Comment by mssola** [comment]
Good catch!
