### ISSUE TITLE
trusted docker image on public repository

### ISSUE THREAD

**Issue by thenewguy** [SUSE/Portus#515]
It would be handy if the installation documentation mentioned a trusted public docker repository build that could be used to skip the build phase in production.

**Comment by Swatto** [comment]
+1

**Comment by mssola** [comment]
This was discussed somewhere else but I'm failing at finding that issue... Anyways, I agree with this.

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
