### ISSUE TITLE
Build worker accounts

### ISSUE THREAD

**Issue by owenhaynes** [SUSE/Portus#517]
Is there any nice way for build user accounts eg Jenkins.

At the moment I have just created a jenkins user, but would need permission to all namespaces in a team. 
Repository level permissions would help this a little but even better would be tag permissions if even possible so that jenkins can only publish build tags e.g sample/test:build_1304, so sample/test:latest can never be overwritten by a jenkins build.

**Comment by flavio** [comment]
> At the moment I have just created a jenkins user, but would need permission to all namespaces in a group.

What do you mean with group? Are you talking about a team?

> Repository level permissions would help this a little but even better would be label permissions if even possible so that jenkins can only publish build labels e.g build_1304, so latest can never be overwritten by a jenkins build.

What do you mean with "label", are you referring to a namespace or a repository?

**Comment by mad0house** [comment]
Yes by group I mean team to me they are the same things at the moment. 

A label I mean tag of a repository  will correct the original post to make account of this.

**Comment by flavio** [comment]
Unfortunately what you are asking is not possible. When you push a docker image to a certain namespace, the docker registry will ask the client to show it can actually write to that namespace. The permission requested by the registry is not about a repository or even a tag, it's about the whole namespace.

So right now the only solution would be to add your jenkins user as a contributor to your team. By doing that he will be able to push and pull to all the namespaces controlled by the team.

**Comment by mad0house** [comment]
According to the registry docks it talks about permissions per repository in a namespace unless  I have miss interpreted the docs

'''
For example, say I (username jlhawn) am attempting to push an image to the repository samalba/my-app. For the registry to authorize this, I either need push access to the samalba/my-app repository or push access to the whole samalba namespace in general. The registry will first return this response:
'''

**Comment by flavio** [comment]
@mssola do you think they changed something recently? In the past they just asked for permissions against the namespace...

**Comment by mad0house** [comment]
It mentions this on the page under the heading 
https://docs.docker.com/registry/spec/auth/token/
How to authenticate

Fyi

**Comment by flavio** [comment]
@mad0house you are right! We will surely think about a way to have even more granular control over push and pull. What you are proposing is definitely doable.

**Comment by holgerreif** [comment]
I didn't found any hint in https://docs.docker.com/registry/spec/auth/token/ that an authorization is possible at tag level. The only information the authorization server gets is the namespace and the repository.
Thus the initial request "can only publish build tags e.g sample/test:build_1304" seems impossible to fullfill.

**Comment by owenhaynes** [comment]
Yes label level may require some testing to see what the docker repository sends for tags, if its possible, 

But repository level would be more then enough, as namespace is level as currently is to restrictive.

**Comment by mssola** [comment]
So, in the conversation there's been a bit of confusion :) The thing here is that for now Portus can only be configured on the namespace level, which can be a bit too restrictive. So:

- The `feature` tag goes for allowing admins to set per-repo permissions.
- For now the docker registry is not sending the tag, therefore it's impossible to do this on the tag level.

**Comment by mssola** [comment]
This has been partially implemented in #1856, and the issue #1861 has been created as a follow-up of that PR and this issue. Closing.
