### ISSUE TITLE
E-mail guessing fails silently

### ISSUE THREAD

**Issue by kidhasmoxy** [SUSE/Portus#520]
Users are able to authenticate to Portus via LDAP creds, but their e-mail is not being set automatically, using the "guess" option with no attribute. 

When the attribute is defined (set to "mail" in this case) users receive an "Invalid username" error when they try to login. 

This compounds with #514 to make the system unusable for new users until all users have an e-mail address defined.

The workaround (for now) is to force the e-mail naming convention in code, which works because all users in this LDAP setup have the same domain. 

The fact that the "guess" fails with no attribute defined seems to point to a failure in the ldap search, or that the ldap search.

**Comment by mssola** [comment]
Thanks for the heads up. If I understand it correctly, it should be enough if Portus would be more verbose on the given alert message. I guess that it would also be nice to log the error.

Anyways, the `guess_email` was meant to be used when the LDAP server follows a very specific pattern (being that the CN follows a pattern, or that the LDIF provides an attribute for it). Note that now that #514 has been fixed, maybe you don't run into so many errors from now on.

**Comment by kidhasmoxy** [comment]
There's 2 parts to this for me. The first is a bug, where the LDIF attribute feature doesn't seem to work properly, as I supplied a valid attribute, and e-mail generation fails. My guess is that pulling the user record from LDAP fails, so all steps after fail. This would explain why neither the default guessing, nor the specific attribute definition works.

The "null" value helps here, as e-mails aren't strictly required for use anymore. 

Second, is the enhancement, which requests an alert or error message when Portus fails to generate an e-mail address.

**Comment by mssola** [comment]
>  The first is a bug, where the LDIF attribute feature doesn't seem to work properly, as I supplied a valid attribute, and e-mail generation fails. My guess is that pulling the user record from LDAP fails, so all steps after fail. This would explain why neither the default guessing, nor the specific attribute definition works.

Ok, this is a bit weird... Let me investigate.

> Second, is the enhancement, which requests an alert or error message when Portus fails to generate an e-mail address.

1. On the UI side, if the guessing of the email failed, you'll be redirected anyways to the profile and you'll be asked to fill the email. So the user is already aware that something went wrong.
2. From an admin site, I agree that we should log more properly what went wrong.

**Comment by mssola** [comment]
@kidhasmoxy I've investigated on it, and I catched an error (See 3e00cb0ee2d4d7270055c4c6d964d9524543a328). However, I'd need more information for the bug you're mentioning.

Please, make sure that you're using the right values for things like `uid`, `base`, `authentication`, etc. If you're still stuck with this, maybe you could add some debugging statements inside of the `guess_email` method and we can investigate what's going on if you paste what you get. Interesting stuff would be to investigate:

- What does your `APP_CONFIG` look like at this point (filter out passwords and sensible data).
- What does `search_options` return.
- What does `@ldap.search(search_options)` return.

Thanks!

**Comment by mssola** [comment]
Closing now, since I believe that this has already been done. Feel free to re-open if you think that it has not been addressed.
