### ISSUE TITLE
Unable to integrate with existing registry

### ISSUE THREAD

**Issue by summerQLin** [SUSE/Portus#528]
We've already got lots of repositories in our private registry. And when integrating with Portus, I found portus failed to write existing namespaces into portus database. It stuck at crono job, trying to fetch manifests of existing repositories, and got 401.
So is there anyway recommended to do integration with existing registry? Or grant user 'portus' the ability to fetch manifests, and grant team "portus" the right to access those existing registries?

**Comment by mssola** [comment]
Ok, so there are two things here:

1. Fetching a manifest returns a 401.
2. The catalog job does not create the namespaces from a registry that already had some namespaces in them.

The first point is more troublesome, and it means that you have something wrong in the configuration between Portus and your registry. Check the logs (`log/development.log`, or `production.log` if you're on production). Make sure that the registry is reachable. From the sources, you can do this with:

    $ bundle exec rails r bin/client.rb catalog

The second point has been done on purpose. The point of the catalog job is to act as a job that keeps the consistency of what has been pushed since Portus has been installed. This job is not a migration tool from one registry to another. This is because creating a namespace involves:

- Assigning it to a team.
- Assigning the level of visibility of the namespace to be created.

This is tricky, and it cannot be done automatically by this job, since it might need intervention from an admin. Therefore, there should be some sort of migration tool that helps you with this process. We don't have this right now, and we haven't given enough thought to this. Thus, by now you should create the namespaces that you have on your registry by hand in Portus, configuring everything as you expect. This way, all your repos should be available in Portus after the catalog job runs again.

**Comment by summerQLin** [comment]
@mssola, the log is like this:
```
Started GET "/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=myhub%3A443" for 10.42.43.157 at 2015-11-03 02:15:48 +0000
Cannot render console from 10.42.43.157! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"myhub:443"}
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus'  ORDER BY `users`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  SQL (0.4ms)  UPDATE `users` SET `current_sign_in_at` = '2015-11-03 02:15:48', `sign_in_count` = 177295, `updated_at` = '2015-11-03 02:15:48' WHERE `users`.`id` = 1
   (1.4ms)  COMMIT
  Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'myhub:443' LIMIT 1
  CACHE (0.0ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'myhub:443' LIMIT 1  [["hostname", "myhub:443"]]
[jwt_token] [claim] {:iss=>"portus.test.lan", :sub=>"portus", :aud=>"myhub:443", :iat=>1446516948, :nbf=>1446516943, :exp=>1446517248, :jti=>"GjSDdf9cs8EAB1GAahezxBzp7X96LcPxSuw8UU4tRM", :access=>[{:type=>"registry", :name=>"catalog", :actions=>["*"]}]}
Completed 200 OK in 137ms (Views: 7.0ms | ActiveRecord: 3.0ms)

Started GET "/v2/token?account=portus&scope=repository%3Aalm_user_service_app%3Apull&service=myhub%3A443" for 10.42.43.157 at 2015-11-03 02:15:49 +0000
...
Completed 200 OK in 211ms (Views: 9.8ms | ActiveRecord: 4.1ms)

Started GET "/v2/token?account=portus&scope=repository%3Abusybox%3Apull&service=myhub%3A443" for 10.42.43.157 at 2015-11-03 02:15:49 +0000
...
Completed 200 OK in 156ms (Views: 8.2ms | ActiveRecord: 3.6ms)

Started GET "/v2/token?account=portus&scope=repository%3Achavezom%2Fgraphops-api%3Apull&service=myhub%3A443" for 10.42.43.157 at 2015-11-03 02:15:50 +0000
Cannot render console from 10.42.43.157! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"portus", "scope"=>"repository:chavezom/graphops-api:pull", "service"=>"myhub:443"}
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus'  ORDER BY `users`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  SQL (0.4ms)  UPDATE `users` SET `last_sign_in_at` = '2015-11-03 02:15:50', `current_sign_in_at` = '2015-11-03 02:15:50', `sign_in_count` = 177301, `updated_at` = '2015-11-03 02:15:50' WHERE `users`.`id` = 1
   (1.0ms)  COMMIT
  Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'myhub:443' LIMIT 1
  Namespace Load (0.2ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'chavezom' LIMIT 1
Denied access on these grounds: Cannot find namespace chavezom
Completed 401 Unauthorized in 193ms (ActiveRecord: 2.8ms)

```
It seems after calling catalog api, portus will fetch manifests of those repositories. But since namespace "chavezom" is not in database yet, fetching manifest for "chavezom/graphops-api" failed.  By this way, we will never synchronize between registry and portus database.

**Comment by summerQLin** [comment]
I manually create a team and add namespace "chavezom", and this time crono job will have 200 to get manifest of "chavezom/graphops-api". But still I can't see "chavezom/graphops-api" and it's tags from portus UI, maybe the sync job is still blocked by other existing namespaces but unknown to portus.

Then I tried to push to chavezom/ using username 'qing.lin@hpe.com', and pushed successfully. We use ldap for authentication. But I still can't see new pushed repositories and tags from UI. Check web container's log, I saw web hook events arrived, but saying error "Cannot find user qing.lin@hpe.com". I guess it's because my username becomes "qinglinhpecom". I think this is a defect.

**Comment by mssola** [comment]
> I manually create a team and add namespace "chavezom", and this time crono job will have 200 to get manifest of "chavezom/graphops-api". But still I can't see "chavezom/graphops-api" and it's tags from portus UI, maybe the sync job is still blocked by other existing namespaces but unknown to portus.

Are you sure that the catalog job has run again after you've created the namespace ? Could you print the logs after creating the `chavezom` namespace ? The fact that there are still namespaces to be created shouldn't matter.

> Then I tried to push to chavezom/ using username 'qing.lin@hpe.com', and pushed successfully. We use ldap for authentication. But I still can't see new pushed repositories and tags from UI. Check web container's log, I saw web hook events arrived, but saying error "Cannot find user qing.lin@hpe.com". I guess it's because my username becomes "qinglinhpecom". I think this is a defect.

Is the email your username ? Anyways, maybe you're referring an error that was fixed with the PR #431. If that's the case, maybe upgrading to current master will fix your issue.

Moreover, you say that you check your web container's log. Does this mean that you're running all this in the compose setup ? If this is the case, be aware that currently this setup is a bit [broken](https://github.com/SUSE/Portus/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Abug+label%3Adocker-compose). Sadly, I haven't found any time to fix this situation yet... Maybe you could try our vagrant setup for now.

**Comment by summerQLin** [comment]
@mssola, I really appreciate your help. After updating, now notification works. I created a team and assign namespace "chavezom" for that team. Then image "chavezom/graphops-api" is pushed, I am able to see that repo and tag, which is really great.
But the problem is catalog job. I am sure crono job is working, as it is requesting catalog and manifests every 10 sec. From web container log, token requests are like
```
11/3/2015 10:04:12 PM[16] 10.42.43.157 - - [03/Nov/2015:14:04:12 +0000] "GET /v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=myhub%3A443 HTTP/1.1" 200 - 0.1421
11/3/2015 10:04:18 PM[9] 10.42.43.157 - - [03/Nov/2015:14:04:18 +0000] "GET /v2/token?account=portus&scope=repository%3Aalm_user_service_db%3Apull&service=myhub%3A443 HTTP/1.1" 200 - 0.1490
11/3/2015 10:04:18 PM[9] 10.42.43.157 - - [03/Nov/2015:14:04:18 +0000] "GET /v2/token?account=portus&scope=repository%3Achavezom%2Fgraphops-api%3Apull&service=myhub%3A443 HTTP/1.1" 401 - 0.0184
...repeating...
```
And crono container log is like
```
(0.1ms)  BEGIN
  Crono::CronoJob Exists (0.2ms)  SELECT  1 AS one FROM `crono_jobs` WHERE (`crono_jobs`.`job_id` = BINARY...
...
 INFO -- : Finished CatalogJob in 8.88 seconds\nI, [2015-11-03T10:44:08.779903 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:44:18.736148 #10]  INFO -- : Finished CatalogJob in 9.96 seconds\nI, [2015-11-03T10:44:18.780219 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:44:28.780542 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:44:30.476589 #10]  INFO -- : Finished CatalogJob in 1.70 seconds\nI, [2015-11-03T10:44:38.780817 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:44:41.538442 #10]  INFO -- : Finished CatalogJob in 2.76 seconds\nI, [2015-11-03T10:44:48.781137 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:44:52.053523 #10]  INFO -- : Finished CatalogJob in 3.27 seconds\nI, [2015-11-03T10:44:58.781455 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:45:02.708379 #10]  INFO -- : Finished CatalogJob in 3.93 seconds\nI, [2015-11-03T10:45:08.781799 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:45:11.815960 #10]  INFO -- : Finished CatalogJob in 3.03 seconds\nI, [2015-11-03T10:45:18.782197 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:45:19.331561 #10]  INFO -- : Finished CatalogJob in 0.55 seconds\nI, [2015-11-03T10:45:28.782524 #10]  INFO -- : Perform CatalogJob\nI, [2015-11-03T10:45:36.064394 #10]  INFO -- : Finished CatalogJob in 7.28 seconds\nI, [2015-11-03T10:45:38.782978 #10]  INFO -- : Perform CatalogJob\n', `updated_at` = '2015-11-03 10:45:43' WHERE `crono_jobs`.`id` = 1
   (0.1ms)  ROLLBACK
...
```
This log grows very fast, I have to clean it sometimes. But at least I am sure crono job is working. By the way I don't share volume between web and crono container, so their logs are separated and kept in the container.

As you know I already have a private registry in use. In order to integrate it with portus, I plan to ask user to create their own team and namespaces, e.g. "chavezom". Or push images to their default namespace, e.g. "qinglinhpecom". However, catalog job transaction seems never succeed, which is the most important issue I have to fix. I don't know if my direction is right or not, it would be great if you could help to check. 

Thanks again.

**Comment by summerQLin** [comment]
I didn't use compose setup. The whole stuff I setup manually.

**Comment by summerQLin** [comment]
I tested `bundle exec rails r bin/client.rb catalog` and got error,
```
/portus/lib/portus/http_helpers.rb:108:in `request_auth_token': Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x007faa1cfa8750> (Portus::HttpHelpers::AuthorizationError)
        from /portus/lib/portus/http_helpers.rb:46:in `perform_request'
        from /portus/lib/portus/registry_client.rb:92:in `block in add_tags'
        from /portus/lib/portus/registry_client.rb:91:in `each'
        from /portus/lib/portus/registry_client.rb:91:in `add_tags'
        from /portus/lib/portus/registry_client.rb:57:in `catalog'
        from bin/client.rb:19:in `<top (required)>'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `load'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `<top (required)>'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:90:in `runner'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/bundle/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
```
