### ISSUE TITLE
The activity for editing a description shouldn't have the contents of the description

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#537]
Right now the whole description is shown when editing the description. This is weird visually, and it doesn't add too much useful information really.

**Comment by jloehel** [comment]
The old description and the new description are part of the public_activity but not displayed at the dashboard or admin site. They are only added to the .csv-File. Sorry for the misunderstanding.

**Comment by mssola** [comment]
Ok, thank you for clearing up
