### ISSUE TITLE
Docker images is not working

### ISSUE THREAD

**Issue by rajeswarr** [SUSE/Portus#544]
Hi,

I built new image from the source code by using dockerfile, but portus application it not running when I run docker image. Is there any issue or something wrong at my end can someone help on the same.

**Comment by Salzig** [comment]
Could you provide the container log?

**Comment by rajeswarr** [comment]
Hi Salzig,

Surprisingly docker logs command did not provided any output. So is there a way to provide the required information.

Are you able to run the application from bydga/protus image?

**Comment by mssola** [comment]
@rajeswarr note that the `bydga/portus` is not an official image. In fact, just looking at the Dockerfile I can tell that it surely does not work. If you want to try Portus out, follow our instructions on the wiki: https://github.com/SUSE/Portus/wiki
