### ISSUE TITLE
When accessing the github page, it always redirects

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#554]
This is a really weird thing that is happening to me with Firefox since always. Whenever I access the page, it kind of lags and then it redirects again to the same page, now rendering just fine.

Weirdly enough, this also happens to Portus in the signup page.

**Comment by thenewguy** [comment]
I've been scratching my head over this.  I also get redirected to 500?fixes=true without any helpful logging.  I will be back in town next week to see if the issue is Firefox specific which would be nice and let me move forward

**Comment by mssola** [comment]
I've checked Chrome and this does not happen with this browser...

**Comment by mssola** [comment]
Funnily enough, opensuse.org also has this issue with Firefox. I guess that this should really narrow the list of possible JS sources that are triggering this issue.

**Comment by mssola** [comment]
As noted by @cyntss I cannot reproduce this anymore on either openSUSE Tumbleweed or Leap. Thus, I believe that this was a regression on some specific firefox version. Closing this.
