### ISSUE TITLE
Production portus in Docker container -- database setup 'problem'?

### ISSUE THREAD

**Issue by clarktlaugh** [SUSE/Portus#574]
I am trying to run a production Portus in a docker container, but am not using docker-compose.  I already have a working environment with an nginx reverse proxy container, a registry container running and I just want to integrate Portus into it rather than replacing everything.

I have built a Portus container by cloning the Portus tree and running docker build on the Dockerfile in there.

I am not to the point of testing the integration of Portus with my registry.  I am just trying to get Portus and the database setup without errors.

I am starting the mariadb container as follows:

```
docker run -d  \
        --name=portus-database  \
        --restart=unless-stopped  \
        -e "MYSQL_ROOT_PASSWORD=portus"  \
        library/mariadb
```

I am starting the Portus container as follows:

```
docker run  \
        -d
        --name=portus  \
        -e VIRTUAL_HOST=${DOCKER_PORTUS_VIRTUAL_HOST}  \
        -e RAILS_ENV=production  \
        -e PORTUS_KEY_PATH=/ssl/private.key  \
        -e PORTUS_SECRET_KEY_BASE=${PORTUS_SECRET_KEY}  \
        -e PORTUS_MACHINE_FQDN=${DOCKER_PORTUS_VIRTUAL_HOST}  \
        -e PORTUS_PASSWORD=${PORTUS_PASSWORD}  \
        -e PORTUS_PRODUCTION_HOST=db  \
        -e PORTUS_PRODUCTION_USERNAME=root  \
        -e PORTUS_PRODUCTION_PASSWORD=portus  \
        -e PORTUS_PRODUCTION_DATABASE=portus  \
        --link=portus-database:db  \
        -v ${BASE}/logs:/portus/log  \
        -v ${CERTS_DIR}:/ssl:ro  \
        local/portus  \
        puma -b tcp://0.0.0.0:3000 -w 3
```

Running rake db:setup on it:

```
docker run  \
        -rm
        --name=temp  \
        -e VIRTUAL_HOST=${DOCKER_PORTUS_VIRTUAL_HOST}  \
        -e RAILS_ENV=production  \
        -e PORTUS_KEY_PATH=/ssl/private.key  \
        -e PORTUS_SECRET_KEY_BASE=${PORTUS_SECRET_KEY}  \
        -e PORTUS_MACHINE_FQDN=${DOCKER_PORTUS_VIRTUAL_HOST}  \
        -e PORTUS_PASSWORD=${PORTUS_PASSWORD}  \
        -e PORTUS_PRODUCTION_HOST=db  \
        -e PORTUS_PRODUCTION_USERNAME=root  \
        -e PORTUS_PRODUCTION_PASSWORD=portus  \
        -e PORTUS_PRODUCTION_DATABASE=portus  \
        --link=portus-database:db  \
        -v ${BASE}/logs:/portus/log  \
        -v ${CERTS_DIR}:/ssl:ro  \
        local/portus  \
        rake db:setup
```

This is the output I am getting.  Any suggestions what I might be doing wrong?  Should I be seeing all of the migration messages when just doing db:setup?

```
Configuring database...start Portus: 'rake db:setup'
WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.8.0
== 20150414104850 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0139s
-- add_index(:users, :username, {:unique=>true})
   -> 0.0074s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0076s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0080s
== 20150414104850 DeviseCreateUsers: migrated (0.0369s) =======================

== 20150416121417 CreateNamespaces: migrating =================================
-- create_table(:namespaces)
   -> 0.0108s
-- add_index(:namespaces, :name, {:unique=>true})
   -> 0.0077s
== 20150416121417 CreateNamespaces: migrated (0.0186s) ========================

== 20150416121842 CreateRepositories: migrating ===============================
-- create_table(:repositories)
   -> 0.0113s
-- add_index(:repositories, :name, {:unique=>true})
   -> 0.0072s
-- add_index(:repositories, :namespace_id)
   -> 0.0060s
== 20150416121842 CreateRepositories: migrated (0.0246s) ======================

== 20150416122030 CreateTags: migrating =======================================
-- create_table(:tags)
   -> 0.0124s
-- add_index(:tags, :repository_id)
   -> 0.0076s
== 20150416122030 CreateTags: migrated (0.0200s) ==============================

== 20150417095841 CreateTeams: migrating ======================================
-- create_table(:teams)
   -> 0.0164s
== 20150417095841 CreateTeams: migrated (0.0165s) =============================

== 20150417100647 AddTeamReferenceToNamespace: migrating ======================
-- add_belongs_to(:namespaces, :team, {:index=>true})
   -> 0.0241s
== 20150417100647 AddTeamReferenceToNamespace: migrated (0.0242s) =============

== 20150426115313 CreateTeamUsers: migrating ==================================
-- create_table(:team_users)
   -> 0.0141s
== 20150426115313 CreateTeamUsers: migrated (0.0141s) =========================

== 20150427092952 AddAdminToUsers: migrating ==================================
-- add_column(:users, :admin, :boolean, {:default=>false})
   -> 0.0205s
== 20150427092952 AddAdminToUsers: migrated (0.0206s) =========================

== 20150428081205 AddOwnerToTeamUsers: migrating ==============================
-- add_column(:team_users, :owner, :boolean, {:default=>false})
   -> 0.0191s
== 20150428081205 AddOwnerToTeamUsers: migrated (0.0192s) =====================

== 20150428081530 RemoveOwnerIdFromTeams: migrating ===========================
-- remove_column(:teams, :owner_id, :integer)
   -> 0.0156s
== 20150428081530 RemoveOwnerIdFromTeams: migrated (0.0156s) ==================

== 20150429102443 AddRoleToTeamUser: migrating ================================
-- add_column(:team_users, :role, :integer, {:default=>0})
   -> 0.0159s
-- remove_column(:team_users, :owner)
   -> 0.0174s
== 20150429102443 AddRoleToTeamUser: migrated (0.0376s) =======================

== 20150429185051 AddPublicToNamespace: migrating =============================
-- add_column(:namespaces, :public, :boolean, {:default=>false})
   -> 0.0162s
== 20150429185051 AddPublicToNamespace: migrated (0.0162s) ====================

== 20150507155138 CreateRegistries: migrating =================================
-- create_table(:registries)
   -> 0.0099s
-- add_index(:registries, :name, {:unique=>true})
   -> 0.0077s
-- add_index(:registries, :hostname, {:unique=>true})
   -> 0.0075s
== 20150507155138 CreateRegistries: migrated (0.0253s) ========================

== 20150507155425 AddRegistryIdToNamespaces: migrating ========================
-- add_belongs_to(:namespaces, :registry, {:index=>true})
   -> 0.0256s
== 20150507155425 AddRegistryIdToNamespaces: migrated (0.0257s) ===============

== 20150512105052 CreateActivities: migrating =================================
-- create_table(:activities)
   -> 0.0125s
-- add_index(:activities, [:trackable_id, :trackable_type])
   -> 0.0079s
-- add_index(:activities, [:owner_id, :owner_type])
   -> 0.0073s
-- add_index(:activities, [:recipient_id, :recipient_type])
   -> 0.4032s
== 20150512105052 CreateActivities: migrated (0.4312s) ========================

== 20150513133049 AddIndexToActivitiesKey: migrating ==========================
-- add_index(:activities, :key)
   -> 0.0076s
== 20150513133049 AddIndexToActivitiesKey: migrated (0.0076s) =================

== 20150515111638 AddAuthorToTag: migrating ===================================
-- add_belongs_to(:tags, :user, {:index=>true})
   -> 0.0269s
== 20150515111638 AddAuthorToTag: migrated (0.0270s) ==========================

== 20150515114145 AddGlobalFlagToNamespaces: migrating ========================
-- add_column(:namespaces, :global, :boolean, {:default=>false})
   -> 0.0218s
== 20150515114145 AddGlobalFlagToNamespaces: migrated (0.0219s) ===============

== 20150518142223 AddHiddenToTeams: migrating =================================
-- add_column(:teams, :hidden, :boolean, {:default=>false})
   -> 0.0122s
== 20150518142223 AddHiddenToTeams: migrated (0.0123s) ========================

== 20150521145620 AddFulltextIndexesOnRepositoriesNamespaces: migrating =======
-- add_index(:namespaces, :name, {:type=>:fulltext, :name=>"fulltext_index_namespaces_on_name"})
   -> 0.0945s
-- add_index(:repositories, :name, {:type=>:fulltext, :name=>"fulltext_index_repositories_on_name"})
   -> 0.0883s
== 20150521145620 AddFulltextIndexesOnRepositoriesNamespaces: migrated (0.1829s)

== 20150522140822 AddIndexNameOnTeams: migrating ==============================
-- add_index(:teams, :name, {:unique=>true})
   -> 0.0074s
== 20150522140822 AddIndexNameOnTeams: migrated (0.0074s) =====================

== 20150522141052 FixIndexNameOnRepositories: migrating =======================
-- remove_index(:repositories, {:column=>:name})
   -> 0.0043s
-- add_index(:repositories, [:name, :namespace_id], {:unique=>true})
   -> 0.0058s
== 20150522141052 FixIndexNameOnRepositories: migrated (0.0101s) ==============

== 20150522141547 FixIndexNameOnNamespaces: migrating =========================
-- remove_index(:namespaces, {:column=>:name})
   -> 0.0040s
-- add_index(:namespaces, [:name, :registry_id], {:unique=>true})
   -> 0.0059s
== 20150522141547 FixIndexNameOnNamespaces: migrated (0.0099s) ================

== 20150522144027 AddIndexOnTagNameRepositoryId: migrating ====================
-- add_index(:tags, [:name, :repository_id], {:unique=>true})
   -> 0.0076s
== 20150522144027 AddIndexOnTagNameRepositoryId: migrated (0.0076s) ===========

== 20150629080516 ChangeRegistryIdFromNamespace: migrating ====================
-- change_column_null(:namespaces, :registry_id, false)
   -> 0.0941s
== 20150629080516 ChangeRegistryIdFromNamespace: migrated (0.1081s) ===========

== 20150722194840 CreateStars: migrating ======================================
-- create_table(:stars)
   -> 0.0704s
== 20150722194840 CreateStars: migrated (0.0704s) =============================

== 20150729153854 AddEnabledToUsers: migrating ================================
-- add_column(:users, :enabled, :bool, {:default=>true})
   -> 0.0205s
== 20150729153854 AddEnabledToUsers: migrated (0.0205s) =======================

== 20150805130722 CreateCronoJobs: migrating ==================================
-- create_table(:crono_jobs)
   -> 0.0134s
-- add_index(:crono_jobs, [:job_id], {:unique=>true})
   -> 0.0072s
== 20150805130722 CreateCronoJobs: migrated (0.0207s) =========================

== 20150831131727 AddLdapNameToUsers: migrating ===============================
-- add_column(:users, :ldap_name, :string, {:default=>nil})
   -> 0.0240s
-- add_index(:users, :ldap_name, {:unique=>true})
   -> 0.0073s
== 20150831131727 AddLdapNameToUsers: migrated (0.0313s) ======================

== 20150915130327 AddLockableToUsers: migrating ===============================
-- add_column(:users, :failed_attempts, :integer, {:default=>0})
   -> 0.0287s
-- add_column(:users, :locked_at, :datetime)
   -> 0.0260s
== 20150915130327 AddLockableToUsers: migrated (0.0547s) ======================

== 20150923091830 AddUseSslToRegistries: migrating ============================
-- add_column(:registries, :use_ssl, :boolean)
   -> 0.0159s
== 20150923091830 AddUseSslToRegistries: migrated (0.0159s) ===================rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `repositories` CASCADE
/portus/db/schema.rb:72:in `block in <top (required)>'
/portus/db/schema.rb:14:in `<top (required)>'
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/portus/db/schema.rb:72:in `block in <top (required)>'
/portus/db/schema.rb:14:in `<top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)


== 20150924084635 AddAttributeToTeams: migrating ==============================
-- add_column(:teams, :description, :text)
   -> 0.0155s
== 20150924084635 AddAttributeToTeams: migrated (0.0155s) =====================

== 20150928112551 AddDescriptionToNamespace: migrating ========================
-- add_column(:namespaces, :description, :text)
   -> 0.0966s
== 20150928112551 AddDescriptionToNamespace: migrated (0.0967s) ===============

== 20151029145958 RemoveNotNullConstraintOnUsersEmail: migrating ==============
-- change_column(:users, :email, :string, {:null=>true})
   -> 0.0214s
== 20151029145958 RemoveNotNullConstraintOnUsersEmail: migrated (0.0215s) =====

== 20151112003047 AddDigestToTags: migrating ==================================
-- add_column(:tags, :digest, :string)
   -> 0.0197s
== 20151112003047 AddDigestToTags: migrated (0.0198s) =========================

-- create_table("activities", {:force=>:cascade})
   -> 0.0162s
-- add_index("activities", ["key"], {:name=>"index_activities_on_key", :using=>:btree})
   -> 0.0074s
-- add_index("activities", ["owner_id", "owner_type"], {:name=>"index_activities_on_owner_id_and_owner_type", :using=>:btree})
   -> 0.0073s
-- add_index("activities", ["recipient_id", "recipient_type"], {:name=>"index_activities_on_recipient_id_and_recipient_type", :using=>:btree})
   -> 0.0077s
-- add_index("activities", ["trackable_id", "trackable_type"], {:name=>"index_activities_on_trackable_id_and_trackable_type", :using=>:btree})
   -> 0.0096s
-- create_table("crono_jobs", {:force=>:cascade})
   -> 0.0173s
-- add_index("crono_jobs", ["job_id"], {:name=>"index_crono_jobs_on_job_id", :unique=>true, :using=>:btree})
   -> 0.0086s
-- create_table("namespaces", {:force=>:cascade})
   -> 0.0192s
-- add_index("namespaces", ["name", "registry_id"], {:name=>"index_namespaces_on_name_and_registry_id", :unique=>true, :using=>:btree})
   -> 0.0067s
-- add_index("namespaces", ["name"], {:name=>"fulltext_index_namespaces_on_name", :type=>:fulltext})
   -> 0.0838s
-- add_index("namespaces", ["registry_id"], {:name=>"index_namespaces_on_registry_id", :using=>:btree})
   -> 0.0077s
-- add_index("namespaces", ["team_id"], {:name=>"index_namespaces_on_team_id", :using=>:btree})
   -> 0.0070s
-- create_table("registries", {:force=>:cascade})
   -> 0.0147s
-- add_index("registries", ["hostname"], {:name=>"index_registries_on_hostname", :unique=>true, :using=>:btree})
   -> 0.0063s
-- add_index("registries", ["name"], {:name=>"index_registries_on_name", :unique=>true, :using=>:btree})
   -> 0.0072s
-- create_table("repositories", {:force=>:cascade})
 failed, will retry
```

**Comment by InAnimaTe** [comment]
Mine also fails at this point:

```
-- create_table("repositories", {:force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `repositories` CASCADE
/portus/db/schema.rb:72:in `block in <top (required)>'
/portus/db/schema.rb:14:in `<top (required)>'
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails
/portus/db/schema.rb:72:in `block in <top (required)>'
/portus/db/schema.rb:14:in `<top (required)>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)

```

**Comment by mssola** [comment]
Ok, I can reproduce this with `rake db:setup` but not with `rake db:migrate`. So, instead of doing setup, could you: `rake db:create && rake db:migrate && rake db:seed`. Does this fix it for you ?

**Comment by mssola** [comment]
Of course you can skip the rake db:create if it has already been created for you ;)

**Comment by clarktlaugh** [comment]
When I try all together, I get this:

```
Configuring database...start Portus: 'rake db:create && rake db:migrate && rake db:seed'
WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.8.0
rake aborted!
Don't know how to build task '&&'
```

I will attempt to run each task separately.


On a related note -- has there been any thought to having Portus, when starting, automatically perform any database creation/migration that is necessary (could be disabled with a config setting/EV if desired) to get rid of the need to have that be an external task that needs to be run?

It would be nicer to just be able to start the container without having to do any extra steps.

**Comment by InAnimaTe** [comment]
^totally. I think a lot of work needs to be done in the container area to make deploying portus a lot easier. There are a ton of inter-dependent things which have to be configured to a tee in order to get this running..

**Comment by mssola** [comment]
Agreed.

**Comment by clarktlaugh** [comment]
Honestly, the difficulties I have had have mainly been around documentation... figuring out all of the EVs that needed to be set.

Beyond that, it's going pretty well.  I understand that what I am doing is not what was originally intended for the container use-case of Portus, but I don't think there is any reason it can't be used for production. 

Aside from just documentation, the two issues that have had to be worked around are:

(1) the database initialization (which I think should be handled during portus startup) and
(2) getting a CA certificate into the image

(1) seems to have been resolved for now by the suggestion above to run ```rake db:create && rake db:migrate && rake db:seed``` (though I had to run as 3 separate steps).

(2) was resolved by creating a new portus image built from the original one using a simple Dockerfile like this:

```
FROM suse/portus  # the tag I gave for my locally-built Portus image from the source
COPY certs/gd_bundle-g2-g1.crt /usr/local/share/ca-certificates
RUN update-ca-certificates
```

I am not sure of a better way to handle (2) yet (other than modifying the portus files, which I would prefer to leave alone)... perhaps someone has another suggestion.

**Comment by cthiebault** [comment]
Did you finally manage to run Portus as Docker container?

**Comment by egidijus** [comment]
If you are running migration outside the container and ARE using compose:
`docker-compose run --rm portus sh -c "rake db:create && rake db:migrate && rake db:seed &> /dev/null"`

or without compose

`docker run -it --rm portus sh -c "rake db:create && rake db:migrate && rake db:seed &> /dev/null"`

**Comment by tinybitsofnothingness** [comment]
@clarktlaugh Did you manage to get this up and running? Would you mind to share your configuration maybe?

I was following your steps because I would like to do a similar setup, I didn't have problems with `db:setup` and I managed to link my registry in front-end (with SSL enabled) and managed to log in from command line (`docker login -u user -p pass -e mail my.hub.com:5000` responded with `Login Succeeded`).
However, when I tried to push an image, everything seemed fine in command line:

    docker tag busybox my.hub.com:5000/namespace/xxx
    docker push my.hub.com:5000/namespace/xxx
    The push refers to a repository [ my.hub.com:5000/namespace/xxx] (len: 1)
    b175bcb79023: Pushed 
    583635769552: Pushed 
    latest: digest: sha256:2eb1ddfaac19903855f96626e66aac5caadc2d712c444ae84b5e3870a5021325 size: 2736

however, no image appeared on front-end. Nginx and registry logs are clearly showing 401, so I'm probably missing some EV or something similar.

**Comment by flavio** [comment]
> however, no image appeared on front-end. Nginx and registry logs are clearly showing 401, so I'm probably missing some EV or something similar.

Are you sure you configured the registry to send notification to Portus? Are you sure the registry machine can actually connect to portus (for login and push it doesn't).

**Comment by tinybitsofnothingness** [comment]
@flavio thanks for the answer, let me maybe try to elaborate what am I trying to do here...

I have 2 domains, let's call them `my.hub.com` and `reg.hub.com`. I am using [nginx-proxy](https://github.com/jwilder/nginx-proxy) and [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) for setting up NginX with SSL.

I am running registry container like this:

    docker run -d -p 5000:5000 --restart=always --name registry \
      -v $(pwd)/certs:/certs:ro \
      -v $(pwd)/custom.yml:/etc/docker/registry/config.yml \
      -e VIRTUAL_HOST=reg.hub.com \
      -e LETSENCRYPT_HOST=reg.hub.com \
      -e LETSENCRYPT_EMAIL=info@hub.com \
      registry:2

then firing up NginX containers:

    docker run -d --name nginx -p 80:80 -p 443:443 \
      -v /var/run/docker.sock:/tmp/docker.sock:ro \
      -v $(pwd)/conf.d:/etc/nginx/conf.d:rw \
      -v $(pwd)/vhost.d:/etc/nginx/vhost.d:rw \
      -v /etc/nginx/certs:/etc/nginx/certs:ro \
      -v /usr/share/nginx/html \
      --link registry:registry \
      --restart=always \
      jwilder/nginx-proxy
    
    docker run -d --name nginx_ssl \
      -v /etc/nginx/certs:/etc/nginx/certs:rw \
      -v /var/run/docker.sock:/var/run/docker.sock:ro \
      --volumes-from nginx \
      --restart=always \
      jrcs/letsencrypt-nginx-proxy-companion

building Portus image:

    cd Portus
    docker build -t portus .

running Portus database:

    docker run -d --name=portus-database \
      --restart=unless-stopped \
      -e MYSQL_ROOT_PASSWORD=portus \
      library/mariadb

running portus web:

    docker run -d --name=portus \
      -e VIRTUAL_HOST=my.hub.com \
      -e LETSENCRYPT_HOST=my.hub.com \
      -e LETSENCRYPT_EMAIL=info@hub.com \
      -e RAILS_ENV=production \
      -e PORTUS_KEY_PATH=/certs/server.key \
      -e PORTUS_SECRET_KEY_BASE=long_string_here \
      -e PORTUS_MACHINE_FQDN=my.hub.com \
      -e PORTUS_PASSWORD=zepasswort \
      -e PORTUS_PRODUCTION_HOST=db \
      -e PORTUS_PRODUCTION_USERNAME=root \
      -e PORTUS_PRODUCTION_PASSWORD=portus \
      -e PORTUS_PRODUCTION_DATABASE=portus \
      --link=portus-database:db \
      -v $(pwd)/certs:/certs:ro \
      portus \
      puma -b tcp://0.0.0.0:3000 -w 3

and finally setting up the database:

    docker run --rm --name=temp \
      -e RAILS_ENV=production \
      -e PORTUS_KEY_PATH=/certs/server.key \
      -e PORTUS_SECRET_KEY_BASE=long_string_here \
      -e PORTUS_MACHINE_FQDN=my.hub.com \
      -e PORTUS_PASSWORD=zepasswort \
      -e PORTUS_PRODUCTION_HOST=db \
      -e PORTUS_PRODUCTION_USERNAME=root \
      -e PORTUS_PRODUCTION_PASSWORD=portus \
      -e PORTUS_PRODUCTION_DATABASE=portus \
      --link=portus-database:db \
      -v $(pwd)/certs:/certs:ro \
      portus \
      rake db:setup

I am using `custom.yml` file to configure my registry and it looks like this:

    version: 0.1
    loglevel: debug
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      host: reg.hub.com
      tls:
        certificate: /certs/server.pem
        key: /certs/server.key
    auth:
      token:
        realm: https://my.hub.com/v2/token
        service: reg.hub.com:5000
        issuer: reg.hub.com
        rootcertbundle: /certs/server.pem
    notifications:
      endpoints:
        - name: portus
          url: https://my.hub.com/v2/webhooks/events
          timeout: 500ms
          threshold: 5
          backoff: 1s

I have copied certificate and key for `reg.hub.com` into `/etc/docker/certs.d` and restarted docker service before everything:

    sudo mkdir -p /etc/docker/certs.d/reg.hub.com:5000
    sudo cp /etc/nginx/certs/reg.hub.com/fullchain.pem /etc/docker/certs.d/reg.hub.com:5000/ca.cert
    sudo cp /etc/nginx/certs/reg.hub.com/key.pem /etc/docker/certs.d/reg.hub.com:5000/ca.key

and also copied certificate to the host machine itself:

    sudo cp /etc/nginx/certs/reg.hub.com/fullchain.pem /usr/local/share/ca-certificates/reg.hub.com.crt
    sudo update-ca-certificates

At this moment I'm sort of sure that I messed up with copying the wrong certificates or with configuration in my `custom.yml` file. I'm not sure any more which certificates/keys should I copy where but obviously that's what's I'm missing to make everything work.

I have noticed one more thing on front-end side: when I go to dashboard's 'admin' page I see the error message on the top of the page saying: **The Portus user does not exist!**  
Not sure if that makes any difference for my setup, but somehow I think it is unrelated to my problem.

Any help with this is extremely appreciated! :)

**Comment by mssola** [comment]
> I have noticed one more thing on front-end side: when I go to dashboard's 'admin' page I see the error message on the top of the page saying: The Portus user does not exist!

That's because you haven't seed the database (and possibly you haven't migrated it). Take a look at what we do in the [compose-setup.sh](https://github.com/SUSE/Portus/blob/14fc5bcddd8b290b70f5adf7a674c562ca5162f0/compose-setup.sh#L60).

Hope this helps.

**Comment by tinybitsofnothingness** [comment]
@mssola ah, I see, you changed this just recently... Alright, I'll try with those commands, and try to figure out the certificate-domain-registryconfig confusion in my head...

**Comment by tinybitsofnothingness** [comment]
Yes, I can confirm that replacing `rake db:setup` with `sh -c "rake db:migrate:reset && rake db:seed"` when running the container fixes the mentioned "Portus user does not exist" message in admin page.

I am trying to figure out how to properly configure `custom.yml` file and I am generally confused with which certificate should I link and how to properly set up domain names. I created now 2 sets of certificates - for `my.hub.com` and `reg.hub.com` and copied them to folder which I'm sharing with containers. My `custom.yml` file looks like this now:

    version: 0.1
    loglevel: debug
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      host: my.hub.com
      tls:
        certificate: /certs/my.hub.com.pem
        key: /certs/my.hub.com.key
    auth:
      token:
        realm: https://my.hub.com/v2/token
        service: reg.hub.com
        issuer: my.hub.com
        rootcertbundle: /certs/my.hub.com.pem
    notifications:
      endpoints:
        - name: portus
          url: https://my.hub.com/v2/webhooks/events
          timeout: 500ms
          threshold: 5
          backoff: 1s

I also changed `PORTUS_KEY_PATH` variable to `/certs/my.hub.com.pem` value.
Is this proper registry configuration? If so, what should I enter when creating the registry in front'end and trying to log in from command line? Is it `my.hub.com:5000` or `reg.hub.com:5000`?

**Comment by mssola** [comment]
I believe this issue is no longer valid since the new images were created. Check the `examples` directory for usages of the new Docker image (but mind the current #1418 issue...).
