### ISSUE TITLE
Improve Dockerfile to allow configuration via compose

### ISSUE THREAD

**Issue by thenewguy** [SUSE/Portus#582]
I have spent some time toying with Portus and ran into some issues when trying to host it at a subpath url using compose.

I've put together a new Dockerfile to build Portus that allows all configuration to be overriden with compose using volumes and environment variables.

Would it be acceptable to change the base docker image and use nginx+passenger for serving the app?

Here is my Dockerfile:
```
FROM phusion/passenger-ruby22:0.9.17

RUN echo 'env COMPOSE;' > /etc/nginx/main.d/portus-env.conf
RUN echo 'env PORTUS_KEY_PATH;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env PORTUS_MACHINE_FQDN;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env PORTUS_SECRET_KEY_BASE;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env PORTUS_PASSWORD;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env PORTUS_PRODUCTION_DATABASE;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env SSL_CERT_FILE;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env RAILS_ENV;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env RACK_ENV;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env WSGI_ENV;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env NODE_ENV;' >> /etc/nginx/main.d/portus-env.conf
RUN echo 'env PASSENGER_APP_ENV;' >> /etc/nginx/main.d/portus-env.conf

RUN rm -f /etc/service/nginx/down

RUN rm /etc/nginx/sites-enabled/default

# install supervisord, this is required to run cronos
RUN apt-get update && apt-get install -y supervisor

RUN mkdir /portus
WORKDIR /portus

ADD Gemfile* /portus/
RUN gem install bundler && bundle install --retry=3
ADD . /portus

RUN chown -R app:app /portus
```

This Dockerfile has allowed me to configure portus and registry to be served via the same fqdn.  But it would also support more traditional deployments as well.

My compose files are a little complicated because I use an internal certificate authority so I have to pass in certs and keys.  But I would be happy to share them if the utility of my Dockerfile is not easily observed.

**Comment by mssola** [comment]
Hi @thenewguy, sorry for taking so long for us to respond. In this milestone we are going to re-bump our docker setup, and we will take this issue also in consideration.

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
