### ISSUE TITLE
The pagination only shows up after a complete reload of the page.

### ISSUE THREAD

**Issue by jloehel** [SUSE/Portus#585]
If a user add more than 10 team members or 15 namespaces at once a complete reload of entire webpage is necessary to trigger the pagination.

**Comment by vitoravelino** [comment]
Current status: 

- [X] Namespaces
- [ ] Teams
- [ ] Team members

**Comment by mssola** [comment]
@vitoravelino this is already the case for teams and team members no ?

**Comment by vitoravelino** [comment]
I fixed the namespaces tables. The teams and team members are still missing the refactoring.

**Comment by mssola** [comment]
@vitoravelino ok sorry then, I thought it was also applied to teams and teams members already 😁

**Comment by vitoravelino** [comment]
No worries! I want to do that soon. That would be really awesome!

**Comment by vitoravelino** [comment]
Finally able to close this after merging the last piece. :D
