### ISSUE TITLE
how portus comminication with personal registy on one's own initiative

### ISSUE THREAD

**Issue by testzlx** [SUSE/Portus#589]
here is the situation ,I build the personal registy successfully,and I use the crono to receive messages from the registy,however ,how can i send message in portus to the registy? for example
I create an acoount a in team A and A has no rights (no viewer,no admin ,no contributor ) to namspace B, so how can I send the right message to the registry so that the account a can not pull/push any images in namespace B .

**Comment by mssola** [comment]
I'm not sure I understand your question, but here I go :)

> I create an acoount a in team A and A has no rights (no viewer,no admin ,no contributor ) to namspace B, so how can I send the right message to the registry so that the account a can not pull/push any images in namespace B . 

It depends:

- Does the namespace `B` belong to the same team as namespace `A` ? If so, then `a` will have the same access as it has for the namespace `A` (e.g. viewer).
- If the namespace `B` belongs to a different team that the one that owns the namespace `A` (where the `a` account has been added), then you will need to add this account to the team that owns the namespace `B` (in pretty much the same way you added this account to the team that owns the namespace `A`). That is, the same account can be added to as many teams as you want.

For more information about teams, namespaces and users, please feel free to read our documentation [page](http://port.us.org/features/3_teams_namespaces_and_users.html) about this.

Does this answer your question?

**Comment by testzlx** [comment]
thank you for your reply,generally speaking,if I change the  access right of a role in the portus, how can the personal  registy know the change. in my opinion ,the portus should tell the change to the  personal registy,so in which method?

**Comment by mssola** [comment]
@testzlx It doesn't :) Take a look at [this](https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md#docker-registry-v2-authentication-via-central-service) document to get a better grasp on how this works.

In short, roles are a concept specific to Portus. That is, when you try to pull/push into the registry, the registry will first ask Portus if said user has permissions to perform the action. This is when roles & teams come into play.
