### ISSUE TITLE
Check ldap group membership

### ISSUE THREAD

**Issue by dkruscka** [SUSE/Portus#601]
Is it possible to implement an "LDAP group membership" check before the ldap login prozess starts?

br Detlef

**Comment by mssola** [comment]
LDAP groups support is one of the big things that we have yet to implement for LDAP support. There are certainly lots of things that we can do with LDAP groups, and it's on our roadmap. We'll keep you posted.

**Comment by mssola** [comment]
Closing in favor of #734.
