### ISSUE TITLE
Add an "internal" policy for namespaces

### ISSUE THREAD

**Issue by CleverWhiteWolf** [SUSE/Portus#606]
Hello!

First of all thank you for your project.

I have deployed Portus at our own environment and was able to connet it with our private docker registry. And I found that I cannot change permission access for global namespace. 

I need configure restricted access to our docker registry. So that everybody could pull/push docker images to/from registry only after authentication. 
Can I do such behavior using Portus?

Thanks.

**Comment by flavio** [comment]
Right now this is not possible.

As discussed with issue https://github.com/SUSE/Portus/issues/279 we are open to the introduction of a "protected" level in addition to "public" and "private".

**Comment by mssola** [comment]
Maybe instead of `protected` a better name would be `internal`, since it would reflect better the purpose of this policy.

**Comment by mssola** [comment]
I've changed the title to reflect better what's this feature actually about :)

**Comment by diranged** [comment]
Within the context of this ticket, I think an `internal` or `protected` setting makes sense. I think it should be specific to each namespace, and I think that the basic concept is correct. From a naming perspective, I do think `internal` makese sense for _me_, but frankly `protected` makes just as much sense. If other services (gitlab?) use `protected`, then I'd suggest using that.

**Comment by holgerreif** [comment]
Just to summarize the discussion (even if it would be clear for involved people) and to add a possible piece for documentation:

Namespaces carry an attribute according to their policy for read access. Read access is required to
   * pull images from the namespace
   * search for images (once a search endpoint in registry with sufficient access control is available)
   * listing of and search for namespaces and respositories at the web UI
The following access policies are implemented
   * a _private_ namespace is accessable only by team members
   * a _protected_ namespace is accessable by any authenticated account 
   * a _public_ namespace is accessable without any authentication
The policy for each name space is configured by the owner role of the team owning the namespace or by the user for his personal namespace.

As a special case the global namespace can only have the access policy _protected_ or _public_. 

BTW: I don't like the term _internal_ if not only for the fact that _private_ is kind of internal as well.

**Comment by mssola** [comment]
> Namespaces carry an attribute according to their policy for read access

For now, this is relegated to teams. Team admins assign which kind of policy do members have onto the belonging namespaces. @diranged has proposed (and I agree with him) that namespaces should be the one regulating the access policy, not teams (thus, teams would merely become bags of users). This will not be implemented for 2.1 though, because it's too disruptive.

> As a special case the global namespace can only have the access policy protected or public. 

I think that we never discussed this specific case actually :) I think it's fine to allow admins to set the global namespace as protected (note that push access would still be allowed only for admins).

**Comment by holgerreif** [comment]
> > Namespaces carry an attribute according to their policy for read access

> This is relegated to teams. Team admins assign which kind of policy do members have
> onto the belonging namespaces. 

Whether a namespace is public or not is defined at the namespace level (I doubble-checked - look at [pic from doc](http://port.us.org/build/images/docs/team-show.png).

At team level there is a defintion of additional rights (write access for all kinds of namespaces and read access for private namespaces)

> > As a special case the global namespace can only have the access policy protected or public.

> I think that we never discussed this specific case actually

I was more stating, that the global namespace could not be a private one. But just strike ~~protected~~

**Comment by mssola** [comment]
Seems like I miss-understood what you were saying, sorry :sweat_smile:
