### ISSUE TITLE
Portus hangs for a long time, after a docker push

### ISSUE THREAD

**Issue by Multiply** [SUSE/Portus#608]
We've set up Portus using the docker-compose route, using a registry on a different server. Everything works nicely, except for when we push new images, then portus hangs.

I've read about the nginx solution to the issue, and assumed puma in itself would solve the problem.

Puma was configured with `-w 3` and I tried to bump it to `-w 8 -t 16:32 --preload` to see if that solved the issue, but it really just ended up using more resources, and not fix the problem.

Is nginx or some other webserver that does proxying, a better choice for this kind of task, and will it actually solve the issue?

**Comment by mssola** [comment]
For Puma I'm using the setup as explained [here](http://port.us.org/docs/setups/3_nginx_bare_metal.html#puma). Maybe you need to configure that `on_worker_boot` call ? If this doesn't work, then I'm afraid that you'd have to try NGinx (or some other web server for this matter). For extra safety, make sure that NGinx has at least two workers.

**Comment by Multiply** [comment]
I'll give it a try, thanks!
