### ISSUE TITLE
Link to Appliance not working

### ISSUE THREAD

**Issue by primozcankar** [SUSE/Portus#609]
Link to: http://suse.github.io/docs/setups/2_appliance.html on http://suse.github.io/Portus/ is not working

**Comment by mssola** [comment]
It's http://port.us.org/docs/setups/2_appliance.html now. Where did you find this link ?

**Comment by primozcankar** [comment]
Found it at the bottom of the page on the word appliance: 
We provide also a ready to go **appliance based** on openSUSE.

**Comment by mssola** [comment]
We fixed that in the commit 7147f2f79e2134e2d78b58c0f9d2aa298939831c. But the real problem is that for some reason, in our github pages setup, suse.github.io/Portus is not redirecting to port.us.org :/ Let me investigate on this.

**Comment by mssola** [comment]
But until that is not fixed, just use http://port.us.org ;)

**Comment by flavio** [comment]
I think @eotchi is the only one who can help us.

**Comment by mssola** [comment]
AFAIK this has been fixed. Feel free to re-open if this is not the case.
