### ISSUE TITLE
portusctl error if RUBYLIB is not set

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/Portus#612]
We have found that under certain circumstances, portusctl fails to run bundler.

After debugging it, we found out that on our test machine RUBYLIB was set as

/usr/lib64/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/

which was causing bundler not being able to run, since this is a different version than the one we have in /srv/Portus/vendor/....

My guess is that this is because of rubygem-bundler being installed on that system.

The easiest solution would be to set that environment variable to our bundler directory, when running a bundle command.

**Comment by flavio** [comment]
> The easiest solution would be to set that environment variable to our bundler directory, when running a bundle command.

I agree

**Comment by mssola** [comment]
Fixed with PR  #613
