### ISSUE TITLE
Portus shows wrong amount of teams for admin user

### ISSUE THREAD

**Issue by Evalle** [SUSE/Portus#614]
I created 3 teams in Portus, and admin is a member of each of them 

![after3](https://cloud.githubusercontent.com/assets/2839811/11590258/3f7d6612-9a8f-11e5-9598-b10eb4ea02f0.jpeg)

but on users page I can see that admin is member of 5 teams

![after2](https://cloud.githubusercontent.com/assets/2839811/11590295/7941ac14-9a8f-11e5-8f51-6f78bc6e1302.jpeg)

**Comment by mssola** [comment]
Note that Portus shows the proper amount of teams, the only thing that to of them are "virtual"/"hidden". Therefore, this is not a bug but an enhancement, since it's not obvious from a user's perspective.
