### ISSUE TITLE
Permissions on server.key

### ISSUE THREAD

**Issue by JonathonReinhart** [SUSE/Portus#621]
I'm using Portus RPM Version 20151027090209, Release 1.1.

In #611 I explained how I set up Portus with my own keys/certs. In doing so, I ensured that the target of `/srv/Portus/config/server.key` (which is `/etc/apache2/ssl.key/portus.example.com.key`) was owned by root, and readable only by root (0400). This is a security best-practice; private keys shouldn't be visible to other users of the system.

However, this setup causes the following error to appear in `production.log`:
```
 INFO -- : Started GET "/v2/token?account=portus&scope=registry..."
...
FATAL -- :
Errno::EACCES (Permission denied @ rb_sysopen - /srv/Portus/config/server.key):
  lib/portus/jwt_token.rb:43:in 'binread'
  lib/portus/jwt_token.rb:43:in 'private_key'
  lib/portus/jwt_token.rb:20:in 'encoded_hash'
  app/controllers/api/v2/tokens_controller.rb:16:in 'show'
```

Apache handles this problem, by having the parent process, (running as `root`) read the SSL keys, and the forked child processes run as `wwwrun` (presumably "inheriting" the keys).

I'm not familiar with Passenger, but I'm assuming it is the `Passenger RubyApp: /srv/Portus (production)` process, running as `wwwrun`, who is trying to access this key. Is there some way that Passenger can work the same way, so that the key doesn't need to be readable by `wwwrun`?

**Comment by mssola** [comment]
I'm not familiar with Passenger either :( Let me take a look at this. In the meantime, @jordimassaguerpla or @flavio could take a look into this ?

**Comment by flavio** [comment]
@jordimassaguerpla AFAIK this is going to solved with v2. Am I right?

**Comment by jordimassaguerpla** [comment]
Yes this is solved in v2. It is a permission problem. You can workaround it by removing the symlinks and instead copying the keys.

**Comment by mssola** [comment]
Closing then. @JonathonReinhart, if you have any more problems with this, please, feel free to re-open this.

**Comment by JonathonReinhart** [comment]
I'll just wait for v2 then. Thanks again. Seems like I should just wait for v2 RPMs before reporting any more bugs :-)
