### ISSUE TITLE
Put logs in /var/log

### ISSUE THREAD

**Issue by JonathonReinhart** [SUSE/Portus#626]
Currently, logs are stored in `/srv/Portus/log`. It is much more customary to store logs in `/var/log`. Not only is this more expected, but it would allow them to be managed by [`logrotate`](https://www.suse.com/documentation/opensuse114/book_tuning/data/sec_tuning_logfiles_logrotate.html).

**Comment by JonathonReinhart** [comment]
There's also some inconsistency in the owner/group of the logs.  At different times, I've seen e.g. `production.log` owned by `root:root`, `root:www`, while the other logs are either `root:root` or `wwwrun:www`.  This makes it difficult to setup `logrotate`, which tries to respect permissions and ownership.

**Comment by mssola** [comment]
We've set them in `/src/Portus/log` because it's what a Rails application expects. But I think you're right, we should improve this situation.

**Comment by mssola** [comment]
@JonathonReinhart take a look at PR #662. A pretty simple solution to you case I think :)

**Comment by JonathonReinhart** [comment]
@mssola I believe you are right. As a web app application running under Apache (in the RPM installation), it makes sense to see things in the apache logs.
