### ISSUE TITLE
Issue while integrating Portus with registry 

### ISSUE THREAD

**Issue by endejoli** [SUSE/Portus#631]
Portus version : 2.0.0
OS: Ubuntu 14.04
Registry Version: 2.2.1

I am facing an issue with integrating registry with Portus. I have setup the portus, which is accessible over https://registry.mydomain.com/portus . In same server I am trying to setup the registry with below command

```
docker run -d -p 5000:5000 -v /etc/ssl/certs/registry.mydomain.com.crt:/etc/ssl/certs/registry.mydomain.com.crt -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt -v /etc/ssl/certs/root.crt:/etc/ssl/certs/root.crt -v /etc/ssl/private/registry.mydomain.com.key:/etc/ssl/private/registry.mydomain.com.key -e "REGISTRY_STORAGE=s3" -e "REGISTRY_STORAGE_S3_REGION=us-east-1" -e "REGISTRY_STORAGE_S3_BUCKET=registry" -e "REGISTRY_STORAGE_S3_ACCESSKEY=AAAAA" -e "REGISTRY_STORAGE_S3_SECRETKEY=BBBBBBBXX"  -e "REGISTRY_HTTP_ADDR=localhost:5000" -e "REGISTRY_HTTP_HOST=registry.mydomain.com" -e "REGISTRY_AUTH=token" -e "REGISTRY_AUTH_TOKEN_REALM=https://registry.mydomain.com/portus/v2/token" -e "REGISTRY_AUTH_TOKEN_ISSUER=registry.mydomain.com" -e "REGISTRY_AUTH_TOKEN_SERVICE=localhost:5000" -e "REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/etc/ssl/certs/root.crt" -e "REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME=registry" -e "REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=https://registry.mydomain.com/portus/v2/webhooks/events" -e "REGISTRY_NOTIFICATIONS_ENDPOINTS_BACKOFF=1s" -e "REGISTRY_NOTIFICATIONS_ENDPOINTS_THRESHOLD=5" -e "REGISTRY_NOTIFICATIONS_ENDPOINTS_TIMEOUT=500ms"  -e "REGISTRY_LOGLEVEL=debug" --name docker-registry registry:2.2.1
```

docker runs is successful, but from the server, if i try telnet localhost 5000, it gets connected and connection terminates immediately saying "Connection closed by foreign host."

```
$telnet localhost 5000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

I am not able to add registry to Portus web ( tried with localhost:5000). If I skip the remote check and add the registry, client login is failing

```
docker login https://registry.mydomain.com/portus 
Username: hound
Password:
Email: hound@test.com
Error response from daemon: Unexpected status code [404] :
```

If i run the above docker run command without -e "REGISTRY_HTTP_ADDR=localhost:5000", i see telnet connection doesn't get terminated. But still I am unable to add registry.

This may not be bug and could well be in something wrong I am doing. But I spent a whole day trialing this issue and didn't get any clue.    I am not able to figure out the issue at all, can anyone give me any clue?

PS: I was following the documentation => http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html

**Comment by flavio** [comment]
> If i run the above docker run command without -e "REGISTRY_HTTP_ADDR=localhost:5000", i see telnet connection doesn't get terminated. But still I am unable to add registry.

By doing that the registry process will listen to the loopback device of the container, hence the external port mapping won't work.

Try using `REGISTRY_HTTP_ADDR=0.0.0.0:5000`

Also you should not set `REGISTRY_AUTH_TOKEN_SERVICE` to `localhost:5000`. You should use the hostname of Docker host running the registry.

**Comment by endejoli** [comment]
Ok, I just updated REGISTRY_HTTP_ADDR=0.0.0.0:5000 and REGISTRY_AUTH_TOKEN_SERVICE=docker-registry:5000". Now the telnet connection doesn't get disconnected. 
But my database already has this enty

MariaDB [portus_production]> select * from registries;
+----+----------+----------------+---------------------+---------------------+---------+
| id | name     | hostname       | created_at          | updated_at          | use_ssl |
+----+----------+----------------+---------------------+---------------------+---------+
|  1 | registry | localhost:5000 | 2015-12-11 06:55:48 | 2015-12-11 06:55:48 |       0 |
+----+----------+----------------+---------------------+---------------------+---------+

So i should update the hostname to,  0.0.0.0:5000 correct?

**Comment by flavio** [comment]
No the hostname should match with what you specify for `REGISTRY_AUTH_TOKEN_SERVICE`

**Comment by endejoli** [comment]
Ok, did that. Now in Portus web UI, Registry updated successfully!   

But docker login still fails
docker login https://registry.mydomain.com
Password:
Email: hound@hp.com
Error response from daemon: no successful auth challenge for https://registry.mydomain.com/v2/ - errors: [token auth attempt for registry https://registry.mydomain.com/v2/: https://registry.mydomain.com/portus/v2/token?account=hound&service=docker-registry%3A5000 request failed with status: 500 Internal Server Error]

MariaDB [portus_production]> select * from registries;
+----+----------+----------------------+---------------------+---------------------+---------+
| id | name     | hostname             | created_at          | updated_at          | use_ssl |
+----+----------+----------------------+---------------------+---------------------+---------+
|  1 | registry | docker-registry:5000 | 2015-12-11 06:55:48 | 2015-12-11 08:26:54 |       0 |
+----+----------+----------------------+---------------------+---------------------+---------+

**Comment by flavio** [comment]
You have to do: `docker login registry.mydomain.com`

**Comment by flavio** [comment]
`docker login -u foo -p bar -e does-not-matter docker-registry:5000`

**Comment by endejoli** [comment]
I am bit confused here, as per the documentation http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html, it says
Portus is going to be reachable by visiting: https://docker.suse.con/portus.
Docker registry is going to be reachable at docker.suse.con on port 443.. 

So i should be able to login over 443 right? (https://registry.mydomain.com).
Also docker login docker-registry:5000 won't work from client machine since "docker-registry" is the name of my container(registry container), which is not accessible from outside world. Also if I am accessing registry over 5000 means, I have to keep port 5000  open and data is not encrypted as well. 

Am I not following the correct steps as per documentation :( ? Or is this not the way to setup registry to work with Portus?

**Comment by flavio** [comment]
You are mixing the deployment models. You are using containers and then referencing a guide that installs all the components in the "traditional" way on the same machine.

However a couple of clarifications:
  * portus is a web UI, you don't have to point your docker clients to it
  * docker clients need to be pointed to the host where distribution is running. If distribution is running on a port different from 80 or 443 then you must add the port number inside of the repository name (so `docker login my-docker-host.test.lan:5000`)

**Comment by endejoli** [comment]
I guess I have confused you with my explanation, sorry about that.  I am only using container for setting up distribution(registry:v2). I am not sure if we can setup the v2 registry in a traditional way(without using containers)  
Here is what I have done so far,
1. Set up Portus like any other rails application using apache, passenger and mariadb - working just fine and is accessible through URL https://registry.mydomain.com/portus
2.On the same server(registry.mydomain.com), setup the docker registry(registry:2.2.1) using the official docker image. I used the commands i posted in my 1st post of course with the modification you suggested.  I was able to add registry to portus through web UI. 
 
![reg](https://cloud.githubusercontent.com/assets/16251873/11750741/caff2e14-9fe9-11e5-8b9d-e6d401246458.JPG)

3. Now from host machine(my workstation) I am trying to login to distribution(for pushing and pulling images) using the command,
$ docker login https://registry.mydomain.com
Password:
Email: hound@mydomain.com
Then I got the error:

Error response from daemon: no successful auth challenge for https://registry.mydomain.com/v2/ - errors: [token auth attempt for registry https://registry.mydomain.com/v2/: https://registry.mydomain.com/portus/v2/token?account=hound&service=docker-registry%3A5000 request failed with status: 500 Internal Server Error]

Kindly let me know if this is not the right approach to setup Portus in production?

**Comment by mssola** [comment]
> I am not sure if we can setup the v2 registry in a traditional way(without using containers)

Yes, you can, just install it from your package manager (e.g. in openSUSE `zypper in docker-distribution-registry`. That being said, this is not the recommended way: by using the official container (the one you're using) and running it as stated in the documentation of the docker registry, it should be more than enough.

> Now from host machine(my workstation) I am trying to login to distribution(for pushing and pulling images) using the command, $ docker login https://registry.mydomain.com Password: Email: hound@mydomain.com Then I got the error:

As @flavio said: `docker login registry.mydomain.com:5000` or whatever you have set for the hostname in Portus (so from your image I guess that `docker-registry:5000` ?). Moreover, I see that in Portus you have set SSL off, but on docker login you are specifying `https`. Again, as @flavio said, just use the hostname (with the port).

**Comment by endejoli** [comment]
Ok I will try with these instructions once again.
The reason for turning ssl off is, I was following the documentation =>  http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html  [It says, 'As you can see the tls configuration has been dropped; this is no longer needed because Apache2 is already encrypting all the network traffic'.] May be I misunderstood that statement and it is not applicable  if registry is setup using container.    Also at the beginning of the documentation, it says
  . Portus is going to be reachable by visiting: https://docker.suse.con/portus.  (works just like explained)
  . Docker registry is going to be reachable at docker.suse.con on port 443.  (This is was the reason I was trying to login to my distribution with the command => docker login https://registry.mydomain.com

Really appreciate your reply. I will try once again and post the update

**Comment by mssola** [comment]
Hi @endejoli, is everything working for you now ? If not, would you mind continuing this conversation in our new mailing list: https://groups.google.com/forum/#!forum/portus-dev. If we figure that there's an actual bug in portus, we can open a new one. What do you think ?

**Comment by macropin** [comment]
I think this ticket should be flagged as a call to improve the documentation of setting up token auth. The official Docker Distribution/Registry docs are terrible.

**Comment by mssola** [comment]
Documentation has been improved (see [this page](http://port.us.org/docs/deploy.html) for example), lots of examples that work out of the box have been provided, etc. We can close this one :+1:
