### ISSUE TITLE
Support for management of registry's notifications

### ISSUE THREAD

**Issue by holgerreif** [SUSE/Portus#643]
Portus already gets all notifcations from the registry.
Redistribution of the notificaztions should be controlled by an authorization framework. This means, if a user has access to the registry he is allowed to register an endpoint for notifcation. I propose to filter the notifications not only by registry but by event type as well to fullfill the least privilige principle.

The notification sent by portus should follow the registry API in order to reuse possibly existing endpoints - portus just filters the notifications.

It is unclear to me whether an API for automated configuration of notifications and endpoint is needed. However I think extending the base funtionality to support API should be straight forward.

**Comment by flavio** [comment]
Portus leverages distrubution's notifications to built its internal knowledge of the external registry.

Are you proposing to extend Portus to broadcast distributions' notifications?

**Comment by holgerreif** [comment]
Partially. 
The difference between "simple broadcasting" and my proposal is:
- manage the notification subscriptions via web UI (currently they are hard coded into the registry's configuration)
- provide a means of autorization (who is allowed to receive notification for a given repsitory) and filtering (although I havn't seen other notifications besides for pull actions, the notification API spec doesn't restrict the actions)

**Comment by flavio** [comment]
> manage the notification subscriptions via web UI (currently they are hard coded into the registry's configuration)

This is something which should not exposed to the final user. Portus' uses the notification received from the registry to perform internal work, hence all the filter is decided by us according to the features we want to implement.

> provide a means of autorization (who is allowed to receive notification for a given repsitory) and filtering (although I havn't seen other notifications besides for pull actions, the notification API spec doesn't restrict the actions)

The notifications provided by distribution are translated into internal Portus' events. All these events are later exposed to the user according to their level of clearance.

For example: a push notification from distribution will trigger some internal events inside of Portus. These events will lead to the creation of an audit log about the creation of a new image. This event is going to be shown only to the users who have access to that repository or, in the case of a public repository, to all Portus' users.

I hope that clarifies your initial request. I'm going to close this issue, but feel free to provide more comments if something is not clear.

**Comment by holgerreif** [comment]
I understand the way portus internally uses the notifcations sent by the registry. However, what I proposed is an indepent use case.

Sure, we can somehow edit the registry's config from time to time and restart the registry container afterwards, however I'd see it as bad design, if two independent consumers have access to one config file.

Furthermore if we want to restrict access to notifications we have to implement some of the authenication and autorization engine that Portus has anyway.

Does it make more sense now?

**Comment by flavio** [comment]
> Sure, we can somehow edit the registry's config from time to time and restart the registry container afterwards, however I'd see it as bad design, if two independent consumers have access to one config file.

So you want to send registry's notification to Portus and to another service? Did I get it right?

Can you provide more details about what you plan to build and how portus can fit into the picture? I'm sorry but I'm still confused

**Comment by holgerreif** [comment]
The actual use case behind is the following: 

Suppose we have a base image A and an image B that is built FROM A.
Once A is updated we want to rebuilt image B. Thus we need a notification, that A was pushed so that another service (we are looking at jenkins right now) can trigger an automated build, tag and push of B.

Portus would be the place where the endpoints, that should get notifications, are registered and the place where the decision, whether or not the endpoint is entitled to get notified (based on access to the namespace) about the new image A.

**Comment by flavio** [comment]
Now I totally understand what you mean. This is something we have in mind, to achieve that the task has to be split into different topics. I'm going to file dedicated issues after the holiday season.

**Comment by holgerreif** [comment]
@flavio Could you look at this feature request again? 
I don't think it is important enough for upcoming 2.1 version, but I like it to be evaluated for the milestone after this.

**Comment by flavio** [comment]
> Suppose we have a base image A and an image B that is built FROM A.
> Once A is updated we want to rebuilt image B. Thus we need a notification, that A was pushed so that another service (we are looking at jenkins right now) can trigger an automated build, tag and push of B.

I created https://github.com/SUSE/Portus/issues/794 to track it.

**Comment by flavio** [comment]
I also created https://github.com/SUSE/Portus/issues/795.

Sorry for being so late...

**Comment by holgerreif** [comment]
That's fine, there are always more ideas then time ;-)
