### ISSUE TITLE
configuration of the Docker client

### ISSUE THREAD

**Issue by adidragomir** [SUSE/Portus#644]
Hi,
I tried to install Portus and Docker registry on the same machine accordingly with the guide. After many tries I was able to login, pull and push images from the registry. The only way to manage that was to configure the Docker client with the famous "--insecure-registry myregistrydomain.com:5000".
I did not find this requirement anywhere in the Portus documentation.
That's the good implementation? And if yes, could we put it in the documentation?

**Comment by jordimassaguerpla** [comment]
On 12/19/2015 04:40 PM, adidragomir wrote:
>
> Hi,
> I tried to install Portus and Docker registry on the same machine 
> accordingly with the guide After many tries I was able to login, pull 
> and push images from the registry The only way to manage that was to 
> configure the Docker client with the famous "--insecure-registry 
> myregistrydomaincom:5000"
> I did not find this requirement anywhere in the Portus documentation
> That's the good implementation? And if yes, could we put it in the 
> documentation?
>

Which version are you running? We had an issue in 1.0.1 regarding the 
file permissions of the keys which may be the cause ... You have version 
2.0 already in our development repos if you want to give it a try


http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/2.0.0/openSUSE_13.2/

http://download.opensuse.org/repositories/Virtualization:/containers:/Portus:/Release:/2.0.0/openSUSE_Leap_42.1/

**Comment by adidragomir** [comment]
The registry is working on a brand new vanilla installation OpenSuse Leap 42.1 with all the updates
Portus -2.0.0-3.1.x86_64
docker-distribution-registry-2.1.1-11.3.x86_64

**Comment by flavio** [comment]
I supposed you followed [this](http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html) documentation.

The registry runs on localhost (where localhost is the machine running the registry) without using SSL. However it's exposed to the world using apache that is indeed using the public IP of the machine running apahe.

If you access the registry using the public IP then you will have to use SSL. Is that what you are doing?

**Comment by adidragomir** [comment]
Hi Flavio,
Thank for your help.

Indeed I was using your documentation from: 

http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html

And of course I use the public IP of the machine running Apache, in fact the external IP address since I have a simple test environment.
My test environment is consist of two virtual machines with OpenSuse Leap 42.1 vanilla installation (I have snapshots to go back fast every time I need). These machines have one network card in the 192.168.2.x network and their hostnames are openX.local.com. Each machine has the other on the /etc/hosts file. 
First I was trying to setup Portus and registry on different machines but I could not (this is another discussion and I put my comment here:https://github.com/SUSE/Portus/issues/611).

So I followed your guide to implement Portus and registry on the same machine and finally I was able to add the registry to the Portus application with the settings:

hostname: 127.0.0.1:5000
SSL: disable

I was pointing the internet browser to the https://open1.local.com/portus

The only modification to the portus_and_registry.conf was:

   SSLCertificateFile /etc/apache2/ssl.crt/open1.local.com-ca.crt

My registry configuration is:

version: 0.1
loglevel: info
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
  delete:
    enabled: true
http:
  addr: localhost:5000
  host: open1.local.com

auth:
  token:
    realm: https://open1.local.com/portus/v2/token
    service: 127.0.0.1:5000
    issuer: open1.local.com
    rootcertbundle: /etc/registry/ssl.crt/portus.crt

notifications:
  endpoints:
    - name: portus
      url: https://open1.local.com/portus/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s

After adding successfully the registry I was creating a user and I was trying to login to the registry to push and pull images with the command:

docker login –u user –p user1234 –e user@user.com open1.local.com:5000

I’ve got the following error:

"v2 ping attempt failed with error: Get https://open1.local.com:5000/v2/: dial tcp 192.168.2.42:5000: connection refused"  

I was using docker-1.9.1-7.1.x86_64 and I did not make any other configuration.

The only way to login was to add “—insecure –registry open1.local.com:5000” setting to the /etc/sysconfig/docker and to delete the localhost setting from the registry configuration file as following:

http
  addr: :5000

If you need more details just let me know.

**Comment by flavio** [comment]
Ok, this is happening because the certificate used by the registry is unknown on the host. You have to add the certificate to all the machines that intend to access the registry.

You can follow modern distribution rules:

  * copy the certificate under `/etc/pki/trust/anchors`
  * run `update-ca-certificates`

Or you could place the file under: `/etc/docker/<registry hostnaname>/ca.crt` I'm not so sure about this path, I'm just writing down what I remember. Usually docker tells you the right path inside of the error message sent to journald.

**Comment by adidragomir** [comment]
I tried the method adding the certificate to the /etc/docker/certs.d/open1.local.com:5000/ path, restart the docker service and still not working because of the following error:
"Get https://open1.local.com:5000/v1/_ping: tls: oversized record received with length 20527."
It appears docker cannot pass the certificate to the registry or the registry does not recognize the certificate from the docker.

**Comment by adidragomir** [comment]
I am trying to put the certificate under /etc/pki/trust/anchors but it was already there. I run update-ca-certificates but the same error received.

**Comment by flavio** [comment]
Did you restart the docker daemon after having done that?

**Comment by adidragomir** [comment]
Of course, I mentioned that in my first comment after you make those suggestions.

**Comment by adidragomir** [comment]
The same behaviour is if I am trying to login from the registry machine or from the second machine.

**Comment by flavio** [comment]
Wait a second, let's focus on using the docker client from a machine that is not open1.local.com.

From such a machine you will be able to access the registry in that way:
`docker login open1.local.com`

There's no need to specify any port, that's the main purpose of the whole setup. You shouldn't even be able to access the registry by accessing it on port 5000; that's because according to your configuration it listens on localhost:5000, hence nothing is going to be listening on 0.0.0.0:5000.

The whole "insecure" thing happens because you are connecting straight to the registry without going through apache's reverse proxy. SSL is provided by apache, not by the registry with this configuration.

**Comment by adidragomir** [comment]
So I was trying to login from open42.local.com to the registry machine which is open1.local.com with
docker login –u user –p user1234 –e user@user.com open1.local.com (without port) and I get the following error:
"x509: certificate signed by unknown authority"

**Comment by flavio** [comment]
That happens because the certificate is unknown on open42. Make sure you add it, update the certificates and then restart the docker daemon. At least now we have proof it's working :)

**Comment by adidragomir** [comment]
I just did it before you post the comment and is working now :)

**Comment by adidragomir** [comment]
In my opinion the documentation should be updated by mentioning the docker clients machines should have the certificates updated with the registry machine certificate at the machine level ( it's not enough to copy the certificate to the /etc/docker/certs.d/registry.com:5000/ca.crt, in fact it's working without ca.crt file).
And I do not know if the same procedure should be done on the registry and Portus machine, I will test later.

**Comment by adidragomir** [comment]
I recreate all the testing environment from the beginning to make sure is working. So for login all to do is to copy the certificate from the registry machine to the docker client machine to the /etc/pki/trust/anchors/ path and run update-ca-certificates.
But when I tried to push a busybox image tagged as open1.local.com/busybox, I've got the error:
"ac6a7980c6c2: Pushing 1.024 kB
Error parsing HTTP response: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n  \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n<head>\n<title>Method not allowed!</title>\n<link rev=\"made\" href=\"mailto:%5bno%20address%20given%5d\" />\n<style type=\"text/css\"><![CDATA[/*></style>\n</head>\n\n<body>\n<h1>Method not allowed!</h1>\n<p>\n\n\n    The PATCH\n    method is not allowed for the requested URL.\n    \n</p>\n<p>\nIf you think this is a server error, please contact\nthe <a href=\"mailto:%5bno%20address%20given%5d\">webmaster</a>.\n\n</p>\n\n<h2>Error 405</h2>\n<address>\n  ...."

**Comment by adidragomir** [comment]
I reproduce the issue with the docker push in a brand new test environment. There is no problem with the certificates, in fact there is no errors in the logs.
Just the above feedback from the docker push command:
Error parsing HTTP response: invalid character '<' looking for beginning of value:
Method not allowed:The PATCH\n method is not allowed for the requested URL

Docker login is working well.

**Comment by flavio** [comment]
Ok, I'll try to reproduce the issue later

**Comment by vanveele** [comment]
I had a similar issue after running portusctl. I was able to correct the "Error 405" by editing the http->host in /etc/registry/config.yml to point to "https://portus.fqdn.hostname" since this was set to "portus.fqdn.hostname" . I was then able to push an image after a restart of the registry service to pick up the change.

**Comment by adidragomir** [comment]
Unfortunately I could not get rid of the "error 405". My two cents is the HTTP request has a typo ("invalid character '<' looking for beginning of value").

**Comment by apatard** [comment]
Got similar issues while playing with http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html some months ago. Forgot to mention here that I found a workaround (solution?) for this:

1. Add to your vhost configuration : `RequestHeader set X-Forwarded-Proto "https"`
2. Enable apache mod_header module (and restart apache)

**Comment by adidragomir** [comment]
Well done!! Bravo !! Your solution is the right one...this two settings should be add to the guide!
