### ISSUE TITLE
OAuth Authentication

### ISSUE THREAD

**Issue by liamdawson** [SUSE/Portus#645]
It would be awesome to support logins in Portus from other source (such as Gitlab), as it would be one less account developers need. Any plans to provide this functionality, or can anyone provide me pointers on what changes would need to be made? I would personally add omniauth, and integrate it that way, as there's support for a lot of authentication methods. For reference, in this scenario, Gitlab lets you specify a Gitlab password for HTTPS git authentication.

**Comment by mssola** [comment]
This is something that we plan to discuss soon. I'll leave a comment here once we have a roadmap for the next milestone :)

**Comment by jsindy** [comment]
OAuth support would be awesome! SSO FTW!

**Comment by qrpike** [comment]
+1

**Comment by bufferoverflow** [comment]
I suggest using [omniauth](https://github.com/intridea/omniauth) based oauth2, this would allow other authentication to be used as well.

**Comment by mohamedhaleem** [comment]
+1

**Comment by GerDner** [comment]
+1

**Comment by jared-m-combs** [comment]
+1

**Comment by qwding** [comment]
+1

**Comment by lborguetti** [comment]
+1

**Comment by soumyadipDe** [comment]
+1

**Comment by tlvenn** [comment]
Any update on this ?

**Comment by mssola** [comment]
@tlvenn as you can see [here](http://port.us.org/docs/release-schedule.html), this will not make it for the next release. This doesn't mean that we will not accept PR's on this regard, but we wanted to prioritize some other tasks and we wanted to have a narrower focus for the next release.

**Comment by avaranovich** [comment]
Did someone progress on integration with omniauth?
