### ISSUE TITLE
portus with Active Directory as a LDAP:  no more notifications ?

### ISSUE THREAD

**Issue by xinity** [SUSE/Portus#646]
hi,

since we rebuild our portus installation with ldap (active directory integration), we can no more see docker images pushed to the registry

both registry v2 and portus are behind an nginx

is it related to the fact that our username are all appended with numerical ? how to avoid this by the way ?

any clues ?

thanks a lot for your help, we only need these little steps to finally complete our portus production system

regards,

**Comment by flavio** [comment]
> since we rebuild our portus installation with ldap (active directory integration), we can no more see docker images pushed to the registry

Did you nuke the old database used by portus?

> is it related to the fact that our username are all appended with numerical ? how to avoid this by the way ?

Can you provide more details about that?

**Comment by xinity** [comment]
We did nuke database yep. 

For ldap account here's an example. 
My account is xinity and I log-in portus as xinity, but my account in portus dashboard is xinity563 

Account are in form domain\account in our active directory. 

For the time being regarding notification, waiting to fix it, we use crono with 10 seconds of activation time. 

Feel free to ask if needed more informations. 

Regards

**Comment by xinity** [comment]
notifications works , sorry for the bad issue, miss configuration on our side
