### ISSUE TITLE
encryption_private_key_path where to set Password for keyfile like in Apache SSLPassPhraseDialog

### ISSUE THREAD

**Issue by franky4u** [SUSE/Portus#647]
When key file ist password protected one can't log in via 'docker login -u <user> -p <password> -e <email> docker-registry-fqdn
There should be a mechanism like Apache SSLPassPhraseDialog to provide a password for the key file

**Comment by flavio** [comment]
Are you talking about the key pointed by `config/secrets.yml -> encryption_private_key_path`?

**Comment by franky4u** [comment]
Yes, it looks like that I can't login when this key is  passphrase protected.
In  my portus_and_registry.conf for Apache I use SSLPassPhraseDialog to automate Apache start with a script that gets the passphrase from a password store....

SSLPassPhraseDialog exec:/erv/bin/get_erv-global.net_pwd_local.sh
<VirtualHost *:443>
   ServerName docker
   ServerAlias docker.erv-global.net portus portus.erv-global.net
   SSLEngine on
   SSLProxyEngine On
   SSLProtocol all -SSLv2 -SSLv3
   SSLHonorCipherOrder on
   SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
   SSLCompression on

   SSLCertificateFile /etc/apache2/ssl.crt/v1290.erv-global.net-ca.crt
   SSLCertificateKeyFile /srv/Portus/config/server.key

   RewriteEngine On

   RewriteCond %{HTTP_HOST} ^portus$ [OR]
   RewriteCond %{HTTP_HOST} ^portus\.erv-global\.net$
   RewriteCond %{REQUEST_URI} !^/portus.*$
   RewriteRule ^/(.*)$ "https:\/\/docker\.erv-global\.net\/portus\/$1" [P,L]

   RewriteCond %{REQUEST_URI} !^/portus.*$
   RewriteRule ^/(.*)$ "https:\/\/docker\.erv-global\.net\:5000\/$1" [P,L]

   Alias /portus /srv/Portus/public
   <Location /portus>
     PassengerBaseURI /portus
     PassengerAppRoot /srv/Portus
   </Location>

   <Directory /srv/Portus/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
      # Uncomment this if you're on Apache >= 2.4:
      Require all granted
      SetEnv GEM_PATH /srv/Portus/vendor/bundle/ruby/2.1.0
      SetEnv PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY 0
      SetEnv PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY 0
      PassengerAppEnv production
   </Directory>
</VirtualHost>

**Comment by flavio** [comment]
Yeah, apache is not going to help AFAIK. Some code need to be added to Portus to unlock the code from the rails process.

**Comment by franky4u** [comment]
So it would be handy to configure a script in config.yml that provide this code with the passphrase - right?

**Comment by franky4u** [comment]
Sorry in secrets.yml I meant.

**Comment by flavio** [comment]
I would pass that via an environment variable, I think it would be safer than writing the plaintext password straight to secrets.yml

**Comment by franky4u** [comment]
Well, Apache get it via stdin from the script and so it is the same way to use it - In addition an environment variable could also be handy for someone.

**Comment by mssola** [comment]
We moved away from Apache since quite a long time ago. Closing...
