### ISSUE TITLE
crono logs auth token required : Portus + LDAP config

### ISSUE THREAD

**Issue by xinity** [SUSE/Portus#648]
anyone can tell me why crono is filling up my disk with this kind of logs ?

```
registry_1 | 172.17.3.187 - - [28/Dec/2015:07:17:33 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 200 20 "" "Ruby"
registry_1 | time="2015-12-28T07:17:43.548451343Z" level=warning msg="error authorizing context: authorization token required" environment=staging http.request.host=registry.[domain].com http.request.id=e3e6ef26-0022-4d92-a902-5b6174ed60a1 http.request.method=GET http.request.remoteaddr=172.17.42.1 http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=223612f2-7984-44d0-8538-417bf01766c5 service=registry version=v2.1.1 
registry_1 | 172.17.3.187 - - [28/Dec/2015:07:17:43 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 161 "" "Ruby"
```

seems i have to make crono "login" into the registry, but i may have missed how to :(

any clues maybe ?

**Comment by flavio** [comment]
Which version of portus are you using, how did you deploy it?

**Comment by xinity** [comment]
deployed using docker-compose using a cloned repo last tuesday.

i've build portus_web container without the ENV regarding compose
and deployed the whole stack using this compose file:
```
web:
  image: portus_web
  command: puma -b 'tcp://0.0.0.0:3000' -w 3
  environment:
    VIRTUAL_HOST: webregistry.[mydomain].com
    VIRTUAL_PORT: 3000
    RAILS_ENV: production
    PORTUS_KEY_PATH: /etc/nginx/ssl/registry.[mydomain].com.key
    PORTUS_SECRET_KEY_BASE: [my key]
    PORTUS_MACHINE_FQDN: webregistry.[mydomain].com
    PORTUS_PASSWORD: [Portus Password]
    PORTUS_PRODUCTION_HOST: db
    PORTUS_PRODUCTION_USERNAME: root
    PORTUS_PRODUCTION_PASSWORD: [PASSWORD]
    PORTUS_PRODUCTION_DATABASE: portus
    AUTH_ENABLED: 0
    FILTERED_METHOD: 0

  volumes:
    - /home/synodocker/conf/registrycerts:/etc/nginx/ssl/
    - /home/synodocker/conf/Portus/config-prod.yml:/portus/config/config.yml
  links:
    - db
  container_name: webregistry.[mydomain].com
  domainname: [mydomain].com
  hostname: webregistry

crono:
  image: portus_web
  command: /usr/bin/supervisord
  environment:
    RAILS_ENV: production
    PORTUS_KEY_PATH: /etc/nginx/ssl/registry.[mydomain].com.key
    PORTUS_SECRET_KEY_BASE: [my key]
    PORTUS_MACHINE_FQDN: webregistry.[mydomain].com
    PORTUS_PASSWORD: [Portus Password]
    PORTUS_PRODUCTION_HOST: db
    PORTUS_PRODUCTION_USERNAME: root
    PORTUS_PRODUCTION_PASSWORD: [PASSWORD]
    PORTUS_PRODUCTION_DATABASE: portus
    CATALOG_CRON: "10.seconds"
  links:
    - db
  container_name: portus_cron
  hostname: portuscron


db:
  image: library/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: [PASSWORD]
  container_name: portus_db
  hostname: portusdb

registry:
  image: library/registry:2.1.1
  volumes:
    - /conf/registryv2:/registry
    - /registry_data:/var/lib/registry/
    - /conf/registrycerts:/etc/nginx/ssl/
  entrypoint: /registry/entry.sh
  env_file: /conf/registryv2/environment
  links:
    - web
  environment:
    VIRTUAL_HOST: registry.[mydomain].com
    VIRTUAL_PORT: 5000
    FILTERED_METHOD: 1
    AUTH_ENABLED: 0
    DOCKER_REGISTRY: 1
  container_name: registry.[mydomain].com
  domainname: [mydomain].com
  hostname: registry
``

**Comment by xinity** [comment]
how does crono gets authenticated to the registry ?
is there anywhere to pass the correct credentials ?

as far as i dig in, it seems it's a credential issue as we have connected portus to our LDAP server

**Comment by flavio** [comment]
Crono uses the "portus" special user that is created during the initialization of the database. That should work even when LDAP is being used.

**Comment by xinity** [comment]
@flavio thanks for your reply, as i have a portus user in my LDAP , can i use it ? how to pass the password of my LDAP account ?

**Comment by flavio** [comment]
The crono job allocates a new instance of `RegistryClient` from [there](https://github.com/SUSE/Portus/blob/master/app/jobs/catalog_job.rb#L10). The instance is instatiated [here](https://github.com/SUSE/Portus/blob/master/app/models/registry.rb#L32). As you can see the `RegistryClient` [constructor](https://github.com/SUSE/Portus/blob/master/lib/portus/registry_client.rb#L15) uses the `portus` username and the secret password by default.

I don't suggest to change this piece of code to get the password from LDAP. Most users do not want to introduce artificial user inside of their LDAP directory.

**Comment by xinity** [comment]
@flavio thanks a lot, i won't change a piece of code :)

if i understand correctly their is a portus user created as DB initialization, i guess the password is portus ?

this user then can access the registry right ?

and these are credentials used by crono right ?

**Comment by flavio** [comment]
As you can see [here](https://github.com/SUSE/Portus/blob/master/lib/portus/registry_client.rb#L16) the password is stored inside of [rails' secrets](https://github.com/SUSE/Portus/blob/master/config/secrets.yml#L49).

The value of the password depends on the rails environment that you are using. You are using the compose setup, which is meant just for testing. So you are using the development environment, which inherits from the default one: "portus1234". This is insecure of course, that's why on production mode we behave in a different way.

**Comment by xinity** [comment]
then i really don't understand why crono trigger these logs ... as i override this password using:
`    PORTUS_PASSWORD: [Portus Password] `

i can't figure out why my registry complains.
any chances i can put crono in debug mode ?

**Comment by flavio** [comment]
Oh wait, you are using a custom compose file.

Are you sure the database has been initialized when running on production mode?

Are you also sure other users can actually log into the registry?

**Comment by xinity** [comment]
here how i start my env:
- docker-compose -f [mycompose.yml] up -d
- docker-compose -f [mycompose.yml] run --rm web rake db:create
- docker-compose -f [mycompose.yml] run --rm web rake db:migrate
- docker-compose -f [mycompose.yml] run --rm web rake db:seed

all my ldap users can login into portus AND to the registry (tested by pushing docker images).

**Comment by flavio** [comment]
Try to remove the portus user from the database and then do:
`docker-compose -f [mycompose.yml] run --rm web rake portus:create_api_account`

**Comment by xinity** [comment]
"Try to remove the portus user from the database and then do:"
- directly in the mysql db or using rake ?

**Comment by flavio** [comment]
There's no rake task for that, you have to do that manually. Either from mysql or using rails' console (if you are familiar with it)

**Comment by xinity** [comment]
ok, i'll try and let you know ASAP

thanks for your precious help @flavio

**Comment by xinity** [comment]
FYI, i had to remove the namespace of the user portus as well.

i'll try restart crono and see how it goes

**Comment by xinity** [comment]
ok i did it all , 

new error now (knocking my head!):
`registry_1 | time="2015-12-29T09:23:44.41544458Z" level=warning msg="error authorizing context: insufficient scope" environment=production `

as if the portus user doesn't have sufficient privileges ?

**Comment by flavio** [comment]
That's new to me, we need more time to look into that issue.

**Comment by xinity** [comment]
no problemo, if needed more informations let me , i'll try and dig in

**Comment by xinity** [comment]
all right , starting from scratch but with a registry allready populated.

crono works correctly as it updates the mysql db with the already populated docker images of the registry.

i still have those logs filling up my disk:
```
time="2015-12-29T09:54:52.823027845Z" level=warning msg="error authorizing context: authorization token required" environment=production http.request.host=registry.mydomain.com http.request.id=81e0c8f5-961b-4bdd-983a-bc7559a155e4 http.request.method=GET http.request.remoteaddr=172.17.42.1 http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=26d898e8-f780-4cf5-b34e-e8b0f8568806 service=registry version=v2.1.1 
172.17.3.187 - - [29/Dec/2015:09:54:52 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 161 "" "Ruby"
time="2015-12-29T09:54:52.971118778Z" level=info msg="response completed" environment=production http.request.host=registry.mydomain.com http.request.id=06084a15-b001-40a0-b0c4-4a5adf25c90a http.request.method=GET http.request.remoteaddr=172.17.42.1 http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.43801ms http.response.status=200 http.response.written=30 instance.id=26d898e8-f780-4cf5-b34e-e8b0f8568806 service=registry version=v2.1.1 
172.17.3.187 - - [29/Dec/2015:09:54:52 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 200 30 "" "Ruby"
time="2015-12-29T09:54:52.984795674Z" level=warning msg="error authorizing context: insufficient scope" environment=production http.request.host=registry.mydomain.com http.request.id=f46bc5bb-f944-4a13-8695-10497e0d4c01 http.request.method=GET http.request.remoteaddr=172.17.42.1 http.request.uri="/v2/alpine/tags/list" http.request.useragent=Ruby instance.id=26d898e8-f780-4cf5-b34e-e8b0f8568806 service=registry vars.name=alpine version=v2.1.1 
172.17.3.187 - - [29/Dec/2015:09:54:52 +0000] "GET /v2/alpine/tags/list HTTP/1.1" 401 167 "" "Ruby"
time="2015-12-29T09:54:53.123398323Z" level=info msg="response completed" environment=production http.request.host=registry.mydomain.com http.request.id=f061399c-0469-49cb-9f4a-f6c5915a9364 http.request.method=GET http.request.remoteaddr=172.17.42.1 http.request.uri="/v2/alpine/tags/list" http.request.useragent=Ruby http.response.contenttype="application/json; charset=utf-8" http.response.duration=2.520922ms http.response.status=200 http.response.written=38 instance.id=26d898e8-f780-4cf5-b34e-e8b0f8568806 service=registry version=v2.1.1 
172.17.3.187 - - [29/Dec/2015:09:54:53 +0000] "GET /v2/alpine/tags/list HTTP/1.1" 200 38 "" "Ruby"
```

everything seems to be running fine, but it generates too much logs :(

i'm now sure it's related to crono as, i no more have logs when i stop crono 

i just can't find what's going on :(

**Comment by weynhamz** [comment]
This is how I get it fixed.

Login into the database:

```
USE portus;
SHOW TABLES;
SELECT * FROM users;
DELETE FROM users WHERE username = 'portus';
SELECT * FROM teams;
DELETE FROM teams WHERE name = 'portus';
SELECT * FROM namespaces;
DELETE FROM namespaces WHERE name = 'portus';
```

`docker exec -i -t portus bash`

`rake portus:create_api_account`
