### ISSUE TITLE
Help with getting portus site to use port 80, and registry port 443 (https)

### ISSUE THREAD

**Issue by farahfa** [SUSE/Portus#652]
Hello all,

Can anyone help me (or point me to the right documentation) on how to port forward both the portus site (from 3000 to 80) and the registry (from 5000 to 443), the goal is to have http://dockerhub.domain.com point to the portus site, and https://dockerhub.domain.com point to the registry (for downloading images..etc).

Any help is appreciated,

Fadi

EDIT: At this point of time everything is working fine, however I really don't like it having others to type http://dockerhub.domain.com:3000/ and every time they want to upload/download an image they would have to type dockerhub.domain.com:5000/repo/image .. etc. 

EDIT2: My current situation is I have a self signed SSL cert (will that be a problem, I know it'll have to be located in both the registry server and the server where docker engine is installed and trying to download the images from the private registry). But this will change soon so I will have a proper certificate.

**Comment by ArcticSnowman** [comment]
I run Portus on 443 and Registry on 5000 -   I put a nginx container in front of the Portus container to handle the 443 to 3000 (and do the SSL termination)

**Comment by farahfa** [comment]
So in my case I would have to run an nginx container infront of the Portus container to handle both 80 to 3000 and 443 to 5000?

I'm still relatively new to nginx and I'm trying to figure out how this can be done. Would it be a bother if I asked you to share your nginx config for your setup? Just so I can see how you've done it and learn/modify it to suit my needs?

**Comment by egidijus** [comment]
@farahfa have a look here https://github.com/SUSE/Portus/issues/667

**Comment by mssola** [comment]
@farahfa take a look at #667. Thanks @egidijus for stepping in :+1:
