### ISSUE TITLE
port number lost in self-referential URLs when proxying

### ISSUE THREAD

**Issue by sshipway** [SUSE/Portus#656]
In order to add SSL to Portus, I added an nginx proxy in front of it.  
Since port 443 was in use, I set the on port 8443, forwarding to portus on port 3000.

When using the https://hostname:8443/ URL, clicking on buttons would lose the :8443 and end up forwarding to https://hostname/ instead.

If there is no proxy, then port numbers are not dropped ( http://hostname:3000 works fine ) but they are lost when proxying.

Is there a known good nginx proxy configuration, or a specific header that needs to be set on the proxy for this to work correctly?

nginx config:
````
upstream portus {
    server portus:3000;
}

server {
    listen 8443 ssl;
    server_name rancher.container.auckland.ac.nz;
    ssl_certificate     certs/rancher.container.auckland.ac.nz.crt;
    ssl_certificate_key certs/rancher.container.auckland.ac.nz.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://portus;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 900s;
    }
}
````

**Comment by sshipway** [comment]
The issue seems to affect user-related tasks; /users/edit, /usrs/sign_out, and so on

**Comment by mssola** [comment]
Not an expert on NGinx :P, but you can take a look at the configuration that I'm using: http://port.us.org/docs/setups/3_nginx_bare_metal.html#nginx. Be aware of stuff like `proxy_set_header X-Forwarded-Host` and such.

**Comment by sshipway** [comment]
The problem seems to be the X-Forwarded-Host needs to be set, AND include the port number.  I now have it working with SSL in all cases on a nonstandard port!

This is the final required nginx.conf :
````
server {
    listen 443 ssl;
    ssl_certificate     certs/portus.crt;
    ssl_certificate_key certs/portus.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://portus:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 900s;
    }
}
````
Portus was started with `PORTUS_CHECK_SSL_USAGE_ENABLED=true`, `--name portus` and no port mapping.

**Comment by sshipway** [comment]
The important bit is `proxy_set_header X-Forwarded-Host $http_host;`.  This passes the hostname *and port* in the requested URL down the chain so that it is used for self-referential URLs.

**Comment by mssola** [comment]
Once #661 is merged, the documentation will be updated with `$http_host` in the forwarded host. Thanks for pointing this out!
