### ISSUE TITLE
running everything as root

### ISSUE THREAD

**Issue by egidijus** [SUSE/Portus#664]
Running things as root (anywhere) is bad and should not be done.
this is what we have been doing so far with other dockers:
build a base image and add the `user` and set `guid`s in the base image:

### your base Dockerfile
```
FROM alpine:3.2
ENV TERM=xterm
ENV PROJECT_NAME=tango
RUN adduser -S $PROJECT_NAME && addgroup -S $PROJECT_NAME && addgroup $PROJECT_NAME $PROJECT_NAME
ADD Dockerfile /base.Dockerfile
```
* Note `ADD Dockerfile /base.Dockerfile` is a good way of tracking how the image was built, and you always have the Dockerfile.

`docker build -t portus-base .`

Now every single Dockerfile you create should have `FROM portus-base`
Every image will have the user `tango`

https://github.com/tianon/gosu
Using gosu, you can change the user as which  the process runs.
You may need to have root in the image because of reasons.
Gosu allows you to run the app as tango
`gosu tango nginx`

You can also `chown -R` in your entrypoint file, because the $PROJECT_NAME variable is available in any containers/images built from the new base.

### example entrypoint for nginx
```
#!/bin/sh
mkdir -p /etc/nginx/sites-enabled/
mkdir -p /var/log/nginx
mkdir -p /var/nginx-cache

chown -R $PROJECT_NAME /var/log/nginx
chgrp -R $PROJECT_NAME /var/log/nginx
chmod -R 0775 /var/log/nginx

chown -R $PROJECT_NAME /var/nginx-cache
chgrp -R $PROJECT_NAME /var/nginx-cache
chmod -R 0775 /var/nginx-cache

unset affinity:container
#pongo-blender is a go app that uses jinja2 templating to generate configurations
/usr/bin/pongo-blender /etc/pongo-blender/nginx.conf.tmpl > /etc/nginx/nginx.conf
/usr/bin/pongo-blender /etc/pongo-blender/site.conf.tmpl > /etc/nginx/sites-enabled/site.conf
/usr/bin/pongo-blender /etc/pongo-blender/mime.types > /etc/nginx/mime.types

env
chown -R $PROJECT_NAME /var/lib/nginx
chgrp -R $PROJECT_NAME /var/lib/nginx
chmod -R 755 /var/lib/nginx

gosu tango nginx

```

This way, all containers that share volumes, will have enough permissions to the shared volumes.

**Comment by cyphar** [comment]
One issue we have is that we need to bind to "privileged ports" (one of the few mistakes in the Unix design IMO). There are ways around this issue (`--cap-add NET_ADMIN`). However, IIRC `nginx` knows what to do when it's run as root (it listens on port `80` then drops privileges for all of the actual worker processes).

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
