### ISSUE TITLE
Portus docker container should have SSL option natively

### ISSUE THREAD

**Issue by sshipway** [SUSE/Portus#665]
When creating a container from the Dockerfile, the resulting Portus web interface does not use SSL.

It would be helpful to be able to pass environment variables with the cert/key paths and enable SSL on the web interface, rather than having to use a separate nginx proxy container.

This would get around all problems with proxy configuration, and would make configuration simpler

**Comment by mssola** [comment]
> When creating a container from the Dockerfile, the resulting Portus web interface does not use SSL.

Bear in mind that our current Docker/Compose setup is for development purposes only. That's why we are not using SSL.

> It would be helpful to be able to pass environment variables with the cert/key paths and enable SSL on the web interface, rather than having to use a separate nginx proxy container.

Would that even work ? I mean, in order to get the application notice the changes on the configuration safely, you'd have to restart the process, which would effectively destroy the container itself. Right ?

> This would get around all problems with proxy configuration, and would make configuration simpler

I agree with you. The current setup was meant for development purposes only, and hence all the pains when configuring it for production. That being said, currently I don't see many ways in which we can alleviate these pains. Ideally we would provide a minimalistic image, so it's reduced in size and sufficiently flexible for any kind of setups.

That being said, improving the docker/compose setup is a top priority for us, and we will try to make it better for this milestone.

**Comment by sshipway** [comment]
OK, I had not realised that this was still considered beta.  Even with this caveat, it still seems to me to be the best solution available, and provides a very good authentication and web UI.

I have done some tweaks on a fork of Portus, and have changed the Exec command to run a shellscript which starts up the portus instance.  Before doing this, it uses environment variables to create missing certificates, initialise the database, create the API user, configure the Registry (I added a new rake task for this) and so on.  You could easily do this to edit configuration files; and in any case, you already take env vars to configure Portus - surely SSL configuration could be held in there as well?

The three biggest issues I had with the Dockerfile as shipped were (1) no SSL support (so I needed a separate Nginx container to wrap this), (2) it did not initialise the database (I added these to a startup shellscript), and (3) there was no way to automatically configure the Registry (I added a new Rake task for this and added it to the startup shellscript).  It would be great if these were addressed as the Docker support moves out of beta and into production.

I think a lot of people will be very happy to discover Portus, and even moreso to be given improved docker/compose support.

A minimalist image is always great, provided that there are ways to enable features at startup via env vars as well as mounting volumes.  We use a Rancher cluster, and so volume mounts (and autoconfiguring items in them) are a bit more problematic.

I have been defining a Rancher Template to build a complete registry system (with Portus as the Auth backend and web UI) since it is one thing hugely in demand in the Rancher community.  See my git repos for the Portus fork and Rancher catalogues if interested.  I suspect you may get a lot more people trying out Portus now that people know registry+portus works with Rancher.

Thanks for your work on this!

**Comment by cpoole** [comment]
I think it would be nice to slim down the container image as well. As it currently runs it's a pretty heavy image. https://github.com/h0tbird/docker-portus is a great example of a lightweight container where every portus setting can be enabled with an environment variable. @sshipway I believe your container works similarly with a startup script to sed all of the config.yml variables.

**Comment by sshipway** [comment]
@cpoole - yes, my startup script uses various env vars to set up the config.  It also creates a certificate (if one does not already exist) using the env vars, and spits out an haproxy config file that can be then mounted to an haproxy container to provide SSL over the top.  It also calls the various rake tasks to set up the database and pre-configure the registry URL.

Several people have complained about the bloat in my Portus container; having an official slimmed-down one with all the required startup options would be very helpful.  In fact, any official Portus container on dockerhub would be helpful...

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
