### ISSUE TITLE
Setting up Portus with existing Registry and NginX

### ISSUE THREAD

**Issue by tinybitsofnothingness** [SUSE/Portus#667]
Hi! I am a bit new in Docker, and I have a difficult time to figure out how to "plug-in" Portus (I suppose I need only db and frontend) into my existing set of containers. I am running NginX with SSL support and my Docker Registry is on "default" (5000) port and I am willing to set up rest of images/containers needed for Portus manually, but I just don't completely understand what should I change and do while building and running the images.
Thank you very much for clarification!

**Comment by egidijus** [comment]
So we have a single nginx container proxying both registry and portus on the same host, here is an example site config for nginx.

`ENV PROJECT_NAME="portus"` is set in the Dockerfile for nginx

NGINX entrypoint example:
```
#!/bin/sh
mkdir -p /etc/nginx/sites-enabled/
mkdir -p /var/log/nginx
mkdir -p /var/nginx-cache

chown -R $PROJECT_NAME /var/log/nginx
chgrp -R $PROJECT_NAME /var/log/nginx
chmod -R 0775 /var/log/nginx

chown -R $PROJECT_NAME /var/nginx-cache
chgrp -R $PROJECT_NAME /var/nginx-cache
chmod -R 0775 /var/nginx-cache

unset `env | grep affinity | awk -F= '/^\w/ {print $1}' | xargs`
/usr/bin/pongo-blender /etc/pongo-blender/nginx.conf.tmpl > /etc/nginx/nginx.conf
/usr/bin/pongo-blender /etc/pongo-blender/site.conf.tmpl > /etc/nginx/sites-enabled/site.conf
/usr/bin/pongo-blender /etc/pongo-blender/mime.types > /etc/nginx/mime.types

chown -R $PROJECT_NAME /var/lib/nginx
chgrp -R $PROJECT_NAME /var/lib/nginx
chmod -R 755 /var/lib/nginx

nginx
```



NGINX site config
```
server {
    listen         80;
    return 301 https://$host$request_uri;
}

server {
    listen 0.0.0.0:443 default default_server;

    ssl on;
    ssl_certificate /etc/nginx/ssl_crt.crt;
    ssl_certificate_key /etc/nginx/ssl_key.key;
    ssl_protocols SSLv3 TLSv1;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-HTTPS on;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://{{PORTUS_REGISTRY_PORT_5000_TCP_ADDR}}:5000/;
    }

    access_log off;
    error_log off;

}

server {
    listen 0.0.0.0:443;
    server_name SERVERNAME.com;
    
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_pass http://{{PORTUS_WEB_PORT_3000_TCP_ADDR}}:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 900s;
        }


    access_log /var/log/nginx/{{PROJECT_NAME}}-access.log main;
    error_log /var/log/nginx/{{PROJECT_NAME}}.log error;

}
```
We link the nginx container to registry and to portus.
Then we use **pongo-blender** to read ENV vars and create a config for nginx in entrypoint.
`http://{{PORTUS_REGISTRY_PORT_5000_TCP_ADDR}}` the double curly braces are jinja2 style templates.

**Comment by tinybitsofnothingness** [comment]
@egidijus Thanks for the answer! Maybe I wasn't clear enough, but I need help with setting up everything else except NginX :) In the meantime I tried to experiment with other approaches and I ended up with (still incomplete) configuration which is described in more details [here](https://github.com/SUSE/Portus/issues/574#issuecomment-175666090). I am still struggling with setting up the [registry certificates](https://github.com/SUSE/Portus/issues/574#issuecomment-175723211) now, so any help with it would be extremely appreciated.
Thanks!

**Comment by egidijus** [comment]
So I have been working on an way to deploy portus by pulling a release tag from portus repo, and then injecting our vars and secrets and then everything is wonderful.

It's a very similar wrapper script to portus official, but it is aimed at deploying portus and registry on the same host and then use nginx to proxy portus and registry.
Everything has SSL.
I am using s3 as backend storage.
the only caveat is that portus and registry have their own DNS names - because I had issues proxying portus under another directory.

If that would be useful to you, I could pick it back up and try to push it to github.

**Comment by tinybitsofnothingness** [comment]
@egidijus Thanks, it would be really useful to look at your complete configuration, so whenever you catch some time feel free to post it here :) Thank you one more time!

**Comment by egidijus** [comment]
https://github.com/madedotcom/portus-pie-provisioner
it's not pretty but it should work

**Comment by HackerWilson** [comment]
I added an nginx service in `Portus/compose/docker-compose.yml.template` with 80 port, then changed `Portus/compose/registry/config.yml.template` from
```
service: EXTERNAL_IP:5000
```
to
```
service: EXTERNAL_IP
```
then it is fully compatible with portus now.

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
