### ISSUE TITLE
Can't configure the action mailer delivery method to smtp

### ISSUE THREAD

**Issue by vitorarins** [SUSE/Portus#668]
I am running Portus inside a Docker container but not with compose.
I tried passing environment variables like this `PORTUS_EMAIL_SMTP_ENABLED=true`, and tried changing the config file inside the container but none of those seem to work.
Right now I am changing the `config/environments/production.rb` file in order to enable smtp. After been enabled the other configurations through envvars like `PORTUS_EMAIL_SMTP_ADDRESS` and `PORTUS_EMAIL_SMTP_USER_NAME` work fine.
I think is just the delivery method that is not been taken correctly from the config files or variables.

**Comment by mssola** [comment]
Mmmm, that's weird. I can't reproduce it. These are the steps that I'm doing. I've firstly modified the `docker-compose.yml` file from master to include (in the `web` service):

```yaml
  environment:
    - PORTUS_EMAIL_SMTP_ENABLED=true
```

I've then added some debug statements to the application_controller, and I've read:

```
web_1      | SMTP ? : {"from"=>"portus@example.com", "name"=>"Portus", "reply_to"=>"no-reply@example.com", "smtp"=>{"enabled"=>true, "address"=>"smtp.example.com", "port"=>587, "user_name"=>"username@example.com", "password"=>"password", "domain"=>"example.com"}} -- smtp
web_1      | SMTP: {:address=>"smtp.example.com", :port=>587, :user_name=>"username@example.com", :password=>"password", :domain=>"example.com", :authentication=>:login, :enable_starttls_auto=>true}
```

In the first line, you can see the contents of the config of the email as read by Portus, and then after the `--` characters, I print the delivery method as stored by Rails. The second line corresponds to what Rails has stored for the delivery method. Everything looks like what we expect.

Am I missing any steps to reproduce this ? Which version of Portus are you using ?

**Comment by vitorarins** [comment]
Hi @mssola, I am running the version from master, I built the image yesterday.
As I said, I am not running Portus with docker-compose, but I think that should not make any difference.
I will try to debug it more and will get back to you with the results.

Just to clarify, I am also running it with the `RAILS_ENV=production` envvars, you think that should cause any differences?

**Comment by mssola** [comment]
Nope, it shouldn't be a problem to add `RAILS_ENV=production`. Maybe it will be more difficult to debug, since it won't show debug message. Maybe you can use the `staging` environment. But, afaik, there's no useful message in this regard (that's why I added them myself :P).

**Comment by vitorarins** [comment]
Ah ok. The way I've been checking for this is the log from `docker logs`, which is `puma`'s log, and whenever I click to send the email of forgotten password, it shows the message: `/usr/sbin/sendmail: not found` on the logs.

**Comment by mssola** [comment]
Ah gotcha! This only happens in production/staging :/ Thanks for reporting!
