### ISSUE TITLE
The text on the panels from the admin page should be centered

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#67]
Right now the contents of panels are rendered with Bootstrap's grid system. This can lead to:

![admin](https://cloud.githubusercontent.com/assets/767943/7669534/7d0f0c44-fc77-11e4-9cc4-bccb71a73e68.png)

Even if subtle, you can tell that the "3" in the image above is not in the center. Moreover, depending on the text, the contents will lean more to the left, and sometimes more to the right, leading to an incosistent situation. That's why the text should always be on the center.

**Comment by cyntss** [comment]
Not really, the number stays next to the icon. In your screenshot the icon seems to have a problem but all the UI issues are fixed in the branch https://github.com/SUSE/Portus/tree/front-end-fixes once I make the PR :)

**Comment by cyntss** [comment]
![image](https://cloud.githubusercontent.com/assets/5013096/8091246/fb26815e-0fb2-11e5-85c9-1d9a846ee258.png)

**Comment by cyntss** [comment]
Fixed with merge of front-end-fixes
