### ISSUE TITLE
Group tags by image in WebGUI

### ISSUE THREAD

**Issue by lonewulf** [SUSE/Portus#674]
Hi, it would be nice if the tags were grouped on the same line if they belong to the same image.

**Comment by mssola** [comment]
Hello. Could you be more specific ? In which page do you want this?

**Comment by lonewulf** [comment]
Hi, in /repositories/#, there should be all tagged images belonging to the repo, where tags should be grouped by image id/hash. Seeing the image id would be useful too.

**Comment by mssola** [comment]
> Hi, in /repositories/#, there should be all tagged images belonging to the repo, where tags should be grouped by image id/hash

Maybe there's a confusion :) Repositories are images, and therefore `/repositories/#" already shows the tags of said image. That why I didn't understand "tagged images belonging to the repo", because a repo is in fact an image, and tags are already shown there.

> Seeing the image id would be useful too.

See #512.

**Comment by lonewulf** [comment]
Well, technically, all images in a repository are not the same image per say (different content, different id). Would be nice if the tags could be grouped so you could see which tags belongs to which image id.

Let's say that I have this on my docker host:

```
REPOSITORY                        TAG                 IMAGE ID      
portus.test.local/repo/portus     2-20160122          852105c0b840
portus.test.local/repo/portus     latest              852105c0b840
portus.test.local/repo/portus     2-20160121          2888bd7428e7
portus.test.local/repo/portus     2-20160112          fc5151fbcf7c
```
I would expect to see 3 lines in the WebUI for the repo/portus repository:

```
Tag(s)              Image ID        Author   Pushed at
2-20160122 latest   852105c0b840    ...	     ...
2-20160121          2888bd7428e7    ...      ...
2-20160112          fc5151fbcf7c    ...      ...
```

Hope this clarifies what I meant earlier.

**Comment by mssola** [comment]
Let's pick your `portus.test.local/repo/portus:latest` image. In Docker's terminology `repo` is the *namespace* (not the repository), and `portus` the image. What you are referring as repos, are namespaces. What you are asking for is already available in `/namespaces/:id`

**Comment by lonewulf** [comment]
Let's put it that way:
What I see in ```/namespaces/:id``` are the images (or as they are called in Portus, ```repositories```) which look like that in the WebGUI:
```
Namespace: repo
Belongs to: My Team

Repository	# Tags
portus	         4
```
Which is not the page I was mentioning in my previous post.

When I click on the portus link ```(repositories/:id)``` I actually get that:
```
Tag               Author   Pushed at
2-20160122        ...      ...
latest            ...      ...
2-20160121        ...      ...
2-20160112        ...      ...
```

That's the place I'm talking about where I would expect to see tags grouped by image id.

**Comment by mssola** [comment]
Ah sorry for the missunderstanding. You mean that instead of listing all tags, tags that belong to the same image ID should be put together right ?

**Comment by lonewulf** [comment]
Yup, that's what I meant.

And my bad for using 'repo' as the namepace used in my example, it was definitely confusing.

**Comment by mssola** [comment]
Ok gotcha. Sorry for the missunderstanding. I agree with this. Bear in mind though that this is blocked until we don't get #512 fixed (which should happen anytime soon). Thanks for your patience ;)

**Comment by lonewulf** [comment]
And thanks for yours :)
