### ISSUE TITLE
Multi machine deployment

### ISSUE THREAD

**Issue by hassanlhx** [SUSE/Portus#680]
=======================**********_host1          db**_**************=====================
In docker-compose.yml file
db:
  image: library/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: portus

=======================**********_host2          protus**_**************=====================
In docker-compose.yml file
web:
  extends:
    file: docker/compose-common.yml
    service: web
  volumes:
    - .:/portus
  extra_hosts:
    - "db:host1"

crono:
  image: portus_web
  entrypoint: bundle exec crono
  volumes:
    - .:/portus
  extra_hosts:
    - "db:host1"

=======================**********_host3          registry**_***********===================
In docker-compose.yml file
registry:
  extends:
    file: docker/compose-common.yml
    service: registry
  volumes:
    - ./docker/registry:/registry
    - /registry_data
  entrypoint: /registry/entry.sh
  env_file: docker/environment
  extra_hosts:
    - "web:host2"
  ports:
    - 5001:5001 # required to access debug service

In config.yml.template file
version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /registry_data
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
auth:
  token:
    realm: http://host2:3000/v2/token
    service: host3:5000
    issuer: portus.test.lan
    rootcertbundle: /registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://web:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s

docker login -u test -p test -e test@11.com host3
docker login success
docker push host3/test/mysql:6.1
push success

But in the UI can not see the rep,And there is no database.

docker pull host3/test/mysql:6.1
pull success
I would like to ask what is the cause of the?

**Comment by mssola** [comment]
And if you read the logs with `docker-compose logs` I imagine that you'll see problems with the database, right? Since you are using docker-compose, you might want to take a look at what we do in the [compose-setup.sh](https://github.com/SUSE/Portus/blob/master/compose-setup.sh) file. Basically, I think that you are missing:

    docker-compose run --rm web rake db:setup

You should execute this after `docker-compose up`. Hope it helps. If it doesn't, could you attach logs and the version of docker and docker-compose ?

**Comment by hassanlhx** [comment]
i hava run comose-setup.sh
there is no problem with the database

**Comment by mssola** [comment]
In your original question you said that there was no database, but now you say that there's no problem with it. Could you give me an update of your current situation ? :)

**Comment by hassanlhx** [comment]
Can now be created in UI Portus users, and login docker success
But after push Portus in UI docker did not see the reps
RMI docker to remove the local pull docker after pull can successfully down

**Comment by hassanlhx** [comment]
When I put web, registry, DB on the same host, it won't be a problem.

**Comment by mssola** [comment]
> But after push Portus in UI docker did not see the reps
RMI docker to remove the local pull docker after pull can successfully down

By that I understand that the registry has the image, but it does not appear on Portus, right ? Could you please access the logs of Portus ? It should be on `logs/development.log` (depends whether you're on development or production). This way we will be able to see whether Portus has received the notification.

Also, could you make sure that all hosts are reachable ? As in, that host2 can reach host3, and so on.

**Comment by hassanlhx** [comment]
docker push ip/test/mariadb
see logs/development.log
Could not fetch the tag for target {"mediatype"=>"aplication/vnd.docker.distribution.manifest.vlfison","size"=>25291,"digest"=>"sha256:48s091s9478sf399988939ss997758","length"=>25291,"repository"=>"test/mariadb","url"=>"http://ip:5000/v2/test/mariadb/manifest/sha256:48s091s9478sf399988939ss997758"}
Reason:No route to host - connect(2) for "ip" port 3000

**Comment by flavio** [comment]
> Reason:No route to host - connect(2) for "ip" port 3000

That's look like a networking problem on this host. It's strange because according to your previous comments the web UI of Portus used to work.

**Comment by hassanlhx** [comment]
@flavio 
I think so. But when I put Portus and registry on the same host, there is no such problem.

**Comment by hassanlhx** [comment]
Portus supports multiple host deployments?
When is the next version?

**Comment by mssola** [comment]
> Portus supports multiple host deployments?

Yes, it does. You just have to deploy every piece wherever you want and then in each respective configuration file point to the right location.

> When is the next version?

Version 2.0.3 was released not so long ago. Maybe you can try this version, as it fixes some problems with Docker Distribution 2.3 :)

Moreover, for these kinds of discussions we've created a new mailing list: https://groups.google.com/forum/#!forum/portus-dev. Maybe we can continue this conversation there ? :wink:

**Comment by mssola** [comment]
I think this can be closed. We have written some examples that might help on this question. Feel free to leave more comments if you have more doubts.
