### ISSUE TITLE
Production environment setup

### ISSUE THREAD

**Issue by tinybitsofnothingness** [SUSE/Portus#683]
I've been playing around with docker-compose and I would like to try to set it up in production environment. Which steps should be taken in order to build/run everything for production? Which environmental variables are needed and which files should be edited apart from `secrets.yml`?

**Comment by egidijus** [comment]
```
portus/config/config.yml
portus/config/config-local.yml
portus/config/database.yml
portus/config/secrets.yml
```

Then pass this to container env vars:
`RAILS_ENV=production`

I also found that you need to run puma with extra parameters:
`gosu portus puma -b tcp://0.0.0.0:3000 -w 3 -e production`

(**gosu** is a tool that allows you to run things inside containers as another user)

**Comment by JonathonReinhart** [comment]
See also:
- #498
- #574

**Comment by tinybitsofnothingness** [comment]
@egidijus Thanks for clarification. I included `-e production` in executing `puma`, however if I try to run it with `gosu` I get the following error:

    exec: "gosu": executable file not found in $PATH

Anyway, as I said in #574, I did make some progress with my set up, but still having few problems with certificates...

**Comment by egidijus** [comment]
@tinybitsofnothingness gosu is something you would need to add to your docker image
https://github.com/tianon/gosu

**Comment by wmark** [comment]
Don't use *gosu*. Instead add ```runit``` to  parameters of *apt-get*:

```
apt-get -y install runit

chpst -u portus -- puma -b tcp://0.0.0.0:3000 -w 3 -e production
```

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
