### ISSUE TITLE
Copying <repository URL>:<tag> to clipboard when tag name is clicked

### ISSUE THREAD

**Issue by iitns** [SUSE/Portus#697]
Full URL for repository is quite frequently used when working with docker CLI  
So it would be great if we can easily get the URL

**Comment by iitns** [comment]
Actually, my colleague asked me if I can implement it, so I made following changes on app/view/repositories/show.html.slim:

on line no. 35:
changed ".label.label-success" to "button.btn.btn-success.btn-xs" so tag elements become clickable while not ruining table.

at the end of the file, added:    

    javascript:
      var base_url = '#{request.host}/#{@repository.namespace.clean_name}/#{@repository.name}:';
      var url_to_copy = undefined;
    
      document.addEventListener('copy', function(e) {
        if (url_to_copy != undefined)
        {
          e.clipboardData.setData('text/plain', url_to_copy);
          e.preventDefault();
        }
      });
      $('.btn.btn-success.btn-xs').each(function(i, item) {
        $(item).click(function(e) {
          if (confirm('Copy to clipboard?')) {
            var tagName = $(this).text();
            url_to_copy = base_url + tagName;
            document.execCommand("copy");
            url_to_copy = undefined;
          }
        });
      });

**Comment by mssola** [comment]
Good idea! I've tested the code and it looks good. Could you submit a PR? Some suggestions:

- Could put the JS into a separate file. I don't like mixing JS with HTML :)
- I don't think you need to call `confirm('Copy to clipboard?')`. Just copy the contents to the clipboard directly instead. Maybe you can add a `title` attribute to it saying "Copy to clipboard" ?

**Comment by iitns** [comment]
Thank you for reviewing humble code :)

- I'd move the JS code to a separate file. Would "tag.js" be OK? Since I'm not familiar with ruby, rails and slim, please review after I submit a PR.
- What you suggested perfectly makes sense. The reason why I added confirmation step is because copying URL is not implemented yet, so people wouldn't expect it.(Except some people like my colleague who experienced other Portus like admin tool) So, I'm afraid some users who don't expect copying URL would blow their clipboard when clicked tag accidentally. How about displaying whole URL for each tags, and placing a button for copying URL like the way github does.

**Comment by mssola** [comment]
> I'd move the JS code to a separate file. Would "tag.js" be OK? Since I'm not familiar with ruby, rails and slim, please review after I submit a PR.

We are using CoffeeScript here (even if we allow some JS here and there, mostly on `js.erb` files). Could you do it in CoffeeScript (you could even use a tool such as http://js2.coffee/ to help you if you don't coffeescript :P) ? Otherwise, feel free to do it in JS if you feel more comfortable doing it with JS.

> What you suggested perfectly makes sense. The reason why I added confirmation step is because copying URL is not implemented yet, so people wouldn't expect it.(Except some people like my colleague who experienced other Portus like admin tool) So, I'm afraid some users who don't expect copying URL would blow their clipboard when clicked tag accidentally.

That's a reasonable concern I think. In my opinion, just adding a fancy title "Copy to Clipboard" just like Github does would be enough.

>  How about displaying whole URL for each tags, and placing a button for copying URL like the way github does.

I feel that that's a bit too much. For example, what would happen in the case in which we group multiple tags together in the same line as specified in the issue #674 ? In this case I feel that all the URLs would fill too much space. That's why I think that just adding a fancy title should be enough to warn users (I don't know if bootstrap has fancy titles like the ones on Github now :P).

**Comment by cyphar** [comment]
To be honest, I haven't done JS work in quite a while, but my understanding was that (at least a few years ago) that you needed to use something like [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard) in order to actually be completely cross-platform and support all major browsers (although it does have the **massive** side-effect of requiring Adobe Flash -- which is not a good thing).

My question being, does this work for all major browsers?

**Comment by mssola** [comment]
To ensure cross-platform without flash there's also https://clipboardjs.com/. I'm not sure if bootstrap already provides something on the likes. That being said, according to http://caniuse.com/#search=clipboard, every browser should support it (Opera Mobile being the only exception, and IE8 even supports it!).

**Comment by cyphar** [comment]
@mssola Awesome. :D

**Comment by flavio** [comment]
Hi @iitns, this seems a really interesting feature. Thanks for your contribution.

BTW, it would be nice to see a screen shot ;)

**Comment by iitns** [comment]
@mssola I do respect the way it is now as well as [contribution guidelines](https://github.com/SUSE/Portus/blob/master/CONTRIBUTING.md). I'll try CoffeeScript

> In my opinion, just adding a fancy title "Copy to Clipboard" just like Github does would be enough.

As @flavio said, it would be easier to understand with screenshots so I've taken one to check we're on the same page. On mouse hover on tag name, showing "Copy to Clipboard" message like below?
![copy to clipboard](https://cloud.githubusercontent.com/assets/7313784/12721206/f0dbd2f0-c941-11e5-9020-b7986a870e39.jpg)

> In this case I feel that all the URLs would fill too much space.

I strongly agree with you on this. Showing a speech balloon on mouse hover would familiar with users (as most users have experienced github)
After searching on Bootstrap reference pages, I found [Tooltips (tooltip.js)](http://getbootstrap.com/javascript/#tooltips). I think this is exactly what we need. :)

**Comment by mssola** [comment]
> As @flavio said, it would be easier to understand with screenshots so I've taken one to check we're on the same page. On mouse hover on tag name, showing "Copy to Clipboard" message like below?

That's exactly it :)

> After searching on Bootstrap reference pages, I found Tooltips (tooltip.js). I think this is exactly what we need. :)

Since we are already using bootstrap, it's possible that we already include it, so you wouldn't even need to do anything at all in this regard. But I might be wrong :)

**Comment by iitns** [comment]
@cyphar pointed out a very important issue before proceed. Actually, I underestimated to implement "Copy to clipboard" because I've seen that feature so many time on so many website. After an hour of search, I also found that most browser doesn't fully support Clipboard API even chrome.    
I didn't embed [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard) because most of my colleagues are using chrome and it worked as I changed,(remember it started from my colleague's request? :smiley:) but it should be tested cross-browser compatibility.    

I guess GitHub also uses ZeroClipboard and it seems it's well tested, so it'd be better to utilize it.   
I'll try on this too.

**Comment by mssola** [comment]
@iitns you're right that not all browsers implement *all* the features from the clipboard API. That being said, the only endpoint from this API being used is:

```js
e.clipboardData.setData('text/plain', url_to_copy);
```

According to http://caniuse.com/#search=clipboard, all browsers should indeed implement this. I'll check in Chrome just to be sure though

**Comment by iitns** [comment]
Thank you for your warm welcome, @flavio
I and my colleagues really like Portus.

After reading your comment, I reviewed my first comment and it seems I didn't explain enough - what page I'm talking about.

It's about [repository page](https://github.com/SUSE/Portus/blob/master/app/views/repositories/show.html.slim).
Let's say the blue box on the bottom of right side is "Tag buttons", the red box on the top of right side is "Repository title" area.
![repositories](https://cloud.githubusercontent.com/assets/7313784/12722086/8c64d0f6-c946-11e5-98af-5d77239a88ab.PNG)

My colleague wanted to easily copy the URL for the repository or one with tag name. So first change I made was adding <code>request.host</code> with '/'(slash) on Repository title so they can easily copy the URL.
And the next changes(from enabling tag name element clickable, and so on) are described on 2nd comment that I wrote.

Fortunately, @mssola understood what I meant. :)

So, here's another suggestion on repository page. How about adding a <code>request.host</code> on Repository title area?

**Comment by mssola** [comment]
> So, here's another suggestion on repository page. How about adding a request.host on Repository title area?

I think that it's maybe too much, but probably it's just me :) From my point of view, just add the URL on click, while adding a fancy title with bootstrap's tooltips ;)

**Comment by mssola** [comment]
Regarding my last commit, I apparently forgot that we do exactly this for the global namespace. So, adding the complete URL also for other namespaces might not be that bad (it adds consistency).

**Comment by mssola** [comment]
@iitns this patch also works with Chromium (47.0.2526.106 (64-bit)). So, as I said, I believe that we are targeting a method of the clipboard API that works across all browsers. There's one bug though on the link. You are using `request.host`, which is wrong, because Portus and the Registry are not necessarily on the same machine. You should use `Registry.get.hostname`.

**Comment by iitns** [comment]
@mssola That's exactly what I needed! Since I didn't know how I can list up all available variables in template, I couldn't find proper one. You read my mind.

**Comment by mssola** [comment]
@iitns are you still working on this ? If so, could you submit a PR ?

**Comment by iitns** [comment]
Sorry for late response. I've been busy that I couldn't make it.
I'll submit a PR or at least a candidate by next coming Sunday, 1 May KST.

Thank you for waiting for my submit!

**Comment by iitns** [comment]
At long last, I finished working code with tooltip.js
But some issues to decouple javascript code from `show.html.slim` remained. I'll ask these later on

I'd really like to link to codes which needs to be changed, but the codes I'm working on are way too far behind.
So, at this moment, I'll just summarize changes and I'll submit PR in few days.

- dom element to show image's tag name(tag.name, now t.name i guess)
    - (From) ".label.label-success"
    - (To) "**button.btn.btn-success.btn-xs._tag-name_ data-title="Copy to clipboard" data-placement="bottom" data-toggle="tooltip" data-trigger="hover"**"
- Javascripts that has to be loaded (converted w/ js2coffee)
```
  var baseUrl, urlToCopy;

  baseUrl = '#{request.host}/#{@repository.namespace.clean_name}/#{@repository.name}:';

  urlToCopy = void 0;

  document.addEventListener('copy', function(e) {
    if (urlToCopy !== void 0) {
      e.clipboardData.setData('text/plain', urlToCopy);
      e.preventDefault();
    }
  });

  $('.btn.btn-success.btn-xs.tag-name').click(function(e) {
    var tagName;
    tagName = $(this).text();
    urlToCopy = baseUrl + tagName;
    document.execCommand('copy');
    urlToCopy = void 0;
    $(this).tooltip('hide').attr('data-original-title', 'Copied!').tooltip().mouseover();
  });
```

**Comment by iitns** [comment]
Like @mssola said, separating JS code from `html.slim` is needed.
How does ruby work? I can see [start.js.erb](https://github.com/SUSE/Portus/blob/master/app/views/repositories/star.js.erb) at [Portus/app/views/repositories/](https://github.com/SUSE/Portus/tree/master/app/views/repositories) but I have no clue how it is embedded and how it works when 'star' button is clicked on `show.html.slim`.

One more thing, can you give me some hint where I have to sign? I think I would sign on, let's say, 'copy_to_clipboard.js' if separating JS code is done.

Thank you in advance.

**Comment by iitns** [comment]
I just found an unintended behavior:
    When a url is copied by clicking tag name, the tooltip for the tag name still remains 'Copied!'.

I'll leave a comment after fixing it. :flushed:

**Comment by iitns** [comment]
Added event handler on `hidden.bs.tooltip`
```
  var baseUrl, urlToCopy;

  baseUrl = '#{request.host}/#{@repository.namespace.clean_name}/#{@repository.name}:';

  urlToCopy = void 0;

  document.addEventListener('copy', function(e) {
    if (urlToCopy !== void 0) {
      e.clipboardData.setData('text/plain', urlToCopy);
      e.preventDefault();
    }
  });

  $('.btn.btn-success.btn-xs.tag-name').click(function(e) {
    var tagName, urlToCopy;
    tagName = void 0;
    tagName = $(this).text();
    urlToCopy = baseUrl + tagName;
    document.execCommand('copy');
    urlToCopy = void 0;
    $(this).tooltip('hide').attr('data-original-title', 'Copied!').tooltip().mouseover();
  }).on('hidden.bs.tooltip', function() {
    $(this).attr('data-original-title', 'Copy to clipboard').tooltip();
  });
```

I'll submit a PR for this in few days.

**Comment by mssola** [comment]
@iitns sorry to bother you again, but are you working on this ?
