### ISSUE TITLE
Add a display name to the users

### ISSUE THREAD

**Issue by lonewulf** [SUSE/Portus#700]
Hi,

If I may, I would be in favor of adding a display name to the users, the namespaces still would be the username (with Docker restrictions) but it would be a far more user friendly experience for the feeds and team management (especially when usernames have absolutely nothing to do with people names).

It would also be great if LDAP is in use to be able to pull this field from an LDAP (same principle that guess_email)

The personal repository is already in its own tab, so I would think it not misleading for the user to have a display name and a username.

Regards,

**Comment by mssola** [comment]
@lonewulf I've copied your comment to #699. Let's keep the discussion there ;)
