### ISSUE TITLE
No sign up page is displayed.

### ISSUE THREAD

**Issue by phupn1510** [SUSE/Portus#701]
After deploying lotus by bydga/portus images, I only access login page.I can not find any page to sign up account.

**Comment by mssola** [comment]
Note that it's not an official version from our side. We do not provide a containers setup ready for production just yet (we're on the plans of providing one pretty soon). That being said, if you are just testing Portus, there's also our [compose](https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment) setup.

**Comment by mssola** [comment]
@phupn1510  By the way, the fact that it's now showing a signup page is because that image is targeting a custom LDAP server. On LDAP, there's no signing up because that's handled by LDAP itself.

**Comment by phupn1510** [comment]
Thank you @mssola , I fixed as you guide.

**Comment by majidpal** [comment]
I am facing loading sign up page. I have used portus and mariadb container. Getting below error -

Started GET "/assets/webpack/application-cf07f57053f06e4d93e5.js" for  at 2018-01-25 01:34:15 +0000

ActionController::RoutingError (No route matches [GET] "/assets/webpack/application-cf07f57053f06e4d93e5.js"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as */*
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (12.6ms)
  Rendered errors/_status_title.html.slim (3.0ms)
Completed 404 Not Found in 52ms (Views: 49.1ms | ActiveRecord: 0.0ms)

**Comment by mssola** [comment]
@majidpal this should be fixed already. It was caused by a bad build of the docker image...

**Comment by majidpal** [comment]
This issue was resolved by passign Ruby parameter while creating Portus
docker

**Comment by mssola** [comment]
> This issue was resolved by passign Ruby parameter while creating Portus docker

Which parameter ? This can be useful for other people getting into this same issue.

**Comment by vitoravelino** [comment]
`RAILS_SERVE_STATIC_FILES`. I helped him in #1626.
