### ISSUE TITLE
Command 'rake db:setup' does not work when setting RAILS_ENV to production.

### ISSUE THREAD

**Issue by linbaiye** [SUSE/Portus#702]
Hi, there:
I'm trying to set up a 'production' environment manually. However, if I run this command: **RAILS_ENV="production" rake db:setup**,  this error message will be thrown (I post only part of it here): 
-- create_table("registries", {:force=>:cascade})
   -> 0.0153s
-- add_index("registries", ["hostname"], {:name=>"index_registries_on_hostname", :unique=>true, :using=>:btree})
   -> 0.0128s
-- add_index("registries", ["name"], {:name=>"index_registries_on_name", :unique=>true, :using=>:btree})
   -> 0.0126s
-- create_table("repositories", {:force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails: DROP TABLE `repositories` CASCADE
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:490:in `drop_table'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:205:in `create_table'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in `create_table'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:652:in `method_missing'
/home/q/Portus-2.0.1/db/schema.rb:91:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/schema.rb:41:in `instance_eval'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/schema.rb:41:in `define'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/schema.rb:61:in `define'
/home/q/Portus-2.0.1/db/schema.rb:14:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:218:in `load_schema_for'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:235:in `block in load_schema_current'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:275:in `block in each_current_configuration'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:274:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:274:in `each_current_configuration'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/tasks/database_tasks.rb:234:in `load_schema_current'

but if I run this command: **RAILS_ENV="test" rake db:setup**, everything works just fine, I'm able to login as well as see docker images pushed to registry. Here is my config/database.yml: 
default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  username: root
  password: password

development:
  <<: *default
  database: portus_development

staging:
  <<: *default
  database: portus_staging

test:
  <<: *default
  database: portus_test

production:
  <<: *default
  database: portus_production

Did I miss something?

**Comment by flavio** [comment]
Can you try doing: 
```
export RAILS_ENV=production
rake db:migrate:reset
rake db:seed
```

**Comment by linbaiye** [comment]
@flavio , thanks for your reply, it worked.

**Comment by thisismydesign** [comment]
Running into the same issue. Anyone know the root cause of this?
