### ISSUE TITLE
introduce an easy db config method

### ISSUE THREAD

**Issue by abonillasuse** [SUSE/Portus#704]
When installing Portus, it would be ideal to automate the database setup process by using a script or any method so that it uses and configures the embedded database.

**Comment by flavio** [comment]
Basically we would have to extend the current db handling and:

  * make sure the database name specified by the user is created
  * make sure the username specified by the user is created, has the right grants to interact with the database and is also protected by the password specified on the CLI

**Comment by flavio** [comment]
I added the "RPM package" tag because this feature is specific to `portusctl`

**Comment by mssola** [comment]
Closing in favor of #1464.
