### ISSUE TITLE
RPM installation fails

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#709]
ln -s '/usr/lib/systemd/system/portus_crono.service' '/etc/systemd/system/multi-user.target.wants/portus_crono.service'
ln -s '/usr/lib/systemd/system/apache2.service' '/etc/systemd/system/httpd.service'
ln -s '/usr/lib/systemd/system/apache2.service' '/etc/systemd/system/apache.service'
ln -s '/usr/lib/systemd/system/apache2.service' '/etc/systemd/system/multi-user.target.wants/apache2.service'
Failed to execute operation: No such file or directory
/srv/Portus/packaging/suse/portusctl/lib/runner.rb:7:in `exec': Something went wrong while invoking: systemctl enable registry (RuntimeError)
	from /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `activate_service'
	from /srv/Portus/packaging/suse/portusctl/lib/configurator.rb:179:in `block in services'
	from /srv/Portus/packaging/suse/portusctl/lib/configurator.rb:178:in `each'
	from /srv/Portus/packaging/suse/portusctl/lib/configurator.rb:178:in `services'
	from /srv/Portus/packaging/suse/portusctl/lib/cli.rb:91:in `setup'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from packaging/suse/portusctl/bin/portusctl:5:in `<main>'
i

I used this command:

portusctl setup --local-registry

Does this imply that the registry must already be installed and running before running the portusctl setup command? The documentation seems to imply that it will install the docker registry as part of the portus setup.

**Comment by opichon** [comment]
It appears to work if the docker registry is installed separately before installing portus. You may want to make the documentation slightly less confusing.

**Comment by mssola** [comment]
The "Portus' dependencies" section says

    (that’s why the RPM just recommends these packages, instead of requiring them)

But you're right that we could have phrased the whole section in a more direct and clear way. I'll take a look at it. Thanks.

**Comment by flavio** [comment]
@mssola we should also change `portusctl` to print some warning when `--local-registry` is passed and the registry package is not found.

**Comment by flavio** [comment]
@mssola I would reopen this issue and change the title accordingly. What do you think?

**Comment by flavio** [comment]
> @mssola I would reopen this issue and change the title accordingly. What do you think?

Ignore me, I've just seen issue #711
