### ISSUE TITLE
Show a warning when the registry package is not installed but --local-registry was used

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#712]
In `portusctl` the registry package is not required, since one may have a docker registry already set up on another host. That being said, if the user is setting the `--local-registry` flag, then we know for sure that the registry has to be there.

For this reason, we could add a warning if the registry RPM has not been installed (not an error because maybe the user has the registry on a container or whatever).

**Comment by flavio** [comment]
Agreed, we should show a warning and do not apply registry's configuration

**Comment by mssola** [comment]
> do not apply registry's configuration

Maybe we should ask that to the user. Maybe the user already has a config.yml.

**Comment by flavio** [comment]
Maybe we should `portusctl` and, before overwriting any configuration file, it should show a warning and ask what to do.

`portusctl` could be configured to just overwrite everything by using a special cli flag.

**Comment by mssola** [comment]
Agreed
