### ISSUE TITLE
 appliance link on hompage returns 404 

### ISSUE THREAD

**Issue by dohnto** [SUSE/Portus#716]
Hi,

on [http://port.us.org/](http://port.us.org/), at bottom, there a link at text:

> We provide also a ready to go [appliance](http://port.us.org/docs/setups/2_appliance.html) based on openSUSE.

which returns 404 atm.

**Comment by mssola** [comment]
Right. We no longer provide the appliance, since it was based on a tech preview. Instead, you should install the RPM. Let me update the documentation...
