### ISSUE TITLE
Can't connect to registry using SSL

### ISSUE THREAD

**Issue by razvip91** [SUSE/Portus#719]
I'm trying to launch portus in production with a registry behind self-signed SSL certs, but have no luck in connecting them. The certs have been inserted at system level to be accepted by the OS, so there shouldn't be any issues of acceptance, but I keep getting the error: "SSL error while communicating with the registry, check the server logs for more details." from portus, and from the registry logs, I get: "http: TLS handshake error from 172.17.0.1:43884: remote error: unknown certificate authority"

Can anyone offer any suggestions?

NOTE: I followed all the configuration templates from other issues and from the portus website, but to no avail.

Thanks!

**Comment by jordimassaguerpla** [comment]
most probably you don't have the certificate authority (HOSTNAME.crt) in /etc/registry/ssl.crt

can you check that?

**Comment by razvip91** [comment]
I put the .crt file in the /etc/docker/registry directory, but still no luck. Same error

**Comment by razvip91** [comment]
Here is a copy of the registry config.yml: 
`version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /certs/hostname.crt
    key: /certs/hostname.key
auth:
  token:
    realm: https://host:port/v2/token
    service: hostname:5000
    issuer: hostname
    rootcertbundle: /etc/docker/registry/hostname.crt
notifications:
  endpoints:
    - name: portus
      url: https://hostname:port/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
`

and a copy of the docker-compose.yml of the registry start configuration:

`registry:
  image: registry:2.2
  volumes:
    - /home/q/data:/var/lib/registry
    - /home/q/certs/hostname.crt:/etc/docker/registry/hostname.crt:ro
    - /home/q/certs:/certs
    - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
  ports:
    - 5000:5000
  links:
    - web
`

**Comment by razvip91** [comment]
And this is what portus prints out from the debug log in production:

`SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed

Registry not reachable:
#<Registry id: nil, name: "admin", hostname: "goblin.lan.softnrg.ro:5000", created_at: nil, updated_ at: nil, use_ssl: true>
SSL error while communicating with the registry, check the server logs for more details.`

**Comment by lonewulf** [comment]
Did you add the registry certificate to the trusted certificates of your Portus image ?

**Comment by razvip91** [comment]
Well, I presume that means modifying the secrets.yml file. Here is mine: 

`production:`
  `secret_key_base: '/etc/docker/registry/goblin_lan_softnrg_ro.key'`
  `encryption_private_key_path: '/etc/docker/registry/goblin_lan_softnrg_ro.key'`
  `portus_password: 'portus'`

**Comment by razvip91** [comment]
I just modified the `secret_key_base` parameter to contain the result of the commnad
`rake secret`

**Comment by lonewulf** [comment]
The OS in the container still wouldn't trust the repository certificate.
You'd have to build an image based on the one you use with something on the lines of:
```
FROM portus
COPY hostname.crt /usr/local/share/ca-certificates
RUN  update-ca-certificates
```

**Comment by jordimassaguerpla** [comment]
please also look into /var/log/apache2/* for error logs.
what @lonewulf said is a good question. On SUSE you have to copy the certificate into /etc/pki/trust/anchors/ and run update-ca-certificates

**Comment by lonewulf** [comment]
That said, the same thing applies to the registry container with the portus certificate

**Comment by razvip91** [comment]
@lonewulf is right. I tried that yesterday, but didn't work while doing it directly in the container.
But now it works. 

Thanks guys for the support! :+1:

**Comment by tinybitsofnothingness** [comment]
@lonewulf Is this step absolutely necessary? I don't remember I saw it anywhere in documentation.

@razvip91 May I just ask, in [your configuration](https://github.com/SUSE/Portus/issues/719#issuecomment-182284921), are `/certs/hostname.crt` and `/etc/docker/registry/hostname.crt` the same certificate? Are you trying to put both registry and web behind SSL?

**Comment by lonewulf** [comment]
@tinybitsofnothingness If you're using self-signed certificates, you'd have to have them trusted by the OS, container based deployment or not

**Comment by razvip91** [comment]
Yes @tinybitsofnothingness , they are the same and yes, I'm trying to put both registry and portus web behind SSL

**Comment by CayoM** [comment]
since i had the same issue and didn't want to maintain an own docker-image of portus only in order to use a self-signed certificate, i came up with this ugly workarround:

as described here https://github.com/openSUSE/ca-certificates :
```
- /etc/ssl/ca-bundle.pem: Concatenated bundle of CA certificates
  with server-auth purpose. Avoid using this in applications.
```

i did abuse this and mount the file /etc/ssl/certs/ca-certificates.crt (since i already imported my self-signed certificate in my Ubuntu 16.04 Host via update-ca-certificates, my /etc/ssl/certs/ca-certificates.crt now contains my cert) from my ubuntu host into the portus and background container:

```
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/ca-bundle.pem:ro
```

im not getting the TLS handshake failed message anymore.

**Comment by joaoelvas** [comment]
> since i had the same issue and didn't want to maintain an own docker-image of portus only in order to use a self-signed certificate, i came up with this ugly workarround:
> 
> as described here https://github.com/openSUSE/ca-certificates :
> 
> ```
> - /etc/ssl/ca-bundle.pem: Concatenated bundle of CA certificates
>   with server-auth purpose. Avoid using this in applications.
> ```
> i did abuse this and mount the file /etc/ssl/certs/ca-certificates.crt (since i already imported my self-signed certificate in my Ubuntu 16.04 Host via update-ca-certificates, my /etc/ssl/certs/ca-certificates.crt now contains my cert) from my ubuntu host into the portus and background container:
> 
> ```
>     volumes:
>       - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/ca-bundle.pem:ro
> ```
> im not getting the TLS handshake failed message anymore.

This solved the problem of the TLS between Portus and the Registry, I can confirm that I can now reach the registry. However a new problem shows up now. The Background and the registry cannot communicate.

**I get this error.**

```
background_1_199bac5e215c | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
background_1_199bac5e215c | 	from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
background_1_199bac5e215c | 	from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
background_1_199bac5e215c | 	from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
background_1_199bac5e215c | 	from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:56:in `each'
background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:56:in `each_with_index'
background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:55:in `loop'
background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:55:in `<top (required)>'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1_199bac5e215c | 	from bin/rails:12:in `require'
background_1_199bac5e215c | 	from bin/rails:12:in `<main>'
background_1_199bac5e215c | exit status 1
portus_1_514c193677b4 | Started GET "/api/v1/namespaces" for 172.18.0.6 at 2018-12-06 17:39:09 +0000
portus_background_1_199bac5e215c exited with code 1
```

**Comment by KostyaEsmukov** [comment]
Entrypoint script [includes](https://github.com/SUSE/Portus/blob/c670f72c867ce1cf620214483982816f5f73e549/docker/init#L88) the `update-ca-certificates` command, so it should be enough to simply add the self-signed certificate as a volume:
```
-v /my/path/to/registry.crt:/usr/share/pki/trust/anchors/registry.pem:ro
```

Also ensure that the certificate's Subject Name matches the [internal] hostname of the docker registry -- otherwise the ssl validation would still fail.

**Comment by RjEcho217** [comment]
> > since i had the same issue and didn't want to maintain an own docker-image of portus only in order to use a self-signed certificate, i came up with this ugly workarround:
> > as described here https://github.com/openSUSE/ca-certificates :
> > ```
> > - /etc/ssl/ca-bundle.pem: Concatenated bundle of CA certificates
> >   with server-auth purpose. Avoid using this in applications.
> > ```
> > 
> > 
> > i did abuse this and mount the file /etc/ssl/certs/ca-certificates.crt (since i already imported my self-signed certificate in my Ubuntu 16.04 Host via update-ca-certificates, my /etc/ssl/certs/ca-certificates.crt now contains my cert) from my ubuntu host into the portus and background container:
> > ```
> >     volumes:
> >       - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/ca-bundle.pem:ro
> > ```
> > 
> > 
> > im not getting the TLS handshake failed message anymore.
> 
> This solved the problem of the TLS between Portus and the Registry, I can confirm that I can now reach the registry. However a new problem shows up now. The Background and the registry cannot communicate.
> 
> **I get this error.**
> 
> ```
> background_1_199bac5e215c | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
> background_1_199bac5e215c | 	from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
> background_1_199bac5e215c | 	from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
> background_1_199bac5e215c | 	from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
> background_1_199bac5e215c | 	from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
> background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
> background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:56:in `each'
> background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:56:in `each_with_index'
> background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
> background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:55:in `loop'
> background_1_199bac5e215c | 	from /srv/Portus/bin/background.rb:55:in `<top (required)>'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
> background_1_199bac5e215c | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
> background_1_199bac5e215c | 	from bin/rails:12:in `require'
> background_1_199bac5e215c | 	from bin/rails:12:in `<main>'
> background_1_199bac5e215c | exit status 1
> portus_1_514c193677b4 | Started GET "/api/v1/namespaces" for 172.18.0.6 at 2018-12-06 17:39:09 +0000
> portus_background_1_199bac5e215c exited with code 1
> ```
> 
> Anyone found a solution for this?

IM having the same issue, when i use the TLS with nginx the background process stops working with exit code 1.....However the front end works fine, what is the deal??
