### ISSUE TITLE
The link to the user documentaion is broken

### ISSUE THREAD

**Issue by brundabanm** [SUSE/Portus#726]
In case of routing to **http://suse.github.io/Portus/docs/Configuring-Portus.html#ldap-support**, it routes to **http://suse.github.io/docs/Configuring-Portus.html#ldap-support** . Portus/ is missing while routing in documentation. Rest all is working fine.

Example :  The User documentation on the main page http://suse.github.io/Portus/, routes to http://suse.github.io/documentation.html, whereas it should route to http://suse.github.io/Portus/documentation.html.

**Comment by mssola** [comment]
Where did you find this http://suse.github.io URL ? This was the one used before we had http://port.us.org . Please use this last one. That being said, did you find anywhere in the documentation targeting the link you are using ?

**Comment by mssola** [comment]
Closing this issue. Feel free to re-open and give more information whenever you can :wink:
