### ISSUE TITLE
push events for distribution 2.3 not working

### ISSUE THREAD

**Issue by databus23** [SUSE/Portus#729]
Seems to me the recent fixes regarding newer distribution versions are not sufficient.

When I push an image to the registry (2.3) the repository/tags don't show up in Portus
The error I'm seeing in the logs is:
```
  Repository Load (0.3ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`name` = 'd062284/busybox' LIMIT 1
Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>711, "digest"=>"sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd", "length"=>711, "repository"=>"d062284/busybox", "url"=>"http://192.168.163.129:5000/v2/d062284/busybox/manifests/sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd"}
Reason: undefined method `tags' for nil:NilClass
```

Looking at the push event payload the target repository is reported prefixed with the namespace:
```json
{
  "id": "dea22f71-c821-44dc-b6a3-9dba86ea124f",
  "timestamp": "2016-02-12T13:09:46.057017951Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 711,
    "digest": "sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd",
    "length": 711,
    "repository": "d062284/busybox",
    "url": "http://192.168.163.129:5000/v2/d062284/busybox/manifests/sha256:9176b113ee7620cb59f5df4c8afa86e990529e3ca328fe15cbc499eeb64bedfd"
  },
...
```

But then the call in this line https://github.com/SUSE/Portus/blob/master/app/models/registry.rb#L116 tries to find the repository by that value which fails because the name column in the `Repository` model is not prefixed with the namespace.

Am I doing something wrong or is this a bug?

I'm using Portus latest master (5e63b9801d2d2eb718432df5cd591c1fe715eb7b) and the `registry:2.3` image.

**Comment by databus23** [comment]
Actually this does not seem to be the only problem.

Handling events for repositories that are not yet known to portus are bound to always fail because of the ordering in Repository.handle_push_event:
```ruby
namespace, repo_name, tag_name = registry.get_namespace_from_event(event)
return if namespace.nil?

repository = Repository.add_repo(event, namespace, repo_name, tag_name)
return if repository.nil?
```
In my obersavation `registry.get_namespace_from_event` always returns nil for the initial push event because for v2 manifests `Registry#get_tag_from_target` already expects to find the repository in the database but it is not yet created.

**Comment by mssola** [comment]
Hi @databus23. I'm investigating on it. For now, it seems that by only fixing the tags part, it works. I'll try again with an empty registry though.

> In my obersavation registry.get_namespace_from_event always returns nil for the initial push event because for v2 manifests Registry#get_tag_from_target already expects to find the repository in the database but it is not yet created.

```ruby
Repository.add_repo(event, namespace, repo_name, tag_name)
```

This will effectively create the repository if it doesn't exist. My change has been that `Registry#get_tag_from_target` will return the first tag if the repository doesn't exist on the DB. This way, `Repository.add_repo` will create both the repo and the tag.

**Comment by mssola** [comment]
Thanks for reporting by the way :)

**Comment by databus23** [comment]
@mssola 
I think returning early here when no tag is found is problematic:
https://github.com/SUSE/Portus/blob/master/app/models/registry.rb#L66

**Comment by mssola** [comment]
@databus23 could you elaborate ? :)

**Comment by databus23** [comment]
The problem is that for v2 manifests `Registry#get_tag_from_target` calls `Registry#get_tag_from_list` which fails with "undefined method 'tags' for nil:NilClass" when the Repository is not yet in the database (https://github.com/SUSE/Portus/blob/master/app/models/registry.rb#L134).

So `Registry#get_namespace_from_event ` returns nil and `Repository.add_repo` is never called in `Repository.handle_push_event`.

I hope this is making some sense.

**Comment by databus23** [comment]
Not sure where to fix this but its definitly a chicken and egg problem:

`registry.get_namespace_from_event(event)` only returns non nil if the repository is found in the database but the repository will only be created later if it returns something else then nil. This will never work for repositories not already present in the database.

**Comment by mssola** [comment]
Ok, I got it. The thing here, is that now it won't return nil in this valid case. We don't want to add a repo if something along the processing went wrong. This is what I've got now:

```ruby
  # Fetch the tag by making the difference of what we've go on the DB, and
  # what's available on the registry. Returns a string with the tag on success,
  # otherwise it returns nil.
  def get_tag_from_list(repository)
    tags = client.tags(repository)
    return if tags.nil?

    repo = Repository.find_by(name: repository)
    return tags.first if repo.nil?
    resulting = tags - repo.tags.pluck(:name)

    # Note that it might happen that there are multiple tags not yet in sync
    # with Portus' DB. This means that the registry might have been
    # unresponsive for a long time. In this case, it's not such a problem to
    # pick up the first label, and wait for the CatalogJob to update the
    # rest.
    resulting.first
  end
```

Now, it will only return nil when `client.tags` fail, which is fine, because it means that we cannot detect which tag has been pushed. In this case we should do nothing.

**Comment by mssola** [comment]
You are right on `registry.get_namespace_from_event(event)` returning nil. This is a known limitations, because which team do you assign this namespace that has to be created on-the-fly. This is important, because someone has to own the team. One solution that we've thought is to add the ability to change the ownership from one team to the other. If this is possible, then in this case we could always assign new namespaces to the global team, and then the admin could move them as desired. What do you think ?

**Comment by databus23** [comment]
I think your changes to `get_tag_from_list` fixes the chicken and egg problem I tried to describe. :+1:

**Comment by databus23** [comment]
But I think the initial bug i reported i still valid: `Registry#get_tag_from_list` does not work for anything but the global namespace because `Repository.find_by(name: repository)` expects a repository without a namespace

**Comment by mssola** [comment]
@databus23 you're right. I should change:

```ruby
repo = Repository.find_by(name: repository)
```

for

```ruby
repo = Repository.find_by(name: repository, namespace: namespace)
```

**Comment by lonewulf** [comment]
@mssola 
Let's say normal user pushes an image to a non-existing namespace, it would be created, belonging to the global team. There are two possibilites :
- That normal user is not part of the global team, so he won't be allowed to push the image anyway.
- The image is pushed, but won't be accessible to the user
Either way I think it'll just be annoying for the users (and admins that would have to deal with the aftermath)

That said, the ability to change ownership of a namespace sounds like a good idea

**Comment by mssola** [comment]
> - That normal user is not part of the global team, so he won't be allowed to push the image anyway.
> - The image is pushed, but won't be accessible to the user Either way I think it'll just be annoying for the users (and admins that would have to deal with the aftermath)

Good points. We have to give it more thought into it :)

**Comment by mssola** [comment]
@databus23 I'd appreciate if you could take a look at the PR #731 :P

**Comment by flavio** [comment]
@lonewulf, you raised good points.

I have a question for you: from an admin point of view does it even make sense to allow push of images to non-existing namespaces? I guess the answer is no...

Maybe we could do something like that:

  1. User Alice pushes a `foo/bar`. The `foo` namespace does not exist yet.
  2. Portus will block the push request and will log the event
  3. All the admins can review the log and, with a simple click, create the namespace `foo` and assign it to Alice. A mail can be sent to Alice stating she can now push the `bar` image to the `foo` namespace

I think we can collect all the information required to perform the 3rd step during the 1st one.

What do you think?

**Comment by lonewulf** [comment]
@flavio , from an admin perspective, having an image pushed to a non existing namespace should fail.

With the current Portus behavior, the user can create the namespace by himself, so no need to change the way Portus behaves. The only issue is the docker cli not being clear about the namespace not existing, it behaves like the user doesn't has the right credentials to upload to said namespace. I guess notifying him by email could help, but I don't see it as a necessary thing.

When #676 is implemented I guess the workflow you're suggesting would work. Though I would add an option to disable said workflow. If for example, you take a business having strict change policies on production environments, granting access to a user would take a formal demand, an possibly need an approval by people that are not the ones managing Portus.
