### ISSUE TITLE
RFC: do not create a namespace upon team creation

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#73]
Right now when a new team is created an associated namespace is created as well.

Given:
  * we do not have a way to delete teams yet
  * this consumes the possible usernames to pick (because the team's name is used to created the associated namespaces, the same thing happens with users)

I would propose to stop doing that. That would also close issue #72

**Comment by flavio** [comment]
@eotchi what do you think about it?

**Comment by eotchi** [comment]
As discussed elsewhere, I am completely fine with that
