### ISSUE TITLE
How to restart portus

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#733]
How do I restart portus, say after editing the config-local.yml file?
I've looked everywhere in your docs for this basic piece of information.
Simply restarting the apache server is not enough.
please advise.

**Comment by mssola** [comment]
Hi @opichon, it depends. If you are using the RPM setup (is that what are you using ?), then restarting apache should be enough (maybe you also want to restart the crono daemon with systemd). Could you tell me what are you experiencing exactly ?

**Comment by opichon** [comment]
apache log says this:

[Tue Feb 16 10:02:50.074837 2016] [mpm_prefork:notice] [pid 17417] AH00163: Apache/2.4.16 (Linux/SUSE) OpenSSL/1.0.1i-fips Phusion_Passenger/5.0.18 configured -- resuming normal operations
[Tue Feb 16 10:02:50.074943 2016] [core:notice] [pid 17417] AH00094: Command line: '/usr/sbin/httpd-prefork -f /etc/apache2/httpd.conf -D SYSCONFIG -D SSL -C PidFile /var/run/httpd.pid -C Include /etc/apache2/sysconfig.d/ -D SYSTEMD -D FOREGROUND'
App 17484 stdout:
App 17484 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 17484 stderr:
App 17484 stderr:       rake (>= 0.8.1)
App 17484 stderr:
App 17484 stderr: WARN: Clearing out unresolved specs.
App 17484 stderr:
App 17484 stderr: Please report a bug if this causes problems.
App 17484 stderr:
App 17484 stderr: /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `require'
App 17484 stderr: :
App 17484 stderr: cannot load such file -- phusion_passenger
App 17484 stderr:  (
App 17484 stderr: LoadError
App 17484 stderr: )
App 17484 stderr:       from /usr/lib64

**Comment by opichon** [comment]
Yes, I am using the RPM. The server shows an error  message: We are sorry, but something went wrong. The apache log complains about passenger.

**Comment by jordimassaguerpla** [comment]
which version of the RPM are you using?

**Comment by jordimassaguerpla** [comment]
also, can you paste the config-local.yml file you are trying to load?

**Comment by jordimassaguerpla** [comment]
@opichon : Also, please enable passenger debug in /etc/apache2/conf.d/mod_passenger.conf and check the logs again, there may be more information on the problem.

**Comment by opichon** [comment]
I'm using Portus-2.0.1-2.1.x86_64.rpm.
I've reinstalled it and now it works again. As far as the immediate issue is concerned, I can close this ticket. 
But everytime I run zypper update there's a problem.
You may want to keep this in mind.

**Comment by jordimassaguerpla** [comment]
@opichon What exactly do you mean by "But everytime I run zypper update there's a problem" . Which problem is it? In the initial comment you were stating that you had a problem modifying the config-local.yml ...

**Comment by opichon** [comment]
I mean that all my recent problems with portus (which was working fine after an initial installation) seem to cone from the fact that I ran "zypper update" on the server. After running that command, portus didn;t work any more until I reinstalled it.

**Comment by jordimassaguerpla** [comment]
ok. We are just preparing an update package. We'll make sure zypper update does not break anything. Thanks for reporting it.

**Comment by flavio** [comment]
@opichon did something change with the latest package?

**Comment by mssola** [comment]
Closing in favor of #747. In the next release we are going to work on a smoother upgrade path. Feel free to re-open this if the issue still persists though.
