### ISSUE TITLE
Get back to original URL when sent to the login page

### ISSUE THREAD

**Issue by lonewulf** [SUSE/Portus#737]
When you try to access a specific page directly (let's say https://portus-web/teams/4) and you're not logged-in, you are redirected to the login page. After a successful login, you land on the homepage, and not the page you were trying to access initially.
I think you should be taken back to the page you were intending to go first.

Regards,

**Comment by mssola** [comment]
Makes sense. Thanks :)

**Comment by bertoost** [comment]
Hmm I'm not redirected at all. I'll got an 'successfully logged in' message and have to remove `/users/sign_in` manually to go to the dashboard page. Is this a settings or something?

**Comment by mssola** [comment]
@bertoost this is not happening to me on `master` (and honestly I've never thing anything like this on previous releases). Which version are you using?

**Comment by bertoost** [comment]
@mssola I am using v2.4.2 as docker image.

**Comment by bertoost** [comment]
Look.. When logged out, I'll end on the sign-in page;
Logging in again will stay on the sign-in page with a flash message.

![image](https://user-images.githubusercontent.com/398492/54314641-8485e580-45dc-11e9-9575-38a0bf29ac50.png)

I manually have to remove the url part to go back to the dashboard.

**Comment by vitoravelino** [comment]
@bertoost I tested with both master and 2.4.2 and this is not happening. 

If you are signed in and try to visit `/users/sign_in` it redirects you to the index page saying that you are already signed in. So it's pretty weird that you have this behavior. I used the latest versions of Chrome and Firefox. 

Did you try in another browser? Try also to clean up your cookies.

**Comment by bertoost** [comment]
Maybe it's because it's behind a reverse proxy? (Traefik)

**Comment by bertoost** [comment]
Today I thought.. let me google this, ended up with finding this issue 😄 
It's still the issue. Does someone know it's because it's behind a proxy? (Traefik)
