### ISSUE TITLE
using custom ssl certificates

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#738]
I'm trying to use my own ssl certificates. The apache server works (https://www.mydomain.com), but the authentication doesnt (https://www.mysqomain.com/v2//token?account=op&service=my.registry.com%3A5000 )

The apache logs says:
Fri Feb 05 01:17:40.250819 2016] [ssl:warn] [pid 15269] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name

AH00557: httpd-prefork: apr_sockaddr_info_get() failed for ip-172-30-0-232
...skipping...
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
App 6146 stderr:   /srv/Portus/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
App 6146 s

**Comment by jordimassaguerpla** [comment]
1- Do you run registry in the same machine?
2- Where did you copy your certificate? and your private key?

**Comment by opichon** [comment]
Registry is on a different machine.
Certificate is under/etc/ssl/certs and private key under /etc/ssl/private/

in etc/apache2/vhost.d/portus.conf I have these lines:
  SSLCertificateFile /etc/ssl/certs/star_united-asian_com.chain.crt
   SSLCertificateKeyFile /etc/ssl/private/united-asian.com.key

Now my apache config must be correct, since the portus web site works. 
I have also updated the /srv/Portus/config/server.key (symbolic link) to point to the private key.

**Comment by jordimassaguerpla** [comment]
My guess is that the problem is the comunication with the registry since your apache configuration is fine.

Registry needs to be aware of the certificate as well. That may be the problem. You need to do 2 things in that machine:

1- copy the certificate in /etc/registry/ssl.crt
2- add the certificate to your known certificates. If  you are running SUSE in that machine, copy the certificate in  /etc/pki/trust/anchors/ and then run "update-ca-certificates"

Also, you can run the registry to see the logs. Just stop the service and run "registry" and you should see the logs on your standard output. There should be more info on the error.

**Comment by opichon** [comment]
The docker registry in using the same certificates, and they are already installed.
The regisstry config is:
auth:
    token:
        realm: https://dk2.united-asian.com/v2/token
        service: dk1.united-asian.com:5000
        issuer: dk2.united-asian.com
        rootcertbundle: /certs/star_united-asian_com.chain.crt
notifications:
    endpoints:
        - name: portus
          url: https://dk2.united-asian.com/v2/webhooks/events
          timeout: 500ms
          threshold: 5
          backoff: 1s

that config was working initially. The certs have not changed. 
I have restricted the registry just to make sure, but the problem persists.

**Comment by opichon** [comment]
I have also "updated" the registry in the portus admin page. Still no luck.

**Comment by opichon** [comment]
This is the output of the docker login dk1.united-asian.com:5000 command:
Error response from daemon: no successful auth challenge for https://dk1.united-asian.com:5000/v2/ - errors: [token auth attempt for registry https://dk1.united-asian.com:5000/v2/: https://dk2.united-asian.com/v2/token?account=XX&service=dk1.united-asian.com%3A5000 request failed with status: 500 Internal Server Error]
I guess the registry is correctly configured, since it uses the correct url for the portus authentication server.

**Comment by opichon** [comment]
In addition, the error appears when I enter the https://dk2.united-asian.com/v2/token /... url directly in a broswer, without trying to authenticate on the registry. So it's most likely a problem on the portus server.
The apache error log says:
```
[Fri Feb 05 01:17:40.250819 2016] [ssl:warn] [pid 15269] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
AH00557: httpd-prefork: apr_sockaddr_info_get() failed for ip-172-30-0-232
```
ip-172-30-0-232 is the internal IP address for the AWS EC2 instance running the portus server.
As far as I can see, the apache server is correctly configured with Servername dk2.united-asian.com.
But somehow portus still considers the internal ip.

in srv/Portus/config/secrets.yml, I have configured the machine_fqdn setting to dk2.united-asian.com.

**Comment by opichon** [comment]
I've also tried adding
machine_fqdn:
  value: dk2.united-asian.com
to the portus config-local.yml file.

**Comment by jordimassaguerpla** [comment]
Everything was working before you updated it with your own certificate?

Can you run:

openssl x509 -in SERVER.crt -noout -subject

Just to see the CN.

And then, in portus, run

hostnamectl --static status

Are they the same hostname?

**Comment by opichon** [comment]
Everything was working fine with my own certificates until I ran "zypper update".

openssl x509 -in /etc/ssl/certs/star_united-asian_com.chain.crt -noout -subject
subject= /OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.united-asian.com
hostnamectl --static status
dk2.united-asian.com

**Comment by opichon** [comment]
I have reinstalled portus RPM in a new AWS EC2 instance. The website works: I can login. But the apache error log displays this:

AH00557: httpd-prefork: apr_sockaddr_info_get() failed for ip-172-30-0-85
AH00558: httpd-prefork: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
[Wed Feb 17 11:33:07.051490 2016] [mpm_prefork:notice] [pid 3221] AH00163: Apache/2.4.16 (Linux/SUSE) OpenSSL/1.0.1i-fips Phusion_Passenger/5.0.18 configured -- resuming normal operations
[Wed Feb 17 11:33:07.051592 2016] [core:notice] [pid 3221] AH00094: Command line: '/usr/sbin/httpd-prefork -f /etc/apache2/httpd.conf -D SYSCONFIG -D SSL -C PidFile /var/run/httpd.pid -C Include /etc/apache2/sysconfig.d/ -D SYSTEMD -D FOREGROUND'
App 3337 stdout:
App 3337 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 3337 stderr:
App 3337 stderr:       rake (>= 0.8.1)
App 3337 stderr:
App 3337 stderr: WARN: Clearing out unresolved specs.
App 3337 stderr:
App 3337 stderr: Please report a bug if this causes problems.
App 3337 stderr:
App 3337 stderr: /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `require'
App 3337 stderr: :
App 3337 stderr: cannot load such file -- phusion_passenger
App 3337 stderr:  (
App 3337 stderr: LoadError
App 3337 stderr: )
App 3337 stderr:        from /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `<main>'
App 3354 stdout:

**Comment by opichon** [comment]
I seem to have resolved the "ServerName" issue by adding a ServerName directive in /etc/apache2/global.conf. I am not familiar with opensuse, and I am afraid that this setting may be overwritten at some stage. It looks like the global.conf file is generated somehow.

**Comment by opichon** [comment]
The hostname keeps changing back. I don't know if this is an opensuse problem (some forums questions mention this problem) oran AS EC2 issue.

**Comment by opichon** [comment]
The hostname issue, I believe, was because the hostname was set bvia DHCP. I've changed the setting in /etc/sysconfig/network/dhcp, and it now seems to work. However, I still have this error in the apache2 log when loading a page in the portus server (UI):


Wed Feb 17 14:13:15.085565 2016] [mpm_prefork:notice] [pid 10426] AH00163: Apache/2.4.16 (Linux/SUSE) OpenSSL/1.0.1i-fips Phusion_Passenger/5.0.18 configured -- resuming normal operations
[Wed Feb 17 14:13:15.085633 2016] [core:notice] [pid 10426] AH00094: Command line: '/usr/sbin/httpd-prefork -f /etc/apache2/httpd.conf -D SYSCONFIG -D SSL -C PidFile /var/run/httpd.pid -C Include /etc/apache2/sysconfig.d/ -D SYSTEMD -D FOREGROUND'
App 10493 stdout:
App 10493 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 10493 stderr:
App 10493 stderr:       rake (>= 0.8.1)
App 10493 stderr:
App 10493 stderr: WARN: Clearing out unresolved specs.
App 10493 stderr:
App 10493 stderr: Please report a bug if this causes problems.
App 10493 stderr:
App 10493 stderr: /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `require'
App 10493 stderr: :
App 10493 stderr: cannot load such file -- phusion_passenger
App 10493 stderr:  (
App 10493 stderr: LoadError
App 10493 stderr: )
App 10493 stderr:       from /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `<main>'
App 10510 std

**Comment by jordimassaguerpla** [comment]
This error means there has been a 500 error but we can't tell which is the error. Could you try sending us more info? I mean from the logs, so that we can know if this is the same error (hostname not matching certificate) or is a new problem.

**Comment by opichon** [comment]
The logs are what I posted earlier. Tell me what else I can give you. What other logs do you want?

**Comment by opichon** [comment]
After a reinstallation of portus with the latest rpm, this now works.
