### ISSUE TITLE
docker-compose.sh assumes docker-compose 1.6 without expressing it

### ISSUE THREAD

**Issue by twizod** [SUSE/Portus#741]
#> git clone https://github.com/SUSE/Portus.git
#> cd into Portus
#> run: ./docker-compose.sh -e <internal ip of vm>

Get message saying, "No such thing as version"

docker-compose below 1.6 has no "version" option so had to upgrade to latest docker-compose to get it to work.

Probably need some check in script to express this requirement since main page doesn't explicitly say what version of docker-compose you should have installed on: https://github.com/SUSE/Portus.

Also, since I just upgraded docker-compose I am still running docker engine 1.9.1 build a34a1d5 and worked fine executing script.

**Comment by cyphar** [comment]
@twizod You're right. It's meant to be `docker-compose --version`.
