### ISSUE TITLE
Improve our containers setup

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#746]
- [ ] Improve setup when other pieces already exist on the system (e.g. there's already a registry in place).
- [ ] Add documentation on how to run all this on production: both with docker-compose and when only some pieces are to be deployed.
- [ ] Portus docker container should have SSL option natively: See #665.
- [ ] Possibly add documentation on how to integrate it with orchestration solutions.
- [ ] Prebuilt images for our docker-compose setup. See #370.

**Comment by egidijus** [comment]
Hi again,
With this project I am hoping to do 90% of what you have listed.
https://github.com/madedotcom/portus-pie-provisioner

Plugging-in portus in to an existing registry automagically does not sound easy. It is going to depend on how managed your configuration is.

I can provide practical (real, production) examples and documentation of/for:
* building portus locally
* tagging and pushing to some kind of existing registry
* deploying portus with the pushed images and Ansible on AWS
* Ansible
* building working (alpine-based) docker images without secrets, secrets injected at runtime (no need for consul yet)

just a matter of time and what to focus on first..

**Comment by mssola** [comment]
Hi @egidijus, thanks for stepping in. I'll definitely take a look at the project you're mentioning whenever I have the time to tackle this issue.

> Plugging-in portus in to an existing registry automagically does not sound easy. It is going to depend on how managed your configuration is.

What I'm mentioning is actually a pretty frequent scenario: I want to deploy Portus and I already have a registry in place. I don't think there's an automatic way to do this, but we should provide a way to minimize the effort of doing this.

What I'm mostly talking in this issue is that a containerized version of Portus should be as minimalistic as possible, while being friendly to real-world production environments. People should be able to pick up our image then and perform some basic customizations in order to fit their production setup.

Most importantly, what we lack are examples. So any guide, setup, etc. on how to deploy Portus on platform/orchestration solution/environment X, would be welcome. Note that we have a `Setup` section on our [documentation](http://port.us.org/documentation.html), but none of these setups are based on containers (which is sad). The documentation of Portus simply lives on the `gh-pages` branch, so if you have some ideas don't be afraid. You can even pull PPP into this :)

Thanks for all your comments :+1:

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
