### ISSUE TITLE
Crono should be able to create missing namespaces

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#751]
One option would be to move it to the global namespace, and then allow admins to change the ownership to the corresponding team (see #750). But I'm not sure, so I'm marking this as `discussing` :P

**Comment by holgerreif** [comment]
One idea is to introduce a kind of state attribute to a namespace. 
* State `discovered` means there is something in the registry found by crono.
   On the UI the namespace is only visible and managable by portus admin. Once the portus admin names one or more teamspace owners, the state switches to `managed`. 
Alternatively the portus admin could mark this namespace as a personal one switching to state `managed` as well. However I'm not sure whether there are conflicts if the user later signs up or is recognized via LDAP.
* State `managed` is exactly the current behaviour.
* In state `abandoned` the namespace is only visible to the portus admin. It means the admin is aware of a discovered namespace but he does not want to provide access to it. It must be possible for portus admin to change the state afterwards .
* Optionally a discovered namespace could get promoted to state `public` which means there is no owner but everyone could pull from this space and access it (ro) from the UI.

**Comment by mssola** [comment]
> State discovered means there is something in the registry found by crono. On the UI the namespace is only visible and managable by portus admin. Once the portus admin names one or more teamspace owners, the state switches to managed. Alternatively the portus admin could mark this namespace as a personal one switching to state managed as well. However I'm not sure whether there are conflicts if the user later signs up or is recognized via LDAP.

I also thought of this: put a new namespace into either the global team, or into an admin-managed special dashboard of some sorts. In there, an admin would then designate the namespace into the proper team.

I guess that my main fear is: will admins really take a look into the `discovered` namespaces ? If not (which is the most probable :P), we should then be sending emails, which can be annoying. For that reason I was proposing to simply put it into the global (hidden) team and made them public: if the admin forgets about the namespace being created, it would still be usable for other users. Another option would be to add a configuration option that tells Portus which visibility value (public/private) should imported namespaces have by default. This way we would avoid annoying administrators with emails/notifications/extra work, while keeping it simple (there wouldn't be states). Of course, if admins then want to take care of all this, they can still change the visibility of the namespace or change the ownership of it (see #750).

> In state abandoned the namespace is only visible to the portus admin. It means the admin is aware of a discovered namespace but he does not want to provide access to it. It must be possible for portus admin to change the state afterwards .

How is that different from a `private` namespace ?

**Comment by holgerreif** [comment]
I see, we might have a different philosophy here about the role of the protus admin, who finally initiates - and delegates - access control permission.
   * My POV is strong control by portus admin: somthing found but not approved by him should not be usable
   * Your POV seems to be maximum usability w/o admin intervention
I won't judge what is better approach, but I think if I invest in something like portus I should have some procedures in place...

> I guess that my main fear is: will admins really take a look into the discovered namespaces ?

Actually, the appearance of a discovered namespace should be a rare event. Generating an email is not needed. I guess the user who can't access his repository would send a mail to the admin anyway...

> How is that different from a `private` namespace ?

A `private` namespace belongs to a user as his personal namespace or to a team. The `abandoned` namespace belongs to nobody. It just no longer visible in the list of `discovered` namespaces. It's a marker from the admin "I have noticed this namespace but I won't no longer bother with it".

> For that reason I was proposing to simply put it into the global (hidden) team

From the user's perspective it's the same (belongs to nobody), but the admin perspective is different: there is no distinction whether he already decided or not. Another advantage for proposed state `abandoned` is that admin could mark some repositories as no longer belonging to someone.

**Comment by half-dead** [comment]
I'm more agreed with holgerreif's idea, the State attribute makes it more flexible.
About the `abandoned` State, I think it could be used for those repos that belongs to a former-employee, or those that are deprecated.

**Comment by mssola** [comment]
@holgerreif @half-dead  thanks for the feedback :)

> Your POV seems to be maximum usability w/o admin intervention I won't judge what is better approach, but I think if I invest in something like portus I should have some procedures in place...

Would just making them private by default work for you in this scenario ?

> Actually, the appearance of a discovered namespace should be a rare event. Generating an email is not needed. I guess the user who can't access his repository would send a mail to the admin anyway...

Fair enough.

> A private namespace belongs to a user as his personal namespace or to a team. The abandoned namespace belongs to nobody. It just no longer visible in the list of discovered namespaces. It's a marker from the admin "I have noticed this namespace but I won't no longer bother with it".
>
> From the user's perspective it's the same (belongs to nobody), but the admin perspective is different: there is no distinction whether he already decided or not. Another advantage for proposed state abandoned is that admin could mark some repositories as no longer belonging to someone.

At first I wasn't convinced, but now I am :) That being said, I see this as a separate feature.

**Comment by ghostsquad** [comment]
Is there a way to do this manually?

**Comment by weynhamz** [comment]
Due to some problems with the background sync process, it deleted some of the namespaces in Portus db, (I have no idea why, the logs are long gone), but the images seem still in the registry, I am trying to recover those namespaces into to Portus db, looks like this is the exact feature I need, but I can not wait for it to be roll out, so, is there a way to do manually?

**Comment by mssola** [comment]
> Is there a way to do this manually?

Well, before running the background process (that's how it's called since `2.3`), you can actually pull the catalog like so (from the portus directory, and use `portusctl` instead of `bundle` if you are inside of the container):

```
$ bundle exec rails r bin/client.rb catalog
```

This will list the catalog, and so you will be able to fetch the list of namespaces (by using `jq` and a bit of unix trickery :wink:). Then you simply create these namespaces yourself.

> Due to some problems with the background sync process, it deleted some of the namespaces in Portus db, (I have no idea why, the logs are long gone)

Oh... Could you be a bit more specific though? (version of Portus, configuration being used, etc.).

> I am trying to recover those namespaces into to Portus db, looks like this is the exact feature I need, but I can not wait for it to be roll out, so, is there a way to do manually?

See what I said above :wink:

**Comment by mssola** [comment]
I'm also going to close this old issue in favor of the more specific #1961. That issue will also take into consideration what has been discussed here so far :+1:
