### ISSUE TITLE
Automate further the release process

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#757]
@jordimassaguerpla has a [set of scripts](https://github.com/jordimassaguerpla/Portus/tree/automate_portus_release/packaging/suse/release) in his personal fork that already automates some of the stuff involved when releasing Portus. The idea would be to further improve these scripts in order to make the releasing proccess smoother.

**Comment by diranged** [comment]
I'm curious -- why is Portus not just natively released as a Docker Image? We forked the repo purely so we could build the image and ship it to DockerHub -- no code changes necessary.

**Comment by mssola** [comment]
This is not relevant anymore. Closing (see #1464 for the portusctl part).

**Comment by mssola** [comment]
> why is Portus not just natively released as a Docker Image?

See [the official docker image](https://hub.docker.com/r/opensuse/portus/).
