### ISSUE TITLE
Allow admins to create/register users

### ISSUE THREAD

**Issue by egidijus** [SUSE/Portus#758]
This feature request is primarily aimed at automated services.
We create a pusher and a puller user in portus.

We have per project(namespace) pusher/puller user accounts.
Example: `nodejs-app-pusher`
Jenkins builds our images, tags them, and then pushes to a namespace.
Ansible/nomad will use the puller user to pull image from namespace.

Alternatively, we will create users directly on the database and copy/paste users for new projects.

**Comment by lonewulf** [comment]
As far as I know, you can already do that, when logged in with an administrator account:
- Go to the admin dashboard
- Click on 'Users'
- Click on 'Create new user'

**Comment by egidijus** [comment]
@lonewulf I am probably being stupid, but do you know which release has this feature ?

**Comment by mssola** [comment]
@egidijus this has been implemented in the PR #543. It's on master, and it will be inside of the 2.1 release. Does that cover what you need?

**Comment by egidijus** [comment]
Excellent, yes it does.
Thank you both!
