### ISSUE TITLE
Cannot get /v2/<repo>/tags/list to work - error is "insufficient scope"

### ISSUE THREAD

**Issue by wolfch** [SUSE/Portus#760]
I wrote a Python client to interact with v2 registry with token authentication enabled via Portus.  I have a wrapper function around [requests.get](http://docs.python-requests.org/en/master/user/quickstart/#make-a-request) that fetches a token based on the challenge in the `WWW-Authenticate` header.  It works fine for calling `/v2/_catalog` to get the list of repositories, however when I try to get a list of tags I get an "insufficient scope" error.

If I don't use the wrapper function and run the same code on a v2 registry without authentication, the code works - it lists the all the tags of each repository.

Here is the debug output showing the challenge, token and response headers of the failed request, if anyone can help me out - thanks!

```
DEBUG:RegistryV2Client:{'scope': 'repository:cwolf/busybox:pull', 'service': 'ulv-tordockerhub01.canlab.com:5000', 'Bearer realm': 'http://ulv-tordockerhub01.canlab.com:3000/v2/token'}
DEBUG:RegistryV2Client:{u'issued_at': u'2016-02-25T00:09:06+00:00', u'token': u'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlBUV1Q6Rk5KRTo3VFc3OlVMSTc6RFpRQTpKSkpJOlJESlE6Mk03NjpIRDZHOlpSU0M6VlBJRjpPNUJVIn0.eyJpc3MiOiJ1bHYtdG9yZG9ja2VyaHViMDEuY2FubGFiLmlibS5jb206NTAwMCIsInN1YiI6bnVsbCwiYXVkIjoidWx2LXRvcmRvY2tlcmh1YjAxLmNhbmxhYi5pYm0uY29tOjUwMDAiLCJpYXQiOjE0NTYzNTg5NDYsIm5iZiI6MTQ1NjM1ODk0MSwiZXhwIjoxNDU2MzU5MjQ2LCJqdGkiOiJZVDFTZW5IM0JFajRqcno0czd1MXFhUlFmZ0w3S0dqRDNmV3k2aW9reXciLCJhY2Nlc3MiOltdfQ.LIG8qHH1vMHoWYqKGOP4v9K7jQasWKy8WT0o8JoT-EfOQY5jGg2f1eoKIt_Lemj58kgngWUZh0ru1CG_NUNzvgHKIAE5wZoAQwVddm7876Ehggos-5ru2GErlD768bx3LGfZBAYrf9RTqaMDo3YF2cLb2peIXja1cyA6gSoKO77jObzgIGeRyxqIrQxVxRRUDhfFZyhynUAeJXTOFHgoAB6cJHlWxzahU4R9v2VjSDw62zTyG0X7NSPEbMg4kwiG4Su_Im4AsFmEYDQCqYXuwb5uweSkSIAOZgtkQbhv3Qjd4nOj0Q4pAYm88BGrLU68VpxySSymH0FYkHeeRuYdg8FrIutnVhwgRCRsFpDxsAro_qDDH-Qv0Nwiuk9NyPZCzuVLp7KmTQVtuTn4uBiKVrrOeStFFxdHwTOxEjLkpac-FJdJbjZf-T35PIsi7JRxo8hWz3e4qLZ2TBsM5w0AYAo04LoWU6qIrEvWf6BDfD0-fxqrIHQb1sA4vCH3UXSlc8haVSH79KMBbg55gjhm3kXlkCyOCx2OTfkdkAhjO9kLMV_wA4upx1ceU-YX1T40C7dQzcMjeZwAh2ohbRf8jKon1EQcFy5DfHOG4j5bYo3kkxNpYPT8ouprvYVkMHVtIpn2HyNt4dSbY0Qg8DdF7tTwKwBixYGmzPI5eMdR7-M', u'expires_in': 300}
DEBUG:RegistryV2Client:{'date': 'Thu, 25 Feb 2016 00:09:07 GMT', 'docker-distribution-api-version': 'registry/2.0', 'content-length': '145', 'content-type': 'application/json; charset=utf-8', 'www-authenticate': 'Bearer realm="http://ulv-tordockerhub01.canlab.com:3000/v2/token",service="ulv-tordockerhub01.canlab.com:5000",scope="repository:cwolf/busybox:pull",error="insufficient_scope"'}
```

**Comment by wolfch** [comment]
On a hunch, I programmatically altered the scope string from ```repository:cwolf/busybox:pull``` to ```repository:cwolf/busybox:*``` and this time, the code successfully retrieved the list of tags for that repository - the question is why do I need to override the actions portion of the scope string with wildcard, rather then using what Portus returns?

I also noticed that in Portus code, ```Portus/lib/portus/http_helpers.rb```, the function, ```parse_unhauthorized_response(res)``` - that code adds a request parameter named "account" equal to the login username, however, I don't see any mention of that in the token auth spec: https://github.com/docker/distribution/blob/master/docs/spec/auth/token.md

If I add that "account" header or not it doesn't seem to matter.  Is this "leftovers", or really required?

**Comment by mssola** [comment]
Hi @wolfch. Which version of Portus/docker/distribution are you using ? There's been some changes lately on all sides :sweat_smile:.

**Comment by wolfch** [comment]
Hi @mssola, thanks:

Portus, master branch and commit:
```
 $ git rev-parse HEAD
51b780d3c44cc51c0d820fe22c47c72b7ea5f3aa
$ docker --version
Docker version 1.9.1, build a34a1d5
```
...and registry/distribution is 2.2.0.

**Comment by diranged** [comment]
This is interesting -- I was trying to do the same thing with some bash scripts and ran into the exact same problem. Catalog pulls were fine, but tags/list pulls all threw insufficient scope errors. I never thought to use `*` ... I'll try that later and report back.

**Comment by wolfch** [comment]
Even if ```*``` works, I still think there's a potential bug in Portus since when you attempt to access a resource, the challenge from Portus is supposed to identify the _minimum_ required scope in the ```WWW-Authenticate``` header _from Portus_.  

For attempting a tag list - _Portus_ is telling me to request ```pull``` as the action part of the scope from the token server, so either it should be specifying some other action or actions - or the the action, ```pull``` is correct but there's a problem with the access control code when the action part of the scope is evaluated.

**Comment by wolfch** [comment]
Unless @diranged is still having this issue in his script, I consider the matter - _**not a bug**_.  Today, doing the tags/list works now with ```pull``` as the action part of the scope rather then having to override it with ```*```.  Sorry guys - I've been making a lot of changes to the environment, trying to convert the development, out-of-the-box docker-compose setup to be production worthy.  We can't use the SUSE RPM because we're on Ubuntu & RHEL.

**Comment by cyphar** [comment]
@wolfch You could probably adapt the build script for the SUSE RPM for RHEL. Feel free to open a PR to add support for either distribution!

**Comment by wolfch** [comment]
@cyphar Ok, once I have a process in place I will advise - thanks.

**Comment by mssola** [comment]
This should be fixed by now. If you have further issues with the deployment, check the examples and the [how to deploy](http://port.us.org/docs/deploy.html) page.

**Comment by wesm-outreach** [comment]
@wolfch I'd like more clarification on what the correct way is to make docker registry API requests based on your previous comment.

**Comment by wolfch** [comment]
@wesm-outreach It's been years since I've messed with Portus.  
If you're asking just about registry API calls, I only recall just running a bare, insecure registry:
```
docker run -d -p 5000:5000 --restart=always --name registry registry:2
```
...then let's say you pushed an image: `docker push 127.0.0.1:5000/coreos:latest`
Then you can do:
```
$ curl http://localhost:5000/v2/_catalog
{"repositories":["coreos"]}
$ curl http://localhost:5000/v2/coreos/tags/list
{"name":"coreos","tags":["latest"]}
```
This is without Portus and with an insecure registry.  For other API calls see:
https://docs.docker.com/registry/spec/api/#introduction

Apologies if you were asking how to setup the full locked-down registry using Portus.

**Comment by wesm-outreach** [comment]
@wolfch the question was along the lines of having Portus be the authentication mechanism. This particular issue seems to point to an issue with Portus not providing the correct scope when requested. Here's an issue describing the exact problem I'm having:
https://github.com/SUSE/Portus/issues/1134 but unfortunately it doesn't got into any detail as to a real fix. The user says they are an admin already, and the code that is pointed out is just checking if that user is an admin.

I've done a fair bit of digging and found these other issues too
This issue points to FQDN mismatch, which is not the case
https://github.com/SUSE/Portus/issues/1736

This issue completely sidesteps the problem with a workaround:
https://github.com/SUSE/Portus/issues/1715

I'm just lost as to what could be the problem. I can put together a compose file to repro this.

**Comment by danielclasen** [comment]
Same issue for me here with registry:2.6 and registry:2.6.2 and portus:2:3
But for me it occurs while the portus background container tries to sync with the registry. Checked multiple times that the FQDN and REGISTRY_AUTH_TOKEN_SERVICE do actually match. Any help appreciated.
I am going to try an older registry version now... *fingers crossed*

**Comment by danielclasen** [comment]
It is also happening with portus:head and registry:2.4 - registry:2.6.2 (with all combinations). In the portus container I can see that the token request gets answered with a HTTP 200, like that:

```
31.7.2018 11:40:29Started GET "/v2/token?account=portus&scope=repository%3Alogs%2Flogstash%3Apull&service=portus.intra.mytld.de" for 10.42.193.162 at 2018-07-31 09:40:29 +0000
31.7.2018 11:40:29Processing by Api::V2::TokensController#show as JSON
31.7.2018 11:40:29  Parameters: {"account"=>"portus", "scope"=>"repository:logs/logstash:pull", "service"=>"portus.intra.mytld.de"}
31.7.2018 11:40:30Completed 200 OK in 58ms (Views: 0.1ms | ActiveRecord: 0.9ms)
```

While the registry shows the following:

```
31.7.2018 11:40:2910.42.193.162 - - [31/Jul/2018:09:40:29 +0000] "GET /v2/logs/logstash/tags/list?n=100 HTTP/1.1" 401 156 "" "Ruby"
31.7.2018 11:40:30time="2018-07-31T09:40:30.043216687Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=portus.intra.mytld.de http.request.id=1e7d452b-e8b5-4005-b9fd-1b8bd32e6835 http.request.method=GET http.request.remoteaddr=10.42.139.30 http.request.uri="/v2/logs/logstash/tags/list?n=100" http.request.useragent=Ruby instance.id=e148ec43-ec77-4710-bb95-394ec5b40d46 service=registry vars.name="logs/logstash" version=v2.6.2
31.7.2018 11:40:30time="2018-07-31T09:40:30.043478903Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=portus.intra.mytld.de http.request.id=1e7d452b-e8b5-4005-b9fd-1b8bd32e6835 http.request.method=GET http.request.remoteaddr=10.42.139.30 http.request.uri="/v2/logs/logstash/tags/list?n=100" http.request.useragent=Ruby instance.id=e148ec43-ec77-4710-bb95-394ec5b40d46 service=registry vars.name="logs/logstash" version=v2.6.2

```
