### ISSUE TITLE
Gem install with RAILS_ENV=production is missing something

### ISSUE THREAD

**Issue by dforste** [SUSE/Portus#768]
Doing a bundle install with IGNORE_ASSETS="no"  and RAILS_ENV=production causes several things to not work. 

Logout link is broken/404 along with trying to make a namespace public and team creation.

**Comment by mssola** [comment]
This is weird (and I can't reproduce it). Are you sure that the needed gems have been installed ? Have you changed the `Gemfile.lock` somehow ? Which version of Portus are you using ?

**Comment by dforste** [comment]
I used this docker file to build and run it. 
```
ENV PORTUS_VER 2.0.2

RUN git clone https://github.com/SUSE/Portus.git /portus && \
    cd /portus && \
	git checkout $PORTUS_VER

WORKDIR /portus

ENV IGNORE_ASSETS="no" 
ENV RAILS_ENV=production 
RUN bundle install --retry=3

RUN bundle exec rake assets:precompile
ENV IGNORE_ASSETS="yes" 

ADD puma.rb /portus/config/

EXPOSE 3000

CMD ["/usr/local/bundle/bin/puma", "-C", "/portus/config/puma.rb"]
```

Removing these lines fixes things: 
```
ENV IGNORE_ASSETS="no" 
ENV RAILS_ENV=production 

RUN bundle exec rake assets:precompile
ENV IGNORE_ASSETS="yes" 
```


puma.rb 
```
#!/usr/bin/env puma

# Workers and connections.
threads 1, 4
workers 3
bind "tcp://0.0.0.0:3000"

# #Daemon config. It will save the pid to tmp/pids/puma.pid. All the output
# #from both stdout and stderr will be redirected to logs/puma.log.
# log_file = File.join(Dir.pwd, "log/puma.log")
# stdout_redirect log_file, log_file, true
# pidfile File.join(Dir.pwd, "tmp/pids/puma.pid")
# daemonize

# Copy on write.
preload_app!

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end

```

**Comment by dforste** [comment]
I tested this on what I think is the latest version of the rails container. This container ships with ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

I see a note about only being compatible with ruby 2.1. Is this still the case? 
http://port.us.org/docs/setups/1_rpm_packages.html#common-pitfalls

**Comment by mssola** [comment]
So officially we only support 2.1. That being said, future ruby versions should be ok, as we also test them. Could you use the same rails version that we are using, so ruby 2.1 is picked, and test if you can still reproduce it then ?

**Comment by dforste** [comment]
I do not currently have time to reproduce this error. If someone else runs into it they can look at simply removing the RAILS_ENV from their dockerfile.
