### ISSUE TITLE
error loading portus certificate

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#770]
After a fresh installation of portus and configuring the docker registry for portus, the docker registry is broken and I get this error in the docker registry logs:

```
panic: unable to configure authorization (token): unable to parse token auth root certificate: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:257 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} tbsCertificate @4
```

The registry runs the latest registry:2 image in a separate server. The config is as per the portus docs (as output after running portusctl setup). This output refers to "the portus certificate" (to be copied to the registry server). I have taken this to mean `/etc/apache2/ssl.crt/<portus hostname>-server.crt`.

**Comment by opichon** [comment]
The appropriate certificate to copy to the registry is the `<portus.hostname,com>-ca.cert` certificate, NOT  `<portus.hostname.com>-server.crt`.

**Comment by jordimassaguerpla** [comment]
thanks

**Comment by jordimassaguerpla** [comment]
Where did you get you should use the *-server.crt ? I just a did a grep on our docs and code and didn't find it ... I'd like to fix it if it is on our code or documentation.
thanks

**Comment by opichon** [comment]
After running `portusctl setup` the command outputs a sample registry configuration. In it it mentions the portus certificate as 'portus.crt' but does not say which of the 2 certificates generated by portus should be used (-server.crt or -ca.crt). The -server.crt seemed to me to be the obvious choice -- wrongly, as it turned out.
