### ISSUE TITLE
Logout and Repository Search in small devices

### ISSUE THREAD

**Issue by msfernandes** [SUSE/Portus#772]
[Vagrant Setup]
Logout button and "Repository Search" in top bar is not displayed in small devices (e.g. my xperia z3 compact in portrait mode), so I can not logout the system or search for a repository.

My suggestion: showing only portus logo (the lighthouse) increases the available space to insert the logout button and a button to "Search Repository", that would open the search form below the top bar.

![photo_2016-03-03_11-05-28](https://cloud.githubusercontent.com/assets/2891076/13496596/dc9771d6-e12f-11e5-9cf1-3cdbf6e84660.jpg)

**Comment by msfernandes** [comment]
![photo_2016-03-03_11-05-28](https://cloud.githubusercontent.com/assets/2891076/13496596/dc9771d6-e12f-11e5-9cf1-3cdbf6e84660.jpg)

**Comment by mssola** [comment]
Good catch :)

Even though I'd say that the UI of Portus has not been thought to be displayed on small devices. This is something that we should improve in the future.

**Comment by msfernandes** [comment]
I started to work in this issue, but I want a feedback about the solution:
![photo_2016-03-03_14-04-39](https://cloud.githubusercontent.com/assets/2891076/13502248/e54203d2-e148-11e5-9de8-fc0a539b914d.jpg)
