### ISSUE TITLE
Create dynamic robots.txt

### ISSUE THREAD

**Issue by bhaprayan** [SUSE/Portus#775]
This is a possible improvement to the existing project
Could we generate a separate robots.txt file for the production and development environments?
It could be generated dynamically based on the current environment.

**Comment by holgerreif** [comment]
Can you give examples for different `robots.txt` files?

**Comment by tboerger** [comment]
@bhaprayan and what do you want to change? You need to be logged in anyway to see real content?

**Comment by mssola** [comment]
Seems like I didn't see this issue, sorry about that ! Just like @holgerreif and @tboerger I don't see the usefulness of this feature. Could you expand on this ?

**Comment by bhaprayan** [comment]
Hi, thanks for the response! Well the plan was to create a dynamic robots.txt file for web crawlers, to allow selective access for crawling. I later realized that would be a redundant feature,as @tboerger has mentioned already, due to the fact that the web crawler wouldn't be able to access the content without the login credentials.
