### ISSUE TITLE
scripts and Dockerfiles for easy portus + docker registry

### ISSUE THREAD

**Issue by egidijus** [SUSE/Portus#784]
This should make deploying portus + docker registry on a single host very easy.

https://github.com/madedotcom/portus-pie-provisioner

**Comment by mssola** [comment]
Thanks! :clap:

**Comment by mssola** [comment]
@egidijus we've just created an open mailing list specific to Portus. See: https://groups.google.com/forum/#!forum/portus-dev. Maybe you'd want to consider posting this there. I believe that issues should be for actual bugs and so on :wink: What do you think ?

**Comment by egidijus** [comment]
DONE, thank you.
