### ISSUE TITLE
500 Error when trying to get Token from the registry

### ISSUE THREAD

**Issue by veacks** [SUSE/Portus#790]
Hi,

I can connect on Portus UI without any issue with a selfsigned certificate.

But when I try to login with my docker client to the registry, I always have the following error from Portus when it try to generate the authorisation  token:

	OpenSSL::PKey::RSAError (Neither PUB key nor PRIV key: nested asn1 error):
	  lib/portus/jwt_token.rb:48:in `initialize'
	  lib/portus/jwt_token.rb:48:in `new'
	  lib/portus/jwt_token.rb:48:in `private_key'
	  lib/portus/jwt_token.rb:20:in `encoded_hash'
	  app/controllers/api/v2/tokens_controller.rb:31:in `show'

	Processing by ErrorsController#show as JSON
	Parameters: {"account"=>"vdubois", "service"=>"ec2-xx-xx-xx-xxx.ap-southeast-2.compute.amazonaws.com:5000", "status"=>"500"}
	Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
	Error during failsafe response: Missing template errors/500, application/500 with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee]}. Searched in:
		* "/portus/app/views"
		* "/usr/local/bundle/gems/kaminari-0.16.3/app/views"
		* "/usr/local/bundle/gems/devise-3.5.1/app/views"

	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/path_set.rb:46:in `find'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/lookup_context.rb:121:in `find'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/renderer/template_renderer.rb:8:in `render'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/renderer/renderer.rb:42:in `render_template'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/renderer/renderer.rb:23:in `render'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/rendering.rb:100:in `_render_template'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/streaming.rb:217:in `_render_template'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/rendering.rb:83:in `render_to_body'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/abstract_controller/rendering.rb:25:in `render'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/rendering.rb:16:in `render'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
	/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
	/usr/local/bundle/gems/activerecord-4.2.2/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
	/portus/app/controllers/errors_controller.rb:13:in `show'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/abstract_controller/base.rb:198:in `process_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:117:in `call'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:505:in `call'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:92:in `_run_callbacks'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
	/usr/local/bundle/gems/activerecord-4.2.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/abstract_controller/base.rb:137:in `process'
	/usr/local/bundle/gems/actionview-4.2.2/lib/action_view/rendering.rb:30:in `process'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal.rb:196:in `dispatch'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_controller/metal.rb:237:in `block in action'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:74:in `call'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:43:in `serve'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:30:in `each'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/journey/router.rb:30:in `serve'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/routing/route_set.rb:819:in `call'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/usr/local/bundle/gems/railties-4.2.2/lib/rails/rack/logger.rb:38:in `call_app'
	/usr/local/bundle/gems/railties-4.2.2/lib/rails/rack/logger.rb:20:in `block in call'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:26:in `tagged'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/tagged_logging.rb:68:in `tagged'
	/usr/local/bundle/gems/railties-4.2.2/lib/rails/rack/logger.rb:20:in `call'
	/usr/local/bundle/gems/actionpack-4.2.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
	/usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	/usr/local/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
	/usr/local/bundle/gems/railties-4.2.2/lib/rails/engine.rb:518:in `call'
	/usr/local/bundle/gems/railties-4.2.2/lib/rails/application.rb:164:in `call'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/commonlogger.rb:31:in `call'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
	/usr/local/bundle/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
	[7] 210.8.12.141 - - [21/Mar/2016:05:45:05 +0000] "GET /500?account=vdubois&service=ec2-xx-xx-xx-xxx.ap-southeast-2.compute.amazonaws.com%3A5000 HTTP/1.1" 500 - 0.0845

I have tried with a wrong password and get a proper 401 (so the issue doesn't come from a wrong username/password)

	registry_1 | time="2016-03-21T06:09:28Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host=ec2-52-62-70-225.ap-southeast-2.compute.amazonaws.com http.request.id=3438a9f4-6dcb-4aef-a723-69476ca763a2 http.request.method=GET http.request.remoteaddr=210.8.12.141 http.request.uri="/v2/" http.request.useragent="docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/4.0.9-boot2docker os/linux arch/amd64" instance.id=b2eb7dca-8f00-4850-bd1a-ceab95f32836 version=v2.3.1 
	registry_1 | 172.17.0.1 - - [21/Mar/2016:06:09:28 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "docker/1.8.1 go/go1.4.2 git-commit/d12ea79 kernel/4.0.9-boot2docker os/linux arch/amd64"
	portus_1   | Started GET "/v2/token?account=vdubois&service=ec2-52-62-70-225.ap-southeast-2.compute.amazonaws.com%3A5000" for 210.8.12.141 at 2016-03-21 06:09:28 +0000
	portus_1   | Processing by Api::V2::TokensController#show as JSON
	portus_1   |   Parameters: {"account"=>"vdubois", "service"=>"ec2-52-62-70-225.ap-southeast-2.compute.amazonaws.com:5000"}
	portus_1   | Completed 401 Unauthorized in 81ms (ActiveRecord: 4.2ms)
	portus_1   | [7] 210.8.12.141 - - [21/Mar/2016:06:09:28 +0000] "GET /unauthenticated?account=vdubois&service=ec2-52-62-70-225.ap-southeast-2.compute.amazonaws.com%3A5000 HTTP/1.1" 401 - 0.0938

I could point it out from this post that the error come from the certificate:
http://stackoverflow.com/questions/2293608/what-causes-neither-pub-key-nor-priv-key-nested-asn1-error-when-building-a-p

I'm using the same certificate on the same server for Nginx, the Registry and Portus and run everything via docker-compose.

This is an example of the compose file that I use:

	web:
	  image: nginx
	  hostname: secureweb
	  links:
	    - registry
	  volumes:
	    - /etc/ssl/certs/server.crt:/etc/ssl/certs/server.crt
	    - /etc/ssl/private/server.key:/etc/ssl/private/server.key
	    - /var/log/nginx:/var/log/nginx
	    - /opt/docker-registry/portus_nginx.conf:/etc/nginx/conf.d/default.conf
	  ports:
	    - "443:443"
	    - "80:80"
	    - "5002:5002"

	portus:
	  image: bydga/portus
	  hostname: portus
	  command: puma -b tcp://0.0.0.0:3000 -w 3
	  #command: thin start --ssl --ssl-key-file /certs/registry.key --ssl-cert-file /certs/registry.crt
	  environment:
	    RAILS_ENV: production
	    PORTUS_PRODUCTION_HOST: db
	    PORTUS_PRODUCTION_USERNAME: administrator
	    PORTUS_PRODUCTION_PASSWORD: portus_pwd
	    PORTUS_PRODUCTION_DATABASE: portus
	    PORTUS_MACHINE_FQDN: ec2-52-62-70-225.ap-southeast-2.compute.amazonaws.com
	    PORTUS_SECRET_KEY_BASE: a0123a4186105fa8275676ccec745a59bf2473d9168496e10abca4dbad497f26b090a586f190e9619f6773550a33a9765b78d7deec0a8964f5b01768ec3a8732
	    PORTUS_KEY_PATH: /etc/docker/key.pem
	    PORTUS_PASSWORD: portus_pwd
	  volumes:
	    - /opt/docker-registry/portus_config_local.yml:/portus/config/config-local.yml
	    - /etc/ssl/certs/server.crt:/etc/docker/key.pem

	  ports:
	    - "3000:3000"
	  links:
	    - db

	crono:
	  image: bydga/portus
	  command: bin/crono
	  environment:
	    RAILS_ENV: production
	    PORTUS_PRODUCTION_HOST: db
	    PORTUS_PRODUCTION_USERNAME: administrator
	    PORTUS_PRODUCTION_PASSWORD: portus_pwd
	    PORTUS_PRODUCTION_DATABASE: portus
	    PORTUS_MACHINE_FQDN: ec2-52-62-70-225.ap-southeast-2.compute.amazonaws.com
	  links:
	    - db

	db:
	  image: library/mariadb:10.0.23
	  hostname: db
	  environment:
	    MYSQL_ROOT_PASSWORD: portus
	    MYSQL_DATABASE: portus
	    MYSQL_USER: administrator
	    MYSQL_PASSWORD: portus_pwd
	  volumes:
	    - /opt/docker-registry/db_datas:/var/lib/mysql
	  ports:
	    - "3306:3306"

	registry:
	  image: registry:2
	  hostname: registry
	  ports:
	    - "5000:5000"
	    - "5001:5001"
	  volumes:
	    - /etc/ssl/private/server.key:/ssl/server.key
	    - /etc/ssl/certs/server.crt:/ssl/server.pem
	    - /opt/docker-registry/data:/var/lib/registry
	    - /opt/docker-registry/registry_config.yml:/etc/docker/registry/config.yml
	  #restart: always
	  environment:
	    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
	  links:
	    - portus

Thanks for any help :)

**Comment by mssola** [comment]
For what I've been reading, this usually occurs when:

- You've entered a wrong password (but not possible as you've mentioned)
- There's something wrong with your cert/key.

Take a look at these other:

- http://stackoverflow.com/questions/14391312/openssl-neither-pub-key-nor-priv-key-nested-asn1-error
- http://stackoverflow.com/questions/15133239/client-certificate-problems-with-nethttp-neither-pub-key-nor-priv-key-neste

So, maybe you pem file is malformed somehow ? or there was a problem when generating the certificate ?

**Comment by veacks** [comment]
All good, I providing the .CRT instead of the .Key in my Ansibe bindings.
Thanks for your help.
