### ISSUE TITLE
Public namespace can only be written by admin

### ISSUE THREAD

**Issue by erwanncloarec** [SUSE/Portus#792]
I'm currently using Portus, and I'm having some trouble with the public registry.

I have configure Portus to work with LDAP, and it's working perfectly regarding each user and each team's namespace. 
But when I'm using the public registry, only admin users can push to the registry, others got `unauthorized: access to the requested resource is not authorized`. It does not seems to be a bug, is it a wanted behavior? 

In my opinion, the public registry should be opened for every authenticated user to push.

**Comment by lonewulf** [comment]
I guess it depends on how you want to use Portus. For the usage we have, the 'public' registry, as you call it, is for 'company validated' images, and we certainly don't want regular users being able to mess with them.

**Comment by erwanncloarec** [comment]
Ok, I get it, thanks!

**Comment by lonewulf** [comment]
It's only my opinion, maybe the Portus guys could add an option that allows regular users to push into it :)

**Comment by erwanncloarec** [comment]
Oh yeah but I just had a doubt that it could be a bug... Just wanted to be sure!
If it's the way it works, then so be it, I'll use it that way.

**Comment by mssola** [comment]
Hi @erwanncloarec, @lonewulf is right :+1:

Also note that if you just have a question, you can use the [mailing list](https://groups.google.com/forum/#!forum/portus-dev) that we recently created for Portus :wink:
