### ISSUE TITLE
Add webhoooks

### ISSUE THREAD

**Issue by flavio** [SUSE/Portus#794]
Webhooks allow to build or set up integrations which subscribe to certain events on Portus. When one of those events is triggered, we'll send a HTTP POST payload to the webhook's configured URL. Webhooks can be used to update an external issue tracker, trigger CI builds, deploy to your production server...

**Comment by tboerger** [comment]
So we will integrate on the namespace level the functionality to send webhooks based on the ideas of https://github.com/drone-plugins/drone-webhook/blob/master/DOCS.md excluding the custom templating for now.

Optionally we can add it also to the repo level later on.

**Comment by tboerger** [comment]
For the first draft version I would suggest the following database structure. Currently it's a mix of drone webhooks and the GitHub webhook functionality.

Initially I would trigger the webhooks and don't care about if it succeeds or not. But to keep it debuggable somehow I would store the last ~10 webhooks within the `webhook_deliveries` table. This table can be truncated automatically with an `after_save` hook. I would simply add a button to retrigger a webhook, that's pretty much the same what GitHub does.

To reduce the pain and keeping it mostly simple I would store JSON blobs for request headers, request body, response headers and response body.

```
bin/rails g model webhook url username password request_method:enum content_type:enum enabled:bool
bin/rails g model webhook_header webhook:references name value
bin/rails g model webhook_delivery webhook:references uuid status request_header:text request_body:text response_header:text response_body:text
```

**Comment by flavio** [comment]
> I would simply add a button to retrigger a webhook, that's pretty much the same what GitHub does.

Fine for me. Who is going to resend the notification, rails or a crono process?

**Comment by flavio** [comment]
Also where should we show the failure? Should it be shown inside of the namespace or should it be shown as a notification to all the owners of the namespace?

I fear that showing that only inside of the namespace page would just bury the error.

Also what happens if there's a delivery failure, but then another notification is received and this time the delivery is fine? I think in that case we could just remove the old failure.

We could also create a new Portus event about failed deliveries to show inside of the activities stream.

I fear this is going to make everything more complex... maybe we should just log the error and that's it. It would be better to add support for 3rd parties logger and leave the system administrator in charge of collecting and dealing the failures.

**Comment by tboerger** [comment]
I would add a simple entry to the activity stream and details within the webhook detail page that needs to be created.

I just took GitHub as an example implementation, there you can simple retrigger every webhook (see screenshot attached).

> Fine for me. Who is going to resend the notification, rails or a crono process?

That's something we need to decide, maybe we can do that directly without background processing as the user wants to see the result anyway?

**Comment by flavio** [comment]
>>    Fine for me. Who is going to resend the notification, rails or a crono process?

>That's something we need to decide, maybe we can do that directly without background processing as the user wants to see the result anyway?

Sounds good to me

**Comment by tboerger** [comment]
So if you are ok with that I will start to write specs and the models tomorrow together with @monstermunchkin

**Comment by mssola** [comment]
Sounds like a good plan to me. Thanks for taking care of this :+1:

**Comment by holgerreif** [comment]
> Webhooks allow to build or set up integrations which subscribe to certain events on Portus.

As long as events sent by the registry qualify as _events on Portus_ too. (this was my main use case from #643).

> So we will integrate on the namespace level the functionality to send webhooks

I think namespace level is perfect, since this is the level where currently we do all the administration in portus. As long as detailed information about repo etc. are contained the receiver can easily do filtering.

> Initially I would trigger the webhooks and don't care about if it succeeds or not.

Do you mean there is no buffering and retransmission logic in place? That's fine with me.

> Also what happens if there's a delivery failure, but then another notification is received and this time the delivery is fine? I think in that case we could just remove the old failure.

I don't think so. If a human user gets the notifcation he might look into something and eventually find out what he missed.
If however a robot missed a certain notification his action is lost forever.

> But to keep it debuggable somehow I would store the last ~10 webhooks within the webhook_deliveries table. 

Since errors are more important then successfull deliveries I'd suggest to put failed deliveries into a separate table that keeps entries longer. This could even be the starting point for error handling in future. Keeping about 10 successfull deliveries per hook "online" and the others "offline" in logs would be fine.

> > > Fine for me. Who is going to resend the notification, rails or a crono process?

> > That's something we need to decide, maybe we can do that directly without background processing as the user wants to see the result anyway?

> Sounds good to me

That's fine with me too. Even if the consumer is non-human, failure analysis would be done by a human who might resend this hook with a button click.

**Comment by holgerreif** [comment]
> So if you are ok with that I will start to write specs and the models

Just for the record: see #814

**Comment by mssola** [comment]
> As long as events sent by the registry qualify as events on Portus too. (this was my main use case from #643).

Agreed.

> Since errors are more important then successfull deliveries I'd suggest to put failed deliveries into a separate table that keeps entries longer. This could even be the starting point for error handling in future. Keeping about 10 successfull deliveries per hook "online" and the others "offline" in logs would be fine.

Fair point. @tboerger what do you think ?

**Comment by tboerger** [comment]
> Fair point. @tboerger what do you think ?

I think we can generally hold back enough notifications. Or maybe we can even make it configurable to define how many records we hold back?

**Comment by tboerger** [comment]
![screenshot from 2016-04-13 13-12-11](https://cloud.githubusercontent.com/assets/156964/14491309/4f0d9714-0178-11e6-98e8-f1363a301cfc.png)

**Comment by holgerreif** [comment]
Creation, removal, enabling and disabling of a webhook is something that belongs to an audit trail and should be stored forever (according to one's definition of _forever_). 

Sending out a webhook is of interest for current operation. Failures are of more concern then success (one motivation for my proposal to store failures separately). If it doesn't complicate implementation too much I'd suggest adding two columns `keep_successes` and `keep_failures` to table `webhooks`. Both of type integer the define the number of records to keep with special value of `0` indicating never delete a record. Define sensible defaults (e.g. 10 for both) in code and possibly allow for overwriting in portus config. To keep things on track a maximum value might be defined in portus configuration.

**Comment by holgerreif** [comment]
@tboerger in [your comment](https://github.com/SUSE/Portus/issues/794#issuecomment-208395736) you show a screenshot of a detailed [delivery content page](https://cloud.githubusercontent.com/assets/156964/14432094/e6059db8-0008-11e6-8885-3608e6ccda3e.png). 

I was not able to find this page within current master. How to access this page?

**Comment by tboerger** [comment]
It should be on the webhook detail page

**Comment by holgerreif** [comment]
I only found this page /namespaces/12/webhooks/2 showing 
![724ea52e6e2d2f9e](https://cloud.githubusercontent.com/assets/12717933/16808097/5ad5d22e-491b-11e6-9bc3-6cc09288624d.jpg) 
No further link to details

**Comment by tboerger** [comment]
@holgerreif the screenshot I have attached was from GitHub. @monstermunchkin you have not integrated any webhook delivery details into the view?

**Comment by monstermunchkin** [comment]
We currently do not have a detailed delivery page. It only shows whether or not a delivery was successful, and allows the user to retrigger it.

**Comment by holgerreif** [comment]
@monstermunchkin Is this issue the right place to discuss what changes the delivery overview page needs? As of now the delivery overiew is not of much help.

**Comment by monstermunchkin** [comment]
Actually, this issue should have been closed already. I think we should move this discussion to a new issue.

**Comment by mssola** [comment]
Yeah, I've just opened #984 for this. I'm also closing this issue as suggested by @monstermunchkin.
