### ISSUE TITLE
Portus vs Docker credential store 

### ISSUE THREAD

**Issue by scriptjs** [SUSE/Portus#796]
This is more of a question for the maintainers of project. Docker is supposed to be landing capability to use an external credential store for registry authentication in 1.11  How do you see this development in relation to this project? Will there be redundancies?

**Comment by mssola** [comment]
Hi! In principle there should be no redundancies. The thing here is that the external credential store is a safer way to implement the credentials stored in your system that docker will use. Therefore, there's no interference between this new credential store and the registry or Portus.

That being said, one of the side-effects of this is that [Application tokens](http://port.us.org/features/application_tokens.html) are no longer required to work around this security threat. However, we are planning to use application tokens for other use cases, so this new credential store support does not discard this idea either.

**Comment by mssola** [comment]
Moreover, we recently setup a [Google Group](https://groups.google.com/forum/#!forum/portus-dev) for Portus in which these kinds of questions are better suited. So keep that in mind for the next time. For now, feel free to submit comments here if you have any more doubts on this topic :wink:

**Comment by scriptjs** [comment]
Hello, appreciate this. Many thanks.
