### ISSUE TITLE
Portus LDAP doesnt work

### ISSUE THREAD

**Issue by arjunm183** [SUSE/Portus#798]
I am using portus and i have configured LDAP to authenticate users and i have normal users as well in Portus. Eventhough i have LDAP enabled in my config-local.yml file the login page still doesnt comes to LDAP LOGIN button.

Version of Portus : Portus-20151120162040-2.2.x86_64
LDAP SERVER : Active Directory

Kindly help with this issue. Reference of my config-local.yml

ldap:
enabled: true
hostname: emea.corpdir.net
port: 389
method: "plain"
base: "dc=my,dc=ad,dc=server"
uid: "cn"
guess_mail:
enabled: true
attr: ""
authentication:
enabled: true
bind_dn: "cn=userid,ou=admins,ou=resources,ou=docker,dc=my,dc=ad,dc=server"
password: "blahblah"
first_user_admin:
enabled: true

check_ssl_usage:
enabled: true

signup:
enabled: true

machine_fqdn:
value: "serverhostname.with.fqdn"

Note: When i use my ldap bind dn username and password it works perfectly fine. I am able to fetch users. No issue in my configuration.

Can someone help me with this or route me to a right channel where i can get help.

**Comment by mssola** [comment]
Hi @arjunm183, note that we do not allow to mix regular users with LDAP users. Doing so is undefined behavior :)

> Note: When i use my ldap bind dn username and password it works perfectly fine. I am able to fetch users. No issue in my configuration.

Are you saying that if you try to authenticate through LDAP in Portus (regardless of what the button says) it works ? That is weird... Are you sure that Portus is picking the right configuration ? As in, did you restart Portus when you introduced your `config-local.yml` file ?

**Comment by arjunm183** [comment]
Thanks for the Reply Portus geeks. 

So if i understood you correct, you mean either we should use LDAP users or normal users for Portus Login.

No it doesn't work when i try to login with LDAP user in Portus, even if button is not showing as LDAP login, however normal users login work.

After ldap configuration in Portus, i have restarted the service named portus_crono.
systemctl portus_crono restart

But still the ldap login page didnt came. I have posted the configuration of config-local.yml in my previous post as well. Please help me in fixing this.

**Comment by mssola** [comment]
> So if i understood you correct, you mean either we should use LDAP users or normal users for Portus Login.

That is correct. If you have LDAP enabled, then only users authenticated through the LDAP server are allowed to enter. If you previously set up Portus without LDAP and entered some users, these users are probably not usable any more. I say probably because that's what I expect, but it's undefined behavior.

> After ldap configuration in Portus, i have restarted the service named portus_crono.
systemctl portus_crono restart

This is just the crono service. You should restart Portus itself. You can do that by restarting Apache, NGinx or whatever method you are using to deploy Portus.

**Comment by arjunm183** [comment]
I have deployed in apache2 so now hurray i am able to see the LDAP Login page.

When i try to login with my ldap user id it doesnt login.

However when i try to fetch the ldapuser with the given attr in the portus with ldapsearch command 
it shows the details of the user. 
Can you suggest.

**Comment by mssola** [comment]
Maybe you can check what are the logs saying ? Maybe there's some value wrong on your `config-local.yml` file ? Maybe it's because of Active Directory (we are not doing anything specific for AD) ?

**Comment by ac0v** [comment]
I recommend you to use sAMAccountName as uid and mail for the attr in guess_mail.

Here is a working example for authenticating against active directory:

```yaml
ldap:
  enabled: true

  hostname: "mydomain.com"
  port: 389

  method: "plain"

  base: "dc=mydomain,dc=com"

  uid: "sAMAccountName"

  authentication:
    enabled: true
    bind_dn: "cn=service-domain-user-for-portus,cn=Users,dc=mydomain,dc=com"
    password: "the-correct-password"

  guess_email:
    enabled: true
    attr: "mail"
```

**Comment by arjunm183** [comment]
Here is my config-local.yml file
ldap:
  enabled: true

  hostname: AD Server name
  port: 389

  method: "plain"
  base: "dc=fully,dc=qualified,dc=domain"

  uid: sAMAccountName

  authentication:
      enabled: true
      bind_dn: "cn=username,ou=portus,ou=ouname,ou=ext,dc=fully,dc=qualified,dc=domain"
      password: "blahblah"

  guess_mail:
      enabled: true
      attr: "mail"

first_user_admin:
  enabled: true

# By default require ssl to be enabled when running on production
check_ssl_usage:
  enabled: true

When i enter the username it says INvalid username or password.

But as i said in my previous quotes ldapsearch command i am able to query the username with sAMAccountName

Additional Information: I have config.yml file as well in the config folder for portus. Does it matters if i have two yml config files " config.yml and config-local.yml "

**Comment by mssola** [comment]
>  I have config.yml file as well in the config folder for portus. Does it matters if i have two yml config files " config.yml and config-local.yml

This doesn't matter. The contents of `config-local.yml` override `config.yml`. See [the documentation page for this](http://port.us.org/docs/Configuring-Portus.html).

> My ldap user name contains special character

That doesn't matter either. Portus just acts as a proxy when it comes to LDAP authentication.

> But as i said in my previous quotes ldapsearch command i am able to query the username with sAMAccountName

When you do that, do you also use the authentication bind_dn that you provide to Portus ? Just checking whether what you have wrong is the bind_dn or the password for that (note that in some servers you can event have that disabled).

**Comment by arjunm183** [comment]
Yes, ofcourse when i use ldapsearch command i use the same bind_dn and password which i have provided to Portus as well.

**Comment by arjunm183** [comment]
I wanted to know whether i have did something wrong

Initially my portus was running in normal user id and then i tried configuring LDAP ... Is there something which i have to do in such kind of cases.

**Comment by mssola** [comment]
@arjunm183 you really want to start fresh with your LDAP configuration (that is, without entering a user that doesn't go through LDAP). If you don't want to start all over again, maybe you can try running on `debug` mode as explained in the last point of [this section](https://github.com/SUSE/Portus/blob/master/CONTRIBUTING.md#reporting-issues).

Otherwise, maybe you can try to run another Portus instance with a fresh DB and configured with LDAP from the beginning (but I'd recommend running on debug mode before doing anything crazy :P)

**Comment by arjunm183** [comment]
I tried in debug mode. However couldn't get much information in the log file (other than DB query commands) mentioned with debug tag 

Planning to run another portus instance with fresh DB configuration.

I doubt if we initially setting up portus either we have to configure with normal users or LDAP users.

Changing from Normal to LDAP doesnt work. Let me give a try and update you ..

**Comment by arjunm183** [comment]
@mssola Hi i tried setting up seperate portus instance and from the beggining i am using ldap only 
here is the configuration of ldap

ldap:
  enabled: false
ldap:
    enabled: true
    hostname: "ema.corp.net"
    port: 389
    method: "starttls"
    base: "dc=ema,dc=corp,dc=net"
    uid: "sAMAccountName"
    authentication:
       enabled: true
       bind_dn: "cn=E117_s_ldap-lookup,ou=UsersAdministrative,ou=_GlobalResources,ou=e1,dc=ema,dc=corp,dc=net"
       password: "blahblah"
    guess_mail:
       enabled: true
       attr: "mail"

It shows ldap login and when i entered by userid it says invalid user name and password
my user name is similar to this
username : ecd_a_arjun


I am able to fetch my user id using ldapsearch command in linux

Kindly help on this.

**Comment by arjunm183** [comment]
More information on this issue . **Production logs for portus** as follows

I, [2016-05-16T07:54:46.775397 #17832]  INFO -- : Completed 401 Unauthorized in 251ms (ActiveRecord: 0.0ms)
I, [2016-05-16T07:54:46.776802 #17832]  INFO -- : Processing by Auth::SessionsController#new as HTML
I, [2016-05-16T07:54:46.776974 #17832]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ksjC1m+tXu/+7nEkpHtPnyS67Z1h5u9RWdAcumpwQWWXnKbV5g19p0J/45NhMa8rn5362kyZbcJYJ65MQ9CY6A==", "user"=>{"username"=>"ECD_a_ARJUN", "password"=>"[FILTERED]"}, "button"=>""}
I, [2016-05-16T07:54:46.915777 #17832]  INFO -- :   Rendered shared/_notification.html.slim (0.1ms)
I, [2016-05-16T07:54:46.916229 #17832]  INFO -- :   Rendered shared/_notification.html.slim (0.1ms)
I, [2016-05-16T07:54:46.916539 #17832]  INFO -- :   Rendered shared/_notifications.html.slim (1.1ms)
I, [2016-05-16T07:54:46.920306 #17832]  INFO -- :   Rendered devise/sessions/new.html.slim within layouts/authentication (5.1ms)
I, [2016-05-16T07:54:46.921610 #17832]  INFO -- : Completed 200 OK in 144ms (Views: 7.0ms | ActiveRecord: 0.7ms)

**Comment by gvenka008c** [comment]
@arjunm183 Did you find a fix for the ldap issue? Can you post your finding if possible.

**Comment by gvenka008c** [comment]
@mssola @here I turned on debug mode to troubleshoot LDAP issue. Here is the error message 

```
Processing by Auth::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Z7YLm1wQqB9M4B06rbxB29ccbYqMbfH6XvZJCgs3bvwonURohCwD2z+MT/TqNppmfZ6n43QisXcuqFHTkOQHvw==", "user"=>{"username"=>"gvenka008c", "password"=>"[FILTERED]"}, "button"=>""}
Completed 401 Unauthorized in 22ms (ActiveRecord: 0.0ms)
Processing by Auth::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"Z7YLm1wQqB9M4B06rbxB29ccbYqMbfH6XvZJCgs3bvwonURohCwD2z+MT/TqNppmfZ6n43QisXcuqFHTkOQHvw==", "user"=>{"username"=>"gvenka008c", "password"=>"[FILTERED]"}, "button"=>""}
   (0.5ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')
  Rendered shared/_notification.html.slim (0.4ms)
  Rendered shared/_notification.html.slim (0.2ms)
  Rendered shared/_notifications.html.slim (2.0ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')  [["username", "portus"]]
  Rendered devise/sessions/new.html.slim within layouts/authentication (7.2ms)
Completed 200 OK in 126ms (Views: 35.7ms | ActiveRecord: 0.5ms)

```

Any way to find out if the bind was successful? Please suggest. Thanks.

**Comment by mssola** [comment]
We don't really log error messages on unsuccessful binds. So, my guess is that either your credentials are not correct, or the LDAP server is not reachable somehow, etc. Either way, maybe you could investigate this in the logs of your LDAP server if you have access to it ?

**Comment by mssola** [comment]
A lot has happened meanwhile and I believe this issue is no longer relevant in master. If it is, please re-open this issue, or we can proceed this discussion in our mailing list. Thanks for the feedback 👍
