### ISSUE TITLE
Crono authorisation failed

### ISSUE THREAD

**Issue by cedvan** [SUSE/Portus#800]
Hi,

I have a cluster of 3 VMs with 4 containers hosted : mariadb, portus, registry, crono.

Portus interface works with login and logout. I can create namespaces, teams, etc...
Registry work with authentification, I can pull/push image.
Sync between Portus and registry don't work, Portus always displays 0 images.

When crono get list images, registry refused with 401 : 
```
30/3/2016 14:19:56[33mWARN[0m[1063] error authorizing context: authorization token required  [33mhttp.request.host[0m=docker.cedvan.com [33mhttp.request.id[0m=f15bfde4-794f-4e0b-ab8a-599890bf3c9c [33mhttp.request.method[0m=GET [33mhttp.request.remoteaddr[0m=192.168.10.22 [33mhttp.request.uri[0m=/v2/_catalog?n=100 [33mhttp.request.useragent[0m=Ruby [33minstance.id[0m=41bebb97-06b8-4418-9eec-99440839d59d [33mversion[0m=v2.1.1
30/3/2016 14:19:5610.42.27.236 - - [30/Mar/2016:12:19:56 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 161 "" "Ruby"
30/3/2016 14:19:57[34mINFO[0m[1064] response completed                            [34mhttp.request.host[0m=docker.cedvan.com [34mhttp.request.id[0m=25f682bb-4fb6-4ec3-9776-08b21b591245 [34mhttp.request.method[0m=GET [34mhttp.request.remoteaddr[0m=192.168.10.22 [34mhttp.request.uri[0m=/v2/_catalog?n=100 [34mhttp.request.useragent[0m=Ruby [34mhttp.response.contenttype[0m=application/json; charset=utf-8 [34mhttp.response.duration[0m=86.611552ms [34mhttp.response.status[0m=200 [34mhttp.response.written[0m=39 [34minstance.id[0m=41bebb97-06b8-4418-9eec-99440839d59d [34mversion[0m=v2.1.1
30/3/2016 14:19:5710.42.27.236 - - [30/Mar/2016:12:19:57 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 200 39 "" "Ruby"
30/3/2016 14:19:57[33mWARN[0m[1064] error authorizing context: insufficient scope  [33mhttp.request.host[0m=docker.cedvan.com [33mhttp.request.id[0m=03d95a1b-b392-4ad9-9818-e15b98021e12 [33mhttp.request.method[0m=GET [33mhttp.request.remoteaddr[0m=192.168.10.22 [33mhttp.request.uri[0m=/v2/infra/toran-proxy/tags/list?n=100 [33mhttp.request.useragent[0m=Ruby [33minstance.id[0m=41bebb97-06b8-4418-9eec-99440839d59d [33mvars.name[0m=infra/toran-proxy [33mversion[0m=v2.1.1
30/3/2016 14:19:5710.42.27.236 - - [30/Mar/2016:12:19:57 +0000] "GET /v2/infra/toran-proxy/tags/list?n=100 HTTP/1.1" 401 176 "" "Ruby"
30/3/2016 14:19:57[33mWARN[0m[1064] error authorizing context: insufficient scope  [33mhttp.request.host[0m=docker.cedvan.com [33mhttp.request.id[0m=347a6935-4f68-4347-93d9-afce32911c2f [33mhttp.request.method[0m=GET [33mhttp.request.remoteaddr[0m=192.168.10.22 [33mhttp.request.uri[0m=/v2/infra/toran-proxy/tags/list?n=100 [33mhttp.request.useragent[0m=Ruby [33minstance.id[0m=41bebb97-06b8-4418-9eec-99440839d59d [33mvars.name[0m=infra/toran-proxy [33mversion[0m=v2.1.1
30/3/2016 14:19:5710.42.27.236 - - [30/Mar/2016:12:19:57 +0000] "GET /v2/infra/toran-proxy/tags/list?n=100 HTTP/1.1" 401 176 "" "Ruby"
```

An idea from where come the problem ?

NB : VMs date sync with `sntp -4sSc pool.ntp.org`

Thank you

**Comment by mssola** [comment]
Could you tell me the versions of Portus, docker, and the registry ?

**Comment by cedvan** [comment]
Portus and Crono : use https://hub.docker.com/r/bydga/portus, so latest
Registry : 2.1.1
Mariadb : 10.0.23

**Comment by cedvan** [comment]
I would like stay on official hub docker image. But this repository https://github.com/h0tbird/docker-portus is much more clear and better explained. It is possible to do the same thing on the official ? And add versions to docker hub ?

**Comment by mssola** [comment]
Please note that https://hub.docker.com/r/bydga/portus is not the official image of Portus. The official containerized solution that we provide for now is only for development purposes. See the [wiki](https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment). We are working on improving that, but if you are just testing Portus, it should be fine.

That being said, https://github.com/h0tbird/docker-portus is also a good option.

> And add versions to docker hub ?

This has been discussed before and it's part of our "Let's improve our containers setup experience". We are currently working on this, and you can see multiple open issues about this.

**Comment by cedvan** [comment]
Ok great ! I'll try https://github.com/h0tbird/docker-portus ;)

**Comment by mssola** [comment]
Feel free to re-open this issue if you have more questions. I'd prefer if you'd use our [Google groups](https://groups.google.com/forum/#!forum/portus-dev) though :)
