### ISSUE TITLE
Mixed LDAP and local users in Portus and their auth tokens

### ISSUE THREAD

**Issue by holgerreif** [SUSE/Portus#801]
This proposal arises from thinking on #734 and #517.
## What is a technical account?

Looking at different real-world applications I see that often they support both personal user accounts and technical (non-personal) accounts. 

What is the difference between them? 
- personal accounts belong to an individual who often has accounts on multiple apps
- technical accounts are unique to a specific app
  Usually this is not of a big difference as long as you store accounts locally. With LDAP (or any other centralized auth system) support a personal user has just one account with access rights on multiple apps.

OTOH technical accounts are often managed locally in the specific app they are vaild for.
With LDAP support not allowing local users one forces technical accounts, valid for a single app only, to be created in a central directory.

This is not very convenient.
## The need for technical accounts

Why do I need technical accounts? They are required for specfic tasks like 
- pushing images from automatic builds
- pulling images for automatic deployments
- deleting images for housekeeping purposes
  In fact: the portus user is a technical account as well!
## Technical accounts and authentication tokens

Technical accounts are very closely related to the use of application tokens. Thus it might be possible to forgo technical accounts, depending on the implementation. 
However it would be easier to assign an account a set of rights on a longer term (authorization) and issue short lived tokens for athentication.

In order to understand the whole issue better, let's look on how one would use auth token connected to my personal account which is not just a replacment for my password but used to delegate some rights
- I go to profile page and request a token
- I enter a name 
- I decide whether this has access restrictions
  - none (means everything I have access to is usable with the token)
  - on namespace level
  - on repository level (I know, currently access is at namespace level only)
- If I restrict I get a list of all namespaces or namespace/repo combos I have access to 
- For every listed item I choose access type
  - none (default selection)
  - read access (-> viewer role)
    - could not only be a pull but a reception of a notification too
  - write access (-> collaborator role)
    - it covers both push and delete operations
    - even if currently delete is not accessable from the docker client it could be used for a possible portus API call
  - manage access (-> owner role) 
    - it is unclear whether this role is sensible since it a token is not valid for web UI access 
    - however for access to a portus API it could be meaningfull
      As a real world example consider a role owner who wants to issue a token which has only pull access right to some namespace he manages!

The listing of auth token would have to show the very same information as it was asked during token creation.
## Implementation proposal for technical accounts and their auth tokens

I hope from this description the following should become clear:
- Configuration for auth tokens would then be exactly the same as configuration of access rights for personal users.
- There is a complex realtionship between an account and the access rights of a token issued to this account.
- The number of tokens (currently 5) might not be a good limit at all.

IMHO it is more straightforward to treat technical accounts similiar personal accounts and maintain a 1:1 realtionship between an account and it's auth tokens. Important differences between a personal and  technical acocunt are 
- a technical account is managed not by portus admin but by team owner
- a technical account is only member of one team (otherwise it's unclear which team owner would manage that account) 
- a technical account does not need to have a password to log in (of course it could)
- the owner of a team could issue an auth token for a technical account that belongs to his team (whereas he could not isse a token for a personal account).

The only drawback of this proposal is that we mix LDAP and local accounts.
However it seems possible to add an account and mark it as "local". This marker means
- don't ask LDAP for the password
- don't touch team membership when synchronizing with LDAP group memberships

While I don't see an implementation of this proposal very soon I'd like to start the discussion early. 
This will hopefully help implementing upcomming new features in a way that makes the above proposal more smoothly feasible.

Should we follow-up @ [Google Groups](https://groups.google.com/forum/#!forum/portus-dev)?

**Comment by mssola** [comment]
Generally speaking I like this idea. So, to sum it up:

- Team owners would create technical accounts, which are useful for a variety of applications (e.g. continuous integration, housekeeping, etc).
- Technical accounts would be plain user accounts under the hood, nothing special about them (we would just add a boolean inside of the `users` table).
- Technical accounts authenticate themselves via authentication tokens that the team owners manage and are responsible for.
- We should raise the number of application token available. I wonder how we can optimize this, since we restricted the number for performance reasons (maybe we can first assume that only technical accounts use this, and then fallback to regular users if we fail ? This would make sense since docker 1.11 introduces credential stores and the usage of application tokens for regular users shouldn't be the usual anymore)

That being said, I'd propose changing the name of `technical users` to `bots` or `applications`. What do you think ? :P

> don't ask LDAP for the password

We already do this for the special `portus` user. We can do this also for technical accounts.

> don't touch team membership when synchronizing with LDAP group memberships

:+1: 

> While I don't see an implementation of this proposal very soon I'd like to start the discussion early.
This will hopefully help implementing upcomming new features in a way that makes the above proposal more smoothly feasible.

Agreed, this won't make it for 2.1. That being said, I can see this implemented for the release next to 2.1 :) (2.1 to be released on August-September)

@flavio what do you think ?

**Comment by holgerreif** [comment]
I really like your term `bot account`, which is in perfect harmony with `user account` ;-) !

There is one problem to solve that I didn't mention before:

> a technical account is only member of one team (otherwise it's unclear which team owner would manage that account) 

We must ensure the uniqueness of `bot account` names for the follwing reasons:
   * Use during authentication (which is possibly not the case, but I want to mention)
   * Storage in user table of database

One way to achieve the uniqeness is to prepend `<teamname>`+ `.` (or underscore) to the `bot account` name. In the web UI the name this prefix is not shown, since it is implicit clear which team the account belongs to.

A further note : A `bot account` doesn't own a personal namespace. While it is not strictly required to supress such a personal namespace, however it is not necessary to add any code to support this.

**Comment by mssola** [comment]
I agree. For this though, there's already issue #699 that deals about the idea of a display name vs stored name in a clean way. Maybe we can take advantage of issue #699 before moving to fix this one :)

> A further note : A bot account doesn't own a personal namespace. While it is not strictly required to supress such a personal namespace, however it is not necessary to add any code to support this.

Agreed.

**Comment by holgerreif** [comment]
Well I'd expect to adress #699 earlier then this one, just because it's easier to do ;-).
And even if not, then the UI would show the prefixed name until #699 is done. The less special handling the better.

**Comment by flavio** [comment]
I like the proposal. I would call these account either "bot" or "robot" :)

I was wondering: why don't we allow the creation of a robot account only at the namespace level? This makes more clear to which resource a robot can access and also what his privileges would be regarding to this resource.

I would keep the `login` of the robot unique. Each request received by Portus has always a scope (am I right @mssola) which can be either the `namespace` or the `namespace/repository`. The authentication code would just have to look if the namespace has a bot enabled, if the token matches and if the operation can be fulfilled by the privileges the bot has on the namespace.

**Comment by mssola** [comment]
I'd create a bot as a team option. This is to make things easier for cases like: team A has a jenkins jobs for all their projects, allow the bot to push onto all the team's namespaces. Optionally, I'd say that you should be able to then disable namespaces for the bot maybe, just in case owners want a finer grain of permissions for the bot.

**Comment by holgerreif** [comment]
My idea was to make `bot` users as similiar as normal users. Thus we can hopefully reuse much aof the right's management logic.

Besides that, I like the use case based explaination by @mssola.

**Comment by awiddersheim** [comment]
I have use cases for this so 👍 from me.

**Comment by Vad1mo** [comment]
I'd like to see this feature happen. I someone currently working on it? If not I could allocate some time to it and learn a bit ruby/rails by the way.

**Comment by mssola** [comment]
I'm not. Feel free to proceed 👍

**Comment by jordanjennings** [comment]
This would be a really helpful feature for us as well. If I've understood the discussion so far, it sounds like people are mostly thinking in terms of bots at the team level, however I'd really like to be able to treat a "bot" user like any other user and put them in multiple teams. We have several internal teams that share a jenkins and it would be simplest just to have a single user to manage. That said, it would be manageable to have different bots per team if that makes things simpler for design or implementation.

**Comment by ArcticSnowman** [comment]
@mssola @flavio  - Any update on when this feature might get into a release?

**Comment by mssola** [comment]
@ArcticSnowman it won't be released in 2.3 for sure (we are already in code freeze..). We still have to prioritize 2.4. I'll add it on the milestone and re-evaluate it once we plan for 2.4 😉

**Comment by ArcticSnowman** [comment]
@mssola Many thanks for you and the teams hard work on this...

**Comment by jordanjennings** [comment]
For what it's worth - we came up with a hack that works well enough for now: we directly create entries in the users table of the Portus DB and generate a salt and token for that user in the application_tokens table using ruby's BCrypt (same as what the Portus code does). Then these non-LDAP users work for docker pushes from Jenkins (but they don't allow login to the UI, which is exactly what we want anyway). Not sure if the new REST API will allow the same thing, going to look into it when I have the time.

**Comment by mssola** [comment]
The pull request #1856 partially implements this. I've also created #1860 and #1862 as follow-ups of that PR and this issue. I'm going to close now this one in favor of these two which are more detailed and with a more constrained scope. Thanks for all the feedback :+1:
