### ISSUE TITLE
Running in docker

### ISSUE THREAD

**Issue by zachaller** [SUSE/Portus#81]
Just wondering if running this in docker will ever be a thing or something people would be interested in.

**Comment by flavio** [comment]
I think it would be nice to have a docker image for portus. Right now it's not on our roadmap.

**Comment by arabold** [comment]
I've started to play with a `Dockerfile` for Portus. It starts up now but still needs some work:
https://github.com/arabold/Portus/tree/feature/add-dockerfile

At this time I'm only playing with it to see what I can do with Portus. But feel free to take a look and do some improvements to the Dockerfile.

**Comment by kikicarbonell** [comment]
:+1:

**Comment by flavio** [comment]
Done
