### ISSUE TITLE
Build and Ship Portus on Docker Hub

### ISSUE THREAD

**Issue by diranged** [SUSE/Portus#820]
Is there a reason why this repo isn't being built regularly and shipped on Docker Hub? Right now I have a forked version of the repo _purely_ so that we can have hub.docker.com build the image for us.

**Comment by mssola** [comment]
This has been suggested before, and I agree that we should do this. That being said, I'm currently working on improving integration testing, which might affect this, that's why I'm waiting to finish on that before moving to tackle all the issues we have on the [containers setup](https://github.com/SUSE/Portus/labels/docker-compose)

**Comment by diranged** [comment]
Though I agree theres room for improvement, there is nothing about the repo right now that doesn't "work" as is. See our [blog](https://engblog.nextdoor.com/using-puppet-to-set-up-docker-distribution-and-portus-17e41143af17#.osxgy4x4i) post here for exactly how we're currently launching Portus, Crono and Distribution as Docker containers using all of the major features of each platform (SSL, LDAP, etc, etc, etc).

Assuming you guys have a `suse` organization in hub.docker.com, its a matter of minutes to enable the building of master and tags.. and it would save the rest of us quite a bit of time.

**Comment by ntrifunovic** [comment]
:+1:

**Comment by JustinPullen** [comment]
It would be nice to see this soon with official documentation.  Appears the community is flooding to https://hub.docker.com/r/bydga/portus/ and pulling from there.  Unfortunately there are not many run details so I am not sure how far users are getting I know I did not get very far. 👍  for the suggestion.

**Comment by srikarm** [comment]
This should help folks who need to run Portus out of the box.
https://hub.docker.com/r/srikarm/portus-allinone/

**Comment by EugenMayer** [comment]
same here, pretty configureable and used in a rancher-catalog: https://github.com/EugenMayer/portus-build or https://hub.docker.com/r/eugenmayer/portus/

**Comment by mssola** [comment]
Superseded by #1027. Feel free to re-open this issue if you think that there is still things to discuss here and that they are not suitable to be discussed in #1027.
