### ISSUE TITLE
unauthorized: access to the requested resource is not authorized

### ISSUE THREAD

**Issue by ghoul008** [SUSE/Portus#833]
I deploy docker client and server in same vm
I can login use "docker login IP：5000",but canot push images.

I already created namespace on wedUI

**Comment by mssola** [comment]
Could you be more specific ?

- What's the version of docker, docker distribution and Portus ?
- Which namespace are you pushing to ?
- Are you sure that the user you are using is allowed to push there ? Try an admin user.
- Could you provide logs ?

**Comment by ghoul008** [comment]
1.
-Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:39:25 2016
 OS/Arch:      linux/amd64

-portus version used github code 2.0
-how to see docker distribution version?

2:I used "Special namespaces" likeed "admin" also used alread new created namespace liked "microbox" .
cmd like this 
   #docker tag busybox  x.x.x.x:5000/microbox/adminbusybox
   #docker push x.x.x.x:5000/microbox/adminbusybox
   The push refers to a repository [X.X.X.X:5000/adminbusybox]
5f70bf18a086: Preparing 
1834950e52ce: Preparing 
unauthorized: access to the requested resource is not authorized

3.yes,i used admin,which created when i first login on webui
4.oh where can see CONTAINER log,first used portus.

**Comment by ghoul008** [comment]
i see step.sh success tip:
To push an image to the private registry:

  $ docker pull busybox
  $ docker tag busybox 172.17.0.1:5000/<username>busybox
  $ docker push 172.17.0.1:5000/<username>busybox

is that not config namespace name?or it just push on Special namespaces 172.17.0.1:5000,am i comprehend wrong?
BTW "- Do *not* check the "Use SSL" checkbox, since this setup is not using SSL."i am not check it.

**Comment by ghoul008** [comment]
i am not install "Docker Distribution" ,is this necessary?i can step successed whithout it.

**Comment by ghoul008** [comment]
i reinstall portus(used 2.0.2 source code) after install Docker Distribution (version  docker-distribution.x86_64 0:2.3.1-1.el7)
but same error exist.
 #docker login 10.1.241.132:5000
 #docker tag busybox 10.1.241.132:5000/adminbusybox
 #docker push 10.1.241.132:5000/adminbusybox

 10.1.241.132:5000 is same whith webui's Special namespaces

**Comment by mssola** [comment]
> 4.oh where can see CONTAINER log,first used portus.

If you are running Portus in a container, then use `docker logs` to fetch the logs as given by Portus. If you are not using docker, then it depends on how you are running it. For example, if you are doing it behind Apache, then check the logs where apache is writing them.

 It would be even better to setup Portus in debug mode for this (see last point of [this document](https://github.com/SUSE/Portus/blob/master/CONTRIBUTING.md#reporting-issues)).

**Comment by ghoul008** [comment]
@mssola
