### ISSUE TITLE
crono failes with self signed certificates

### ISSUE THREAD

**Issue by santosh0705** [SUSE/Portus#835]
In my setup everything working fine except crono run fails.

```
portus-crono       | I, [2016-04-22T15:42:00.474747 #59]  INFO -- : Perform CatalogJob
portus-crono       |   Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1000
portus-crono       | Exception: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed
portus-crono       | I, [2016-04-22T15:42:00.504563 #59]  INFO -- : Finished CatalogJob in 0.03 seconds
portus-crono       |   Crono::CronoJob Load (0.3ms)  SELECT  `crono_jobs`.* FROM `crono_jobs` WHERE `crono_jobs`.`id` = 1 LIMIT 1
portus-crono       | I, [2016-04-22T15:52:00.475009 #59]  INFO -- : Perform CatalogJob
........
```

details of my setup:
both registry server and portus web run behind nginx proxy ssl terminated with self signed certificates. Docker client and login and push & pull images. The registry webhook working perfectly on http. But the crono job fails with above exception.

How to use self signed certificates with crono?
There is also one more issue while setting up the registry on portus first run. Since the registry is on  FQDN `dockerhub.xyz.com` and on secure https it is not taking while adding for first time (may be its failing due to self signed certificate issue). To registry I've to give insecure docker linking name to get it working and than editing it to change it to FQDN.

**Comment by santosh0705** [comment]
It was an self signed certificate issue. Once the certificate added to the `/usr/local/share/ca-certificates` and updated the ca certificates the error gone.

**Comment by mssola** [comment]
Closing this then :) Bear in mind that next time you could probably ask this on our [Google group](https://groups.google.com/forum/#!forum/portus-dev) :wink:
