### ISSUE TITLE
Private namespace of user shows up in team with the same name

### ISSUE THREAD

**Issue by rennhak** [SUSE/Portus#836]
### Abstract

Private user namespace shows up in team of same name. All team members of that team are thus able to see (possibly, read/write) private namespace of that given user.

### Description

In Portus you have users, namespaces (public, private) and teams. This is useful and each has their intended purpose, but it seems there is a (bug?) behavior that exposes private namespaces to teams with the same name.

Given eg. you have a team 'carbon' (project name) and a couple of custom namespaces under that team as well as a range of developers being part of it. Now, if you have a user of the same name (eg. CI account for that project) as the team, then his/her private namespace shows up in the team as well.

It is not clear if this is intended behavior or a bug, in our case we consider it a bug.

Problem I can see is that the PRIVATE namespace of the user is exposed to the group with the same name as the user, which is some sort of information leakage and fail of ACL.

### Steps to reproduce

- create eg. team 'carbon' (project name)
- (optional) create some namespaces in that team eg. 'carbon-stable' (used to contain eg. stable images)
- (optional) assign various other users to that team
- create eg. user 'carbon' which owns (created automatically) private namespace 'carbon' (CI user)
- assign user 'carbon' to team 'carbon'
- then its private namespace shows up in team carbon

### Tags

- bug, security, minor

**Comment by sergioasantiago** [comment]
+1

**Comment by mssola** [comment]
This is indeed a bug

**Comment by rennhak** [comment]
Thank you
