### ISSUE TITLE
Cannot create new team from UI

### ISSUE THREAD

**Issue by rastapopulous** [SUSE/Portus#855]
When I try to create a new team the dialog box opens and closes again immediately before I can type anything. Not seeing any error in the console. Tried this on both Chrome and Safari, both on OSX.

**Comment by rastapopulous** [comment]
Restarting puma a few times seemed to make the issue go away - no clue what the bug could be. It happened in the past and again restarting puma fixed the issue. Perhaps something with a timer?

**Comment by mssola** [comment]
Which version of Portus are you using ? I haven't been able to reproduce this in current master.

**Comment by rastapopulous** [comment]
2.0.3 - If I can recreate again I'll let you know.

**Comment by rastapopulous** [comment]
Switching to the master branch I was unable to recreate this bug. I will close this as fixed.
