### ISSUE TITLE
Portus can not fetch the tag for target on push event

### ISSUE THREAD

**Issue by injectives** [SUSE/Portus#879]
Hello everybody,

After updating my docker-compose setup to Portus 2.0.4 and Docker Registry 2.4.0 the notifications have stopped working. Unfortunately, I can't understand why. Could somebody give me an advice please?

Basically, I have Portus and Docker Registy behind NGinx proxy. I am using NGinx to provide SSL. Portus and Docker Registry speak to each other without SSL. This definitely worked on the previous version of Portus and Docker Registry, but unfortunately I made a silly mistake and didn't backup the working copy.

I might be wrong with my decision, but I think that it doesn't make sense to use SSL between Portus and Docker Registry as I am not exposing their ports publicly. Please correct me if I am wrong.

**docker-compose.yml:**
version: '2'

services:
  registry:
    image: registry:2.4.0
    volumes:
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./cert/domain.crt:/cert/portus.crt:ro
      - registry.data:/var/lib/registry
    expose:
      - "80"
  db:
    image: mariadb:10.1.14
    environment:
      MYSQL_ROOT_PASSWORD: portus
    volumes:
      - db.data:/var/lib/mysql
  portus:
    build:
      context: https://github.com/SUSE/Portus.git#2.0.4
    image: portus:2.0.4
    command: puma -b tcp://0.0.0.0:3000 -w 3
    links:
      - registry:injectives.com
    depends_on:
      - db
      - registry
    environment:
      - PORTUS_MACHINE_FQDN=portus
      - PORTUS_KEY_PATH=/cert/portus.key
    volumes:
      - ./portus/config.yml:/portus/config/config.yml:ro
      - ./cert/domain.key:/cert/portus.key:ro
  nginx:
    image: nginx:1.9.15
    depends_on:
      - portus
      - ldap
    ports:
      - 443:443
      - 3000:3000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/ssl/nginx:ro
volumes:
  registry.data:
  db.data:

**Docker registry config.yml:**
auth:
  token:
    realm: https://injectives.com:3000/v2/token
    service: injectives.com
    issuer: portus
    rootcertbundle: /cert/portus.crt
notifications:
  endpoints:
    - name: portus
      disabled: false
      url: http://portus:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s

**Portus log contains the following:**
Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>529, "digest"=>"sha256:dab35d96c737835527e5f0174ab3f8831e83e52a8fc1676c6f4a39eec689ec45", "length"=>529, "repository"=>"centos", "url"=>"https://injectives.com/v2/centos/manifests/sha256:dab35d96c737835527e5f0174ab3f8831e83e52a8fc1676c6f4a39eec689ec45", "tag"=>"5"}
Reason: Connection refused - connect(2) for "injectives.com" port 3000

**Docker registry log contains the following:**
registry_1  | time="2016-05-16T18:24:25.263024978Z" level=error msg="retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying"
registry_1  | time="2016-05-16T18:24:25.763630254Z" level=error msg="retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying"
registry_1  | time="2016-05-16T18:24:26.148668459Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.1 http.request.host=injectives.com http.request.id=6c7967fb-106c-4cfa-90bb-3766fd01ef14 http.request.method=GET http.request.remoteaddr="172.18.0.6:49824" http.request.uri="/v2/centos/tags/list?n=100" http.request.useragent=Ruby instance.id=bc88ebd4-56f2-4057-9741-b4ce0952ac97 service=injectives.com vars.name=centos version=v2.4.0
registry_1  | 172.18.0.6 - - [16/May/2016:18:24:26 +0000] "GET /v2/centos/tags/list?n=100 HTTP/1.1" 401 138 "" "Ruby"

The complete logs can be downloaded here: [Logs.zip](https://github.com/SUSE/Portus/files/266733/Logs.zip)

As far as I can see Portus is receiving the events and in the end tries to get a manifest, but registry is rejecting the request. By the way, did the previous version of Portus try to get the manifest?

Thank you very much for your help.

**Comment by injectives** [comment]
Hm. I suspect that the problem is:
- Portus is trying to get the manifest;
- Registry sends him response to authorise;
- Portus is trying to authorise against injectives.com:3000, when injectives.com is pointing to the Docker Registry container;
- Portus fails to authorise and therefore everything fails.

**Comment by injectives** [comment]
I've checked it without SSL and it works.
I've also tried to make Portus communicate with Registry though NGinx with SSL enabled. I can see that event comes to Portus. When event is received Portus tries to get manifest, but gets 401. Then he tries to authorise and hangs. I believe it is related to: #373. While processing the event he needs to make a request to authorise himself, but the socket is busy. However, I am not sure here... Could somebody advise on this please?
As far as I understand, a workaround is to use Thin on two sockets. However, as I can see Thin has been removed for a reason: [https://github.com/SUSE/Portus/commit/858e819180141c63fb00c7c05dac75c933d1b198#diff-8b7db4d5cc4b8f6dc8feb7030baa2478](docker-compose: switch to Puma).
Is there any change to get it working with SSL enabled on Puma?

**Comment by mssola** [comment]
Hi @injectives. Sorry for taking some time to respond :sweat_smile:. 

If this is really the same issue as #373, then it's enough to just increase the number of workers that you're using on Thin or Puma. Note that this is explained in the documentation in [this page](http://port.us.org/docs/How-to-setup-secure-registry.html), and also in the [NGinx example setup](http://port.us.org/docs/setups/3_nginx_bare_metal.html).

**Comment by injectives** [comment]
Hi @mssola! Thank you for looking at this issue.
Unfortunately adding more workers didn't help.
I have created a repo with the source code. It is not pretty, but does opportunity to test the setup quickly. Src: https://github.com/injectives/portus-compose
Could you have a look please?

**Comment by mssola** [comment]
I have not been able to try out your setup, sorry about that. I've given a quick look to it though, what happens if you raise the number of nginx `worker_processes` ?

**Comment by injectives** [comment]
@mssola Hello :) Unfortunately it didn't help either.

**Comment by chadyred** [comment]
Same problem here, see this:

["Example apache2"](https://github.com/SUSE/Portus/pull/1151/files)

In your case your nginx host doesn't proxy pass because the 443 port is forward to your container so add this instruction:

```
proxy_set_header X-Forwarded-Proto "https";
```

Or if you have a proxy before your nginx, and it porxy pass your request, you have to remove this line.

**Comment by mssola** [comment]
This should've been fixed by now. Check the examples or the documentation on [how to deploy](http://port.us.org/docs/deploy.html) portus for more info. Thanks!
