### ISSUE TITLE
token signed by untrusted key with ID

### ISSUE THREAD

**Issue by EvertMDC** [SUSE/Portus#887]
Hello,

I'm trying to install Portus for our private registry and the registry is not trusting the token issued by Portus. Any help getting in the right direction would be appreciated.

The error as showed in the registry log:

`level=error msg="token signed by untrusted key with ID:`

Portus log does not give any more information than this:
```
Started GET "//v2/token?account=evert&service=Docker+registry" for 195.130.156.202 at 2016-05-19 14:53:13 +0200
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"test", "service"=>"Docker registry"}
Completed 200 OK in 155ms (Views: 0.2ms | ActiveRecord: 8.5ms)
[25] 195.130.156.202 - - [19/May/2016:14:53:13 +0200] "GET /v2/token?account=test&service=Docker+registry HTTP/1.0" 200 - 0.1575
```

Some questions:

1. Is PORTUS_KEY_PATH the private key that is used to create the token? This defaults to encryption_private_key_path in the secrets.yml file
2. Are there other parameters that influence the token creation and validation? To my knowledge and as explained by the docker [documentation](https://docs.docker.com/registry/spec/auth/token/) it successfully gets through steps 1-5 but fails on step 6 with the validation of the token.

setup:
- mariadb docker container
- portus docker container based on an image from [bydga](https://hub.docker.com/r/bydga/portus/)
- official registry container

nginx:
- forwarding port 80 to port 443
- forwarding / to portus:3000
- forwarding /v2/token to portus:3000
- forwarding /v2/ to registry:5000
- all certificates are signed by Letsencrypt
- all certificate files used in the containers are symlinked from the original ones so it is one set.

I use docker login portus.mydomain.com to login. Everything is as you can see under the portus subdomain. My real domain has another name of course.

I've been searching for related issues and have tumbled upon this one: [#523](https://github.com/SUSE/Portus/issues/523)
However I can't find the key symlink that person is talking about so I believe it is not related.
There was also a link to a wiki page regarding running on the same FQDN but that page has unfortunately been removed.
Issue [#509](https://github.com/SUSE/Portus/issues/509) has a  discussion about running on the same FQDN but I'm not using domain.com/portus or domain.com/registry (as explained below)

Here is my Portus docker command

```
docker run -d --name=portus -e RAILS_ENV=production \
--link portus_mariadb -e PORTUS_PRODUCTION_HOST=portus_mariadb \
-e PORTUS_PRODUCTION_USERNAME=portus \
-e PORTUS_PRODUCTION_PASSWORD=<removed> \
-e PORTUS_PRODUCTION_DATABASE=portus \
-e PORTUS_MACHINE_FQDN=portus.mydomain.com \
-e PORTUS_SECRET_KEY_BASE=<removed> -p 192.168.x.x:3000:3000 \
-e PORTUS_KEY_PATH=/etc/docker/key.pem \
-e PORTUS_PASSWORD=<removed> \
-v /applications/portus/certificates/privkey.pem:/etc/docker/key.pem \
 mdc/portus puma -b tcp://0.0.0.0:3000 -w 3
```

Here is my registry docker command

```
docker run -d -p 192.168.x.x:5000:5000 \
-e REGISTRY_HTTP_SECRET=fzND4y8c8mnCZXBq2xHE \
-e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry \
-e REGISTRY_AUTH=token \
-e REGISTRY_AUTH_TOKEN_REALM=https://portus.mydomain.com/v2/token \
-e REGISTRY_AUTH_TOKEN_SERVICE="Docker registry" \
-e REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME=portus \
-e REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=https://portus.mydomain.com:443/v2/webhooks/events \
-e REGISTRY_NOTIFICATIONS_ENDPOINTS_BACKOFF=1s \
-e REGISTRY_NOTIFICATIONS_ENDPOINTS_THRESHOLD=5 \
-e REGISTRY_NOTIFICATIONS_ENDPOINTS_TIMEOUT=500ms \
-e REGISTRY_AUTH_TOKEN_ISSUER="portus.mydomain.com" \
-e REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/fullchain.pem \
-v /applications/registry/certificates/fullchain.pem:/ssl/fullchain.pem \
-v /applications/registry/data:/var/lib/registry \
--name portus_registry registry:2
```

**Comment by EvertMDC** [comment]
I've been investigating this behaviour a bit further.

[According to the docker documentation](https://docs.docker.com/registry/spec/auth/jwt/) the token is signed and generated using [ECDSA](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm).
The sample key used for signing was shown in the Docker documentation so I was wondering  where Portus got or stored his key for signing.

I stumbled upon [this post](https://github.com/docker/distribution/issues/520#issuecomment-106511459) from a docker member stating that the registry will check the token against a normal certificate like the ones used in a browser. This makes sense.
Elaborating on this this means the key defined in encryption_private_key_path in the [secrets.yml](https://github.com/SUSE/Portus/blob/master/config/secrets.yml) file of Portus is logically the one used for signing.

This leaves the possibility for errors in the following:
1. secret_key_base is also used for token signing and is not the same between registry and Portus
2. portus_password is also used for token signing and is not the same between registry and Portus
3. The Portus container image contains a certificate from the owner, I might have to find it and replace it with my own.

The second one seems a bit weird to me.
Regarding the first, the registry container has an environment variable called REGISTRY_HTTP_SECRET but this does not seem to be related.

The last possibility seems the most plausible. Any idea where this can be found?

Best regards

**Comment by EvertMDC** [comment]
The solution to this issue was to use a different docker container.
I assume the one I used had a certificate hard-coded somewhere.

**Comment by tychota** [comment]
@EvertMDC : can you elaborate ?

**Comment by EvertMDC** [comment]
Hello @tychota 
When using the docker container of [bydga](https://hub.docker.com/r/bydga/portus/) I couldn't get my setup to work. This was mostly due to the fact that that container is not configured to be used outside the enterprise of that user. When looking around in the image you can see that it's tailor-made.
I ended up using the [sshipway](https://hub.docker.com/r/sshipway/portus/) image which worked. The only thing I that isn't working at the moment are the webhooks but with the automatic refresh every 5 minutes it's not a major loss. I think that's due to a configuration issue on my side rather than an issue with the container.

Hope this can help you.

**Comment by tboerger** [comment]
What's wrong with our portus container?

**Comment by EvertMDC** [comment]
Hello @tboerger 
I'm sure the container itself is great but since I was new to portus and containers I would have needed a bit more documentation to get started.
I would prefer to use the official image but I can't seem to find the requirements, list of possible environment variables, there are no examples on how to set it up.
If this could be put in the readme on docker hub there would be a lot more pulls.

**Comment by mssola** [comment]
@EvertMDC we are going to update the documentation with all this shortly. We've been busy with other stuff but I'm aware that the documentation needs some love.

**Comment by arthurd2** [comment]
FIXED!
I had the same problem on  Omnibus.
I figured out that the Certificate and Key on the "registry" part of /etc/gitlab/gitlab-secrets.json MUST MATCH with the ones in following  configurations on /etc/gitlab/gitlab.rb : 
```
registry['rootcertbundle'] 
gitlab_rails['registry_key_path']
```

Now, to be sure that the certificate matches the key, you can use the openssl command:
```
 openssl x509 -noout -modulus -in server.crt | openssl md5
 openssl rsa -noout -modulus -in server.key | openssl md5
```
