### ISSUE TITLE
Portus user

### ISSUE THREAD

**Issue by erwanncloarec** [SUSE/Portus#889]
I have a question about _portus_ user.

From what I understand, it is useful for crono to sync the registry with Portus database. 

When I initiate the database with ```rake db:migrate:reset```, the _portus_ user is not created. I have to create it in the webapp. The problem is that this user needs to be admin to perform the crono task. I cannot make the user admin in the webapp since it does not appear. I had to update the database manually.

Did I miss something about the creation of this user?

**Comment by mssola** [comment]
This user is created with `rake db:seed`, not from the web app :wink:

**Comment by erwanncloarec** [comment]
Right, I forgot that command...

Is there anything else that this command do except creating _portus_ user?

**Comment by mssola** [comment]
If you are running integration tests, then it will also create some convenient object. Other than that, no :)

Also, I think that these kinds of questions would be more fitting in our [Google groups](https://groups.google.com/forum/#!forum/portus-dev) :wink:

I'm closing this issue now, but feel free to make more questions though.

**Comment by erwanncloarec** [comment]
Thank you! I'll use the group next time
