### ISSUE TITLE
removing image not working in namespace

### ISSUE THREAD

**Issue by recteurlp** [SUSE/Portus#897]
Hi,

Juste tested image deletion in a docker-compose setup with registry 2.4.0 it's working great with image in the "root" namespace (registry:5000/image).

But not on other namespace for example registry:5000/user1/fedora:23.
In registry log i can see that portus is trying to get the manifest for the wrong repo :

```
registry | "GET /v2/fedora/manifests/23 HTTP/1.0" 401 138 "" "Ruby"
registry | level=error msg="response completed with error" auth.user.name=portus environment=production err.code="manifest unknown" err.detail="unknown tag=23" err.message="manifest unknown" go.version=go1.6.1 http.request.host=registry:5000 http.request.id=9c294197-c201-420c-8ca4-90a101f68442 http.request.method=GET http.request.remoteaddr=172.17.0.1 http.request.uri="/v2/fedora/manifests/23" http.request.useragent=Ruby http.response.contenttype="application/json; charset=utf-8" http.response.duration=5.153083ms http.response.status=404 http.response.written=92 instance.id=79f84872-9b54-45be-be30-c384b9bc6921 service=registry vars.name=fedora vars.reference=23 version=v2.4.0
```

i think it should be /v2/user1/fedora/manifests/23 ?

Best Regards,

**Comment by mssola** [comment]
You are right, thanks.

**Comment by mssola** [comment]
Hi @recteurlp, maybe you could try PR #900. It works for me, but it would be awesome if you could give me some feedback :)

**Comment by recteurlp** [comment]
Hi just tested PR #900 deletion is working great :+1: 

Thanks, now waiting for PR to be merge ;)
