### ISSUE TITLE
unsynced Clocks produces nbf to fail as it issued on before time actual on registry

### ISSUE THREAD

**Issue by kalabiyau** [SUSE/Portus#9]

**Comment by mssola** [comment]
As discussed on IRC, this is not really an issue from our side. Just use NTP to keep all the clocks on sync.

**Comment by kalabiyau** [comment]
@mssola at least worth a mention on the README, I guess

**Comment by mssola** [comment]
@kalabiyau done! https://github.com/SUSE/Portus/wiki/Synchronizing-the-Registry-and-Portus#synchronizing-clocks-between-the-registry-and-portus
