### ISSUE TITLE
webhook events not working in registry 2.4.x

### ISSUE THREAD

**Issue by EugenMayer** [SUSE/Portus#905]
Issue:
It seems like webhooks/events are no longer working when >= registry:2.4 is used.

My build:
- portus build from today from the repo
- self signed certificate in a ssl-proxy nginx, but http://portus:3000 is no ssl connection

Reproduction:
When webhooks are configured like
```
REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://portus:3000/v2/webhooks/events
          timeout: 500
          threshold: 5
          backoff: 2s
```

which does work with registry:2.3.1, will not work with 2.4 and 2.4.1 - i could not find any changelog informations or whatever. Seems like the configuration is still the says https://docs.docker.com/registry/configuration/#endpoints

The error looks like this

```
registry    | ERRO[0110] retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying
registry    | WARN[0110] httpSink{http://portus:3000/v2/webhooks/events} encountered too many errors, backing off
```

I can run 

```
curl -X POST http://portus:3000/v2/webhooks/events
```

without an error. So its probably the the payload?

**Comment by EugenMayer** [comment]
if usefull / interesting you can use my build here https://github.com/EugenMayer/portus-build - test environment is explained. But this can be reproduced using any setup, also using the current stable release 2.0.5 of portus

**Comment by mssola** [comment]
@EugenMayer weird, it works for me on an NGinx + Puma setup :confused:. Could you paste the logs of Portus itself ?

**Comment by EugenMayer** [comment]
@mssola you can easily test and see it yourself 

1. pull https://github.com/EugenMayer/portus-build
2. ```cd test && start.sh```
3. point portus.dev and registry.dev to your docker-machine IP (/etc/hosts)

You should now be able to access portus with a registry:2.3.1 using user admin/admin

If you know push something to the registry:

```
docker tag alpine registry.dev:alpine
docker push
```

you see those issue in the compose logs.

I can reproduce this with totally different setups. With rancher-catalog HA(ssl)->portus setup, also with this sertup using nginx(ssl)->portus as exaclty in the case i gave you.

Maybe its interesting to share how you setup the notification hook, mine is done using: https://github.com/EugenMayer/portus-build/blob/master/test/docker-compose.yml#L63

**Comment by EugenMayer** [comment]
Just started the setup and pushed. As before

```
```

It seems like not portus logs are generated

```
root@fe4e626609fa:/portus/log# cat /portus/log/production.log
root@fe4e626609fa:/portus/log#
```

```
dc logs portus
portus |   Parameters: {"account"=>"admin", "scope"=>"repository:alpine:push,pull", "service"=>"registry.dev:443"}
portus | Completed 200 OK in 63ms (Views: 0.1ms | ActiveRecord: 2.3ms)
portus | [95] 172.19.0.1 - - [30/May/2016:15:16:31 +0000] "GET /v2/token?account=admin&scope=repository%3Aalpine%3Apush%2Cpull&service=registry.dev%3A443 HTTP/1.0" 200 - 0.0650
```

so it seems like portus is never contacted - i though about that before, so i tested (on the running regsitry container:

```
apt-get update && apt-get install curl
curl -X POST http://portus:3000/v2/webhooks/events
```

and got in the logs

```
portus | Completed 500 Internal Server Error in 0ms (ActiveRecord: 0.0ms)
portus |
portus | JSON::ParserError (A JSON text must at least contain two octets!):
portus |   app/controllers/api/v2/events_controller.rb:5:in `create'
portus |
portus |
portus | [90] 172.19.0.5 - - [30/May/2016:15:18:25 +0000] "POST /v2/webhooks/events HTTP/1.1" 500 - 0.0055
```

so infrastructural wise its all set and the container can reach the endpoint. Maybe portus blocks the requests before it even reaches anything that logs it - like because of headers?

**Comment by EugenMayer** [comment]
@mssola any ideas here? Its a huge blocker for me since without 2.4.x the GC is not working. Best

**Comment by mssola** [comment]
@EugenMayer so, I've tried it unsuccessfully. First of all, I had to change eugenmayer/portus:latest to eugenmayer/portus:2.4-rc1. Besides that, at the end I got an error from docker-machine:

ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

**Comment by EugenMayer** [comment]
fixing the reference to the hub image, sorry, tag-confusion :)

```
ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.
```

It seems you have no local docker running do you. What OS do you have? Are you using dockertoolbox/docker for mac? Did you start them before?

Did you try to start docker with
```
docker-machine start default
```

Are you generally familiar with running docker locally?

what happens if you run

```
docker ps
docker images
```

**Comment by EugenMayer** [comment]
@mssola the image was set to eugenmayer/portus:2.4-rc1 already, since 29th Mai - you might use a outdated repo - please pull

**Comment by EugenMayer** [comment]
@mssola sorry to bump this, is there any chance you look into this? Since i can reproduce this in 2 different stacks i do at least do not expect this to be an infrastructural issue - but i am happy to work on this, if required.

I think i tried to exclude any idea of a network/dns/ssl/infrastructural issue, as posted the result above. It must at least be a combination of software and maybe infrastructure, or only software. 

Can i help you somehow? As portus and esp. the regsitry even hooks is not very speaking to me, i would at least hope you could cover the software part of "digging".

Thanks in anyway

**Comment by EugenMayer** [comment]
@mssola any way i can help out to make this easier for you to reproduce?

**Comment by parruda** [comment]
+1 same problem here
Using with Rancher
```
[31mERRO[0m[36747] retryingsink: error writing events: httpSink{http://portus:3000/v2/webhooks/events}: error posting: Post http://portus:3000/v2/webhooks/events: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying 
```

**Comment by EugenMayer** [comment]
@parruda are you using my catalog or the community catalog?

**Comment by parruda** [comment]
I am using community:registry, but I updated manually the registry to 2.4 and portus to the latest commit on master.

**Comment by parruda** [comment]
@EugenMayer also, curl -X POST http://portus:3000/v2/webhooks/events does not return error.

**Comment by EugenMayer** [comment]
@mssola any way you can follow up on this? Thanks!

**Comment by EugenMayer** [comment]
still no progress on this, thats kinda bad. Today i upgraded to the newest portus, using registry 2.5

```
still no progress on this, thats kinda bad. Today i upgraded to the newest portus, using registry 2.5

```
8/19/2016 11:36:22 PM[31mERRO[0m[6456] retryingsink: error writing events: httpSink{https://portus.dw.domain:443/v2/webhooks/events}: error posting: Post https://portus.dw.domain:443/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying 
8/19/2016 11:36:22 PM[31mERRO[0m[6456] retryingsink: error writing events: httpSink{https://portus.dw.domain:443/v2/webhooks/events}: error posting: Post https://portus.dw.domain:443/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying
8/19/2016 11:36:22 PM[31mERRO[0m[6456] retryingsink: error writing events: httpSink{https://portus.dw.domain:443/v2/webhooks/events}: error posting: Post https://portus.dw.domain:443/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying 
8/19/2016 11:36:22 PM[31mERRO[0m[6456] retryingsink: error writing events: httpSink{https://portus.dw.domain:443/v2/webhooks/events}: error posting: Post https://portus.dw.domain:443/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying
I
```

Its not like this is cosmetic, after 30 minutes it creates a horrible load ad actuall stalls the whole barebone.

**Comment by EugenMayer** [comment]
on the portus side, it looks like this

```
8/19/2016 11:44:25 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:25 PMCompleted 202 Accepted in 1ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:25 PM[36] 172.17.0.1 - - [19/Aug/2016:21:44:25 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.0700
8/19/2016 11:44:26 PMCompleted 202 Accepted in 84ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:26 PM[36] 172.17.0.1 - - [19/Aug/2016:21:44:26 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1183
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMCompleted 202 Accepted in 0ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.0397
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMStarted POST "/v2/webhooks/events" for 10.42.41.26 at 2016-08-19 21:44:28 +0000
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMCompleted 202 Accepted in 2ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.0849
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMCompleted 202 Accepted in 59ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PMCompleted 202 Accepted in 1ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PMCompleted 202 Accepted in 69ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1026
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1156
8/19/2016 11:44:28 PMCompleted 202 Accepted in 84ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1376
8/19/2016 11:44:28 PMProcessing by Api::V2::EventsController#create as JSON
8/19/2016 11:44:28 PMCompleted 202 Accepted in 0ms (ActiveRecord: 0.0ms)
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1303
8/19/2016 11:44:28 PM[32] 172.17.0.1 - - [19/Aug/2016:21:44:28 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.1680
```

**Comment by EugenMayer** [comment]
when doing 
```curl -v -X POST https://portus.dw.domain.com/v2/webhooks/events``` from the registry container, i get something like

```
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; CN=registry.dw.domain.com
*  start date: Jul 28 20:18:43 2016 GMT
*  expire date: Jul 28 20:18:43 2017 GMT
*  subjectAltName: host "portus.dw.domain.com" matched cert's "portus.dw.domain.com"
*  issuer: C=IL; O=StartCom Ltd.; OU=StartCom Certification Authority; CN=StartC
om Class 1 DV Server CA
*  SSL certificate verify ok.
> POST /v2/webhooks/events HTTP/1.1
> Host: portus.dw.kontextwork.com
> User-Agent: curl/7.50.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html; charset=utf-8
< X-Request-Id: c01cb20f-ceeb-481e-b4d6-f45a91595789
< X-Runtime: 0.003044
< Content-Length: 0
<
```

but maybe my payload is wrong? how should a proper curl test request look like?

**Comment by EugenMayer** [comment]
After some digging, i created this gist : https://gist.github.com/EugenMayer/be3ea8cabecf44db0185cf90136ab9a8

So in general the curl POST works with the payload from https://docs.docker.com/registry/notifications/#endpoints .. either the payloads changed and the docs are outdated, and thats why portus is not working, or anything else. You see that i have changed the communication to use the internal link on 3000, to ensure it all works out.

I am really lost on this one, any help appreciated.

**Comment by EugenMayer** [comment]
@mssola also created https://github.com/docker/distribution/issues/1916 for this.

I would even say, that is a blocker for the upcoming stable release, since people will not use 2.3.1 - it does not support the garbage collector and is way outdated. Even your old tests do use 2.3.1 https://github.com/SUSE/Portus/blob/master/compose/docker-compose.yml.template#L31 and i do not think that will reflect what people did have already setup.

**Comment by EugenMayer** [comment]
@mssola from 2.4, this was changed in the notifications even:

```
Tagged Manifest Events
Manifest push and pull events will now include the tag which was used in the operation (if applicable).```

can this cause this issue?

**Comment by mssola** [comment]
Hi @EugenMayer, I was on vacation for a week and a half. After that, I'm afraid this issue simply slipped through my list of tasks to do. Sorry for that. It starts looking like a blocking Portus issue indeed, but I remember doing some work in order to fix that already, and it should be on master. Apparently you are still getting this error, so I'll look it further as soon as possible. Sorry for not getting back to you earlier :sweat:

**Comment by EugenMayer** [comment]
Great, no worries, i am glad we can move on with this!

**Comment by mssola** [comment]
My setup is:

- Portus from the `master` branch. Setup with Puma and NGinx (bare metal)
- Docker Registry 2.4.1

Currently in `master`, when processing an event, if I use the payload you submitted it will be *ignored* because it's a pull, and for now we only account for pushes and deletes. See the line 18 in `lib/portus/registry_notification.rb`:

```ruby
        next unless HANDLED_EVENTS.include?(action)
```

Where `HANDLED_EVENTS` is defined above as `HANDLED_EVENTS = ["push", "delete"].freeze`.

Moreover, I've also tried to modify your payload, but I've found some "funny" things like `actor` being empty. Is this event "authentic" or you have written it manually :sweat_smile:  ? I guess that it's "authentic", so in this case I guess that one improvement would be to default to the global (and hidden) `portus` user ?

If I add the value for the `actor`, then both a push and a delete work fine for me with this payload (assuming that the image exists on the registry of course :smile:).

```
Manifest push and pull events will now include the tag which was used in the operation (if applicable).
```

Yeah, we modified this in Portus' `master` branch a long time ago. As you can see, in the line 140 of the `app/models/registry.rb` file, the first lines of the `get_tag_from_target` method are:

```ruby
    # Since Docker Distribution 2.4 the registry finally sends the tag, so we
    # don't have to perform requests afterwards.
    return target["tag"] unless target["tag"].blank?
```

Did I clear any of your doubts ? :smile:

**Comment by EugenMayer** [comment]
I build the master today ( 2 hours away ) and i use registry 2.5 ( since that is the current stable ) and do still have the same isseus. 

Which payload are you referencing to actually? That payload https://gist.github.com/EugenMayer/be3ea8cabecf44db0185cf90136ab9a8#file-curl-test-payload-json has been copy / pasted from the docker docs : https://docs.docker.com/registry/notifications/#endpoints

Well i am not sure why "actor" is needed, but the "original" payload a registry 2.5 sends, seem to not work - not the one i copied and tried - neither of those work. I do though not have the original payload at hand and i cannot see any particual debug information on the side of portus

**Comment by EugenMayer** [comment]
@mssola i am starting to believe it could really be a "user issue" in terms, how the portus user is setup or what "user" the registry is using to contact portus or whatever.

I do not have any internals how this works in general, if the user is the user pushing/pulling/deleting or rather a management user. 

could you please clone 
- clone https://github.com/EugenMayer/docker-image-portus
- run ./test_start.sh
 
look at the cli how portus is setup. Do you see any oddness?

**Comment by mssola** [comment]
> I build the master today ( 2 hours away ) and i use registry 2.5 ( since that is the current stable ) and do still have the same isseus. 

I'll upgrade to 2.5 and I'll try to reproduce this :+1: 

> I build the master today ( 2 hours away ) and i use registry 2.5 ( since that is the current stable ) and do still have the same isseus.

> Which payload are you referencing to actually? That payload https://gist.github.com/EugenMayer/be3ea8cabecf44db0185cf90136ab9a8#file-curl-test-payload-json has been copy / pasted from the docker docs : https://docs.docker.com/registry/notifications/#endpoints

Ok, that's what I thought. In that payload they ignored the `actor` part. The `actor` means "who has performed the action". Therefore, if a user named `john` pushes onto the registry, then the `actor` value will be john, regardless if john is an admin or not. Now, if `actor` is left empty, then Portus will ignore the request, since we won't be able to determine who has performed the action. As I said in my comment, maybe we could default to the hidden `portus` user in this case (even though I'm not sure when can this happen :confused:).

Moreover, the example payload is fine, but Portus will ignore it, because it's a `pull`, and Portus ignores them right now.

> 
 - clone https://github.com/EugenMayer/docker-image-portus
 - run ./test_start.sh

> look at the cli how portus is setup. Do you see any oddness?

Will do :wink:

**Comment by mssola** [comment]
> I'll upgrade to 2.5 and I'll try to reproduce this :+1:

@EugenMayer now I can confirm :cry: Upgrading to 2.5 broke things for me (why didn't I upgrade to 2.5 before ?!). This is definitively a blocking bug and I'll try to tackle it as soon as possible.

I haven't investigated too much on this, but on a push Portus received only one notification in 2.4. Now Portus is receiving multiple of them (with pull's with a similar payload to yours...).

**Comment by EugenMayer** [comment]
great you could reproduce this finally!

**Comment by mssola** [comment]
@EugenMayer hopefully the PR #1068 fixes this for me. Would it be possible for you to confirm this ? Thanks! (and sorry for taking so long, I was swamped with other stuff :sweat_smile:)

**Comment by EugenMayer** [comment]
@mssola sorry this time i was on holidays. I just redeployed and rebuild the current master to test this, but portus seems to broken:

```
10/1/2016 2:43:27 PMStarted GET "/500?fixes=true" for 127.0.0.1 at 2016-10-01 12:43:27 +0000
10/1/2016 2:43:27 PMProcessing by ErrorsController#show as */*
10/1/2016 2:43:27 PM  Parameters: {"fixes"=>"true", "status"=>"500"}
10/1/2016 2:43:27 PM  Rendered errors/500.html.erb within layouts/errors (1.8ms)
10/1/2016 2:43:36 PM  Rendered errors/_status_title.html.slim (2.4ms)
10/1/2016 2:43:37 PMCompleted 500 Internal Server Error in 9737ms (Views: 9736.5ms | ActiveRecord: 0.0ms)
10/1/2016 2:43:37 PM[34] 127.0.0.1 - - [01/Oct/2016:12:43:37 +0000] "GET /500?fixes=true HTTP/1.1" 500 - 9.7419
```

Anything changed completly - are the migrations broken? Cannot really see what caused the 500 response

**Comment by EugenMayer** [comment]
further informations:

```
10/1/2016 2:51:05 PM[25] Puma starting in cluster mode...
10/1/2016 2:51:05 PM[25] * Version 2.14.0 (ruby 2.2.2-p95), codename: Fuchsia Friday
10/1/2016 2:51:05 PM[25] * Min threads: 0, max threads: 16
10/1/2016 2:51:05 PM[25] * Environment: development
10/1/2016 2:51:05 PM[25] * Process workers: 3
10/1/2016 2:51:05 PM[25] * Phased restart available
10/1/2016 2:51:05 PM[25] * Listening on tcp://0.0.0.0:3000
10/1/2016 2:51:05 PM[25] Use Ctrl-C to stop
10/1/2016 2:51:08 PM[Mailer config] Host:     portus.kw.com
10/1/2016 2:51:08 PM[Mailer config] Protocol: https://
10/1/2016 2:51:08 PM[Mailer config] Host:     portus.kw.com
10/1/2016 2:51:08 PM[Mailer config] Protocol: https://
10/1/2016 2:51:08 PM[Mailer config] Host:     portus.kw.com
10/1/2016 2:51:08 PM[Mailer config] Protocol: https://
10/1/2016 2:51:08 PM[Mailer config] Host:     portus.kw.com
10/1/2016 2:51:08 PM[Mailer config] Protocol: https://
10/1/2016 2:51:09 PM[25] - Worker 1 (pid: 33) booted, phase: 0
10/1/2016 2:51:09 PM[deprecated] The 'x.minutes' format is deprecated for configuration values such as `jwt_expiration_time`. From now on these values are expected to be integers representing minutes.
10/1/2016 2:51:09 PMI, [2016-10-01T12:51:09.622052 #24]  INFO -- : Loading Crono 0.9.0
10/1/2016 2:51:09 PMI, [2016-10-01T12:51:09.622125 #24]  INFO -- : Running in ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
10/1/2016 2:51:09 PMI, [2016-10-01T12:51:09.622148 #24]  INFO -- : Jobs:
10/1/2016 2:51:09 PMI, [2016-10-01T12:51:09.622354 #24]  INFO -- : 'CatalogJob' with rule 'every 300 seconds' next time will perform at 2016-10-01 12:56:09 UTC
10/1/2016 2:51:09 PM[25] - Worker 2 (pid: 37) booted, phase: 0
10/1/2016 2:51:09 PM[25] - Worker 0 (pid: 29) booted, phase: 0
10/1/2016 2:56:09 PMI, [2016-10-01T12:56:09.622111 #24]  INFO -- : Perform CatalogJob
10/1/2016 2:56:21 PMException: Cannot obtain authorization token: #<Net::HTTPServiceUnavailable:0x005630f7c3d880>
10/1/2016 2:56:21 PMI, [2016-10-01T12:56:21.769615 #24]  INFO -- : Finished CatalogJob in 12.15 seconds
```

**Comment by EugenMayer** [comment]
Fixed it, though i needed to use https://github.com/SUSE/Portus/pull/1076 to introduce the dev mode in the rancher catalog - found out that the load balancer was freaking out. Sorry for the inconvenience here.

**Comment by EugenMayer** [comment]
@mssola tested, but i have bad news, for me, the issue still exist:

```
10/1/2016 6:26:13 PM[31mERRO[0m[9806] retryingsink: error writing events: httpSink{https://portus.kw.com:443/v2/webhooks/events}: error posting: Post https://portus.kw.com:443/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying 
10/1/2016 6:26:13 PM[33mWARN[0m[9806] httpSink{https://portus.kw.com:443/v2/webhooks/events} encountered too many errors, backing off
```
This time though, i cannot see any incoming log events in portus during that - so this is even stranger now

**Comment by EugenMayer** [comment]
I entered the shell on the registry container and ran the test using curl and https://gist.github.com/EugenMayer/be3ea8cabecf44db0185cf90136ab9a8 this - and the requests do work when trying to post to https://portus.kw.com:443/v2/webhooks/events without issues

On the portus side, this request is received like this
```
10/1/2016 6:37:35 PMStarted POST "/v2/webhooks/events" for 10.42.13.179 at 2016-10-01 16:37:35 +0000
10/1/2016 6:37:35 PMProcessing by Api::V2::EventsController#create as JSON
10/1/2016 6:37:35 PM  Parameters: {"events"=>[{"id"=>"320678d8-ca14-430f-8bb6-4ca139cd83f7", "timestamp"=>"2016-03-09T14:44:26.402973972-08:00", "action"=>"pull", "target"=>{"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>708, "digest"=>"sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "length"=>708, "repository"=>"hello-world", "url"=>"http://192.168.100.227:5000/v2/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "tag"=>"latest"}, "request"=>{"id"=>"6df24a34-0959-4923-81ca-14f09767db19", "addr"=>"192.168.64.11:42961", "host"=>"192.168.100.227:5000", "method"=>"GET", "useragent"=>"curl/7.38.0"}, "actor"=>{}, "source"=>{"addr"=>"xtal.local:5000", "instanceID"=>"a53db899-3b4b-4a62-a067-8dd013beaca4"}}], "event"=>{"events"=>[{"id"=>"320678d8-ca14-430f-8bb6-4ca139cd83f7", "timestamp"=>"2016-03-09T14:44:26.402973972-08:00", "action"=>"pull", "target"=>{"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>708, "digest"=>"sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "length"=>708, "repository"=>"hello-world", "url"=>"http://192.168.100.227:5000/v2/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf", "tag"=>"latest"}, "request"=>{"id"=>"6df24a34-0959-4923-81ca-14f09767db19", "addr"=>"192.168.64.11:42961", "host"=>"192.168.100.227:5000", "method"=>"GET", "useragent"=>"curl/7.38.0"}, "actor"=>{}, "source"=>{"addr"=>"xtal.local:5000", "instanceID"=>"a53db899-3b4b-4a62-a067-8dd013beaca4"}}]}}
10/1/2016 6:37:35 PMCompleted 202 Accepted in 19ms (ActiveRecord: 0.0ms)
10/1/2016 6:37:35 PM[30] 10.42.13.179 - - [01/Oct/2016:16:37:35 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 0.0267
```

So there is no general infrastructural issue - portus is receiving this event. Still, when looking in the registry, i see

```
10/1/2016 6:39:33 PM[31mERRO[0m[10606] retryingsink: error writing events: httpSink{https://portus.kw.com:443/v2/webhooks/events}: error posting: Post https://portus.kw.kontextwork.com:443/v2/webhooks/events: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retrying 
10/1/2016 6:39:33 PM[33mWARN[0m[10606] httpSink{https://portus.kw.com:443/v2/webhooks/events} encountered too many errors, backing off
```

everywhere. Interestingly, portus does not log this at all.
