### ISSUE TITLE
Due to current "delete image" efforts - a cli to talk with a registry

### ISSUE THREAD

**Issue by EugenMayer** [SUSE/Portus#906]
I have written a tool to be able to talk to a registry:v2 and offer all usual operations, but what i want to talk about is delete_image and delete_tag. Maybe this tool becomes handy for you guys during development, since it makes interfacing the registry easier then using Postman or similar.

https://github.com/EugenMayer/docker_registry_cli

I have seen some rake-tasks maybe doing the same, but i am not sure. This at least simulates the real case of a docker-registry-client.

I added the implementation to authenticate against a token service, so you can test it against a portus enabled registry, i did that to test https://github.com/EugenMayer/portus-build and how portus behaves with deletes.

For now, i am only seeing one odd result:
When deleting all tags of an image, Portus removes the image from the repo, but the _catalog still lists them ( do you filter them by something?)

**Comment by mssola** [comment]
> I have written a tool to be able to talk to a registry:v2 and offer all usual operations, but what i want to talk about is delete_image and delete_tag. Maybe this tool becomes handy for you guys during development, since it makes interfacing the registry easier then using Postman or similar.

> htts://github.com/EugenMayer/docker_registry_cli

> I have seen some rake-tasks maybe doing the same, but i am not sure. This at least simulates the real case of a docker-registry-client.

> I added the implementation to authenticate against a token service, so you can test it against a portus enabled registry, i did that to test https://github.com/EugenMayer/portus-build and how portus behaves with deletes.

That's really nice to see, thanks!

> For now, i am only seeing one odd result:
When deleting all tags of an image, Portus removes the image from the repo, but the _catalog still lists them ( do you filter them by something?)

Mmm, this is weird. I just tested your case, and it works fine by me. If you want to take a closer look, we have our own registry client library (implemented only just what we need, not a full client) at `lib/portus/registry_client.rb`. You can access that in the CLI through:

    $ rails r bin/client.rb catalog

The version of my registry is 2.4.0, and I'm using the `master` branch of Portus.

**Comment by EugenMayer** [comment]
thanks, i will look into your client and see what the implementation might say about this. I think, portus does everything right its just interesting that the client still lists those repos.

How does portus delete images, do you have a deep link to the REST calls ( blogic ) you trigger - i will compare it with mine to see how things differ. Just want to ensure there is no "hidden bug" at some level

**Comment by mssola** [comment]
Closing this since no further discussion was done. But, if during the investigation of this registry issue you found out that there's something wrong with how Portus handles this, please re-open this same issue 😃.

Thanks for this 👍
