### ISSUE TITLE
Cannot delete "latest" tag

### ISSUE THREAD

**Issue by EugenMayer** [SUSE/Portus#907]
I can delete any tag called not "latest". Is there any reason implementing this?

**Comment by mssola** [comment]
I cannot reproduce this :confused:. Maybe this is a duplicate of #897 ?

**Comment by EugenMayer** [comment]
Well it was an image in the root space. And interestingly, i cannot reproduce it myself. Just tried to give you the exact steps, pushed alpine with latest - there is a trash icon and i could easily delete it.

So, i guess, thats a "cannot reproduce" . Sorry

**Comment by stefankip** [comment]
I had the same issue just now. Tried to delete a test image with tag latest. Didn't work. Then I added a second tag to the same image (123) and both latest and 123 showed up in Portus. Then I was able to remove both at the same time.
