### ISSUE TITLE
Update documentation on new features from 2.1

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#927]
There are some pieces in the documentation that describe a new feature from the 2.1 release without alerting users that it's only available as of this specific release. We should put a notice on such features in the documentation, otherwise we confuse people.

**Comment by tboerger** [comment]
Maybe it makes sense to build separate documentations for releases?

**Comment by mssola** [comment]
Mmm, I don't think so. I think it makes more sense to have all the documentation in one central location. Then, for each specific feature we should be more straight-forward in regards to which versions support it.

**Comment by olblak** [comment]
Indeed documentation in one place is way better (less confusing).
And it should be part of the documentation process to say "required 2.0.5 version"

**Comment by tboerger** [comment]
I never said to have it on different locations, just the documentation display split by release with a selection of available releases.
