### ISSUE TITLE
Breaking: Portus hangs for a very long time after image push

### ISSUE THREAD

**Issue by charles-m-knox** [SUSE/Portus#940]
Hello! 
I've deployed Portus using `compose-setup.sh` and it works perfectly. However there is a breaking issue that I have seen in every deployment of Portus that I've done, and would like to know what the issue is and how I can help fix it, if at all.

**The problem:**
After logging in via `docker login portus-site.site.com:5000`, and then subsequently pushing an image via `docker push portus-site.site.com:5000/mynamespace/image:latest`, the Portus `web` container appears to hang for a few minutes. Any and all HTTP requests sit around, waiting for a response. For the purposes of clear discussion, I'm going to refer to this down time as "halt time".

**Investigation**
- I ran weaveworks to see if there were any memory issues or CPU issues with the containers during halt time. There were no outstanding measurements.
- Weaveworks did show that there were ~3 processes running in the Portus web container, all of which appeared to be typical ruby processes. If needed, I can provide specific logs (I just simply don't know where to look, I am at your disposal here).
- I checked the host system's disk usage during the halt time with `iotop`. No outstanding measurements were present, disk usage was normal.
- Running `top` showed no issues either, most processes that were running were idle.

**Specific Logs**
At halt time, here are the logs for Portus web. Note that the last event that occurred is a DB `select` method.

```
Started POST "/v2/webhooks/events" for 172.17.0.1 at 2016-06-24 16:50:37 +0000
Cannot render console from 172.17.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Api::V2::EventsController#create as JSON
Incoming event:
{
  "id": "b2f4586a-4dc8-41f9-9d1d-c0a5d529a6f8",
  "timestamp": "2016-06-24T16:50:37.324040756Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 502,
    "digest": "sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619",
    "length": 502,
    "repository": "chuck/hello-world",
    "url": "http://portus-demo1.site.com:5000/v2/chuck/hello-world/manifests/sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619"
  },
  "request": {
    "id": "4120caf6-da29-4c0a-9aaf-6060228c0d22",
    "addr": "10.19.8.224:62208",
    "host": "portus-demo1.site.com:5000",
    "method": "PUT",
    "useragent": "docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))"
  },
  "actor": {
    "name": "chuck"
  },
  "source": {
    "addr": "b3d7a572b077:5000",
    "instanceID": "46343825-0049-4fd2-b797-df84b0442786"
  }
}
Handling 'push' event:
{
  "id": "b2f4586a-4dc8-41f9-9d1d-c0a5d529a6f8",
  "timestamp": "2016-06-24T16:50:37.324040756Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 502,
    "digest": "sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619",
    "length": 502,
    "repository": "chuck/hello-world",
    "url": "http://portus-demo1.site.com:5000/v2/chuck/hello-world/manifests/sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619"
  },
  "request": {
    "id": "4120caf6-da29-4c0a-9aaf-6060228c0d22",
    "addr": "10.19.8.224:62208",
    "host": "portus-demo1.site.com:5000",
    "method": "PUT",
    "useragent": "docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))"
  },
  "actor": {
    "name": "chuck"
  },
  "source": {
    "addr": "b3d7a572b077:5000",
    "instanceID": "46343825-0049-4fd2-b797-df84b0442786"
  }
}
  Registry Load (0.1ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'portus-demo1.site.com:5000' LIMIT 1
  Namespace Load (0.2ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'chuck' LIMIT 1
```

**After Halt Time Logs**

In the Portus web container, we can start to identify the culprit. It takes two minutes to accomplish the task and return back to the user.

```
Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>502, "digest"=>"sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619", "length"=>502, "repository"=>"chuck/hello-world", "url"=>"http://portus-demo1.site.com:5000/v2/chuck/hello-world/manifests/sha256:e52be8ffeeb1f374f440893189cd32f44cb166650e7ab185fa7735b7dc48d619"}
Reason: Net::ReadTimeout
  CACHE (0.0ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'portus-demo1.site.com:5000' LIMIT 1  [["hostname", "portus-demo1.site.com:5000"]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'chuck' LIMIT 1  [["registry_id", 1], ["name", "chuck"]]
  Webhook Load (0.3ms)  SELECT `webhooks`.* FROM `webhooks` WHERE `webhooks`.`namespace_id` = 3
ETHON: started MULTI
ETHON: performed MULTI
Completed 202 Accepted in 120229ms (ActiveRecord: 0.7ms)
```

The culprit appears to be a timeout of some sort. But what is causing it? This is the question I hope we can work towards answering.

**Comment by chuck-knox** [comment]
**Additional Logs**

At halt time, here are the logs for the registry container.
```
time="2016-06-24T16:50:37Z" level=info msg="response completed" go.version=go1.5.3 http.request.host="portus-demo1.site.com:5000" http.request.id=86bafe78-99de-4d4e-9050-0a0307e63359 http.request.method=HEAD http.request.remoteaddr="10.19.8.224:50244" http.request.uri="/v2/chuck/hello-world/blobs/sha256:a9d36faac0fe2a855f798346f33bd48917bf3af9b6e4b77870ef8862fee8a8a3" http.request.useragent="docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=5.319994ms http.response.status=200 http.response.written=0 instance.id=46343825-0049-4fd2-b797-df84b0442786 version=v2.3.1 
10.19.8.224 - - [24/Jun/2016:16:50:37 +0000] "HEAD /v2/chuck/hello-world/blobs/sha256:a9d36faac0fe2a855f798346f33bd48917bf3af9b6e4b77870ef8862fee8a8a3 HTTP/1.1" 200 0 "" "docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))"
time="2016-06-24T16:50:37Z" level=info msg="response completed" go.version=go1.5.3 http.request.host="portus-demo1.site.com:5000" http.request.id=d006b35f-8047-40b0-8fec-d0aa1f9364f7 http.request.method=HEAD http.request.remoteaddr="10.19.8.224:57825" http.request.uri="/v2/chuck/hello-world/blobs/sha256:693bce72514984f01f217e878d143162b5f4c1b83b018e7e6dc7394f055e7cd5" http.request.useragent="docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=3.819096ms http.response.status=200 http.response.written=0 instance.id=46343825-0049-4fd2-b797-df84b0442786 version=v2.3.1 
10.19.8.224 - - [24/Jun/2016:16:50:37 +0000] "HEAD /v2/chuck/hello-world/blobs/sha256:693bce72514984f01f217e878d143162b5f4c1b83b018e7e6dc7394f055e7cd5 HTTP/1.1" 200 0 "" "docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))"
time="2016-06-24T16:50:37Z" level=info msg="response completed" go.version=go1.5.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host="portus-demo1.site.com:5000" http.request.id=4120caf6-da29-4c0a-9aaf-6060228c0d22 http.request.method=PUT http.request.remoteaddr="10.19.8.224:62208" http.request.uri="/v2/chuck/hello-world/manifests/v5" http.request.useragent="docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))" http.response.duration=28.093659ms http.response.status=201 http.response.written=0 instance.id=46343825-0049-4fd2-b797-df84b0442786 version=v2.3.1 
10.19.8.224 - - [24/Jun/2016:16:50:37 +0000] "PUT /v2/chuck/hello-world/manifests/v5 HTTP/1.1" 201 0 "" "docker/1.12.0-rc2 go/go1.6.2 git-commit/906eacd kernel/3.13.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.12.0-rc2 \\(linux\\))"
time="2016-06-24T16:50:37Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host="portus-demo1.site.com:5000" http.request.id=805084f4-0ffe-4779-ba8a-04b2b934b761 http.request.method=GET http.request.remoteaddr="172.17.0.1:56468" http.request.uri="/v2/chuck/hello-world/tags/list?n=100" http.request.useragent=Ruby instance.id=46343825-0049-4fd2-b797-df84b0442786 vars.name="chuck/hello-world" version=v2.3.1 
172.17.0.1 - - [24/Jun/2016:16:50:37 +0000] "GET /v2/chuck/hello-world/tags/list?n=100 HTTP/1.1" 401 149 "" "Ruby"
```

**Comment by Penguin2600** [comment]
+1 I have seen the same issue in my work environment, I wonder if its somehow proxy related.

**Comment by chuck-knox** [comment]
@Penguin2600 : I removed proxy settings from my Dockerfile and re-built everything, and the issue still occurs, so I think we can safely rule that out.

**Comment by chuck-knox** [comment]
**Additional Notes:**
Here is the anonymized output of `rake portus:info`.

```
[Mailer config] Host:     portus-demo1.site.com
[Mailer config] Protocol: http://

Portus version: 2.1.0-dev
Portus has evaluated the following configuration:
---
email:
  from: portus@site.com
  name: Portus
  reply_to: no-reply@site.com
  smtp:
    enabled: true
    address: smtp.mysite.com
    port: 25
    user_name: git
    password: "****"
    domain: mysite.com
gravatar:
  enabled: false
ldap:
  enabled: true
  hostname: ad.mysite.com
  port: 3268
  method: starttls
  base: DC=somedc,DC=mysite,DC=someotherdc
  filter: "(&(objectcategory=person)(objectclass=user)(mysiteflags=1))"
  uid: sAMAccountName
  authentication:
    enabled: true
    bind_dn: username
    password: "****"
  guess_email:
    enabled: false
    attr: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: false
jwt_expiration_time:
  value: 5.minutes
machine_fqdn:
  value: portus-demo1.site.com
```
The configuration uses LDAP.

**Comment by lexapi** [comment]
We have the same problem.
Our configuration:
* ubuntu 16.04 LTS
* Docker version 1.11.2, build b9f10c9

Docker container:
* portus master (2.1.0 dev)
* registry:2.3.1
* mariadb:10.0.23

Our CI system (we are use Jenkins) build image and push him to repo, after this another job loging to registry and pull image:

> Successfully built b39869fd0e3d
The push refers to a repository [our-registry.lan:5000/namespace/container]
62a99c283c99: Preparing
.
.
.
2d2c6805c1cb: Waiting
62a99c283c99: Pushed
f7b8780a12c9: Layer already exists
...
a7e1c363defb: Layer already exists
2998cfbd1893: Pushed
latest: digest: sha256:5939e2fd1e7f889bf110e9a5f8126fb01ffad08d27a1ea8d899d4b888e5bf647 size: 5336
ssh username@192.168.0.2 bash -s
Login Succeeded
pull image
Error response from daemon: Get https://our-registry.lan:5000/v2/namespace/container/manifests/latest: Get http:///our-registry.lan:3000/v2/token?account=docker&scope=repository%namespace%2Fcontainer%3Apull&service=our-registry.lan%3A5000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

We are not use LDAP.
If you make one more push while the web interface "frozen" this pushing will not be seen in Dashboard (Recent activities), and one time author was changed to portus (we are using another user!)
![portus](https://cloud.githubusercontent.com/assets/955888/16447712/7809371c-3df6-11e6-9166-e53cb836b70d.png)

**Comment by mssola** [comment]
Sorry for the late response, it's been quite busy these past two weeks :sweat:. We've experienced this before, and it usually boils down on some restrictions on the connections that Portus is allowed to perform (see #373). I also saw something on the likes when trying it with docker machine, but I was just doing some experiments with docker machine, so I'm not really sure (I'm not a docker machine user).

@chuck-knox: Now, the configuration seems fine to me, and there shouldn't be any problems. I'll try to reproduce this on my machine and I'll get back to you as soon as possible. In the meantime, could you describe more about your setup ? (are you using docker machine ? operating system, possible proxy/network configuration that might be in the way of docker, etc.).

@lexapi:

> We are not use LDAP.

Authentication is handled before any of this, so this is certainly not the cause of this :grin:.

> If you make one more push while the web interface "frozen" this pushing will not be seen in Dashboard (Recent activities), and one time author was changed to portus (we are using another user!)

This happens when the `crono` job kicks in, take a look at the [documentation](http://port.us.org/features/1_Synchronizing-the-Registry-and-Portus.html) for this. Basically, the contents between the registry and the db are handled through notifications. However, if Portus starts missing notifications (e.g. in this case because it was frozen), then we might have discrepancies between the contents of the registry and Portus. For this reason. there is the `crono` process that does the synchronization. Unfortunately, when `crono` is the one doing the sync'ing, we have no way of knowing which was the user that originally pushed the image. Maybe we should be more verbose on the value of author in this case instead of just saying "portus" :sweat_smile:.

**Comment by chuck-knox** [comment]
Hey @mssola , thanks for getting back to me! I get it, things get busy.

I did actually look at #373 before this, I figured it was similar but the logs are different.

* I am not using docker machine
* It is a distinct possibility that my corporate proxy is causing this. I'll go into detail after this.
* I have deployed using `./compose-setup.sh`, and I am using its `docker-compose.yml` templating mechanism to update my containers. This works fine as far as I can tell, and I like this.
* I am deploying entirely on a single VM.
* I am not using any special configuration settings (aside from proxy) - I will post my `docker-compose.yml.template` file and my `Portus_web` `Dockerfile` shortly, as well as my registry `config.yml`.


Ok. First, allow me to post my `docker-compose.yml.template`. You will see that it is extremely vanilla, aside from the fact that it's using docker-compose v2 format.

```
version: '2'
services:
  web:
    build: .
    command: puma -b tcp://0.0.0.0:3000 -w 3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=EXTERNAL_IP
      - PORTUS_DB_HOST=db
    volumes:
      - .:/portus
    ports:
      - 3000:3000
    links:
      - db

  crono:
    image: portus_web
    entrypoint: bin/crono
    environment:
      - PORTUS_MACHINE_FQDN=EXTERNAL_IP
      - PORTUS_DB_HOST=db
    volumes:
      - .:/portus
    links:
      - db

  db:
    image: library/mariadb:10.0.23
    environment:
      MYSQL_ROOT_PASSWORD: portus
    volumes:
      - /mnt/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.3.1
    volumes:
      - /mnt/registry:/registry_data
      - ./compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
      - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - web
```

Now, here's where the tricky part comes in, and I'm starting to suspect that this is where I'm injecting the problem. Here is the `Dockerfile` that builds `Portus_web`.

You'll notice immediately that I'm adding a bunch of proxy environment variables. This was necessary in order to get `bundle install` to work.

```
FROM library/rails:4.2.2
MAINTAINER Flavio Castelli <fcastelli@suse.com>

ENV COMPOSE=1
EXPOSE 3000

WORKDIR /portus
COPY Gemfile* ./
ENV http_proxy=http://proxy.site.com:9999
ENV https_proxy=http://proxy.site.com:9999
ENV HTTP_PROXY=http://proxy.site.com:9999
ENV HTTPS_PROXY=http://proxy.site.com:9999
ENV ALL_PROXY=http://proxy.site.com:9999
ENV all_proxy=http://proxy.site.com:9999
ENV no_proxy=172.0.0.0/8,10.0.0.0/8,.site.com
ENV NO_PROXY=172.0.0.0/8,10.0.0.0/8,.site.com

RUN HTTP_PROXY=http://proxy.site.com:9999 bundle install --retry=3

# Install phantomjs, this is required for testing and development purposes
# There are no official deb packages for it, hence we built it inside of the
# open build service.
RUN echo "deb http://download.opensuse.org/repositories/home:/flavio_castelli:/phantomjs/Debian_8.0/ ./" >> /etc/apt/sources.list
RUN wget http://download.opensuse.org/repositories/home:/flavio_castelli:/phantomjs/Debian_8.0/Release.key && \
  apt-key add Release.key && \
  rm Release.key
RUN apt-get update && \
    apt-get install -y --no-install-recommends phantomjs && \
    rm -rf /var/lib/apt/lists/*

ADD . .
```

Here is the `compose/registry/config.yml` file, note that it also is quite vanilla:

```
version: 0.1
storage:
  filesystem:
    rootdirectory: /registry_data
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
auth:
  token:
    realm: http://chuck-desk.site.com:3000/v2/token
    service: chuck-desk.site.com:5000
    issuer: chuck-desk.site.com
    rootcertbundle: /etc/docker/registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://chuck-desk.site.com:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

Now, I just tried pushing an image moments ago, and this time it timed out after 60 seconds. You can see the POST takes 60 seconds, and also my attempt to refresh the webpage took 60 seconds too.

```
web_1       | Started GET "/v2/token?account=portus&scope=repository%3Achuck%2Fhello-world%3Apull&service=chuck-desk.site.com%3A5000" for 10.0.2.2 at 2016-06-29 17:15:31 +0000
web_1       | Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1       | Processing by Api::V2::TokensController#show as JSON
web_1       |   Parameters: {"account"=>"portus", "scope"=>"repository:chuck/hello-world:pull", "service"=>"chuck-desk.site.com:5000"}
web_1       |   User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
web_1       |   ApplicationToken Load (1.7ms)  SELECT `application_tokens`.* FROM `application_tokens` WHERE `application_tokens`.`user_id` = 1
web_1       |   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus'  ORDER BY `users`.`id` ASC LIMIT 1
web_1       |    (0.3ms)  BEGIN
web_1       |   SQL (0.7ms)  UPDATE `users` SET `last_sign_in_at` = '2016-06-29 17:14:19', `current_sign_in_at` = '2016-06-29 17:15:31', `sign_in_count` = 8, `updated_at` = '2016-06-29 17:15:31' WHERE `users`.`id` = 1
web_1       |    (25.6ms)  COMMIT
web_1       |   Registry Load (0.3ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'chuck-desk.site.com:5000' LIMIT 1
web_1       |   Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'chuck' LIMIT 1
web_1       | [jwt_token] [claim] {:iss=>"chuck-desk.site.com", :sub=>"portus", :aud=>"chuck-desk.site.com:5000", :iat=>1467220531, :nbf=>1467220526, :exp=>1467220831, :jti=>"UFGcH31ATMiZY49nvgUPwH2SHqmn1jdsBDCwKWkj6W", :access=>[{:type=>"repository", :name=>"chuck/hello-world", :actions=>["pull"]}]}
web_1       | Completed 200 OK in 143ms (Views: 0.3ms | ActiveRecord: 29.8ms)
web_1       | [13] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /v2/token?account=portus&scope=repository%3Achuck%2Fhello-world%3Apull&service=chuck-desk.site.com%3A5000 HTTP/1.1" 200 - 0.1524
web_1       |   Repository Load (3.0ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`name` = 'hello-world' AND `repositories`.`namespace_id` = 3 LIMIT 1
web_1       |    (0.8ms)  SELECT `tags`.`name` FROM `tags` WHERE `tags`.`repository_id` = 1
web_1       |   CACHE (0.0ms)  SELECT  `registries`.* FROM `registries` WHERE (hostname LIKE '%chuck-desk.site.com:5000%')  ORDER BY `registries`.`id` ASC LIMIT 1
web_1       |   CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'chuck' LIMIT 1  [["registry_id", 1], ["name", "chuck"]]
web_1       |   Webhook Load (0.3ms)  SELECT `webhooks`.* FROM `webhooks` WHERE `webhooks`.`namespace_id` = 3
web_1       | ETHON: started MULTI
web_1       | ETHON: performed MULTI
web_1       | Completed 202 Accepted in 60268ms (ActiveRecord: 5.0ms)
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "POST /v2/webhooks/events HTTP/1.1" 202 - 60.2786
web_1       | 
web_1       | 
web_1       | Started GET "/v2/token?account=portus&scope=repository%3Achuck%2Fhello-world%3Apull&service=chuck-desk.site.com%3A5000" for 10.0.2.2 at 2016-06-29 17:15:31 +0000
web_1       | Cannot render console from 10.0.2.2! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1       | Processing by Api::V2::TokensController#show as JSON
web_1       |   Parameters: {"account"=>"portus", "scope"=>"repository:chuck/hello-world:pull", "service"=>"chuck-desk.site.com:5000"}
web_1       |   User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
web_1       |   ApplicationToken Load (0.3ms)  SELECT `application_tokens`.* FROM `application_tokens` WHERE `application_tokens`.`user_id` = 1
web_1       |   User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus'  ORDER BY `users`.`id` ASC LIMIT 1
web_1       |    (0.3ms)  BEGIN
web_1       |   SQL (0.6ms)  UPDATE `users` SET `last_sign_in_at` = '2016-06-29 17:15:31', `current_sign_in_at` = '2016-06-29 17:15:31', `sign_in_count` = 9, `updated_at` = '2016-06-29 17:15:31' WHERE `users`.`id` = 1
web_1       |    (2.9ms)  COMMIT
web_1       |   Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`hostname` = 'chuck-desk.site.com:5000' LIMIT 1
web_1       |   Namespace Load (0.5ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'chuck' LIMIT 1
web_1       | [jwt_token] [claim] {:iss=>"chuck-desk.site.com", :sub=>"portus", :aud=>"chuck-desk.site.com:5000", :iat=>1467220531, :nbf=>1467220526, :exp=>1467220831, :jti=>"B8eZSBSu62axhizmxw9gcaNZfChoCszkEUmtiv8XZ3", :access=>[{:type=>"repository", :name=>"chuck/hello-world", :actions=>["pull"]}]}
web_1       | Completed 200 OK in 120ms (Views: 0.4ms | ActiveRecord: 6.1ms)
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /v2/token?account=portus&scope=repository%3Achuck%2Fhello-world%3Apull&service=chuck-desk.site.com%3A5000 HTTP/1.1" 200 - 60.3887
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /assets/application-5748debb007c6c1426e80b6b91adc432.css?body=1 HTTP/1.1" 304 - 58.2680
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /assets/jquery-62c574bf4aa58060446c8957234361d2.js?body=1 HTTP/1.1" 304 - 58.2750
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /assets/jquery.turbolinks-b3f41da933e7be7a4a4a2234750e25d6.js?body=1 HTTP/1.1" 304 - 58.2941
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /assets/layout/bg-24a72546a6d0a52a1f1ce9832621dbdc.png HTTP/1.1" 304 - 0.0091
web_1       | [17] 10.0.2.2 - - [29/Jun/2016:17:15:31 +0000] "GET /assets/layout/portus-logo-dashboard-0262751817bc72a9c3bc1020dcb44ad1.png HTTP/1.1" 304 - 0.0123
web_1       | 
```

That should be enough info for now, I think. If you need even more specific stuff, please let me know, I'll be happy to provide it!


Also I have a side question. How do I deploy Portus in "Production" mode? More specifically, what environment variable do I set for `Portus_web` when using `docker-compose.yml`? I'm unfamiliar with Ruby so I'm struggling with this one.

**Comment by biolounge** [comment]
I also have the same issue. After I push the image, portus hangs for 30 - 60seconds.

**Comment by chuck-knox** [comment]
@biolounge please, for the sake of solving the issue, can you post more information about your configuration? The devs need as much info as they can get.

**Comment by mssola** [comment]
Today I got some more time and... sigh :sweat:. I can totally reproduce this. No proxies, no LDAP, no nothing: bare Portus. This only happens in the docker-compose setup as far as I can tell (and I don't think it's related to docker-compose this time).

I will try it out with our `opensuse/portus:head` image next time. Just to make sure that it's not puma the one to blame on this. Check out the documentation for this image [here](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus). We are going to blog about it as soon as possible :wink:

**Comment by biolounge** [comment]
I forgot to put configuration details in my previous post.

Portus Version: master@050d095 is running on Ubuntu14.04.3 LTS (GNU/Linux 3.13.0-74-generic x86_64) with Docker  1.11.2.

` docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64`

**Comment by stunndard** [comment]
Any progress on this one? I've used the instructions from https://github.com/Djelibeybi/Portus-On-OracleLinux7 to deploy portus in a 3 container setup (mariadb, registry and portus) on Ubuntu, I always experience a long hang after pushing an image. Tried both portus:2.0 and portus:head (2.1-dev)

**Comment by codablock** [comment]
Please check https://github.com/SUSE/Portus/issues/1235, implementing this may fix the issues seen here. I'm not a Ruby coder however, so I can't implement this by myself.

**Comment by tturbs** [comment]
Anyone did further work on it so far?

**Comment by fentas** [comment]
I experience the same issue :disappointed:. I had other Problems first but finally ended here. I posted some logs: #1345

**Comment by mssola** [comment]
After some previous work, I think I can tackle this issue. I will combine what I've done in #1353 and #1526 to fix this once and for all, regardless of the puma workers you have for Portus.
