### ISSUE TITLE
Merge features from 2.x into master?

### ISSUE THREAD

**Issue by dforste** [SUSE/Portus#947]
Can we get all features merged back into master? 
Master has Authentication Tokens
2.x has Deletion of images

Any way we can get it all merged into master? 
I am in the position where I am running master in production because it has auth tokens. 

I would try a PR but don't understand the code enough to trust I wont break it.

**Comment by mssola** [comment]
I'm confused :sweat_smile:. All the latest feature *are* in master. Maybe you mean that you want all these features (even if they are a subset of them) as part of a stable release ? Then you will be happy to know that we are finishing up the next stable release this July, in August we will focus on bug fixing & documentation, and in September you will have a shiny new stable release :blush:.

The current stable release has been around probably for too much time. We plan to release more often, sorry about that.

**Comment by dforste** [comment]
Sorry I suppose I was confused as well. Please ignore this issue.
