### ISSUE TITLE
Portus trying to delete images pushed by CI

### ISSUE THREAD

**Issue by xinity** [SUSE/Portus#954]
hi,

been updated Portus using master branch (registry 2.3.1).
we haven't enabled delete option.
we push images on your registry using Drone CI, which works perfectly.
but everytime we push/update a image, portus tries to delete it
we have several messages like this on the dashboard:

```
portus deleted mylampdev:latest
about 2 hours
```

hopefully these images aren't delete on the registry and are still available.
any clues on what's going on wrong ?

**Comment by dforste** [comment]
This sounds like the same symptom that I get in https://github.com/SUSE/Portus/issues/952. May be related.

**Comment by xinity** [comment]
indeed :(
no fix then :cry:

**Comment by mssola** [comment]
@dforste @xinity this issue looks weird indeed. Let me try to fix #952 and we can re-evaluate this one :wink:

**Comment by mssola** [comment]
This should be fixed for the 2.3 release and master. We have also added some configurable values to make the whole thing safer.
