### ISSUE TITLE
Crono fails to correct an upgraded DB with image ids

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#964]
As pointed out in #952, `crono` is failing at handling upgrades.

**Comment by phucvinh52** [comment]
+1 i have same the problem :+1:

**Comment by dforste** [comment]
This is preventing us from upgrading and should be resolved before the release. I am not sure what is required for it to be fixed though.

**Comment by mssola** [comment]
@dforste agreed. We will try to make the upgrade experience as smooth as possible before releasing 2.1 :wink:

**Comment by mssola** [comment]
This shouldn't happen anymore.
