### ISSUE TITLE
Unable to anonymous bind

### ISSUE THREAD

**Issue by It4lik** [SUSE/Portus#976]
Hi, 

I wondered if there's any way to authenticate users with LDAP by using an anonymous user. 

I'm actually unable to got that working with the current configuration file.

While I can connect with a simple ruby code sample : 
> ldap = Net::LDAP.new(:host => 'my.host',:base =>'my_base', :auth => {:method =>:anonymous})
puts ldap.bind # this prints true 

Thanks,
It4

**Comment by mssola** [comment]
Hi @It4lik. I thought that allowing administrators to disable authentication would be enough (see the `authentication` section inside of the `ldap` configurable values). For an anonymous access you still have to provide the hostname and the base where to search, and since the lookup is for users, you should provide a user ID as well. Doesn't that work for your use case ?

**Comment by It4lik** [comment]
If I provide user credentials in the authentication section, that works for sure. 

But the idea was to tell Portus to log in the LDAP server as an anonymous user. Then he can retrieve various informations about the users (we want the uid, the password hash, and the email if the guess_email option is set on true), while it's still logged as anonymous.
With the ruby code sample I pasted before, I'm able to retrieve these informations manually (while being logged as anonymous user).

Whereas Portus actually *need* a user to authenticate himself, and then, search for other users in the provided base. 
A workaround can consist in something like an "administrative user" only used by Portus, to log him in the LDAP server. But this requires an additional user, and also requires to write down his password as plain text in the configuration file.

**Comment by mssola** [comment]
Maybe we are not understanding each other,  but you should be able to login/signup LDAP users without providing anything in the `authentication` section. In this case, if you don't provide anything in the authentication section, it should be the same as the anonymous bind, no ? (and that works for me at least :yum:)

Otherwise, if that doesn't work for you, maybe we can add an anonymous mode, but I'm not so sure actually that we need it, that's why I'm asking :wink:

**Comment by It4lik** [comment]
Right, i'll dig a bit deeper, it doesn't work for me with no credentials provided in the authentication section. 
You didn't actually need anything else if this is supposed to work, i agree ehe...
Thanks for your answer again ! :)

**Comment by mssola** [comment]
Well. if it doesn't work for you, maybe it's a bug :sweat_smile:. How could I reproduce this ? Could you paste your LDAP config ? (e.g. by executing `rake portus:info`)

**Comment by It4lik** [comment]
I don't think it's a bug, I created an administrative user to provide somethin in the authentication section and I still can't use the LDAP binding. I get SSL error, and I think the problem is between the keyboard and the chair ;)

Here is my config : 

> Portus version: master@8a67b55
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: '****'
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: true
  hostname: my.ldap
  port: 389
  method: simple_tls
  base: ou=my,dc=base
  filter: ****
  uid: ****
  authentication:
    enabled: true
    bind_dn: cn=my,dc=user
    password: '****'
  guess_email:
    enabled: true
    attr: mail
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
jwt_expiration_time:
  value: 5.minutes
machine_fqdn:
  value: my.registry
display_name:
  enabled: false

Whether the authentication is empty or filled, i still got the same error when trying to connect on the webui : 
> cat ***/thin.1.log
...
OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A):
...

**Comment by mssola** [comment]
I see. If that's the case, maybe you have to use another encryption method (plain or starttls), or the port you are using is not configured to be with SSL, and you have to use another one ? (e.g. port 636 is a usual one for starttls).

**Comment by It4lik** [comment]
I'm not using starttls, but simple_tls over port 636 :) and with authentication field left empty. 

I now got problem while trying to add the registry to Portus webui. It tells me that the certificate was signed by an unknown authority which is... false. I'll dig deeper to see where I did something wrong, I think it's a mistake again. 

Just one last thing : in your official documentation, on this page : http://port.us.org/docs/How-to-setup-secure-registry.html, it's said that *"The issues should be the same as the one defined by machine_fqdn in the config/secrets.yml file."*. This is false since the machine_fqdn is in the config.yml file now

**Comment by mssola** [comment]
> Just one last thing : in your official documentation, on this page : http://port.us.org/docs/How-to-setup-secure-registry.html, it's said that "The issues should be the same as the one defined by machine_fqdn in the config/secrets.yml file.". This is false since the machine_fqdn is in the config.yml file now 

True. Thanks :+1:
