### ISSUE TITLE
TLS handshake failed with trusted certificate

### ISSUE THREAD

**Issue by It4lik** [SUSE/Portus#978]
Hi, 

My config is the following : 
Portus is handled by Thin server. 
Authentication is done via a nginx reverse proxy against a LDAP Server. 
My registry is a container. 
Portus, Nginx and the docker host are on the same machine while the LDAP Server is on the network. 

I'm using a certificate signed by Terena, which is a known authority. I have correctly configured it to access to the WebUI. 

But when I try to use exactly the same certificate to make Portus and the registry communicate securely, i got the following errors : 

On registry : 
$ docker logs registry 
...
http: TLS handshake error from xxx.xxx.xxx.xxx:43378: remote error: unknown certificate authority/
...

On thin :
$ cat log/thin.0.log
...
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
...

I'm investigating but that looks odd to me. 

It4

ps : looks like the same issue as #804 & #719 

edit : I added a few things in the registry Dockerfile to make him trust my certificate. Portus webui and log files keeps telling me same things...
[Dockerfile.txt](https://github.com/SUSE/Portus/files/361539/Dockerfile.txt)

My host OS is centOS 7. 
I also add the certificate to the trusted ones (and I can find it in /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt)

**Comment by dmoshi** [comment]
Were you able to fix? Can you share?

**Comment by joaoelvas** [comment]
Was anyone able to fix this problem?
