### ISSUE TITLE
Webhooks are listed only for portus admin

### ISSUE THREAD

**Issue by holgerreif** [SUSE/Portus#980]
A regular user can create a webhook and edit it later (if he uses a deep link e.g. from the dashboard).
However die menu entry "Show webhooks" in the namespace listing lists webhooks only if you are an admin user.

**Comment by mssola** [comment]
I'm not able to reproduce this. As a regular user, I can create/edit webhooks only if I'm an owner, and I can view webhooks (including the "Show webhooks") even if I'm a viewer.

Could you tell me a combination in which you can reproduce this ?

**Comment by holgerreif** [comment]
Meanwhile I found out, that I can see the hooks on Namespaces I'm a member of (in each of the thre roles) but I cannot see the hooks in my personal namespace. I made my space public before I did the webhook tests.

**Comment by mssola** [comment]
> Meanwhile I found out, that I can see the hooks on Namespaces I'm a member of (in each of the thre roles) 

Yeah, that is expected behavior.

> but I cannot see the hooks in my personal namespace. I made my space public before I did the webhook tests.

Just tried that and I cannot reproduce it. Could you give more details ?

**Comment by holgerreif** [comment]
My collegue did the following:
1. access portus as a new (LDAP) user
2. select namespace tab
3. created a new webhook via "show webhooks" -> "Create new webhook"
4. go to namespaces again and find the webhook listed there (as number "1" wir the link to the webhooks page) 
5. Click the link and find no hook listed (unexpected, seeing one webhook is expected)

However it gets further:
6. Add another member as viewer into your personal namespace
7. This member can see the webhook under the same URL (.../namespaces/12/webhooks) under which the owner cannot see it!

**Comment by mssola** [comment]
Now I was able to reproduce this! Thanks for the patience :sweat_smile:

**Comment by mssola** [comment]
Moreover, adding to this issue, this issue can only be reproduced for personal namespaces. That was probably the part that I was missing before being able to reproduce this bug :grin:

**Comment by mssola** [comment]
@holgerreif implemented and merged. Does this help with your issue ?
