### ISSUE TITLE
Reset Password Email - Change my password link has not got a port.

### ISSUE THREAD

**Issue by zekiunal** [SUSE/Portus#989]
Hi; 

Portus working on http://www.domain.com:3000

But "Reset password instructions" email link working with 

"http://www.domain.com/users/password/edit?reset_password_token=$token" url.

is there any configuration for this issue ?

**Comment by mssola** [comment]
You will have to update the `machine_fqdn` value to "www.doman.com:3000". See [the documentation page](http://port.us.org/docs/Configuring-Portus.html#fqdn-of-your-machine) for this. If you are not using the `master` branch, then this configurable value is in the `config/secrets.yml` file.
