### ISSUE TITLE
Unable to setup an Apache + Passenger config - 404 "Not found: /"

### ISSUE THREAD

**Issue by It4lik** [SUSE/Portus#997]
Hi,

I'm trying to reproduce what you've done here : http://port.us.org/docs/setups/4_portus_and_registry_on_the_same_fqdn.html
 
In both on config files below, I commented the rewrite rules, I didn't need them for WebUI testing.

If I use this config file for Apache, the WebUI actually works at https://my.domain.com/

```
<VirtualHost *:443>

   ServerName my.domain.com
   DocumentRoot /srv/Portus/public
   SSLEngine on
   SSLCertificateFile /certs/my.domain.com.pem
   SSLCertificateKeyFile /private/my.domain.com.fr.key

 #  RewriteEngine On

#   RewriteCond %{REQUEST_URI} !^/portus.*$
#   RewriteRule ^/(.*)$ "http:\/\/127\.0\.0\.1\:5000\/$1" [P,L]

#   Alias /portus /srv/Portus/public
#   <Location /portus>
     PassengerBaseURI /
     PassengerAppRoot /srv/Portus
#   </Location>
     PassengerLogLevel 3
   <Directory "/srv/Portus/public">
   Options FollowSymLinks
   AllowOverride None
   Order allow,deny
   Allow from all
   Options -MultiViews
   # Uncomment this if you're on Apache >= 2.4:
   Require all granted
      SetEnv GEM_PATH /usr/local/lib/ruby/gems/2.1.0/gems:/usr/local/lib/ruby/gems
      SetEnv PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY 0
      SetEnv PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY 0
      PassengerAppEnv development
   </Directory>
</VirtualHost>
```

But with the one you give, I can't get it to work at https://my.domain.com/portus, I keep on getting 404 errors. Things that change are between *** (which obvisoulsy, are not included in the real config file)
BUT I can still go to Portus WebUI on https://my.domain.com/
```
<VirtualHost *:443>

   ServerName my.domain.com
   DocumentRoot /srv/Portus/public
   SSLEngine on
   SSLCertificateFile /certs/my.domain.com.pem
   SSLCertificateKeyFile /private/my.domain.com.key

 #  RewriteEngine On

#   RewriteCond %{REQUEST_URI} !^/portus.*$
#   RewriteRule ^/(.*)$ "http:\/\/127\.0\.0\.1\:5000\/$1" [P,L]

   *** Alias /portus /srv/Portus/public ***
   *** <Location /portus> ***
     *** PassengerBaseURI /portus ***
          PassengerAppRoot /srv/Portus
   *** </Location> ***
     PassengerLogLevel 3
   <Directory "/srv/Portus/public">
   Options FollowSymLinks
   AllowOverride None
   Order allow,deny
   Allow from all
   Options -MultiViews
   # Uncomment this if you're on Apache >= 2.4:
   Require all granted
      SetEnv GEM_PATH /usr/local/lib/ruby/gems/2.1.0/gems:/usr/local/lib/ruby/gems
      SetEnv PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY 0
      SetEnv PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY 0
      PassengerAppEnv development
   </Directory>
</VirtualHost>

```

I got nothing in my Passenger logs nor Nginx'
Thing weird is that I can still get static files (like robots.txt at the https://my.domain.com/portus/robots.txt). For me, that actually means that Apache is correctly responding to HTTP requests but Passenger isn't retrieving anything.

**Comment by It4lik** [comment]
I dropped Passenger. I also want to drop Apache but I can't. I'm on a Apache + Thin setup. 
That is actually working except Apache is unable to launch as a demon, is unable to proxy/lb with unix sockets, and is just crashing no matter what after 5 minutes, even if I don't make a single request to Portus...

**Comment by jmcle** [comment]
Did you get this working? Running into the same problem.

**Comment by It4lik** [comment]
I'm actually workin on an Apache + Unicorn setup. I's workin,  but i still can't push/pull, even if authentication is successful. 
Just try to launch your passenger app as a production app and precompile the assets. You can also try to serve static files from your httpd, insted of your ruby app server. 
Tell me if it's workin !
